/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
(function(h){if(!h.Sfdc||!h.Sfdc.canvas||!h.Sfdc.canvas.module){var s={};if(h.Sfdc&&h.Sfdc.canvas)for(var p in h.Sfdc.canvas)h.Sfdc.canvas.hasOwnProperty(p)&&(s[p]=h.Sfdc.canvas[p]);var t=Object.prototype,l=Array.prototype,q=h.document,e={hasOwn:function(a,b){return t.hasOwnProperty.call(a,b)},isUndefined:function(a){return void 0===a},isNil:function(a){return e.isUndefined(a)||null===a||""===a},isNumber:function(a){return!!(0===a||a&&a.toExponential&&a.toFixed)},isFunction:function(a){return!(!a||
!a.constructor||!a.call||!a.apply)},isArray:Array.isArray||function(a){return"[object Array]"===t.toString.call(a)},isArguments:function(a){return!(!a||!e.hasOwn(a,"callee"))},isObject:function(a){return null!==a&&"object"===typeof a},isString:function(a){return null!==a&&"string"==typeof a},appearsJson:function(a){return/^\{.*\}$/.test(a)},nop:function(){},invoker:function(a){e.isFunction(a)&&a()},identity:function(a){return a},each:function(a,b,c){if(!e.isNil(a)){var d=l.forEach,f=0,g,m;g=a.length;
c=c||a;if(d&&d===a.forEach)a.forEach(b,c);else if(e.isNumber(g))for(;f<g&&!1!==b.call(c,a[f],f,a);)f+=1;else for(m in a)if(e.hasOwn(a,m)&&!1===b.call(c,a[m],m,a))break}},startsWithHttp:function(a,b){return!e.isString(a)?a:"http"===a.substring(0,4)?a:b},map:function(a,b,c){var d=[],f=l.map;if(e.isNil(a))return d;if(f&&a.map===f)return a.map(b,c);c=c||a;e.each(a,function(a,e,f){d.push(b.call(c,a,e,f))});return d},values:function(a){return e.map(a,e.identity)},slice:function(a,b,c){return l.slice.call(a,
e.isUndefined(b)?0:b,e.isUndefined(c)?a.length:c)},toArray:function(a){return!a?[]:a.toArray?a.toArray:e.isArray(a)?a:e.isArguments(a)?e.slice(a):e.values(a)},size:function(a){return e.toArray(a).length},indexOf:function(a,b){var c=l.indexOf,d;if(!a)return-1;if(c&&a.indexOf===c)return a.indexOf(b);c=0;for(d=a.length;c<d;c+=1)if(a[c]===b)return c;return-1},isEmpty:function(a){if(null===a)return!0;if(e.isArray(a)||e.isString(a))return 0===a.length;for(var b in a)if(e.hasOwn(a,b))return!1;return!0},
remove:function(a,b){var c=e.indexOf(a,b);0<=c&&a.splice(c,1)},param:function(a,b){function c(a,f){e.isNil(f)||(f=e.isFunction(f)?f():f,e.isArray(f)?e.each(f,function(b,d){c(a,b)}):d[d.length]=b?encodeURIComponent(a)+"\x3d"+encodeURIComponent(f):a+"\x3d"+f)}var d=[];b=b||!1;if(e.isArray(a))e.each(a,function(a,b){c(b,a)});else for(var f in a)e.hasOwn(a,f)&&c(f,a[f]);return d.join("\x26").replace(/%20/g,"+")},objectify:function(a){var b={},c,d,f,g;if(e.isNil(a))return b;"?"==a.substring(0,1)&&(a=a.substring(1));
a=a.split("\x26");for(c=0;c<a.length;c+=1)d=a[c].split("\x3d"),f=d[0],d=d[1],g=b[f],e.isNil(g)?b[f]=d:e.isArray(g)?g[g.length]=d:(b[f]=[],b[f][0]=g,b[f][1]=d);return b},stripUrl:function(a){return e.isNil(a)?null:a.replace(/([^:]+:\/\/[^\/\?#]+).*/,"$1")},query:function(a,b){if(e.isNil(b))return a;a=a.replace(/#.*$/,"");return a+=/^\#/.test(b)?b:(/\?/.test(a)?"\x26":"?")+b},extend:function(a){e.each(e.slice(arguments,1),function(b,c){e.each(b,function(b,c){a[c]=b})});return a},endsWith:function(a,
b){return-1!==a.indexOf(b,a.length-b.length)},capitalize:function(a){return a.charAt(0).toUpperCase()+a.slice(1)},uncapitalize:function(a){return a.charAt(0).toLowerCase()+a.slice(1)},decode:function(a){var b=[],c,d,f="",g,h="",k=0;a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");do c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(k++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(k++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(k++)),
h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(k++)),c=c<<2|d>>4,d=(d&15)<<4|g>>2,f=(g&3)<<6|h,b.push(String.fromCharCode(c)),64!==g&&b.push(String.fromCharCode(d)),64!==h&&b.push(String.fromCharCode(f));while(k<a.length);return e.escapeToUTF8(b.join(""))},escapeToUTF8:function(a){for(var b="",c=0;c<a.length;){var d=a.charCodeAt(c++),f;if(128>d)b+=String.fromCharCode(d);else if(191<d&&224>d)f=a.charCodeAt(c++),b+=String.fromCharCode((d&31)<<6|f&63);else{f=
a.charCodeAt(c++);var e=a.charCodeAt(c++),b=b+String.fromCharCode((d&15)<<12|(f&63)<<6|e&63)}}return b},validEventName:function(a,b){var c,d=a.split(/\./),f=/^[$A-Z_][0-9A-Z_$]*$/i,g={sfdc:!0,canvas:!0,force:!0,salesforce:!0,chatter:!0,s1:!0};e.each(e.isArray(b)?b:[b],function(a){g[a]=!1});return 2<d.length?1:2===d.length&&(c=d[0].toLowerCase(),g[c])?2:!f.test(d[0])||!f.test(d[1])?3:0},prototypeOf:function(a){var b=Object.getPrototypeOf;return e.isFunction(b)?b.call(Object,a):"object"===typeof{}.__proto__?
a.__proto__:a.constructor.prototype},module:function(a,b){var c=a.split("."),d=h.Sfdc.canvas,f,g;"canvas"===c[1]&&(c=c.slice(2));g=c.length;for(f=0;f<g;f+=1)e.isUndefined(d[c[f]])&&(d[c[f]]={}),d=d[c[f]];e.isFunction(b)&&(b=b());return e.extend(d,b)},document:function(){return q},byId:function(a){return q.getElementById(a)},byClass:function(a){return q.getElementsByClassName(a)},attr:function(a,b){var c=a.attributes,d;for(d=0;d<c.length;d+=1)if(b===c[d].name)return c[d].value},onReady:function(a){e.isFunction(a)&&
n.push(a)},console:function(){function a(){try{return"sessionStorage"in window&&null!==window.sessionStorage}catch(a){return!1}}function b(){}function c(){}function d(){b=Function.prototype.bind?Function.prototype.bind.call(console.log,console):function(){Function.prototype.apply.call(console.log,console,arguments)}}function f(){b=function(){}}var e=!1;window&&!window.console&&(window.console={});window&&!window.console.log&&(window.console.log=function(){});window&&!window.console.error&&(window.console.error=
function(){});(e=a()&&"true"===sessionStorage.getItem("canvas_console"))?d():f();c=Function.prototype.bind?Function.prototype.bind.call(console.error,console):function(){Function.prototype.apply.call(console.error,console,arguments)};return{enable:function(){e=!0;a()&&sessionStorage.setItem("canvas_console","true");d()},disable:function(){e=!1;a()&&sessionStorage.setItem("canvas_console","false");f()},log:b,error:c}}()},n=[],r=function(a){e.isFunction(a)&&n.push(a)};(function(){function a(){c||(c=
!0,a=e.nop,e.each(n,e.invoker),n=[])}function b(){if(!c)try{document.documentElement.doScroll("left"),a()}catch(d){setTimeout(b,30)}}var c=!1,d,f;if(document.addEventListener)document.addEventListener("DOMContentLoaded",a,!1);else if(document.attachEvent){try{d=self!==top}catch(g){}document.documentElement.doScroll&&!d&&b();document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&a()})}window.addEventListener?window.addEventListener("load",a,!1):window.attachEvent?window.attachEvent("onload",
a):(f=window.onload,window.onload=function(){f&&f();a()})})();e.each(e,function(a,b){r[b]=a});e.each(s,function(a,b){r[b]=a});(function(){for(var a,b=function(){},c="assert clear count debug dir dirxml error exception group groupCollapsed groupEnd info log markTimeline profile profileEnd table time timeEnd timeStamp trace warn".split(" "),d=c.length,e="undefined"!==typeof window&&window.console?window.console:{};d--;)a=c[d],e[a]||(e[a]=b)})();h.Sfdc||(h.Sfdc={});h.Sfdc.canvas=r}})(this);
(function(b,a){var g=function(){var e;return{post:function(f,d,c){var h=Sfdc.JSON||JSON;if(b.isNil(d))throw"ERROR: target_url was not supplied on postMessage";d=b.stripUrl(d);c=c||parent;a.postMessage&&(b.isObject(f)&&(f.targetModule="Canvas"),f=h.stringify(f),b.console.log("Sending Post Message ",f),c.postMessage(f,d))},receive:function(f,d){a.postMessage&&(f&&(e=function(c){var a,e,g=Sfdc.JSON||JSON;b.console.log("Post Message Got callback",c);if(!b.isNil(c)){if("string"===typeof d&&c.origin!==
d)return b.console.log("source origin's don't match",c.origin,d),!1;if(b.isFunction(d)&&(e=d(c.origin,c.data),!1===e))return b.console.log("source origin's function returning false",c.origin,c.data),!1;if(b.appearsJson(c.data)){try{a=g.parse(c.data)}catch(k){}if(!b.isNil(a)&&(b.isNil(a.targetModule)||"Canvas"===a.targetModule))b.console.log("Invoking callback"),f(a,e)}}}),a.addEventListener?a.addEventListener("message",e,!1):a.attachEvent("onmessage",e))},remove:function(){a.postMessage&&(a.removeEventListener?
a.removeEventListener("message",e,!1):a.detachEvent("onmessage",e))}}}();b.module("Sfdc.canvas.xd",g)})(Sfdc.canvas,this);
(function(k){var p=function(){function l(d,a,e,g,b){m(d,a,a,function(a,c,d){a.appendChild(document.createTextNode(e));c.appendChild(document.createTextNode(g));d.appendChild(document.createTextNode(b))})}function m(d,a,e,g){if(!k.isNil(d)){var b,f,c,h;b=k.byId("canvas-notify-styles");k.isNil(b)&&(b=document.createElement("style"),b.setAttribute("name","canvas-notify-styles"),b.setAttribute("id","canvas-notify-styles"),b.type="text/css",window.attachEvent&&!window.opera?b.styleSheet.cssText=n:(f=document.createTextNode(n),
b.appendChild(f)),document.getElementsByTagName("head")[0].appendChild(b));b=document.createElement("div");b.setAttribute("class","canvas-notify-block");f=document.createElement("div");f.setAttribute("class","top-line");c=document.createElement("img");c.setAttribute("src",a);c.setAttribute("width","16");c.setAttribute("height","16");c.setAttribute("class","title-image");a=document.createElement("div");a.setAttribute("class","title-text");f.appendChild(c);f.appendChild(a);b.appendChild(f);f=document.createElement("div");
f.setAttribute("class","content");c=document.createElement("div");c.setAttribute("class","contentIcon");h=document.createElement("img");h.setAttribute("src",e);h.setAttribute("width","32");h.setAttribute("height","32");c.appendChild(h);f.appendChild(c);e=document.createElement("div");e.setAttribute("class","notify-message");c=document.createElement("div");c.setAttribute("class","subject-text");h=document.createElement("div");h.setAttribute("class","body-text");k.isFunction(g)&&g(a,c,h);e.appendChild(c);
e.appendChild(h);f.appendChild(e);for(b.appendChild(f);d.firstChild;)d.removeChild(d.firstChild);d.appendChild(b)}}var n="#canvas-notify-block {background: none repeat scroll 0 0 #FFFFFF;border-radius: 5px 5px 5px 5px;margin-bottom: 20px;overflow: hidden;position: relative;top: 1px;color: #222222;font-family: Arial,Helvetica,sans-serif;padding-left: 10px;}.canvas-notify-block .top-line{background-color: #DEDEDE;border: 1px solid #CCCCCC;border-radius: 5px 5px 0 0;padding-bottom: 15px;color: #222222;font-size: 10px;font-weight: bold;margin-bottom: 0px;margin-top: 0px;padding-left: 5px;padding-top: 0px;height: 10px;}.canvas-notify-block .top-line .title-image{float:left;padding-top:5px;}.canvas-notify-block .top-line .title-text{padding-left:20px;margin-top:8px;display:block;}.canvas-notify-block .content{border-bottom: 1px solid #CCCCCC;border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;border-left: 1px solid #CCCCCC;border-right: 1px solid #CCCCCC;font-size: 15px;padding-right: 4px;}.canvas-notify-block .content .contentIcon{float: left;height: 40px;margin-bottom: 3px;margin-left: 20px;margin-top: 6px;padding-top: 6px;width: 40px;}.canvas-notify-block .content .notify-message .subject-text{font-weight: bold;}.canvas-notify-block .content .notify-message .body-text{padding-top: 10px;}.canvas-notify-block .content .notify-message{padding-left:80px;padding-top:20px;padding-bottom:20px;font-size: 11px;}";
return{warning:function(d,a,e,g){l(d,"/img/msg_icons/warning32.png",a,e,g)},error:function(d,a,e,g){l(d,"/img/msg_icons/error32.png",a,e,g)},info:function(d,a,e,g){l(d,"/img/msg_icons/info32.png",a,e,g)},show:l,custom:m}}();k.module("Sfdc.canvas.notify",p)})(Sfdc.canvas);
(function(c){var M=function(){var G,l;function v(a,e,b,d,k){var h=LC.getLabel("CanvasParentJs","defaultNotifyTitle",b);b=LC.getLabel("CanvasParentJs","defaultRenderSummary",b);var g=w(1,f[a]);c.isNil(g)?c.notify.show(e,t("/img/msg_icons/error32.png"),h,b,d):g({title:h,summary:b,detail:d});c.isNil(f[a])||(H({name:"render",type:"ERROR",namespace:f[a].app.namespace,canvas:f[a].app.developerName,referenceId:f[a].app.referenceId,startTime:f[a].startTime,authType:f[a].app.authenticationType,payload:{canvasUrl:f[a].url,
localizedMessage:c.isObject(d)?q.stringify(d):d,debugTrace:c.isNil(k)?"\x3cnone\x3e":k},displayLocation:f[a].options.displayLocation,sublocation:f[a].options.sublocation,cversion:f[a].cversion}),A(a));if(!c.isNil(f[a])&&c.isFunction(f[a].options.onCanvasAppError))f[a].options.onCanvasAppError()}function N(a,e,b,d,k,h){var g=t("/img/msg_icons/info32.png"),m=LC.getLabel("CanvasParentJs","defaultNotifyTitle",b),p=LC.getLabel("CanvasParentJs","defaultRenderSummary",b);b=w(2,f[a]);c.isNil(b)?c.notify.custom(e,
g,g,function(a,b,e){a.appendChild(document.createTextNode(m));b.appendChild(document.createTextNode(p));e.appendChild(document.createTextNode(d));c.isNil(h)||(a=document.createElement("a"),a.setAttribute("href",t(h)),a.setAttribute("title",k),a.appendChild(document.createTextNode(k)),e.appendChild(document.createElement("p")),e.appendChild(a))}):b({title:m,summary:p,detail:d});if(!c.isNil(f[a])){H({name:"render",type:"ERROR",namespace:f[a].app.namespace,canvas:f[a].app.developerName,referenceId:f[a].app.referenceId,
startTime:f[a].startTime,authType:f[a].app.authenticationType,payload:{canvasUrl:f[a].url,localizedMessage:d},displayLocation:f[a].options.displayLocation,sublocation:f[a].options.sublocation,cversion:f[a].cversion});if(c.isFunction(f[a].options.onCanvasAppError))f[a].options.onCanvasAppError();A(a)}}function w(a,e){var b=aa[a];return!c.isNil(e)&&(e.options&&!c.isNil(e.options.customCanvasRenderer)&&!c.isNil(e.options.customCanvasRenderer[b]))&&c.isFunction(e.options.customCanvasRenderer[b])?e.options.customCanvasRenderer[b]:
null}function O(a,e){var b=f[a],d;d=w(0,b);var k=c.isNil(b.app.name)?"":b.app.name,k=LC.getLabel("CanvasParentJs","loadingStatus",k);b.options&&b.options.showLoadingStatus&&(c.isNil(d)?(A(a),d=c.byId("loading-"+a),c.isNil(d)?(d=document.createElement("div"),d.setAttribute("id","loading-"+a),d.setAttribute("style","position:relative;width:25%;height:30px;margin-top:20px;margin-bottom:30px;"),d.style.display="block",e.appendChild(d)):d.style.display="block",b.loadingScreen=new LoadingScreen(d,Sfdc.String.escapeToHtml(k)),
b.loadingScreen.show()):d(!0,k))}function A(a){var e=f[a],b=w(0,e);c.isNil(b)?(c.isNil(e.loadingScreen)||(e.loadingScreen.hide(),e.loadingScreen=null),a=c.byId("loading-"+a),c.isNil(a)||(a.style.display="none",P(a))):b(!1)}function P(a){if(!c.isNil(a))for(;a.firstChild;)a.removeChild(a.firstChild)}function Q(a){var e={},b,d;if(!c.isNil(a.record)&&!c.isNil(a.record.Id)&&(e.Id=a.record.Id,!c.isNil(a.record.fields))){a=a.record.fields.split(",");for(b=0;b<a.length;b+=1)d=a[b].trim(),c.isUndefined(e[d])&&
(e[d]=null)}return e}function D(a,c){var b,d,f,h=c?c+a:a;f=window.document.getElementsByTagName("iframe");d=f.length;for(b=0;b<d;b+=1)try{if(f[b].name===h)return f[b].contentWindow}catch(g){}return frames[h]}function t(a,e){var b=null,d=a;c.isNil(I)?c.isNil(J)||(d=J+d):(b=I+a,d=location.protocol+"//"+location.hostname+":"+location.port+"/services/proxy",e.headers["SalesforceProxy-Endpoint"]=b);UserContext&&UserContext.getUrl&&(d=UserContext.getUrl(d),UserContext.isDefaultNetwork||(d=Sfdc.Url.generateUrl(d)));
return d}function M(a,e){var b=e.id;if(c.isNil(b))throw c.console.error(LC.getLabel("CanvasParentJs","missingIdInContext")),LC.getLabel("CanvasParentJs","missingIdInContext");if(a&&a.body){var d=a.body.type,k=a.seq,h=f[b];h&&(h.cversion=a.clientVersion,h.oauthToken=a.body.config.client.oauthToken);c.console.log("xdCallback type [%s] seq [%d] id [%s]",d,k,b);"ctx"===d?n.services(k,b).ctx(a,h):"ajax"===d?n.services(k,b).ajax(a):"resize"===d?n.frame.childResize(a,h):"subscribe"===d?n.events.subscribe(a.body.subscriptions,
h):"unsubscribe"===d?n.events.unsubscribe(a.body.subscriptions,h):"publish"===d?c.s1&&c.s1.canHandle(a.body.event)?c.s1.handleEvent(a.body.event):n.events.publishClient(a.body.event,h):"refresh"===d?n.services(k,b).refresh(a,h):"repost"===d&&n.services(k,b).repost(a,h)}}function R(){K&&c.xd.remove();c.xd.receive(M,function(a,e){if(c.appearsJson(e)){e=q.parse(e);if(c.isNil(e.body)||c.isNil(e.body.config)||c.isNil(e.body.config.client))return c.console.log("JSON from postMessage invalid",e),!1;if(e.body.config.client.isVF)return c.console.log("can't find canvas, instanceId [%s] assuming from VF page",
e.body.config.client.instanceId),{id:e.body.config.client.instanceId};var b=f[e.body.config.client.instanceId];if(!c.isNil(b))return c.console.log("post url: c.url "+b.url),c.console.log("actual canvas url, c.app.canvasUrl"+b.app.canvasUrl),"refresh"===e.body.config.type&&c.stripUrl(b.app.canvasUrl)!==a?(c.console.error("Source origin and canvas url are from different domains",b.app.canvasUrl,a),!1):{id:e.body.config.client.instanceId}}return!1});K=!0}function S(a,e,b,d){var k=f[a].app.namespace,
h=f[a].app.developerName,g=f[a].app.referenceId,m=Q(e),k="/services/data/v"+r+"/platformconnect/signedrequest?"+(!c.isNil(g)?"referenceId\x3d"+g:"canvas\x3d"+h+(!c.isNil(k)?"\x26namespace\x3d"+k:""));a={success:b,failure:d,headers:{Authorization:"OAuth "+C,Accept:"application/json"},contentType:"application/json",method:"PUT",data:q.stringify({canvasRequest:{context:{environment:{dimensions:{height:e.height.value,width:e.width.value,maxHeight:e.height.max,maxWidth:e.width.max,clientWidth:e.clientWidth,
clientHeight:e.clientHeight},parameters:e.parameters,displayLocation:e.displayLocation,sublocation:e.sublocation,record:m}},client:{targetOrigin:document.location.protocol+"//"+document.location.host,instanceId:a}}})};k=t(k,a);Sfdc.Ajax.request(k,a)}function H(a){var e=c.isNil(a.type)?null:a.type.toUpperCase();if(c.isNil(e)||-1===c.indexOf(["FINISH","ERROR"],e))throw LC.getLabel("CanvasParentJs","invalidTraceEventType");if(c.isNil(a.name))throw LC.getLabel("CanvasParentJs","invalidTraceEventName");
if(c.isNil(a.canvas)&&c.isNil(a.referenceId))throw LC.getLabel("CanvasParentJs","invalidTraceCanvasAppNameOrId");var b="/services/data/v"+r+"/platformconnect/traceevent";a={headers:{Authorization:"OAuth "+C,Accept:"application/json"},contentType:"application/json",data:q.stringify({eventName:a.name,eventType:e,namespace:a.namespace,canvas:a.canvas,referenceId:a.referenceId,payload:a.payload,authType:a.authType,startTime:a.startTime,endTime:(new Date).getTime(),parentVersion:r,clientVersion:a.cversion,
appInstallType:a.appInstallType,appApprovalType:a.appApprovalType,displayLocation:a.displayLocation,sublocation:a.sublocation})};b=t(b,a);Sfdc.Ajax.post(b,function(){},a)}function x(a,e,b){f[a].startTime&&(H({name:"render",type:"FINISH",namespace:f[a].app.namespace,canvas:f[a].app.developerName,referenceId:f[a].app.referenceId,startTime:f[a].startTime,authType:f[a].app.authType,payload:{canvasUrl:f[a].url},cversion:f[a].cversion,appInstallType:f[a].aux.appInstallType,appApprovalType:f[a].aux.appApprovalType,
displayLocation:f[a].options.displayLocation,sublocation:f[a].options.sublocation}),f[a].startTime=null,A(a),e.style.display="inline");if(c.isFunction(b.onCanvasAppLoad))b.onCanvasAppLoad()}function ba(a,e,b,d,k,h){var g,m;g=document.createElement("form");g.setAttribute("name","canvas-hidden-form-"+a);g.setAttribute("style","display:none");g.setAttribute("action",c.isNil(h)?f[a].url:h);g.setAttribute("target",y+a);g.setAttribute("method","post");h=document.createElement("input");h.setAttribute("type",
"hidden");h.setAttribute("name","signed_request");h.value=e;e=document.createElement("input");e.setAttribute("type","submit");e.setAttribute("post","post");g.appendChild(h);g.appendChild(e);b.appendChild(g);d=T(a,d,k);f[a].frameElement=d;b.appendChild(d);d.addEventListener?d.onload=function(){x(a,this,k);this.onload=null}:d.attachEvent&&(m=function(){var b=event.srcElement;c.isNil(b)||(x(a,b,k),b.detachEvent("onload",m))},d.attachEvent("onload",m));c.isNil(document.forms["canvas-hidden-form-"+a])||
document.forms["canvas-hidden-form-"+a].submit()}function T(a,c,b){var d=document.createElement("iframe");d.setAttribute("id",c);d.setAttribute("name",y+a);d.setAttribute("title",LC.getLabel("CanvasParentJs","iframeTitle",f[a].app.name));d.style.display="none";d.frameBorder=b.frameborder;d.width=b.width.value;d.height=b.height.value;d.scrolling=b.scrolling;return d}function ca(a,e,b,d,k){var h,g;b=T(a,b,d);f[a].frameElement=b;e=e.appendChild(b);b.addEventListener?b.onload=function(){x(a,this,d);this.onload=
null}:b.attachEvent&&(g=function(){var b=event.srcElement;c.isNil(b)||(x(a,b,d),b.detachEvent("onload",g))},b.attachEvent("onload",g));e.contentDocument?h=e.contentDocument:e.contentWindow&&(h=e.contentWindow.document);h.location.replace(c.isNil(k)?f[a].url:k)}function U(a,e,b){var d=y+a,k,h,g=f[a].sr.split(".");k={};if(2!==g.length)throw LC.getLabel("CanvasParentJs","invalidSignedRequestFormat");g=q.parse(c.decode(g[1]));if(c.isNil(g)||c.isNil(g.context.application))throw LC.getLabel("CanvasParentJs",
"unableToParseApp");f[a].app=g.context.application;f[a].loginUrl=g.context.links.loginUrl;"OAUTH"!=f[a].app.authType&&c.isNil(g.client.oauthToken)&&(k._sfdc_canvas_auth="user_approval_required");f[a].authStatus=k;O(a,e);!c.isNil(f[a].aux)&&!c.isNil(f[a].aux.idpInitiatedUrl)&&(h=f[a].aux.idpInitiatedUrl,delete f[a].aux.idpInitiatedUrl,c.console.log("IdpInitiated Request..."+h));k=decodeURIComponent(f[a].app.canvasUrl);g=document.location.protocol+"//"+document.location.host;if("OAUTH"===f[a].app.authType||
!c.isEmpty(f[a].authStatus)){var m=c.param(f[a].authStatus);!c.isNil(f[a].loginUrl)&&"https://login.salesforce.com"!==f[a].loginUrl&&(m+=(0<m.length?"\x26":"")+c.param({loginUrl:encodeURIComponent(f[a].loginUrl)}));m+="#target_origin\x3d"+encodeURIComponent(g)+"\x26instance_id\x3d"+a;f[a].url=c.query(k,m);ca(a,e,d,b,h)}else f[a].url=k,ba(a,f[a].sr,e,d,b,h)}function V(a,e){var b="",d;if(!c.isNil(a)&&1<a.length)for(d=1;d<a.length;d+=1)b+=a[d],d<a.length-1&&(b+=e);return b}function W(a,e,b){c.isNil(f[a].sr)?
(X(e,b),S(a,b,function(c){c=q.parse(c);f[a].sr=c.response;f[a].aux=c.auxiliary;U(a,e,b)},function(b,k,h){var g=q.parse(b);h=f[a].app.name||f[a].app.developerName||f[a].app.referenceId||"undefined";if(!c.isNil(g)&&1<=g.length)switch(b=g[0],b.errorCode){case "APP_NOT_FOUND":case "NO_ACCESS":case "UNSUPPORTED_LOCATION":case "ACCESS_TOKEN_RETRIEVAL_ERROR":case "APEX_CONFIGURATION_EXCEPTION":case "ADMIN_AUTH_REQUIRED":v(a,e,h,b.message);break;case "INVALID_SESSION_ID":v(a,e,h,LC.getLabel("CanvasParentJs",
"sessionInvalid"));break;case "NO_PERSONAL_ACCESS":b=b.message.split("#");N(a,e,h,b[0],LC.getLabel("CanvasParentJs","appInfo"),V(b,"#"));break;case "NO_ACCESS_SETUP_ALLOWED":case "UNSUPPORTED_LOCATION_SETUP_ALLOWED":case "ADMIN_AUTH_REQUIRED_SETUP_ALLOWED":b=b.message.split("#");N(a,e,h,b[0],LC.getLabel("CanvasParentJs","configureLabel"),V(b,"#"));break;default:v(a,e,h,LC.getLabel("CanvasParentJs","signedRequestRetrievalError",b.errorCode+":"+b.message))}else v(a,e,h,LC.getLabel("CanvasParentJs",
"unsupportedServerResponse",""),"Received invalid response body from server. Status:"+(c.isNil(k)?"\x3cNo Request Object\x3e":k.status+", Body: '"+b+"', windowLocation:"+document.location.href+", requestConfig:"))})):U(a,e,b)}function X(a,e){var b,d,f;c.isNil(a)||(c.isNil(e.clientWidth)&&(b=a.clientWidth,0===b&&(d=a.offsetParent,c.isNil(d)||(b=d.clientWidth)),e.clientWidth=b+"px"),c.isNil(e.clientHeight)&&(b=a.clientHeight,0===b&&(d=a.offsetParent,f=a.offsetTop,c.isNil(d)||(b=d.clientHeight-f),0>
b&&(b=0)),e.clientHeight=b+"px"))}function L(a,e){return(!c.isNil(a.developerName)?(c.isNil(a.namespace)?"_":a.namespace)+":"+a.developerName:a.referenceId)+(c.isNil(e)?":":":"+e)}function Y(a,e,b){var d={frameborder:"0",width:{value:"800px",max:"1000px"},height:{value:"900px",max:"2000px"},scrolling:"no",displayLocation:"NONE",showLoadingStatus:!0};b&&(!c.isObject(b.width)&&!c.isNil(b.width)&&(b.width=c.extend(d.width,{value:b.width})),!c.isObject(b.height)&&!c.isNil(b.height)&&(b.height=c.extend(d.height,
{value:b.height})),b.width=c.extend(d.width,b.width||{}),b.height=c.extend(d.height,b.height||{}));b=c.extend(d,b||{});b.height.value=n.frame.minPixels(b.height.value,b.height.max);b.width.value=n.frame.minPixels(b.width.value,b.width.max);d=c.isObject(e)?e:c.byId(e);if(c.isNil(d))window.alert(LC.getLabel("CanvasParentJs","containerElementNotFound",e));else{e=L(a.app,b.canvasId);try{if(c.isNil(a)||c.isNil(a.sr)&&(c.isNil(a.app)||c.isNil(a.app.developerName)&&c.isNil(a.app.referenceId)))throw LC.getLabel("CanvasParentJs",
"insufficientAppContainerInfo");if(c.isNil(a.version))throw LC.getLabel("CanvasParentJs","missingParentVersionInfo");C=a.sid||C;if(c.isNil(C))throw LC.getLabel("CanvasParentJs","missingSid");if(!c.isNil(Sfdc.userAgent)&&(Sfdc.userAgent.isIE6||Sfdc.userAgent.isIE7||Sfdc.userAgent.isOpera||Sfdc.userAgent.isNetscape))throw LC.getLabel("CanvasParentJs","unsupportedBrowser");u(d,e);f[e]={instanceId:e,app:a.app,sr:a.sr,cversion:null,options:b,startTime:(new Date).getTime(),onCanvasSubscribed:b.onCanvasSubscribed,
parentElem:d};r=a.version;I=b.salesforceBaseUrl;J=b.customPathPrefix;O(e,d);W(e,d,b);R()}catch(k){a=!c.isNil(a.app)?a.app.developerName||a.app.referenceId||"undefined":"undefined",v(e,d,a,k)}}}function u(a,e,b){n.events.unsubscribeAll(f[e]);a=c.isObject(a)?a:c.byId(a);P(a);c.isNil(b)&&delete f[e]}var K=!1;G="canvas.scroll";l="sfdc.streamingapi";var aa=["toggleLoadingScreen","renderError","renderInfo","renderCanvas"],f={},r,C,I,J,y="canvas-frame-",q=Sfdc.JSON||JSON,n=function(){var a=function(){function b(a,
b){var e,d=a.name;c.isNil(b)||(d===l?!c.isNil(b.handlers)&&!c.isNil(b.handlers[d])&&(e=b.handlers[d][a.params.topic]):!c.isNil(b.handlers)&&!c.isNil(b.handlers[d])&&(e=b.handlers[d]));return e}function d(a){var e=!1;c.each(f,function(d){c.isNil(b(a,d))||(e=!0)});return e}function e(a,d){var g;if(c.isNil(a.target)&&c.isNil(d))c.console.log("Targeting all canvas apps"),c.each(f,function(d,e){g=b(a,d);c.isNil(g)||(c.isFunction(g)?g(a.payload):(c.console.log("Found canvas app with handler"),c.xd.post({parentVersion:r,
clientVersion:d.cversion,payload:a,type:"event"},c.stripUrl(d.url),D(e,y))))});else if(!c.isNil(a.target)&&!c.isNil(a.target.canvas)&&"parent"===a.target.canvas)g=b(a,f.parent),c.isFunction(g)&&g(a.payload);else if(c.isNil(d))if(c.isNil(a.target.iframe))c.isNil(a.target.canvas)?c.console.error("Nothing to target"):(c.console.log("Targeting single canvas ",a.target.canvas),c.each(f,function(d,e){var f=e.split(":");f[f.length-1]===a.target.canvas&&(c.console.log("Found targeted canvas app"),g=b(a,d),
c.isNil(g)?c.console.log("Canvas app has no handler"):c.xd.post({parentVersion:r,clientVersion:d.cversion,payload:a,type:"event"},c.stripUrl(d.url),D(e,y)))}));else{c.console.log("Targeting single iframe");var h=D(a.target.iframe);c.isNil(h)||c.xd.post({parentVersion:r,clientVersion:r,payload:a,type:"event"},"*",h)}else c.console.log("Targeting canvas object"),g=b(a,d),(!c.isNil(g)||a.name===l)&&c.xd.post({parentVersion:r,clientVersion:d.cversion,payload:a,type:"event"},c.stripUrl(d.url),D(d.instanceId,
y))}function h(a,c,b,d){a="/services/data/v"+a.cversion;c={success:b,failure:d,headers:c,method:"HEAD"};a=t(a,c);Sfdc.Ajax.request(a,c)}function g(){var a;s.current===s.ninitd&&(s.current=s.initd,a="/cometd/"+r+"/",Sfdc.cometd.init({url:location.protocol+"//"+location.hostname+":"+location.port+a,requestHeaders:{Authorization:"OAuth "+C},appendMessageTypeToURL:!1}),z=Sfdc.cometd,c.isNil(u)&&(s.current=s.hs,u=z.addListener("/meta/handshake",function(a){a.successful?(!x&&Z()&&z.batch(function(){var a,
b=c.toArray(f),d,e,g,h;for(g=0;g<b.length;g+=1){a=e=b[g];d=[];h=l;!c.isNil(a.handlers)&&!c.isNil(a.handlers[h])&&(d=a.handlers[h],d=c.toArray(d));a=d;for(h=0;h<a.length;h+=1)d=a[h][0],$(d,e)}}),x=!1,s.current=s.hsdone,B()):s.current=s.hs})))}function m(a,c){var b=v(a[l]);if(b)p(b,c);else throw"["+l+"] Streaming subscription has no params or topic";}function p(a,b){var d,g=l;b.handlers=b.handlers||{};d=b.handlers;c.isNil(d[g])&&(d[g]={});c.isNil(d[g][a])&&h(b,{Authorization:"OAuth "+b.oauthToken},
function(){n(a,b)},function(c,d){var h;h=401===d.status?LC.getLabel("CanvasParentJs","subscribeRequiresAPI",g):LC.getLabel("CanvasParentJs","subscribeGenericError",d.status,g);e({name:g,params:{topic:a},method:"onComplete",payload:{success:!1,errorMessage:h}},b)})}function n(a,c){var b,d,h=l,f;g();f=function(){b=z.subscribe(a,function(b){e({name:h,params:{topic:a},method:"onData",payload:b},c)});d={success:!0,handle:b};b&&(c.handlers[h][a]=b,e({name:h,params:{topic:a},method:"onComplete",payload:d},
c))};s.current===s.hsdone?f():E.push(f)}function B(){var a;for(a=0;a<E.length;a+=1)if(c.isFunction(E[a]))E[a]();E=[]}function $(a,c){var b,d=l;(b=z.subscribe(a,function(b){e({name:d,params:{topic:a},method:"onData",payload:b},c)}))&&(c.handlers[d][a]=b)}function q(a){z.unsubscribe(a);Z()||(z.removeListener(u),u=null,x=!0,s.current=s.ninitd,z.disconnect())}function Z(){var a=!1;c.each(f,function(b){return!c.isNil(b.handlers)&&!c.isNil(b.handlers[l])?(a=!0,!1):!0});return a}function v(a){return!c.isNil(a.params)&&
!c.isNil(a.params.topic)?a.params.topic:null}function w(a,b){var d,e=c.validEventName(a,b);if(0!==e)throw d={1:LC.getLabel("CanvasParentJs","eventMultipleNamespaces"),2:LC.getLabel("CanvasParentJs","eventNamespaceReserved"),3:LC.getLabel("CanvasParentJs","eventInvalidCharacters")},d[e];}function A(a){var b,e=l,g,h,f;c.isNil(a)||(b=a.handlers,c.isNil(b)||(h=b[e],c.each(h,function(a,d){g=b[e][d];delete b[e][d];0>=c.size(b[e])&&delete b[e];q(g)}),a.handlers={},c.each(b,function(a,b){f=F[b];!c.isNil(f)&&
!d(b)&&f.unsubscribe()})))}var z,x=!0,s={ninitd:"notInitialized",initd:"initialized",hs:"handshake",hsdone:"handshakeDone",current:"notInitialized"},u,E=[],F=[];F[G]=function(){function a(){e({name:G,method:"onData",payload:{heights:{contentHeight:document.documentElement.scrollHeight,pageHeight:document.documentElement.clientHeight,scrollTop:document.documentElement&&document.documentElement.scrollTop||document.body.scrollTop},widths:{contentWidth:document.documentElement.scrollWidth,pageWidth:document.documentElement.clientWidth,
scrollLeft:document.documentElement&&document.documentElement.scrollLeft||document.body.scrollLeft}}})}var c=!1;return{subscribe:function(b){!0!==c&&(c=!0,window.addEventListener?window.addEventListener("scroll",a,!1):window.attachEvent&&window.attachEvent("onscroll",a))},unsubscribe:function(){!1!==c&&(window.removeEventListener?window.removeEventListener("scroll",a,!1):window.detachEvent&&window.detachEvent("onscroll",a),c=!1)}}}();F["canvas.orientation"]=function(){var a=!1,b;return{subscribe:function(d){!0!==
a&&(a=!0,b=function(){var a={},b;c.isNil(d.parentElem)||X(d.parentElem,a);b={orientation:window.orientation};c.isNil(a.clientHeight)||(b.clientHeight=a.clientHeight);c.isNil(a.clientWidth)||(b.clientWidth=a.clientWidth);e({name:"canvas.orientation",method:"onData",payload:b})},window.addEventListener?window.addEventListener("orientationchange",b,!1):window.attachEvent&&window.attachEvent("orientationchange",b,!1))},unsubscribe:function(){!1!==a&&(window.removeEventListener?window.removeEventListener("orientationchange",
b,!1):window.detachEvent&&window.detachEvent("orientationchange",b),a=!1,b=null)}}}();return{subscribe:function(a,b){var d=b.handlers||{},e,g;c.console.log("Subscribing ",b);if(c.isNil(a[l])){if(c.each(a,function(a,e){c.isNil(e)||(d[e]=a,g=F[e],c.isNil(g)||g.subscribe(b))}),b.handlers=d,c.isFunction(b.onCanvasSubscribed))b.onCanvasSubscribed()}else c.isNil(Sfdc.CometD)?(e=t("/jslibrary/SfdcExtended.js"),Sfdc.Resource.addJavaScript(e,function(){m(a,b)})):m(a,b)},unsubscribe:function(a,e){var g,h;if(c.isNil(a[l])){if(!c.isNil(e))for(g in a)a.hasOwnProperty(g)&&
!c.isNil(e.handlers[g])&&(delete e.handlers[g],h=F[g],!c.isNil(h)&&!d(g)&&h.unsubscribe())}else{var f;h=l;var k;if(g=v(a[h]))f={name:h,params:{topic:g}},f=b(f,e),c.isNil(f)||(f=e.handlers,k=f[h][g],delete f[h][g],0>=c.size(f[h])&&delete f[h],q(k));else throw"["+l+"] unsubscribe has no params or topic";}},unsubscribeAll:function(a){A(a)},parentSubscribe:function(b){var d,e={};K||R();c.isNil(f.parent)&&(f.parent={});d=f.parent;c.each(c.isArray(b)?b:[b],function(a){c.isNil(a.name)||(w(a.name,"canvas"),
e[a.name]=a.onData)});c.console.log("Parent subscribing");a.subscribe(e,d)},parentUnsubscribe:function(b){var d,e={};c.isNil(f.parent)&&(f.parent={});d=f.parent;c.each(c.isArray(b)?b:[b],function(a){c.isNil(a.name)||(w(a.name),e[a.name]=a.onData)});a.unsubscribe(e,d)},publish:function(a,b){e({name:a.name,method:"onData",payload:a.payload,target:a.target},b)},publishClient:function(b){!c.isNil(b.target)&&!c.isNil(b.target.iframe)&&(b.target.iframe=null);a.publish(b)},parentPublish:function(b){w(b.name);
a.publish(b)}}}(),e=function(){function a(b,d){return c.isNil(b)||c.isNil(d)||"final"===d?!1:!0}function d(a,b){if(c.endsWith(a,"%")||"infinite"===b||"final"===b)return c.endsWith(a,"%")||c.endsWith(a,"px")?a:a+"px";a=Number(a.split("px")[0]);b=Number(b.split("px")[0]);return(a<b?a:b)+"px"}function e(f,g){var k,p;!c.isNil(g)&&!c.isNil(g.frameElement)&&(a(f.height,g.options.height.max)&&(p=d(f.height,g.options.height.max),g.frameElement.height=p),a(f.width,g.options.width.max)&&(k=d(f.width,g.options.width.max),
g.frameElement.width=k));return{height:p,width:k}}return{minPixels:d,childResize:function(f,g){var m,p=f.body.config.client.instanceId;c.console.log("Child asking to be resized, id: [%s]",p);if(c.isNil(g)){m=f.body.size;var l,B,q,r,t;c.console.log("Resizing VF [%s] to ",p,m);l=c.byId(p);B=l.getAttribute("data-max-canvas-width")||"final";q=l.getAttribute("data-max-canvas-height")||"infinite";c.console.log("Max Width [%s] Max Height [%s]",B,q);a(m.height,q)&&(t=d(m.height,q),l.style.height=t);a(m.width,
B)&&(r=d(m.width,B),l.style.width=r);m={height:t,width:r};n.events.publish({name:"sfdc.resize",payload:m,target:{iframe:p}});n.events.publish({name:"sfdc.resize",payload:m,target:{canvas:"parent"}})}else m=e(f.body.size,g),n.events.publish({name:"canvas.resize",payload:m},g),n.events.publish({name:"canvas.resize",payload:m,target:{canvas:"parent"}})},parentResize:function(a,b){c.isNil(b)?(c.each(f,function(b){c.isNil(b.instanceId)||(e(a,b),n.events.publish({name:"canvas.resize",payload:a},b))}),n.events.publish({name:"canvas.resize",
payload:a,target:{canvas:"parent"}})):c.isNil(b.canvas)||c.each(f,function(c,d){var f=d.split(":");f[f.length-1]===b.canvas&&(e(a,c),n.events.publish({name:"canvas.resize",payload:a,target:b}),n.events.publish({name:"canvas.resize",payload:a,target:{canvas:"parent"}}))})}}}();return{events:a,services:function(a,d){function e(h,g){var k=g.getResponseHeader("Content-Type"),p={};p.seq=a;p.parentVersion=r;p.clientVersion=f[d].cversion;p.payload=k&&h&&0<=k.indexOf("application/json")?q.parse(h):h;p.status=
g.status;p.statusText=g.statusText;p.responseHeaders=g.getAllResponseHeaders();p.type="callback";c.xd.post(p,c.stripUrl(f[d].app.canvasUrl),D(d,y))}return{ctx:function(a,b){var f=b.app.namespace,p=b.app.developerName,n=b.app.referenceId,l=c.byId(y+d),u=c.isNil(b.cversion)?r:b.cversion,v=Q(b.options),f="/services/data/v"+u+"/platformconnect/canvascontext?"+(!c.isNil(n)?"referenceId\x3d"+n:"canvas\x3d"+p+(!c.isNil(f)?"\x26namespace\x3d"+f:"")),l={success:e,failure:e,headers:{Authorization:"OAuth "+
a.body.accessToken,Accept:"application/json"},contentType:"application/json",method:"PUT",data:q.stringify({environment:{dimensions:{height:l&&l.height||null,width:l&&l.width||null},parameters:b.options.parameters,displayLocation:b.options.displayLocation,sublocation:b.options.sublocation,record:v}})},f=t(f,l);Sfdc.Ajax.request(f,l)},ajax:function(a){var b;a.body.config.success=e;a.body.config.failure=e;b=a.body.url;a=a.body.config;b=t(b,a);Sfdc.Ajax.request(b,a)},refresh:function(a,b){var d,f,l;
if("OAUTH"===b.app.authType)throw LC.getLabel("CanvasParentJs","authTypeMismatch");S(b.instanceId,b.options,function(a,b){200==b.status?(d=q.parse(a),l=d.response.split("."),f=q.parse(c.decode(l[1])),c.isNil(f.client.oauthToken)?e("{}",{status:403,statusText:LC.getLabel("CanvasParentJs","userApprovalRequired"),getAllResponseHeaders:function(){return b.getAllResponseHeaders()},getResponseHeader:function(a){return b.getResponseHeader(a)}}):e(a,b)):e(a,b)},e)},repost:function(a,b){var c=a.body.refresh||
!1;if("OAUTH"===b.app.authType)throw LC.getLabel("CanvasParentJs","authTypeMismatch");c&&(b.sr=null);u(b.parentElem,b.instanceId,!1);b.options.showLoadingStatus=null;b.startTime=(new Date).getTime();W(b.instanceId,b.parentElem,b.options)}}},frame:e}}();return{render:Y,feed:function(a,e,b){var d=c.byId(e),k=c.byId("canvas-icon-"+b.canvasId),h;h=L(a.app,b.canvasId);d&&"block"===d.style.display?(d.style.display="none",k.style.display="block",u(e,h)):c.isNil(f[h])&&(b.onCanvasAppLoad=function(){d.style.display=
"block";k.style.display="none"},b.onCanvasAppError=b.onCanvasAppLoad,b.parameters=q.parse(b.parameters),Y(a,d,b))},subscribe:n.events.parentSubscribe,unsubscribe:n.events.parentUnsubscribe,publish:n.events.parentPublish,resize:n.frame.parentResize,close:function(a,c,b){a=L(a,b);u(c,a)}}}();c.module("Sfdc.canvas.parent",M)})(Sfdc.canvas);
(function(g){var h=function(){function b(a,c){for(var b=["payload",c],d=a;d&&b.length;)d=d[b.shift()];if(0===b.length)return d}function f(a){return Sfdc.isDefAndNotNull(a)&&(15===a.length||18===a.length)}function e(a,c){var b;if($A&&(b=$A.get("e."+a)))b.setParams(c),b.fire();else throw Error("S1 framework or event ["+a+"] is not found");}var d=[];d["s1.back"]=function(){return{handle:function(a){a=b(a,"refresh");Sfdc.isDefAndNotNull(a)&&Sfdc.assert(Sfdc.isBoolean(a),'{"name" : "s1.back", "payload" : {"refresh" : true}} - The refresh parameter is optional but when specified should be a boolean value indicating that you want the page we are going back to should be refreshed.');
e("one:back",{refresh:a})}}}();d["s1.navigateToSObject"]=function(){return{handle:function(a){var c=b(a,"recordId");a=b(a,"view");Sfdc.assert(f(c),'{"name" : "s1.navigateToSObject", "payload" : {"recordId": "recordId", "view": "view"}} - RecordID is a required parameter and must be either 15 or 18 characters long.');Sfdc.isDefAndNotNull(a)&&Sfdc.assert(Sfdc.isString(a),'{"name" : "s1.navigateToSObject", "payload" : {"recordId": "recordId", "view": "view"}}  - view is an optional parameter but when specified should be done so as a string. The default available values are chatter, related and detail. With detail being the default.');
e("force:navigateToSObject",{recordId:c,slideDevName:a})}}}();d["s1.navigateToURL"]=function(){return{handle:function(a){var c=b(a,"url");a=b(a,"isredirect");Sfdc.assert(!Sfdc.isEmpty(c)&&Sfdc.isString(c),'{"name" : "s1.navigateToURL", "payload" : {"url" : "https://na10.salesforce.com/apex/v1.apexp", "isredirect" : true}} - url is a required parameter of type string indicating the location you would like to navigate to.');Sfdc.isDefAndNotNull(a)&&Sfdc.assert(Sfdc.isBoolean(a),'{"name" : "s1.navigateToURL", "payload" : {"url" : "https://na10.salesforce.com/apex/v1.apexp", "isredirect" : true}} - isredirect is an optional parameter of boolean type indicating that the new page should take the old ones place in the browser history.');
e("force:navigateToURL",{url:c,isredirect:a})}}}();d["s1.navigateToFeed"]=function(){return{handle:function(a){var c=b(a,"subjectId");a=b(a,"type");Sfdc.assert(f(c),'{"name" : "s1.navigateToFeed", "payload" : {"subjectId" : "subjectId", "type" : "NEWS"}} - subjectId is a required parameter of type string that indicates the record ID of the entity whos feed you would like to view.');Sfdc.assert(Sfdc.isString(a),'{"name" : "s1.navigateToFeed", "payload" : {"subjectId" : "subjectId", "type" : "NEWS"}} - type is a required parameter of type String that is the Feed type you are trying to display.  Current possible values; NEWS, RECORD, TO, FILES, GROUPS, PEOPLE, BOOKMARKS, COMPANY and TOPICS.');
Sfdc.assert(a===a.toUpperCase(),'{"name" : "s1.navigateToFeed", "payload" : {"subjectId" : "subjectId", "type" : "NEWS"}} - type must be all uppercase letters.  Current possible values; NEWS, RECORD, TO, FILES, GROUPS, PEOPLE, BOOKMARKS, COMPANY and TOPICS.');e("force:navigateToFeed",{subjectId:c,type:a})}}}();d["s1.navigateToFeedItemDetail"]=function(){return{handle:function(a){a=b(a,"feedItemId");Sfdc.assert(f(a),'{"name" : "s1.navigateToFeedItemDetail", "payload" : {"feedItemId" : "feedItemId"}} - feedItemId is a required parameter of type string indicating the feed item to drill into.');
e("force:navigateToFeedItemDetail",{feedItemId:a})}}}();d["s1.navigateToRelatedList"]=function(){return{handle:function(a){var c=b(a,"relatedListId");a=b(a,"parentRecordId");Sfdc.assert(Sfdc.isString(c),'{"name" : "s1.navigateToRelatedList", "payload" : {"relatedListId" : "relatedListId", "parentRecordId" : "parentRecordId" }} - relatedListId is a required value of type String. For standard lists, we use the format Related[Entity]List such as RelatedContactList or RelatedAccountList. For custom lists, you\'ll need to use the ID of the related list.');
Sfdc.assert(f(a),'{"name" : "s1.navigateToRelatedList", "payload" : {"relatedListId" : "relatedListId", "parentRecordId" : "parentRecordId" }} - parentRecordId is a required value and should be an id of 15 or 18 characters long. The actual id of the entity for which to query the data for the related list.');e("force:navigateToRelatedList",{relatedListId:c,parentRecordId:a})}}}();d["s1.navigateToList"]=function(){return{handle:function(a){var c=b(a,"listViewId"),d=b(a,"listViewName");a=b(a,"scope");
Sfdc.assert(f(c),'{"name" : "s1.navigateToList", "payload" : {"listViewId" : "listViewId", "listViewName" : "listViewName", "scope" : "scope"}} - listViewId is a required parameter of length 15 to 18 characters. Which is the unique ID of the listView you wish to display.');Sfdc.assert(Sfdc.isString(a),'{"name" : "s1.navigateToList", "payload" : {"listViewId" : "listViewId", "listViewName" : "listViewName", "scope" : "scope"}} - scope is a required parameter of type string. It is the entity name associated with this listView. If it is a list of Accounts then "Account", Custom objects of type color, then "Color__c".');
Sfdc.isDefAndNotNull(d)&&Sfdc.assert(Sfdc.isString(d),'{"name" : "s1.navigateToList", "payload" : {"listViewId" : "listViewId", "listViewName" : "listViewName", "scope" : "scope"}} - listViewName is optional but when supplied should be done so as a string. It shows up at the top of the list as the primary header of the list.');e("force:navigateToList",{listViewId:c,listViewName:d,scope:a})}}}();d["s1.createRecord"]=function(){return{handle:function(a){var c=b(a,"entityName");a=b(a,"recordTypeId");
Sfdc.assert(Sfdc.isString(c),'{"name" : "s1.createRecord" "payload" : {"entityName" : "entityName", "recordTypeId" : "recordTypeId"}} - entityName is a required parameter of type String. It should match the entity name in the API, such as Account, Contact, CustomObject__c.');Sfdc.isDefAndNotNull(a)&&Sfdc.assert(f(a),'{"name" : "s1.createRecord" "payload" : {"entityName" : "entityName", "recordTypeId" : "recordTypeId"}} - recordTypeId is an optional parameter but when specified should be an id of length 15 or 18. This should be the ID of the record type.');
e("force:createRecord",{entityApiName:c,recordTypeId:a})}}}();d["s1.editRecord"]=function(){return{handle:function(a){a=b(a,"recordId");Sfdc.assert(f(a),'{"name" : "s1.editRecord", "payload" : {"recordId" : "recordId"}} - recordId is a required parameter in the form of an id with length 15 or 18 characters. It is simply the ID of the entity you wish to edit.');e("force:editRecord",{recordId:a})}}}();return{handleEvent:function(a){var c=d[a.name];try{c?c.handle(a):g.console.error("S1 event handler NOT FOUND for the event ["+
a.name+"]")}catch(b){g.console.error(b)}},canHandle:function(a){return"s1"===a.name.split(/\./)[0].toLowerCase()}}}();g.module("Sfdc.canvas.s1",h)})(Sfdc.canvas);

//# sourceMappingURL=/javascript/1428053751000/canvas/source/CanvasRendering.js.map
