/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
(function(b,f){WalkthroughCodeVersion="192.0";WalkthroughApp={GACK_KEY:"WALKTHROUGHS"};WalkthroughStatus={NEW:"new",STARTED:"started",STOPPED:"stopped",FINISHED:"finished"};WalkthroughTypes={TRIAL:"trial",TOUR:"tour"};SalesforceClouds={SALES:"sales",SERVICE:"service",PLATFORM:"platform",IDENTITY:"identity",WORK:"work",DEVELOPER:"developer",CHATTER:"chatter",FOUNDATION:"foundation",FINANCIAL_WEALTH_MGMT:"financialWealthManagement",FINANCIAL_INSURANCE:"financialInsurance",FINANCIAL_HEDGE_FUND:"financialHedgeFund",
FINANCIAL_INVESTMENT:"financialInvestment",FINANCIAL_PE_VC:"financialPrivateEquityVC",HEALTHCARE_MEDICAL_DEVICES:"hlsMedicalDevices",HEALTHCARE_PHYSICIAN_REFERRAL_MGMT:"hlsPhysicianReferralManagement",EVENTS_SALES:"eventsSales",EVENTS_SERVICE:"eventsService",EVENTS_PLATFORM:"eventsPlatform",INSIGHTS:"insights"};SidebarExcludedPages=["/01Z.*/e.*","/sfc.*"];b.provide("SfdcApp.Walkthrough.Core.LogCollector",{name:"SfdcApp.Walkthrough.Core.LogCollector",$constructor:function(a){this.buffer=a},log:function(a,
c,d){b.isString(a)||(a=b.Logging.formatError(a));this.buffer.push(a)}});sendWalkthroughGack=function(a){a.message||(a.message="There was no error message for the GACK - something has gone completely awry.");a.message+="\n\nThe actual page URL was: "+window.location;try{var c=[],d=new SfdcApp.Walkthrough.Core.LogCollector(c);b.ClientLogging.addRelay(d,!0);a.message+="\n\nThe most recent log activity was:\n\n    ";a.message+=c.join("\n    ")}catch(e){b.log("Error during GACK creation - all hope is lost. The latest error was: "+
e)}b.sendGack(WalkthroughApp.GACK_KEY,a)};WalkthroughMessageSeverity={ERROR:"error",WARNING:"warning",INFO:"info"};WalkthroughAuthoringHelp="https://gus.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g\x3d0F9B000000008fd";b.isFunction(b.group)||(b.group=function(a){window.console&&console.group?console.group.call(console,a):b.log(a)},b.groupCollapsed=function(a){window.console&&console.groupCollapsed?console.groupCollapsed.call(console,a):b.log(a)},b.groupEnd=function(a){b.log("\x3c\x3c\x3c ENDGROUP: "+
(a||""));window.console&&console.groupEnd&&console.groupEnd.call(console)})})(Sfdc,this);
(function(a,l){a.provide("SfdcApp.Walkthrough.Core.Runtime.TaskQueue",new a.Class({$decorators:[a.Class.Config],$constructor:function(b){function c(a,b){return("00"+a).slice(-b)}b=a.apply({tasks:[],callbacks:{}},b||{},!0);this.setConfig(b);a.assert(this.config.tasks.length,"The task queue is empty!");this.config.callbacks.success||(this.config.callbacks.success=function(){a.log("The last task was successful, but no callback function was provided.")});this.config.callbacks.failure||(this.config.callbacks.failure=
function(b){a.log("The last task failed, but no callback function was provided.");a.log("The result of the failed task was: "+b)});this.config.id||(this.config.id="task-queue");b=new Date;this.config._created=c(b.getHours(),2)+":"+c(b.getMinutes(),2)+":"+c(b.getSeconds(),2)+"."+c(b.getMilliseconds(),3);this.config.tasks=a.clone(this.config.tasks);var g=this.config.callbacks.failure;this.config.callbacks.failure=function(a){this.logTaskAction("One of the internal tasks failed - halting execution and invoking failure callback...");
g(a);this.logTaskAction("Finished executing task queue.")}.bind(this)},execute:function(b,c){a.assert(b,"The task queue's scope object is null or undefined!");this.logTaskAction("Creating task queue with "+this.config.tasks.length+" tasks...");var g=function(){return{success:d.shift(),failure:this.config.callbacks.failure}}.bind(this),d=a.Array.map(this.config.tasks,function(c){return function(){var e=this.config.tasks.length,f=e-d.length+1;try{1<f&&this.logTaskAction("Completed task #"+(f-1)+" of "+
e);this.logTaskAction("Starting task #"+f+" of "+e);var h=[g].concat(a.Array.toArray(arguments));c.apply(b,h)}catch(k){this.logTaskAction("Caught error on task #"+f+" of "+e),this.config.callbacks.failure(k)}}.bind(this)},this);d.push(function(b){var c=this.config.tasks.length;this.logTaskAction("Completed task #"+c+" of "+c);a.groupEnd(this.logTaskPrefix()+": Finished executing task queue, invoking original callback...");this.config.callbacks.success(b)}.bind(this));a.group(this.logTaskPrefix());
this.logTaskAction("Starting task queue by executing the first task...");d.shift().apply(this,c||[])},logTaskPrefix:function(){return"TASK Q ---\x3e "+this.config.id+" ["+this.config._created+"]: "},logTaskAction:function(b){a.log(this.logTaskPrefix()+b)}}))})(Sfdc,this);
(function(a,f){a.provide("SfdcApp.Walkthrough.Core.Runtime.Upgrader",new a.Class({$decorators:[a.Class.Config],$constructor:function(b){b=a.apply({version:WalkthroughCodeVersion,versionKey:"walkthrough.version",player:null},b||{},!0);this.setConfig(b)},applyChangesForLatestVersion:function(){for(var b=f.UserContext.userId+".walkthrough.instances",c=Object.keys(localStorage),d=0;d<c.length;d++)if(0===c[d].indexOf(b)){var g=a.LocalStorage.getItem(c[d]),e=b.replace("walkthrough","trials.walkthrough");
a.log("Moving data stored at "+c[d]+" to "+e+"...");a.LocalStorage.setItem(e,g);a.LocalStorage.removeItem(c[d])}},hasNewVersion:function(){var b=a.LocalStorage.getItem(this.config.versionKey);if(!b)return a.log("Could not find walkthrough version number in local storage - this is the user's first time logging in."),!0;a.log("The version number in local storage is: "+b);a.log("The version number of the current code is: "+this.config.version);var b=b.split("."),c=this.config.version.split(".");return parseInt(c[0],
10)>parseInt(b[0],10)||parseInt(c[1],10)>parseInt(b[1],10)},patch:function(){var b=a.LocalStorage.getItem(this.config.versionKey);b?a.log("Upgrading the walkthrough app from version "+b+" to "+this.config.version):a.log("Installing the walkthrough app for the very first time. The version number is: "+this.config.version);this.applyChangesForLatestVersion();a.log("Saving new version number in local storage: "+this.config.version);a.LocalStorage.setItem(this.config.versionKey,this.config.version)}}))})(Sfdc,
this);
(function(b,h){b.provide("SfdcApp.Walkthrough.Core.Runtime.Definitions.Caching",{clearCache:function(){b.log("Clearing all data in the walkthrough definition cache!");b.LocalStorage.clear(this.getBaseStorageKey())},generateMappingKey:function(a){return this.getBaseStorageKey()+"."+a+".walkthroughs."+this.getLanguage()},generateRolesKey:function(){return this.getBaseStorageKey()+".roles."+this.getLanguage()},generateSaveConflictKey:function(a){return this.getBaseStorageKey()+"."+a+"."+this.getLanguage()+
".saveconflict"},generateWalkthroughKey:function(a){return this.getBaseStorageKey()+"."+a+"."+this.getLanguage()},getBaseStorageKey:function(){return"walkthrough."+this.config.collection},getLanguage:function(){return this.config.language},getLocalStorageItem:function(a){b.log("Retrieving local storage item: "+a);if(a=b.LocalStorage.getItem(a))return b.JSON.parse(a);b.log("\tNo value found!");return null},getRoleDefinitions:function(){var a=this.generateRolesKey(),a=this.getLocalStorageItem(a);return!a?
(b.log("No role definitions found - have they been put in the cache?"),[]):a},getWalkthroughDefinition:function(a,d){b.assert(a,"Walkthrough ID is null or undefined!");var c=this.generateWalkthroughKey(a),c=this.getLocalStorageItem(c);return!c?(b.log("No walkthrough definition found for '"+a+"' - has it been put in the cache?"),null):d&&!c.steps?(b.log("Caller wants steps but we haven't retrieved them yet - returning null."),null):c},getWalkthroughDefinitions:function(a,d){b.assert(a,"Role ID is null or undefined!");
var c=this.generateMappingKey(a),c=this.getLocalStorageItem(c);if(!c)return b.log("No walkthroughs found for role: "+a),[];var f=[];b.log("Retrieving "+c.length+" walkthroughs for role: "+a);for(var e=0;e<c.length;e++){var g=this.getWalkthroughDefinition(c[e],d);g&&f.push(g)}return f},saveLocalStorageItems:function(a,d,c){b.log("Saving "+a+" in local storage "+(c.saveList?"as a single list":"as individual entries")+".");c.ignore&&b.log("The following IDs will be ignored (not saved): "+c.ignore);if(c.saveList){d=
b.JSON.stringify(d,null,"\t");var f=c.keygenerator?c.keygenerator():a;b.log("Saving list: "+f);b.LocalStorage.setItem(f,d)}else b.isObject(d)&&(b.log("Converting single object to single-entry array."),f=[],f.push(d),d=f),b.each(d,function(e){var d=b.JSON.stringify(e,null,"\t");c.ignore&&0<=c.ignore.indexOf(e.id)?b.log("Ignoring item '"+e.id+"' as requested."):(e=c.keygenerator?c.keygenerator(e.id):a+"."+e.id,b.log("Saving item: "+e),b.LocalStorage.setItem(e,d))});b.log("Successfully saved "+a+" to local storage.")}})})(Sfdc,
this);
(function(c,d){c.provide("SfdcApp.Walkthrough.Core.Runtime.Definitions.IProvider",{clearCache:function(){},getRoleDefinitions:function(){},getWalkthroughDefinition:function(a,b){},getWalkthroughDefinitions:function(a,b){},loadRoleDefinitions:function(a,b){},loadWalkthroughDefinition:function(a,b,c){},loadWalkthroughDefinitions:function(a,b,c){}})})(Sfdc,this);
(function(c,d){c.provide("SfdcApp.Walkthrough.Core.Runtime.Instances.IProvider",{addFinishedWalkthrough:function(a,b){},clearCache:function(){},createWalkthroughInstance:function(a,b){},deleteWalkthroughInstance:function(a,b){},getActiveInstance:function(){},getFinishedWalkthroughs:function(){},getSelectedRole:function(){},getWalkthroughInstance:function(a){},isInitialized:function(){},loadActiveInstance:function(a){},loadFinishedWalkthroughs:function(a){},loadWalkthroughInstance:function(a,b){},
removeActiveInstance:function(a){},setInitialized:function(a){},updateActiveInstance:function(a,b){},updateSelectedRole:function(a,b){},updateWalkthroughInstance:function(a,b){}})})(Sfdc,this);
(function(a,d){a.provide("SfdcApp.Walkthrough.Core.Runtime.Locators.ILocator",{findElements:function(c,b){},hasValue:function(c,b,a){},whereAreWe:function(a,b){}})})(Sfdc,this);
(function(b,h){b.provide("SfdcApp.Walkthrough.Core.Runtime.Util.Dom",{hasValue:function(d,a,c){b.log("Testing "+d+" for a non-zero-length value...");a=this.searchAll(d,a);a=a.length?a[0]:null;if(!a)return b.log("Target element is not even on the page: "+d),!1;if("radio"==a.type||"checkbox"==a.type)return b.log("Target element is a radio button or checkbox that "+(a.checked?"was":"was NOT")+" selected."),a.checked;a=b.String.trim(a.value);if(!a.length)return b.log("Target input field does not have a non-zero-length value: "+
d),!1;if(c&&c!=a)return b.log("Target input field has a value, but it doesn't match the required value:"),b.log("\t"+a+" !\x3d "+c),!1;b.log("Target input field has the following value: "+a);return!0},searchAll:function(d,a){var c=[document];if(a){var e=b.select(a),f=e.length;if(!f)return b.log("There are no iframes that match the selector: "+a),[];for(var c=[],g=0;g<f;g++)try{c.push(e[g].contentWindow.document)}catch(h){b.log("Found an iframe that belongs to another salesforce.com domain - ignoring.")}b.log("There are "+
c.length+" iframes that have searchable documents.")}e=[];for(f=0;f<c.length&&!e.length;f++)e=b.select(d,c[f]);return e}})})(Sfdc,this);
(function(b,f){var d=new b.Event.EventManager(["walkthrough-core:postMessage","walkthrough-core:clearMessages"]);b.provide("SfdcApp.Walkthrough.Core.Runtime.Util.Events",{add:function(a,c,e){b.log("Events.add: Registering listener for '"+a+"'");d.add(this,a,c,e)},fire:function(a,c){b.log("Events.fire: Firing event for '"+a+"'");d.fireEvent(this,a,{data:c})},remove:function(a,c){b.log("Events.remove: Removing listener for '"+a+"'");d.remove(this,a,c)},postMessage:function(a){this.fire("walkthrough-core:postMessage",
a)}})})(Sfdc,this);
(function(b,d){var c=/([a-zA-Z0-9]{3})[a-zA-Z0-9]{2}00[a-zA-Z0-9]{8}/g;b.provide("SfdcApp.Walkthrough.Core.Runtime.Util.SObject",{findID:function(a){return a.search(c)},regexp:function(a){return a?a+"[a-zA-Z0-9]{2}00[a-zA-Z0-9]{8}":c.source},replaceID:function(a,b){return a.replace(c,b)}})})(Sfdc,this);
(function(a,b){a.provide("SfdcApp.Walkthrough.Core.Runtime.Validators.IStepValidator",{canStart:function(c,a){},isCompleted:function(a,b){},validateSchema:function(a){}})})(Sfdc,this);
(function(a,c){a.provide("SfdcApp.Walkthrough.Core.Ui.ImportWizard",new a.Class({$implements:[],$constructor:function(h){function l(){var d=this,b="ImportWizard-"+a.newUID();c.$A&&($A.eventService.addHandler({event:"ui:closeDialog",globalId:b,handler:function(){d.notify("onclose")}}),f.add(a.first(".setupQiDatasourceSelectorList .outlook"),"click",g.call(this,"outlook")),f.add(a.first(".setupQiDatasourceSelectorList .gmail"),"click",g.call(this,"gmail")),f.add(a.first(".setupQiDatasourceSelectorList .linkedIn"),
"click",g.call(this,"linkedIn")),f.add(a.first(".setupQiDatasourceSelectorList .act"),"click",g.call(this,"act")));(b=a.Url.getUrlParameters(c.location.search))&&"true"===b.openImport&&d.open(null,{source:"Url"})}function g(d){var b=this;return function(e){a.Event.getEventTarget(e,".upload")&&b.notify("onImportTypeSelect",d)}}function k(d){var b=this;q("setup:qiAccountsAndContacts",n,m,function(){d&&d();a.log("SfdcApp.Walkthrough.Core.Ui.ImportWizard: Loaded import dialog.");b.notify("onload")})}
function p(a,b){var e=c.$A.get("e.setup:qiOpenImportDialog");e.setParams({triggerEvent:a});e.fire();this.notify("onopen",b&&b.source||"Walkthrough")}function q(d,b,e,f){var g=c.UserContext.getUrl("/_ui/core/dataimporter/servlet/ImportWizardAuraIntegrationServlet");a.Ajax.post(g,null,{data:{initializeAura:void 0===c.$A,locatorDomId:e,localId:b,tag:d},escape:encodeURIComponent,complete:function(b){b=a.JSON.parseWithCSRF(b);var c=a.first("#"+e),c=a.Dom.create(c);b&&b.html?a.Dom.updateHTML(c,"\x3cinput type\x3d'hidden'/\x3e"+
b.html,!0,f):a.error("SfdcApp.Walkthrough.Core.Ui.ImportWizard : Failed to load component "+d)}})}var n="quickImport",m="walkthrough-quick-import",f=new a.Event.EventManager("onload","onopen","onclose","onImportTypeSelect");this.attach=function(a,b,c){f.add(this,a,b,c)};this.detach=function(a,b){f.remove(this,a,b)};this.notify=function(a,b){f.fireEvent(this,a,{data:b})};this.load=function(){k.call(this)};this.open=function(a,b){var e=this;c.$A&&c.$A.getRoot()&&c.$A.getRoot().find(n)?p.call(e,a,b):
k.call(this,function(){p.call(e,a,b)})};(function(){this.attach("onload",l);a.onReady(function(){a.first("#"+m)||a.Dom.create(c.document.body,{id:m});this.load()}.bind(this))}).call(this)}}));SfdcApp.Walkthrough.Core.Ui.ImportWizard.importGmailContacts=function(h,l,g){var k={code:h,state:l,csrfToken:g};(!h||!l||!g)&&a.error(a.String.format("SfdcApp.Walkthrough.Core.Ui.ImportWizard : Invalid OAuth callback parameters: code\x3d{code}, state\x3d{state}, csrfToken\x3d{csrfToken}",k));h=c.$A.get("e.setup:qiImportGmailContacts");
h.setParams(k);h.fire()}})(Sfdc,this);
(function(a,f){a.provide("SfdcApp.Walkthrough.Core.Ui.RoleSelector",a.Class({config:{eventManager:new a.Event.EventManager,roles:null,callback:null},$decorators:[a.Class.Config],$constructor:function(b){this.setConfig(b||{});a.assert(this.config.roles,"No role list provided to the role selector!");a.assert(this.config.roles.length,"Zero roles provided to the role selector!");a.assert(this.config.callback,"No callback provided to the role selector!")},getRoleFromEvent:function(b){b=a.Event.getEventTarget(b);
var c=a.Dom.getParent(b);return b.getAttribute("data-role-id")||c.getAttribute("data-role-id")},remove:function(b){b=a.first(b);a.Dom.removeChild(b)},roleSelected:function(b){if(b.keyCode&&13!=b.keyCode)a.log("Role selector received non-Enter key - ignoring event.");else{a.log("Processing role selection event...");b=this.getRoleFromEvent(b);a.log("The selected role is: "+b);try{this.config.callback(b),this.remove("#walkthrough-role-selector"),this.remove("#walkthrough-role-selector-overlay")}catch(c){a.log("Failed to continue role selection workflow: "+
c)}finally{this.visible=!1,this.rootElement=null,this.setAriaHidden(!1)}}},setAriaHidden:function(b){a.log("Toggling aria-hidden attribute: "+(b?"on":"off"));for(var c=a.select("body \x3e *"),d=0;d<c.length;d++)c[d].setAttribute("aria-hidden",b)},show:function(b){a.assert(b,"No container element in which to draw role selector!");a.log("Creating role selector window...");for(var c=[],d=0;d<this.config.roles.length;d++){var e=this.config.roles[d];a.log("Rendering role choice: "+e.id);e=a.Template.render('\x3cdiv id\x3d"{{roleid}}-choice" class\x3d"walkthrough-role-choice" tabindex\x3d"{{tabindex}}" data-role-id\x3d"{{roleid}}"\x3e\x3cdiv class\x3d"walkthrough-role-avatar walkthrough-role-{{roleid}}"\x3e\x3c/div\x3e\x3cp class\x3d"walkthrough-role-name"\x3e\x3clabel for\x3d"{{roleid}}-choice"\x3e{{rolelabel}}\x3c/label\x3e\x3c/p\x3e\x3c/div\x3e',
{roleid:e.id,rolelabel:e.label,tabindex:d+1});c.push(e)}a.log("Applying overlay to existing UI...");a.Dom.create(b,{id:"walkthrough-role-selector-overlay"});this.setAriaHidden(!0);a.log("Creating window on top of overlay and adding in role choices...");this.rootElement=a.Dom.create(b,{id:"walkthrough-role-selector",className:"zen",attributes:{role:"dialog",tabindex:"-1","aria-labelledby":"walkthrough-role-selector-description","aria-hidden":"false"}});b=a.Template.render('\x3cdiv class\x3d"zen-header zen-pal"\x3e\x3cdiv id\x3d"walkthrough-role-selector-title"\x3e{{title}}\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"zen-header zen-phl"\x3e\x3cdiv id\x3d"walkthrough-role-selector-description"\x3e{{description}}\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"zen-body zen-phl"\x3e\x3cdiv id\x3d"walkthrough-role-selector-list"\x3e\x3c/div\x3e\x3c/div\x3e',
{title:LC.getLabel("walkthroughs","role_selector_title"),description:LC.getLabel("walkthroughs","role_selector_description")});a.Dom.updateHTML(this.rootElement,b);b=a.first("#walkthrough-role-selector-list");a.Dom.updateHTML(b,c.join(""));c=this.roleSelected.bind(this);this.config.eventManager.add(b,"click",c);this.config.eventManager.add(b,"keypress",c);try{a.log("Auto-focusing on the role selector window..."),this.rootElement.focus()}catch(f){a.warn("Failed to auto-focus on the role selector window.")}this.visible=
!0;a.log("Successfully created role selector window.")}}))})(Sfdc,this);
(function(a,r){var s={t:"tl-tl",l:"tl-tl",r:"tr-tr",b:"bl-bl"},t={t:[0,-4],l:[-6,0],r:[6,0],b:[0,4]},u={l:!0,r:!0};a.provide("SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.Border",{$constructor:function(d){d=d||{};var q=d.container||r.document.body,c=null,l=[],m;this.align=function(){var b,e,h,f;if(c){a.isArray(l)||(l=[l]);a.isEmpty(m)&&(m="b");b=l;f=m;var g=1E9,k=1E9;h=e=0;f||(f="b");for(var n,p,d=0;d<b.length;d++)p=b[d],a.Dom.isVisible(p,!0)&&(n=a.Dom.getElementXY(p),g=Math.min(n.y,g),k=Math.min(n.x,
k),e=Math.max(a.Dom.getWidth(p)+n.x,e),h=Math.max(a.Dom.getHeight(p)+n.y,h));b=e-k;e=h-g;h=s[f];f=t[f];g=a.Dom.create(q,{style:{position:"absolute",top:g+"px",left:k+"px",width:b+"px",height:e+"px"}});k=u[m]?{height:e+"px",width:"5px"}:{width:b+"px",height:"5px"};a.Dom.alignTo(c,g,h,f);a.Dom.setStyles(c,k);a.Dom.removeChild(g)}};this.getHashCode=function(){return"SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.Border"};this.show=function(b){a.assert(0===b.highlight.indexOf("border-"),"The highlight mode must be one of border-b, border-t, border-l or border-r. With the value after the hyphen equaling the side to highlight.");
a.isEmpty(b.targets)||(c||(c=a.Dom.create(q,{className:"zen walkthrough-border-highlight"})),m=b.highlight.split("-")[1],l=b.targets,this.align())};this.hide=function(){c&&(a.Dom.removeChild(c),c=null)}}})})(Sfdc,this);
(function(a,r){a.provide("SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.LegacyWindow",{$constructor:function(p){p=p||{};var q=p.container||r.document.body,c=null,f=[],m=[];this.align=function(){var b,d,g,h;if(c){a.isArray(m)||(m=[m]);b=m;g=h=1E9;for(var k=0,n=0,e,l=0;l<b.length;l++)e=b[l],a.Dom.isVisible(e,!0)&&(d=a.Dom.getElementXY(e),h=Math.min(d.y,h),g=Math.min(d.x,g),k=Math.max(a.Dom.getWidth(e)+d.x,k),n=Math.max(a.Dom.getHeight(e)+d.y,n));b=h;d=g;g=k-g;h=n-h;n=a.Dom.create(q,{style:{position:"absolute",
top:b+"px",left:d+"px",width:g+"px",height:h+"px"}});k=b+h/2+"px";e=d+g/2+"px";a.Dom.setStyles(f[0],{top:0,right:0,left:0,height:k});a.Dom.setStyles(f[1],{top:0,left:0,bottom:0,width:e});a.Dom.setStyles(f[2],{right:0,left:0,bottom:0,top:k});a.Dom.setStyles(f[3],{top:0,right:0,bottom:0,left:e});l={duration:"1000"};a.Animation.css(f[0],"height",k,b+"px",l);a.Animation.css(f[1],"width",e,d+"px",l);a.Animation.css(f[2],"top",k,b+h+"px",l);a.Animation.css(f[3],"left",e,d+g+"px",l);a.Dom.removeChild(n)}};
this.getHashCode=function(){return"SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.LegacyWindow"};this.show=function(b){a.isEmpty(b.targets)||(c||(c=a.Dom.create(q,{className:"zen walkthrough-opaque-window"}),f=[a.Dom.create(c,{className:"walkthrough-opaque-window-pane-top"}),a.Dom.create(c,{className:"walkthrough-opaque-window-pane-left"}),a.Dom.create(c,{className:"walkthrough-opaque-window-pane-bottom"}),a.Dom.create(c,{className:"walkthrough-opaque-window-pane-right"})]),m=b.targets,this.align())};
this.hide=function(){c&&(a.Dom.removeChild(c),c=null)}}})})(Sfdc,this);
(function(a,q){a.provide("SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.ModernWindow",{$constructor:function(n){n=n||{};var p=n.container||q.document.body,b=null,k=[];this.align=function(){var c,d,e,f;if(b){a.isArray(k)||(k=[k]);c=k;e=f=1E9;for(var l=0,m=0,h,g=0;g<c.length;g++)h=c[g],a.Dom.isVisible(h,!0)&&(d=a.Dom.getElementXY(h),f=Math.min(d.y,f),e=Math.min(d.x,e),l=Math.max(a.Dom.getWidth(h)+d.x,l),m=Math.max(a.Dom.getHeight(h)+d.y,m));c=f;d=e;e=l-e;f=m-f;m=a.Dom.create(p,{style:{position:"absolute",
top:c+"px",left:d+"px",width:e+"px",height:f+"px"}});l=c+f/2+"px";h=d+e/2+"px";a.Dom.setStyles(b,{width:0,height:0,top:0,left:0});g={tryCSS:!1,duration:1E3};a.Animation.css(b,"width","1px",e+"px",g);a.Animation.css(b,"height","1px",f+"px",g);a.Animation.css(b,"top",l,c+"px",g);a.Animation.css(b,"left",h,d+"px",g);a.Dom.removeChild(m)}};this.getHashCode=function(){return"SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.ModernWindow"};this.show=function(c){a.isEmpty(c.targets)||(b||(b=a.Dom.create(p,{className:"zen walkthrough-opaque-window-modern"}),
a.Dom.create(b)),k=c.targets,this.align())};this.hide=function(){b&&(a.Dom.removeChild(b),b=null)}}})})(Sfdc,this);
(function(a,b){a.provide("SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.Window",{getHighlightClass:function(){return a.userAgent.isIE7||a.userAgent.isIE8?SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.LegacyWindow:SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.ModernWindow},newInstance:function(a){return new (this.getHighlightClass())(a)}})})(Sfdc,this);
(function(b){b.provide("SfdcApp.Walkthrough.Core.Runtime.Analytics",new b.Class({$constructor:function(c){function f(a){g.getCurrentStepUI(a,this.logStep.bind(this,a))}function h(a,b){this.logImport("ContactImportOpen:"+b)}function k(a,b){this.logImport("ContactImport:"+b+"Click")}c=c||{};var d=c.importWizard,g=c.player,e=null;this.logImport=function(a){e&&a&&e.trackActivity(a,{events:["event8"]})};this.logStep=function(a,c){if(e){var d=g.getSelectedRole(),f=b.String.unescapeHtml(a.definition.label),
h=c.title,k=c.stepindex+1;try{e.trackWalkthrough(f,d,h,k)}catch(l){b.log("Failed to send data to Omniture - continuing on. The original error was: "+l)}}else b.warn("Dependent class SfdcApp.Omni.Config is not available.")};this.hashCode=function(){return"SfdcApp.Walkthrough.Core.Runtime.Analytics"};b.require("SfdcApp.Omni.Config",function(a){e=a;d&&(d.attach("onopen",h,this),d.attach("onImportTypeSelect",k,this));g.subscribe("stepstarted",this,f)}.bind(this))}}))})(Sfdc);
(function(b,g){b.provide("SfdcApp.Walkthrough.Core.Runtime.Util.Link",{generate:function(a,e,f){var c="/home/home.jsp",d="wt";a.type==WalkthroughTypes.TOUR&&(c=a.startPage,d="tour");a=b.String.format("/services/walkthrough?path\x3d{path}\x26{key}\x3d{id}",{path:c,key:d,id:a.id});return!e?a:b.String.format("https://{subdomain}.salesforce.com{relative}",{subdomain:f||"login",relative:a})}})})(Sfdc,this);
(function(b,w){var y='\x3cli id\x3d"walkthrough-role-{{id}}" data-role-id\x3d"{{id}}"\x3e\x3cspan\x3e{{label}}\x3c/span\x3e\x3cdiv class\x3d"walkthrough-sidebar-role walkthrough-role-{{id}}"\x3e\x3c/div\x3e\x3c/li\x3e';b.provide("SfdcApp.Walkthrough.Core.Ui.Sidebar",new b.Class({$constructor:function(n){function z(a){n.importWizard.open(a,{source:"Sidebar"})}function A(a){2>e.length||(a=x(-1),this.notify("onroleselect",e[a]))}function B(a){2>e.length||(a=x(1),this.notify("onroleselect",e[a]))}function C(a){this.toggle()}
function D(a){(a=b.Event.getEventTarget(a,"A"))&&this.notify("onwalkthroughselect",a.getAttribute("data-walkthrough-id"))}function x(a){var c=b.Array.indexOf(e,q);if(-1==c)return b.error("Switching to a new role relative to the currently selected role did not work as we could not find the role in the current list."),-1;c+=a;0>c?c=e.length+c:c>=e.length&&(c=e.length-c);return c}function E(a){for(var c=[],d,e=0;e<a.length;e++)d=a[e],d=b.Template.render(y,d),c.push(d);b.Dom.updateHTML(r,c.join(""))}
function u(a){if(a.introduction)b.log("Introductory walkthroughs are not included in the sidebar - skipping.");else{var c=b.first("#walkthrough-list-walkthrough-"+a.id);switch(a.status){case WalkthroughStatus.STARTED:b.log("Setting indicator for walkthrough "+a.id+" to 'started'.");b.Dom.addClass(c,WalkthroughStatus.STARTED);break;case WalkthroughStatus.STOPPED:b.log("Removing 'started' indicator from walkthrough: "+a.id);b.Dom.removeClass(c,WalkthroughStatus.STARTED);break;case WalkthroughStatus.FINISHED:b.log("Removing 'started' indicator from walkthrough: "+
a.id);b.Dom.removeClass(c,WalkthroughStatus.STARTED);b.log("Setting indicator for walkthrough "+a.id+" to 'finished'.");b.Dom.addClass(c,WalkthroughStatus.FINISHED);break;default:throw"Invalid walkthrough state published to UI: "+a.status;}}}function F(a){var c=a.definition,c=a.introduction||c&&c.introduction;a.status==WalkthroughStatus.STARTED&&!c?this.hide():a.status==WalkthroughStatus.FINISHED||a.status==WalkthroughStatus.STOPPED?this.show():b.log("No change to sidebar for status: "+a.status)}
n=n||{};var v=w.UserContext.userId+".walkthrough.ui.sidebar.visible",s=n.container,f=n.player,q=null,g=new b.Event.EventManager("ondraw","onexpand","oncollapse","onrolechange","onroleselect","onwalkthroughselect"),r=null,p=[],e=[],k=null,t=null,l=[];this.hashCode=function(){return"SfdcApp.Walkthrough.Core.Ui.Sidebar"};this.attach=function(a,b){g.add(this,a,b)};this.detach=function(a,b){g.remove(this,a,b)};this.notify=function(a,b){g.fireEvent(this,a,{data:b})};this.dispose=function(){l=t=k=e=p=r=
s=null};this.draw=function(){var a="true"===b.LocalStorage.getItem(v),c=LC.getLabel("walkthroughs","expand"),d=LC.getLabel("walkthroughs","collapse"),a=b.Template.render('\x3cdiv id\x3d"walkthrough-sidebar" class\x3d"zen {{collapsed}}"\x3e\x3cdiv id\x3d"walkthrough-sidebar-inner"\x3e\x3cdiv id\x3d"walkthrough-sidebar-content"\x3e\x3cdiv id\x3d"walkthrough-header"\x3e\x3ca href\x3d"javascript:void(0)" id\x3d"walkthrough-roleselector-left"\x3e\x3c/a\x3e\x3cul id\x3d"walkthrough-sidebar-roles"\x3e\x3c/ul\x3e\x3ca href\x3d"javascript:void(0)" id\x3d"walkthrough-roleselector-right"\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv id\x3d"walkthrough-sidebar-body"\x3e\x3cul\x3e\x3c/ul\x3e\x3c/div\x3e\x3cdiv id\x3d"walkthrough-footer"\x3e\x3ca id\x3d"walkthrough-import-label" href\x3d"javascript:void(0)" title\x3d"{{label_import_title}}"\x3e{{label_import_title}}\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv id\x3d"walkthrough-sidebar-toolbar"\x3e\x3cdiv id\x3d"walkthrough-sidebar-toggle"\x3e\x3cimg src\x3d"/img/spacer.gif" alt\x3d"{{label_toggle}}" title\x3d"{{label_toggle}}"/\x3e\x3c/div\x3e\x3cdiv\x3e{{label_items_plural}}\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',
{collapsed:a?"":"collapsed",label_toggle:a?d:c,label_import_title:LC.getLabel("walkthroughs","import_title"),label_items_plural:LC.getLabel("walkthroughs","items_plural")});k=b.Dom.insertHTML(s,a)[0];a=b.first("#walkthrough-sidebar-toggle",k);g.add(a,"click",C,this);t=b.first("#walkthrough-sidebar-body ul",s);g.add(t,"click",D,this);r=b.first("#walkthrough-sidebar-roles",s);g.add(b.first("#walkthrough-roleselector-left"),"click",A,this);g.add(b.first("#walkthrough-roleselector-right"),"click",B,this);
a=b.first("#walkthrough-footer");g.add(a,"click",z,this);p.length&&this.setRoles(p);l.length&&this.setWalkthroughs(l);q&&this.setCurrentRole(q);this.notify("ondraw")};this.hasDrawn=function(){return!!k};this.hide=function(){b.Dom.addClass(k,"collapsed");this.changeToggleLabel(!0);this.notify("oncollapse")};this.show=function(){b.Dom.removeClass(k,"collapsed");this.changeToggleLabel(!1);this.notify("onexpand")};this.changeToggleLabel=function(a){var c=b.first("#walkthrough-sidebar-toggle img"),d=null,
d=a?LC.getLabel("walkthroughs","expand"):LC.getLabel("walkthroughs","collapse");b.Dom.set(c,{attributes:{alt:d,title:d}})};this.toggle=function(){b.Dom.hasClass(k,"collapsed")?this.show():this.hide()};this.setCurrentRole=function(a){b.log("Setting sidebar view's selected role to: "+a);q=a;if(this.hasDrawn()){b.Array.indexOf(e,a);var c=b.first("\x3e li.selected",r),d=b.first("li[data-role-id\x3d"+a+"]",k);d&&!b.Dom.hasClass(d,"selected")&&(b.Dom.addClass(d,"selected"),c&&b.Dom.removeClass(c,"selected"))}this.notify("onrolechange",
a)};this.setRoles=function(a){b.log("Adding "+a.length+" roles to sidebar view.");if(void 0===a)return!1;null===a&&(a=[]);b.assert(b.isArray(a),b.String.format("Roles must be an Array, was instead type {0} and value {1}",[typeof a,a]));p=a;e=b.Array.map(p,function(a){return a.id});this.hasDrawn()&&E(a);return!0};this.setWalkthroughs=function(a){b.log("Adding "+a.length+" walkthroughs to sidebar view.");if(void 0===a)return!1;null===a&&(a=[]);b.assert(b.isArray(a),b.String.format("Walkthroughs must be an Array, was instead type {0} and value {1}",
[typeof a,a]));l=a;if(this.hasDrawn()){for(var c=[],d,e=0;e<a.length;e++)d=a[e],c.push(b.Template.render('\x3cli id\x3d"walkthrough-list-walkthrough-{{id}}" class\x3d"{{status}}"\x3e\x3cdiv\x3e\x3ca data-walkthrough-id\x3d"{{id}}" href\x3d"javascript:void(0)"\x3e{{label}}\x3c/a\x3e\x3c/div\x3e\x3c/li\x3e',d));b.Dom.updateHTML(t,c.join(""))}return!0};this.updateWalkthroughStatus=function(a,c){b.log("Changing status view of "+a+" to "+c);b.assert(b.isString(a),b.String.format("WalkthroughID must be of type String, was instead type {0} and value {1}",
[typeof a,a]));b.assert(b.isString(c),b.String.format("Status must be of type String, was instead type {0} and value {1}",[typeof c,c]));for(var d=0;d<l.length;d++)if(l[d].id===a){l[d].status=c;u(l[d]);break}};var m={oncollapse:function(){b.LocalStorage.setItem(v,"false")},onexpand:function(){b.LocalStorage.setItem(v,"true")},onroleselect:function(a,b){f.updateRole(b)},onwalkthroughselect:function(a,b){f.startWalkthroughInstance(b)}},h;for(h in m)m.hasOwnProperty(h)&&this.attach(h,m[h].bind(this));
g.add(w,"unload",function(){this.dispose()},this);f.subscribe("rolesloaded",this,this.setRoles);f.subscribe("roleselected",this,this.setCurrentRole);f.subscribe("definitionsloaded",this,this.setWalkthroughs);f.subscribe("instanceloaded",null,u);f.subscribe("finishedloaded",null,function(a){b.log("Setting finished indicator for all finished walkthroughs...");for(var c=0;c<a.length;c++){var d=b.first("#walkthrough-list-walkthrough-"+a[c]);d&&b.Dom.addClass(d,WalkthroughStatus.FINISHED)}});m=["instancestarted",
"instancestopped","instancefinished"];for(h=0;h<m.length;h++)f.subscribe(m[h],null,u),f.subscribe(m[h],this,F)}}))})(Sfdc,this);
(function(b,n){var u={c:"",t:"zen-sideNorth zen-arrowCenter",l:"zen-sideWest zen-arrowMiddle",lb:"zen-sideWest zen-arrowBottom",r:"zen-sideEast zen-arrowMiddle",rb:"zen-sideEast  zen-arrowBottom",b:"zen-sideSouth zen-arrowCenter",tl:"zen-sideNorth zen-arrowLeft",tr:"zen-sideNorth zen-arrowRight",bl:"zen-sideSouth zen-arrowLeft",br:"zen-sideSouth zen-arrowRight"},v={c:[0,0],t:[0,0],l:[0,0],r:[0,0],b:[0,0],tl:[-33,2],tr:[33,2],bl:[-33,0],br:[33,0],rb:[0,33],lb:[0,33]};b.provide("SfdcApp.Walkthrough.Core.Ui.Steps.CalloutBase",
new b.Class({$decorators:[b.Class.Config],$constructor:function(q,w){function l(a){a=a.split("-")[0];return u[a]||""}function p(a,d,c){d=d||n.document.body;c&&f&&(b.Dom.removeChild(f),f=null);f||(f=b.Dom.create(d,{className:x,id:y}));b.Dom.removeClass(f,m);return f}function r(a){for(var d=1E9,c=1E9,e=0,f=0,g,h,k=0;k<a.length;k++)h=a[k],b.Dom.isVisible(h,!0)&&(g=b.Dom.getElementXY(h),d=Math.min(g.y,d),c=Math.min(g.x,c),e=Math.max(b.Dom.getWidth(h)+g.x,e),f=Math.max(b.Dom.getHeight(h)+g.y,f));return{top:d,
left:c,right:e,bottom:f,width:e-c,height:f-d}}function s(a){if(!a)return null;for(var b,c=0;c<a.length;c++)if(b=a[c],"focus"in b)try{return b.focus(),b}catch(e){}return null}function t(a){if(!a)return!1;try{var d=b.Dom.getStyle(a,"position")}catch(c){return!1}return"fixed"===d?!0:a.parentNode?t(a.parentNode):!1}this.setConfig(b.apply({cssClass:"",render:null},w||{},!0));b.assert(q,"CalloutBase: calloutId can not be null or undefined");b.assert(this.config.render,"CalloutBase: render can not be null or undefined");
var y=q,x="zen "+(this.config.cssClass||"walkthrough-callout"),h="l-r",g=[],m="walkthrough-callout-halt",f=null;this.align=function(a){var d,c,e=n.document.body;b.isEmpty(g)?d=b.Dom.create(e,{style:{position:"absolute",top:"0",left:"0",right:"0",bottom:"0"}}):(b.isArray(g)||(g=[g]),c=r(g),e=g[0].ownerDocument.body,d=b.Dom.create(e,{style:{position:"absolute",top:c.top+"px",left:c.left+"px",width:c.width+"px",height:c.height+"px"}}));var e=p(this,e,!1),f=h.split("-")[0];b.Dom.alignTo(e,d,h,v[f]);b.Dom.removeChild(d);
if(!a)if(b.isEmpty(g))window.scrollTo(0,0);else if(!t(g[0])&&(a=c,e)){b.Window.getScrollY();b.Window.getScrollX();c=b.Window.getWindowWidth();d=b.Window.getWindowHeight();var e=r([e]),f=Math.min(e.top,a.top),l=Math.min(e.left,a.left),m=Math.max(e.right,a.right),k=Math.max(e.bottom,a.bottom),k=Math.floor((d-(k-f))/2),k=0>k?0:k;c=Math.floor((c-(m-l))/2);c=0>c?0:c;e.top-a.top>d?window.scrollTo(Math.max(0,l-c),Math.max(0,e.top-50)):window.scrollTo(Math.max(0,l-c),Math.max(0,f-k))}};this.changePosition=
function(a){if(a){var d=l(h);h=a||h;a=l(h);b.log("CalloutBase ---\x3e Changing callout position from "+d+" to "+a);var c=b.first(".zen-callout",f);b.Dom.removeClass(c,d);b.Dom.addClass(c,a);this.align()}};this.show=function(a,d){a=b.apply({stepindex:-1,stepcount:0,targets:[],controls:{}},a||{},!0);d=b.apply({skipScroll:!1,tryFocus:!0,isRedraw:!1},d||{},!0);g=a.targets;h=!g.length?"c-c":a.position||h;var c=g.length?g[0].ownerDocument.body:n.document.body;a.arrowPosition=l(h);a.label_step=LC.getLabel("walkthroughs",
"step_indicator",a.stepindex+1,a.stepcount);a.controls.next?a.controls.nextalt=a.controls.next:a.stepindex+1==a.stepcount?(a.controls.next=LC.getLabel("walkthroughs","finish"),a.controls.nextalt=LC.getLabel("walkthroughs","finish_alt")):(a.controls.next=LC.getLabel("walkthroughs","next"),a.controls.nextalt=LC.getLabel("walkthroughs","next_alt"));a.close=LC.getLabel("walkthroughs","close");a.closealt=LC.getLabel("walkthroughs","close_alt");var e=this.config.render.call(this,a),c=p(this,c,!d.isRedraw);
b.Dom.updateHTML(c,e);this.config.contentAvailable&&!d.isRedraw&&this.config.contentAvailable.call(this,c);this.align(d.skipScroll);if(e=d.tryFocus)e=b.select("#walkthrough-callout-controls .walkthrough-callout-next,#walkthrough-callout-controls .walkthrough-callout-custom",f).reverse(),e=!s(e);e&&s(g);this.config.onShow&&this.config.onShow.call(this,a)};this.getElement=function(){return f};this.hide=function(){f&&(b.Dom.removeChild(f),f=null);this.config.onHide&&this.config.onHide.call(this)};this.error=
function(){var a=p(this,null,!1);b.Dom.isVisible(a)&&(b.Dom.removeClass(a,m),b.Dom.addClass(a,m))}}}))})(Sfdc,this);
(function(a,m){a.provide("SfdcApp.Walkthrough.Core.Runtime.Definitions.StaticFileProvider",new a.Class({$implements:[SfdcApp.Walkthrough.Core.Runtime.Definitions.IProvider],$decorators:[a.Class.Config,SfdcApp.Walkthrough.Core.Runtime.Definitions.Caching],$constructor:function(b){b=a.apply({collection:null,cloud:null,language:m.UserContext.language||"en",knownLanguages:"en da de es es_MX fi fr it ja ko nl pt_BR ru sv th zh_CN zh_TW".split(" "),needsCountry:["es_MX","pt_BR","zh_CN","zh_TW"],urlPrefix:""},
b||{},!0);this.setConfig(b);a.assert(this.config.collection,"StaticFileProvider requires a collection name!");this.config.cloud?(a.log("Files are being segregated by collection ("+this.config.collection+") and cloud ("+this.config.cloud+")."),this.config.cloudSegment=this.config.cloud+"-cloud/"):(a.log("No cloud specified - files are only segregated by collection ("+this.config.collection+")."),this.config.cloudSegment="");0<=this.config.language.indexOf("_")&&0>a.Array.indexOf(this.config.needsCountry,
this.config.language)&&(a.log("Trimming country value off of locale: "+this.config.language),this.config.language=this.config.language.substring(0,2));a.log("The user's language is set to: "+this.config.language);0>a.Array.indexOf(this.config.knownLanguages,this.config.language)&&(a.log("No support for user's language - switching to default (en)."),this.config.language="en");b=this.getBaseStorageKey()+".url.prefix";if(this.config.urlPrefix.length)a.log("Saving URL prefix in local storage: "+this.config.urlPrefix),
a.LocalStorage.setItem(b,this.config.urlPrefix);else if(b=a.LocalStorage.getItem(b))a.log("Found URL prefix in local storage: "+b),this.config.urlPrefix=b},failHttpResponse:function(b,a,d,e){this.logHttpResponse(a,d,e);a="HTTP error: "+d.status;d.statusText&&(a+=" "+d.statusText);b.failure(a)},generateMappingURL:function(b){return"/walkthrough/roles/"+this.config.cloudSegment+this.config.language+"/"+b+".json"},generateRolesURL:function(){return"/walkthrough/roles/"+this.config.cloudSegment+this.config.language+
"/index.json"},generateWalkthroughURL:function(b){return"/walkthrough/"+this.config.collection+"/"+this.config.cloudSegment+b+"/"+b+"-"+this.config.language+".json"},loadDefinitions:function(b,c,d){a.log("Checking to see if "+b+" are available locally...");var e=null;c.reload||(e=c.getter());var g=a.isObject(e),k=e&&(g||e.length);if(!c.reload&&k)a.log("Found "+(g?1:e.length)+" "+b+" in the cache - passing them to the success callback."),d.success(e,!0);else{c.reload?a.log("Caller wants the latest data from the server."):
a.log("No "+b+" were found - they will be retrieved from the server.");e=c.urlgenerator();e=this.config.urlPrefix+e;a.log("Generating HTTP request: GET "+e);try{var f=this.saveHttpResponse.bind(this,b,c,d),l=this.failHttpResponse.bind(this,d);b={success:f,failure:l};c.reload&&(b.data={nocache:(new Date).getTime()});a.Ajax.request(e,b)}catch(h){throw a.log("Failed to send HTTP request - re-throwing without invoking callbacks."),a.log("The original error was: "+h),h;}}},loadRoleDefinitions:function(b,
a){var d={saveList:!0,getter:this.getRoleDefinitions.bind(this),keygenerator:this.generateRolesKey.bind(this),urlgenerator:this.generateRolesURL.bind(this),reload:b};this.loadDefinitions("roles",d,a)},loadWalkthroughDefinition:function(b,c,d){a.assert(b,"Walkthrough ID is null or undefined!");b={getter:this.getWalkthroughDefinition.bind(this,b,!0),keygenerator:this.generateWalkthroughKey.bind(this),urlgenerator:this.generateWalkthroughURL.bind(this,b),reload:c};this.loadDefinitions("walkthroughs",
b,d)},loadWalkthroughDefinitions:function(b,c,d){a.assert(b,"Role ID is null or undefined!");c={getter:this.getWalkthroughDefinitions.bind(this,b,!1),parser:this.parseRoleWalkthroughJSON.bind(this),keygenerator:this.generateWalkthroughKey.bind(this),urlgenerator:this.generateMappingURL.bind(this,b),ignore:c||[]};var e=d.success;d.success=function(c,d){if(!d){a.log("Saving "+c.length+" walkthrough IDs for role: "+b);var f=[];a.each(c,function(a){f.push(a.id)});this.saveLocalStorageItems("walkthrough IDs",
f,{saveList:!0,keygenerator:this.generateMappingKey.bind(this,b)})}e(c)}.bind(this);this.loadDefinitions("walkthroughs",c,d)},logHttpResponse:function(b,c,d){a.log("HTTP response: "+c.status+" ("+b.length+" bytes)");a.log(b||"(empty)")},parseHttpResponseJSON:function(b,c,d){a.log("Parsing response JSON into "+b+"...");c=a.JSON.parse(c);d.parser&&(a.log("Calling custom parser to extract field(s) from object(s)..."),c=d.parser(c));a.isArray(c)?a.log("Successfully parsed "+c.length+" "+b+"."):a.log("Successfully parsed JSON object.");
return c},parseRoleWalkthroughJSON:function(a){return a.walkthroughs},saveHttpResponse:function(b,c,d,e,g,k){this.logHttpResponse(e,g,k);var f=null;try{f=this.parseHttpResponseJSON(b,e,c)}catch(l){a.log("The server returned invalid JSON; short-circuiting and invoking the failure callback.");a.log(l);this.failHttpResponse(d,e,g,k);return}try{this.saveLocalStorageItems(b,f,c)}catch(h){a.log("Failed to save "+b+" in local storage. Execution will continue, but local cache is no longer valid."),a.log("The underlying error was: "+
h),sendWalkthroughGack(h)}a.log("Invoking success callback with the latest definitions.");d.success(f)}}))})(Sfdc,this);
(function(d,f){d.provide("SfdcApp.Walkthrough.Core.Runtime.Instances.LocalStorageProvider",new d.Class({$implements:[SfdcApp.Walkthrough.Core.Runtime.Instances.IProvider],$decorators:[d.Class.Config],$constructor:function(a){this.setConfig(a);d.assert(this.config.collection,"LocalStorageProvider requires a collection name!");d.assert(f.UserContext.userId&&f.UserContext.userId.length,"The user ID was not in the user context loaded from the server!");this.config.userID=f.UserContext.userId},addFinishedWalkthrough:function(a,
b){var c=this.generateFinishedKey();(c=this.getLocalStorageItem(c))||(c={});c[a]=!0;var d={keygenerator:this.generateFinishedKey.bind(this)};this.saveLocalStorageItem(c,d,b)},clearCache:function(){d.log("Clearing all data in the walkthrough instance cache - all user activity will be gone!");d.LocalStorage.clear(this.getBaseStorageKey())},createWalkthroughInstance:function(a,b){d.assert(a,"Walkthrough definition is null or undefined!");d.assert(a.steps&&a.steps.length,"Walkthrough definition is not complete - no steps were found!");
var c={id:a.id,status:WalkthroughStatus.NEW,startTime:null,startPage:null,steps:[],definition:a};d.each(a.steps,function(a){c.steps.push({id:a.id,status:WalkthroughStatus.NEW,page:null,skipped:!1})});var e={keygenerator:this.generateWalkthroughKey.bind(this,a.id)};this.saveLocalStorageItem(c,e,b)},deleteWalkthroughInstance:function(a,b){d.assert(a,"Walkthrough instance is null or undefined!");var c={keygenerator:this.generateWalkthroughKey.bind(this,a.id)};this.removeLocalStorageItem(a,c,b)},fail:function(a,
b,c){d.log(a);d.log("The original exception was: "+b);c&&c.failure(b)},filterInstanceJSON:function(a,b){return"definition"===a?void 0:b},generateActiveKey:function(){return this.getBaseStorageKey()+".active"},generateFinishedKey:function(){return this.getBaseStorageKey()+".finished"},generateInitKey:function(){return this.getBaseStorageKey()+".initialized"},generateRoleKey:function(){return this.getBaseStorageKey()+".role"},generateWalkthroughKey:function(a){return this.getBaseStorageKey()+"."+a},
getActiveInstance:function(){var a=this.generateActiveKey();return(a=this.getLocalStorageItem(a))?this.getWalkthroughInstance(a):null},getBaseStorageKey:function(){return this.config.userID+".walkthrough."+this.config.collection+".instances"},getFinishedWalkthroughs:function(){var a=this.generateFinishedKey();return(a=this.getLocalStorageItem(a))?Object.keys(a):[]},getLocalStorageItem:function(a){d.log("Retrieving item from local storage: "+a);if(a=d.LocalStorage.getItem(a))return d.JSON.parse(a);
d.log("\tNo value found!");return null},getSelectedRole:function(){var a=this.generateRoleKey();return this.getLocalStorageItem(a)},getWalkthroughInstance:function(a){d.assert(a,"Walkthrough ID is null or undefined!");a=this.generateWalkthroughKey(a);return this.getLocalStorageItem(a)},isInitialized:function(){return this.getLocalStorageItem(this.generateInitKey())},loadActiveInstance:function(a){var b=null;try{b=this.getActiveInstance()}catch(c){this.fail("Failed to load active walkthrough.",c,a);
return}b?a.success(b):d.log("There is no active walkthrough - short-circuiting.")},loadFinishedWalkthroughs:function(a){var b=null;try{b=this.getFinishedWalkthroughs()}catch(c){this.fail("Failed to load finished walkthroughs.",c,a);return}a.success(b)},loadWalkthroughInstance:function(a,b){d.assert(a,"Walkthrough ID is null or undefined!");var c=null;try{c=this.getWalkthroughInstance(a)}catch(e){this.fail("Failed to load walkthrough: "+a,e,b);return}c?b.success(c):d.log("There is no instance with that ID - short-circuiting.")},
removeActiveInstance:function(a){var b=this.getActiveInstance(),c={keygenerator:this.generateActiveKey.bind(this)};this.removeLocalStorageItem(b,c,a)},removeLocalStorageItem:function(a,b,c){var e=null;try{e=b.keygenerator(),d.log("Removing item from local storage: "+e),d.LocalStorage.removeItem(e)}catch(f){this.fail("Failed to delete item: "+e,f,c);return}c&&(b.getter&&(a=b.getter(a)),c.success(a))},saveLocalStorageItem:function(a,b,c){var e=null;try{var e=b.keygenerator(),f=d.JSON.stringify(a,b.filter,
"\t");d.log("Saving item in local storage: "+e);d.LocalStorage.setItem(e,f)}catch(g){this.fail("Failed to save item: "+e,g,c);return}c&&(b.getter&&(a=b.getter(a)),c.success(a))},setInitialized:function(a){this.saveLocalStorageItem(a,{keygenerator:this.generateInitKey})},updateActiveInstance:function(a,b){if(a){var c={keygenerator:this.generateActiveKey.bind(this),getter:this.getWalkthroughInstance.bind(this,a.id),filter:this.filterInstanceJSON};this.saveLocalStorageItem(a.id,c,b)}else d.log("Instance is null, forwarding to removeActiveInstance()."),
this.removeActiveInstance(b)},updateSelectedRole:function(a,b){d.assert(a,"Selected role is null or undefined!");var c={keygenerator:this.generateRoleKey.bind(this)};this.saveLocalStorageItem(a,c,b)},updateWalkthroughInstance:function(a,b){d.assert(a,"Walkthrough instance is null or undefined!");var c={keygenerator:this.generateWalkthroughKey.bind(this,a.id),filter:this.filterInstanceJSON};this.saveLocalStorageItem(a,c,b)}}))})(Sfdc,this);
(function(c,m){c.provide("SfdcApp.Walkthrough.Core.Runtime.Player",c.Class({$decorators:[c.Class.Config],$constructor:function(a){a=c.apply({definitions:null,instances:null,locator:null,validator:null,listenersByEvent:{rolesloaded:{},roleselected:{},definitionsloaded:{},finishedloaded:{},instanceloaded:{},instancestarted:{},instancestopped:{},instancefinished:{},instancefailed:{},stepstarted:{},stepfailed:{},stepfinished:{}},defaultListener:{hashCode:function(){return"DEFAULT LISTENER"}},debug:{success:function(a){c.log("The last task was successful, but no callback function was provided, so the resulting data will be printed and then ignored.");
c.log("The result of the last task was:");c.log(c.JSON.stringify(a,null,"\t"))},failure:function(a){c.log("The last task failed, but no callback function was provided, so the only action that will be taken is to print the task metadata.");c.log("The error that caused the task failure was: "+a);sendWalkthroughGack(a.message?a:{message:a})}}},a||{},!0);this.setConfig(a);c.assert(this.config.definitions,"IProvider for walkthrough definitions is null or undefined!");c.assert(this.config.instances,"IProvider for walkthrough instances is null or undefined!");
c.assert(this.config.validator,"IValidator for walkthrough steps is null or undefined!");c.assert(this.config.locator,"ILocator is null or undefined!")},clearDefinitionCache:function(){this.config.definitions.clearCache()},clearInstanceCache:function(){this.config.instances.clearCache()},currentStep:function(a){this.logPlayerAction("Restarting current step in the active walkthrough...");a=this.validateCallbacks(a,"stepstarted");var b=this.getActiveInstance();c.assert(b,"Cannot load current step because none of the walkthroughs are in a started state!");
var d=this.getCurrentStepIndex(b);c.log("The current step index is: "+d);c.log("The real step number is: "+(d+1));try{if(this.isInstanceInProgress(b))this.startStepInstance(b,d),this.config.instances.updateWalkthroughInstance(b,a);else throw"Instance is at the very beginning or very end - short-circuiting.";}catch(e){c.log("Failed to start current step! Invoking failure callback and then pausing instance. "+e),a.failure(e),this.publish("stepfailed",b),this.stopWalkthroughInstance()}},execute:function(a,
b,d,c){d=d||this.validateCallbacks();c||(c="Player.execute");(new SfdcApp.Walkthrough.Core.Runtime.TaskQueue({id:c,tasks:a,callbacks:d})).execute(this,b)},findNextWalkthroughDefinition:function(a,b){if(a.definition.type==WalkthroughTypes.TOUR)a.definition.followedBy&&this.config.definitions.loadWalkthroughDefinition(a.definition.followedBy,!1,{success:b});else{var d=this.getSelectedRole(),d=this.config.definitions.getWalkthroughDefinitions(d),e=this.config.instances.getFinishedWalkthroughs();if(a.definition.introduction)b(d[0]);
else{for(var f=0;f<d.length&&d[f].id!=a.id;)f++;c.assert(f<d.length,"No walkthrough found with the ID '"+a.id+"'!");c.log("The current walkthrough is at index: "+f);for(var g=f==d.length-1?0:f+1;g!=f;){c.log("Testing completion of walkthrough '"+d[g].id+"' (index: "+g+")");if(0>e.indexOf(d[g].id)){c.log("Found a match! The next unfinished walkthrough is at index: "+g);b(d[g]);return}g=g==d.length-1?0:g+1}c.log("All walkthroughs have been completed!");b()}}},finishWalkthroughInstance:function(a,b){c.log("Changing status of the instance to 'finished'.");
a.status=WalkthroughStatus.FINISHED;c.log("Adding the walkthrough's ID to the finished list...");this.config.instances.addFinishedWalkthrough(a.id);c.log("Removing the player's 'active' instance...");this.config.instances.removeActiveInstance();c.log("Deleting the walkthrough instance...");this.config.instances.deleteWalkthroughInstance(a,b)},finishStepInstance:function(a,b){if(!this.config.validator.isCompleted(a.definition,b))throw"The step's completion criteria have not been met.";c.log("Marking step #"+
(b+1)+" as finished.");a.steps[b].status=WalkthroughStatus.FINISHED},getActiveInstance:function(){var a=this.config.instances.getActiveInstance();null!==a&&(a.definition=this.config.definitions.getWalkthroughDefinition(a.id,!0));return a},getCurrentStepIndex:function(a){c.assert(a,"The walkthrough instance is null or undefined!");for(var b=0;b<a.steps.length;b++)if(a.steps[b].status==WalkthroughStatus.STARTED)return b;return-1},getCurrentStepUI:function(a,b){c.log("Creating UI data for the current step...");
var d=this.getCurrentStepIndex(a);c.assert(0<=d,"Attempting to retrieve UI for an instance that isn't in progress!");var e=a.steps[d],f=a.definition.steps[d],g=f.help.primary,l=f.help.secondary,k=f.help.skipped;c.assert(g,"The step definition must contain a primary help object!");var h={player:this,valid:!1,stepindex:d,stepcount:a.steps.length,title:f.label,position:f.position,highlight:f.highlight,event:f.completedWhen.event,autocomplete:f.completedWhen.autoComplete,controls:f.help.controls||{},
force:{},description:null,targets:[]};h.autocomplete&&(h.event&&"pageLoad"!=h.event&&this.config.validator.isCompleted(a.definition,d))&&(c.log("Disabling auto-complete in UI for this step because completion criteria have already been satisfied."),h.autocomplete=!1);if(e.skipped){if(!k)throw"Step was marked skipped, but no skip UI was defined in the walkthrough definition!";c.log("Step was marked skipped.");h.autocomplete=!1;h.valid=!0;h=this.testTargetsAndFillInUI(k,h)}else if(h=this.testTargetsAndFillInUI(g,
h),g.detached||h.targets.length)c.log("Primary target found."),h.valid=!0;else if(h=this.testTargetsAndFillInUI(l,h),l&&l.detached||h.targets.length)c.log("Secondary target found."),h.valid=!0;h.valid?h.force&&h.force.command?setTimeout(function(){b(h)},500):b(h):(d="Invalid walkthrough definition - step was loaded but none of the targeted elements are on the page. The invalid step definition was:\n"+c.JSON.stringify(f,null,"\t"),c.log(d),e="\x3ca href\x3d'"+WalkthroughAuthoringHelp+"' target\x3d'_blank'\x3e",
f="\x3cbr /\x3e\x3cbr /\x3e"+c.JSON.stringify(f.help,null,"\t"),SfdcApp.Walkthrough.Core.Runtime.Util.Events.postMessage({message:LC.getLabel("walkthroughs","invalid_step_def",h.stepindex+1,a.id),details:LC.getLabel("walkthroughs","invalid_step_def_details",e,"\x3c/a\x3e",f),severity:WalkthroughMessageSeverity.ERROR}),this.publish("instancefailed",a),sendWalkthroughGack({message:d}))},getSelectedRole:function(){this.logPlayerAction("Delegating selected role to data provider...");return this.config.instances.getSelectedRole()},
getSelectedRoleDefinition:function(){var a=this.getSelectedRole(),b=this.config.definitions.getRoleDefinitions();c.log("Found "+b.length+" role definitions.");for(var d=0;d<b.length;d++)if(c.log("Comparing '"+a+"' to '"+b[d].id+"'..."),b[d].id==a)return b[d];throw"Selected role ID is invalid: "+a;},isFirefoxAutoCompleteBug:function(a,b){return c.userAgent.isFirefox&&"valueEntered"==b&&a[0]&&"SELECT"==a[0].tagName},isInitialized:function(){return this.config.instances.isInitialized()},isInstanceAtBeginning:function(a){c.assert(a,
"The walkthrough instance is null or undefined!");return a.steps[0].status==WalkthroughStatus.NEW},isInstanceAtEnd:function(a){c.assert(a,"The walkthrough instance is null or undefined!");return a.steps[a.steps.length-1].status==WalkthroughStatus.FINISHED},isInstanceInProgress:function(a){return!this.isInstanceAtBeginning(a)&&!this.isInstanceAtEnd(a)},loadActiveInstance:function(a){this.logPlayerAction("Delegating active walkthrough instance to data provider...");a=this.validateCallbacks(a,"instanceloaded");
var b=a.success;a.success=function(a){a.definition=this.config.definitions.getWalkthroughDefinition(a.id,!0);b(a)}.bind(this);this.config.instances.loadActiveInstance(a)},loadFinishedWalkthroughs:function(a){this.logPlayerAction("Delegating finished walkthroughs to data provider...");a=this.validateCallbacks(a,"finishedloaded");this.config.instances.loadFinishedWalkthroughs(a)},loadRoleDefinitions:function(a){this.logPlayerAction("Delegating role definitions to data provider...");a=this.validateCallbacks(a,
"rolesloaded");this.config.definitions.loadRoleDefinitions(!1,a)},loadWalkthroughDefinitions:function(a,b){c.assert(a,"Role ID is null or undefined!");this.logPlayerAction("Delegating walkthrough definitions to data provider...");b=this.validateCallbacks(b,"definitionsloaded");var d=this.config.instances.getActiveInstance();this.config.definitions.loadWalkthroughDefinitions(a,d?[d.id]:[],b)},loadWalkthroughInstance:function(a,b){c.assert(a,"Walkthrough ID is null or undefined!");this.logPlayerAction("Delegating walkthrough instance to data provider...");
b=this.validateCallbacks(b,"instanceloaded");this.config.instances.loadWalkthroughInstance(a,b)},logPlayerAction:function(a){c.log("PLAYER ---\x3e "+a)},monitorAutoCompleteStatusOnInterval:function(a,b){this.logPlayerAction("Monitor thread is awake.");this.config.validator.isCompleted(a,b)?++this.completes>=this.completesNeeded&&(this.stopAutoCompleteMonitor(),this.nextStep()):this.completes=0},navigateToStep:function(a,b,d){this.logPlayerAction("Trying to determine what step to start (if any).");
c.assert(a.status==WalkthroughStatus.STARTED,"Cannot navigate steps on an inactive instance!");this.nextStep(b,{success:d.success,failure:function(a){c.log("Failed to finish step and move on - trying to load the current step instead...");this.currentStep(d)}.bind(this),validated:d.validated})},nextStep:function(a,b){this.logPlayerAction("Starting next step in the active walkthrough...");var d=this.getActiveInstance();c.assert(d,"Cannot move to next step because none of the walkthroughs is in a started state!");
var e=this.getCurrentStepIndex(d);c.log("The current step index is: "+e);c.log("The real step number is: "+(e+1));try{if(this.isInstanceInProgress(d)){if(a&&!d.definition.steps[e].completedWhen.autoComplete)throw"A new page load has occurred on a step that does not auto-complete - restarting the current step.";c.log("Instance is in progress, so we'll mark the current step finished...");this.finishStepInstance(d,e)}this.isInstanceAtEnd(d)||(c.log("Instance is not at the very end yet, so we'll mark the next step started..."),
this.startStepInstance(d,e+1))}catch(f){c.log("Failed to start the next step! "+f);b&&c.isFunction(b.failure)?b.failure(f):this.publish("stepfailed",d);return}e=this.isInstanceAtEnd(d);b=this.validateCallbacks(b,e?"instancefinished":"stepstarted");e?(c.log("The instance is at the very end, so there were no more steps to start."),this.finishWalkthroughInstance(d,b)):this.config.instances.updateWalkthroughInstance(d,b)},publish:function(a,b){c.log("Publishing event "+a+" to all listeners...");var d=
this.config.listenersByEvent[a];c.assert(d,"No handler collection found for event "+a+" - it must be invalid!");var e=Object.keys(d);c.log("There are "+e.length+" listeners subscribed right now...");for(var f=0;f<e.length;f++)d[e[f]](b);c.log("Finishing notifying listeners.")},reload:function(a){c.log("Reloading the player, up-to-and-including the last active step (if possible).");var b=[function(a){this.loadRoleDefinitions(a())},function(a,b){var c=this.getSelectedRole();this.updateRoleOnly(c,a())},
function(a,b){this.loadWalkthroughDefinitions(b,a())},function(a,b){this.loadFinishedWalkthroughs(a())}];a?(c.log("The reload process will end with the force-start of a new walkthrough: "+a),b.push(function(b,c){this.startWalkthroughInstance(a,!0,b())})):(c.log("The reload process will end with the restart of the active walkthrough (if any)."),b=b.concat([function(a,b){this.loadActiveInstance(a())},function(a,b){this.navigateToStep(b,!0,a())}]));this.execute(b,[])},selectedRoleHasWalkthrough:function(a){c.log("Testing to see if selected role has walkthrough: "+
a);for(var b=this.getSelectedRole(),b=this.config.definitions.getWalkthroughDefinitions(b),d=0;d<b.length;d++)if(c.log("Comparing '"+a+"' to '"+b[d].id+"'..."),a==b[d].id)return!0;c.log("The selected role does NOT have the given walkthrough.");return!1},setInitialized:function(a){this.config.instances.setInitialized(a)},startAutoCompleteMonitor:function(a,b,d){c.log("Starting monitor thread to watch for step completion...");c.assert(!this.config.autoCompleteMonitor,"Another monitor thread is already running!");
this.completes=0;this.completesNeeded=d;a=this.monitorAutoCompleteStatusOnInterval.bind(this,a,b);this.config.autoCompleteMonitor=window.setInterval(a,500)},startStepInstance:function(a,b){var d=a.steps[b],e=a.definition.steps[b],f=this.config.locator.whereAreWe();if(a.definition.stayOnPage&&a.startPage!==f)throw c.log("This walkthrough requires that each step be completed on the same page. The page has changed since the last (re)start, so the instance will be stopped."),c.log("The original page was: "+
a.startPage),c.log("The current page is: "+f),d=LC.getLabel("walkthroughs","invalid_start_details","\x3ca href\x3d'"+WalkthroughAuthoringHelp+"' target\x3d'_blank'\x3e","\x3c/a\x3e"),d+="\x3cbr/\x3e"+LC.getLabel("walkthroughs","invalid_start_expected",a.startPage),d+="\x3cbr/\x3e"+LC.getLabel("walkthroughs","invalid_start_actual",f),SfdcApp.Walkthrough.Core.Runtime.Util.Events.postMessage({message:LC.getLabel("walkthroughs","invalid_start",a.definition.label),details:d,severity:WalkthroughMessageSeverity.INFO}),
"The user has changed pages, so this walkthrough must be closed and stopped.";if(!this.config.validator.canStart(a.definition,b))if(a.definition.type!=WalkthroughTypes.TOUR&&1===b&&this.config.validator.isCompleted(a.definition,b))c.log("This is the first non-intro step, and it's met its completion criteria, so we're going to skip it..."),d.skipped=!0;else throw"The step's start criteria have not been met.";var g=e.completedWhen.autoComplete&&e.completedWhen.event&&"pageLoad"!=e.completedWhen.event,
l=1;if(g){var k=[],h=e.help.primary;h.detached||(k=this.config.locator.findElements(h.target[0],h.iframe));if(this.isFirefoxAutoCompleteBug(k,e.completedWhen.event))c.log("Disabling auto-complete monitor for this step because Firefox changes the selected value for \x3cselect\x3e on hover."),g=!1;else if(k[0]&&("text"==k[0].type||"TEXTAREA"==k[0].tagName))l=2}g&&this.config.validator.isCompleted(a.definition,b)&&(c.log("Disabling auto-complete monitor for this step because completion criteria have already been satisfied."),
g=!1);g&&(c.log("We need to monitor the DOM to watch for the step completion criteria and auto-advance when possible."),this.startAutoCompleteMonitor(a.definition,b,l));c.log("Marking step #"+(b+1)+" as started and recording page URL.");d.status=WalkthroughStatus.STARTED;d.page=f},startWalkthroughInstance:function(a,b,d){c.assert(a,"Walkthrough ID is null or undefined!");this.logPlayerAction("Starting walkthrough: "+a);var e=this.getActiveInstance();e?(this.logPlayerAction("Another walkthrough is already active: "+
e.id),this.logPlayerAction("The active walkthrough will "+(b?"":"not ")+"be stopped."),b?(a=function(a,b){this.logPlayerAction("Stopped previous walkthrough - now we can start '"+a+"'.");this.startWalkthroughInstance(a)}.bind(this,a),this.stopWalkthroughInstance({success:a})):this.publish("instancefailed",{current:e.id,attempted:a})):(d=this.validateCallbacks(d,"instancestarted"),this.execute([function(a,b){var d=a();c.log("Loading walkthrough definition: "+b);var e=this.config.instances.getWalkthroughInstance(b),
e=!e||e.status==WalkthroughStatus.FINISHED;c.log("The definition will "+(e?"be":"not be")+" refreshed before starting.");this.config.definitions.loadWalkthroughDefinition(b,e,d)},function(a,b){this.config.instances.createWalkthroughInstance(b,a())},function(a,b){var d=a();c.log("Setting this instance to be the player's 'active' instance.");this.config.instances.updateActiveInstance(b,d)},function(a,b){var d=a();c.log("Re-fetching active instance with definition included...");b=this.getActiveInstance();
c.log("Updating instance metadata to reflect new state...");b.status=WalkthroughStatus.STARTED;b.startTime=(new Date).getTime();b.startPage=this.config.locator.whereAreWe();c.log("Instance start page URL: "+b.startPage);this.config.instances.updateWalkthroughInstance(b,d)},function(a,b){var d=a();c.log("Trying to load the right step for the instance.");this.navigateToStep(b,!1,d)}],[a],d,"Player.startWalkthroughInstance"))},stopAutoCompleteMonitor:function(){c.log("Killing monitor thread...");this.config.autoCompleteMonitor?
(window.clearInterval(this.config.autoCompleteMonitor),this.config.autoCompleteMonitor=null):c.log("No monitor thread is running - short-circuiting.")},stopWalkthroughInstance:function(a){this.logPlayerAction("Stopping active walkthrough...");a=this.validateCallbacks(a,"instancestopped");this.execute([function(a){this.config.instances.loadActiveInstance(a())},function(a,c){c.status=WalkthroughStatus.STOPPED;this.config.instances.updateWalkthroughInstance(c,a())},function(a,d){var e=a();this.stopAutoCompleteMonitor();
c.log("Removing the player's 'active' instance.");this.config.instances.removeActiveInstance(e)},function(a,d){var e=a();c.log("Deleting the walkthrough instance data.");this.config.instances.deleteWalkthroughInstance(d,e)}],[],a)},subscribe:function(a,b,d){b||(c.log("No listener scope provided, so we'll use the default."),b=this.config.defaultListener);c.assert(a,"Event name is null or undefined!");c.assert(d,"Event handler is null or undefined!");c.assert(c.isFunction(b.hashCode),"Event listener does not implement the hashCode() function!");
var e=b.hashCode();c.log("Hash code provided by event listener: "+e);c.log("Recording subscription to event "+a);this.config.listenersByEvent[a][e]=d.bind(b)},testAndApplyForceOption:function(a,b,d){if(b){c.log("Evaluating force option...");if(b.add)c.log("Adding class name to target: "+b.add),c.Dom.addClass(a,b.add);else if(b.remove)c.log("Removing class name from target: "+b.remove),c.Dom.removeClass(a,b.remove);else if(b.visible)c.log("Turning on visibility for target."),c.Dom.show(a,!0);else if(b.command)c.log("Executing custom command: "+
b.command),eval(b.command);else throw"Invalid force option - you must specify className or visible.";d.force=b}else c.log("No force option specified - short-circuiting.")},testTargetsAndFillInUI:function(a,b){if(!a)return b;if(a.detached)return b.description=a.label,b;var d=a.target.join(","),e=this.config.locator.findElements(d,a.iframe);if(!e.length)return b;for(var f=[],g=0;g<e.length;g++)this.testAndApplyForceOption(e[g],a.force,b),c.Dom.isVisible(e[g],!0)?f.push(e[g]):c.log('Element at index "'+
g+'" returned by the selector "'+d+'" was found on the page but ignored since it is not visible.');c.log('The selector(s) "'+d+'" returned '+e.length+" element(s).");c.log("Of those, "+f.length+" element(s) were visible after evaluation.");f.length?(b.targets=f,b.description=a.label,b.position=a.position,b.highlight=a.highlight,this.isFirefoxAutoCompleteBug(b.targets,b.event)&&(b.autocomplete=!1)):a.iframe&&(c.log("Selector option depends on an iframe and returned zero elements. Check to make sure the iframe is not being served from a separate domain."),
d="\x3ca href\x3d'"+WalkthroughAuthoringHelp+"' target\x3d'_blank'\x3e",SfdcApp.Walkthrough.Core.Runtime.Util.Events.postMessage({message:LC.getLabel("walkthroughs","no_targets_iframe"),details:LC.getLabel("walkthroughs","no_targets_iframe_details",d,"\x3c/a\x3e"),severity:WalkthroughMessageSeverity.WARNING}));return b},unsubscribe:function(a,b){c.assert(a,"Event name is null or undefined!");c.assert(b,"Event listener is null or undefined!");c.log("Deleting subscription to event "+a);var d=b.hashCode();
c.log("Hash code provided by event listener: "+d);delete this.config.listenersByEvent[a][d]},updateRole:function(a){c.assert(a,"Role ID is null or undefined!");this.logPlayerAction("Updating user's selected role: "+a);tasks=[function(a,c){this.updateRoleOnly(c,a())},function(a,c){this.loadWalkthroughDefinitions(c,a())},function(a,c){this.loadFinishedWalkthroughs(a())},function(a,c){this.loadActiveInstance(a())},function(a,d){var e=a();d&&!this.selectedRoleHasWalkthrough(d.id)?(c.log("The new role does not have the currently active walkthrough, so we will stop it."),
this.stopWalkthroughInstance()):e.success()}];this.execute(tasks,[a])},updateRoleOnly:function(a,b){b=this.validateCallbacks(b,"roleselected");this.config.instances.updateSelectedRole(a,b)},validateCallbacks:function(a,b){a||(a={});if(a.validated)return a;a.success||(c.log("No success callback provided for player workflow - using debug callback."),a.success=this.config.debug.success.bind(this));a.failure||(c.log("No failure callback provided for player workflow - using debug callback."),a.failure=
this.config.debug.failure.bind(this));if(b){var d=a.success;a.success=function(a,b){this.publish(a,b);d(b)}.bind(this,b)}a.validated=!0;return a}}))})(Sfdc,this);
(function(b,p){function k(b,d){b=b.replace(/[\-\\\^$*+?.()|\[\]{}]/g,"\\$\x26");b=b.replace(l,function(a,b){return SfdcApp.Walkthrough.Core.Runtime.Util.SObject.regexp(b)});return RegExp("^"+b+"$").test(d)}var m=/^(([^:\/?#]+):)?(\/\/([^\/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,g=[["scheme",2],["authority",4],["path",5],["query",7],["fragment",9]],n=["fcf","setupid","type","pageName"],l=/__([A-Za-z0-9]{3})_SOBJECT_ID__/g;b.provide("SfdcApp.Walkthrough.Core.Runtime.Util.URI",{makeSalient:function(b){return this.patternFor(b,
{wildcards:!1})},parse:function(h,d){d=d||{};var a=null,c=m.exec(h);if(c){for(var a={},e=0;e<g.length;++e)a[g[e][0]]=c[g[e][1]];d.decode&&(a.path?(c=a.path.split("/"),a.pathDecoded=b.Array.map(c,decodeURIComponent)):a.pathDecoded=a.path,a.queryDecoded=a.query?b.Url.getUrlParameters(a.query):a.query)}return a},patternFor:function(h,d){d=b.apply({wildcards:!0},d||{},!0);b.log("URI.patternFor: building pattern for "+h+" { wildcards: "+d.wildcards+" }");var a=this.parse(h,{decode:!0});b.assert(a,"could not parse uri");
var c;c=d.wildcards?b.Array.map(a.pathDecoded,function(a){return SfdcApp.Walkthrough.Core.Runtime.Util.SObject.replaceID(a,"__$1_SOBJECT_ID__")}):a.pathDecoded;c=b.Array.map(c,encodeURIComponent).join("/");if(a.queryDecoded){var e={},f;for(f in a.queryDecoded)if(a.queryDecoded.hasOwnProperty(f)&&0<=b.Array.indexOf(n,f)){var g=a.queryDecoded[f];d.wildcards&&(g=SfdcApp.Walkthrough.Core.Runtime.Util.SObject.replaceID(g,"__$1_SOBJECT_ID__"));e[f]=g}(a=b.Url.generateQueryString("",e,{includeMark:!1}))&&
(c+="?"+a)}return c},test:function(g,d){b.log("URI.test: check uri "+d+" against pattern "+g);var a=this.parse(g,{decode:!0}),c=this.parse(d,{decode:!0});if(a.pathDecoded.length!=c.pathDecoded.length)return b.log("URI.test: uri path "+c.path+" does not match pattern path "+a.path),!1;for(var e=0;e<a.pathDecoded.length;++e)if(!k(a.pathDecoded[e],c.pathDecoded[e]))return b.log("URI.test: uri path "+c.path+" does not match pattern path "+a.path),!1;if(a.queryDecoded){if(!c.queryDecoded)return b.log("URI.test: uri query "+
c.query+" does not match pattern query "+a.query),!1;for(var f in a.queryDecoded)if(a.queryDecoded.hasOwnProperty(f)&&!k(a.queryDecoded[f],c.queryDecoded[f]))return b.log("URI.test: uri query parm "+c.queryDecoded[f]+" does not match pattern query parm "+a.queryDecoded[f]),!1}b.log("URI.test: uri matches pattern");return!0}})})(Sfdc,this);
(function(b,l){var g=[[RegExp(b.Template.render("{{x}}",{x:"\x3cuicontrol\x3e"}),"g"),""],[RegExp(b.Template.render("{{x}}",{x:"\x3c/uicontrol\x3e"}),"g"),""],[RegExp(b.Template.render("{{x}}",{x:"\x3cuserinput\x3e"}),"g"),'\x3cspan class\x3d"walkthrough-callout-user-input"\x3e'],[RegExp(b.Template.render("{{x}}",{x:"\x3c/userinput\x3e"}),"g"),"\x3c/span\x3e"],[/\r?\n/g,"\x3cbr/\x3e"]];b.provide("SfdcApp.Walkthrough.Core.Ui.Steps.Callout",new b.Class({$extends:SfdcApp.Walkthrough.Core.Ui.Steps.CalloutBase,
$constructor:function(d){function h(a){b.Event.getEventTarget(a,".walkthrough-callout-next")?this.notify("onnext",a):b.Event.getEventTarget(a,"#walkthrough-callout-close")?this.notify("onclose",a):b.Event.getEventTarget(a,".walkthrough-callout-previous")}function k(a){c.isKeyAction(a,c.keyCode.ESC)&&this.notify("onclose",a)}function e(a){b.isString(a)&&b.Array.forEach(g,function(b){a=a.replace(b[0],b[1])});return a}d=d||{};var f=d.cloud||SalesforceClouds.SALES;d="walkthrough-callout-"+f;var c=new b.Event.EventManager("onnext",
"onclose");this.parent(d,{contentAvailable:function(a){c.add(a,"click",h,this);c.add(a,"keydown",k,this)},render:function(a){a.cloud=f;a.title=e(b.Template.render("{{x}}",{x:a.title}));a.description=e(b.Template.render("{{x}}",{x:a.description}));return b.Template.render('\x3cdiv class\x3d"zen-callout {{arrowPosition}} {{stateCssClass}}" role\x3d"dialog"\x3e\x3cb class\x3d"zen-arrow"\x3e\x3c/b\x3e\x3cdiv class\x3d"zen-inner"\x3e\x3cdiv class\x3d"zen-header zen-phl"\x3e\x3ch1 class\x3d"walkthrough-callout-title" id\x3d"walkthrough-callout-title-{{cloud}}"\x3e{{{title}}}\x3c/h1\x3e\x3cdiv id\x3d"walkthrough-callout-close" class\x3d"zen-pas"\x3e\x3cimg src\x3d"/img/walkthrough/callout/close{{altIcon}}.png" alt\x3d"{{closealt}}" title\x3d"{{close}}"/\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"zen-body zen-phl"\x3e\x3cdiv class\x3d"walkthrough-callout-description" id\x3d"walkthrough-callout-description-{{cloud}}"\x3e{{{description}}}\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"zen-footer zen-phl"\x3e\x3cdiv id\x3d"walkthrough-callout-footer"\x3e\x3cdiv id\x3d"walkthrough-callout-step-label"\x3e{{#stepcount}}{{label_step}}{{/stepcount}}{{^stepcount}}\x26nbsp;{{/stepcount}}\x3c/div\x3e\x3cdiv id\x3d"walkthrough-callout-controls"\x3e{{^autocomplete}}\x3ca class\x3d"zen-pas walkthrough-callout-next" href\x3d"javascript:void(0)" title\x3d"{{controls.nextalt}}"\x3e{{controls.next}} \x26raquo;\x3c/a\x3e{{/autocomplete}}{{#controls.custom}}{{^autocomplete}} | {{/autocomplete}}\x3ca class\x3d"zen-pas walkthrough-callout-custom" href\x3d"javascript:void(0)" onclick\x3d"{{controls.custom.command}}" title\x3d"{{controls.custom.label}}"\x3e{{controls.custom.label}}\x3c/a\x3e{{/controls.custom}}\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',
a)}});this.attach=function(a,b){c.add(this,a,b)};this.detach=function(a,b){c.remove(this,a,b)};this.notify=function(a,b){c.fireEvent(this,a,{data:b})}}}))})(Sfdc,this);
(function(d,g){d.provide("SfdcApp.Walkthrough.Core.Runtime.Locators.AuraLocator",d.Class({$implements:[SfdcApp.Walkthrough.Core.Runtime.Locators.ILocator],$constructor:function(b){this.targetsByLocalID={}},findComponents:function(b){b=b.split(",");for(var a=[],c=0;c<b.length;c++){var f=b[c].substring(3),e=this.targetsByLocalID[f];d.log("Searched registry for non-prefixed selector: "+f);e?e.isValid()?(d.log("Found a match!"),a.push(e)):(d.log("Found a match, but the component is no longer valid - deleting it from the registry."),
delete this.targetsByLocalID[f]):d.log("No match found!")}d.log("Returning "+a.length+" Aura components.");return a},findElements:function(b,a){if(0!==b.indexOf("$A."))return d.log("AuraLocator was asked to resolve non-Aura (CSS) selectors; forwarding to traditional DOM search."),SfdcApp.Walkthrough.Core.Runtime.Util.Dom.searchAll(b,a);d.log("The first selector is an Aura selector; assuming all selectors in this call have the Aura prefix ($A).");for(var c=this.findComponents(b),f=[],e=0;e<c.length;e++)f.push(c[e].getElement());
return f},hasValue:function(b,a,c){if(0!==b.indexOf("$A."))return d.log("AuraLocator was asked to find the value associated with a non-Aura (CSS) selectors; forwarding to traditional DOM search."),SfdcApp.Walkthrough.Core.Runtime.Util.Dom.hasValue(b,a,c);d.log("Testing whether the Aura component has a non-zero-length value: "+b);b=this.findComponents(b);a=b.length?b[0]:null;if(!a)return d.log("Target component is not even on the page: "+elementSelector),!1;b=a.getDef().getDescriptor().getQualifiedName();
a=a.getValue("v.value").getValue();d.log("The Aura component type is: "+b);if(void 0===a)throw"Component "+b+" does not have a value attribute; does it extend ui:input?";if("ui:inputRadio"==b||"ui:inputCheckbox"==b)return d.log("Target element is a radio button or checkbox that "+(a?"was":"was NOT")+" selected."),a;a=d.String.trim(a.toString());if(!a.length)return d.log("Target input field does not have a non-zero-length value: "+elementSelector),!1;if(c&&c!=a)return d.log("Target input field has a value, but it doesn't match the required value:"),
d.log("\t"+a+" !\x3d "+c),!1;d.log("Target input field has the following value: "+a);return!0},registerTargets:function(b){d.log("Registering "+b.length+" Aura components:");for(var a=0;a<b.length;a++){var c=b[a].getLocalId();d.log("\t"+c);this.targetsByLocalID[c]=b[a]}},removeTargets:function(b){d.log("Removing "+b.length+" Aura components:");for(var a=0;a<b.length;a++){var c=b[a].getLocalId();d.log("\t"+c);delete this.targetsByLocalID[c]}},whereAreWe:function(b,a){var c=g.location;a&&(c=SfdcApp.Walkthrough.Core.Runtime.Util.Dom.searchAll(a),
d.assert(c.length,"No iframes found for selector: "+a),c=c[0].contentWindow.location);c=c.pathname+c.search;return b?SfdcApp.Walkthrough.Core.Runtime.Util.URI.patternFor(c):c}}))})(Sfdc,this);
(function(d,e){d.provide("SfdcApp.Walkthrough.Core.Runtime.Locators.TraditionalWebLocator",d.Class({$implements:[SfdcApp.Walkthrough.Core.Runtime.Locators.ILocator],$constructor:function(c){},findElements:function(c,b){return SfdcApp.Walkthrough.Core.Runtime.Util.Dom.searchAll(c,b)},hasValue:function(c,b,a){return SfdcApp.Walkthrough.Core.Runtime.Util.Dom.hasValue(c,b,a)},whereAreWe:function(c,b){var a=e.location;b&&(a=SfdcApp.Walkthrough.Core.Runtime.Util.Dom.searchAll(b),d.assert(a.length,"No iframes found for selector: "+
b),a=a[0].contentWindow.location);a=a.pathname+a.search;return c?SfdcApp.Walkthrough.Core.Runtime.Util.URI.patternFor(a):a}}))})(Sfdc,this);
(function(c,f){c.provide("SfdcApp.Walkthrough.Core.Runtime.Validators.LocalStepValidator",c.Class({$decorators:[c.Class.Config],$implements:[SfdcApp.Walkthrough.Core.Runtime.Validators.IStepValidator],$constructor:function(a){a=c.apply({locator:null},a||{},!0);this.setConfig(a);c.assert(this.config.locator,"ILocator is null or undefined!")},canStart:function(a,d){c.log("Validating start criteria for walkthrough step...");if(!this.validateStartsOnPageCondition(a,d))return c.log("Start validation failed: page condition"),
!1;if(!this.validateStartsOnTargetCondition(a,d))return c.log("Start validation failed: target condition"),!1;c.log("Validation complete - step can start.");return!0},isCompleted:function(a,d){c.log("Validating completion criteria for walkthrough step...");var b=a.steps[d];if(!b.completedWhen.event)return!0;var e=!1;switch(b.completedWhen.event){case "pageLoad":e=this.validateCompletionPageCondition(a,d);break;case "valueEntered":e=this.validateCompletionValueCondition(b);break;case "isVisible":e=
this.validateCompletionVisibleCondition(b,!0);break;case "isHidden":e=this.validateCompletionVisibleCondition(b,!1);break;default:throw"Invalid step completion event: "+b.completedWhen.event;}b.status==WalkthroughStatus.NEW&&!b.completedWhen.autoComplete&&(c.log("This step is new, but does not support auto-completion, so it cannot be verified complete."),e=!1);e?c.log("Validation complete - step can finish."):c.log("Validation failed - step cannot finish.");return e},validateSchema:function(a){return!a||
!a.id?{isValid:!1,message:"Step id is required"}:!a.label?{isValid:!1,message:"Step title is required"}:100<a.label.length?{isValid:!1,message:"Step title can not be more than 100 characters"}:a.help&&a.help.primary&&a.help.primary.label&&400<a.help.primary.label.length?{isValid:!1,message:"Step description can not be more than 400 characters"}:{isValid:!0,message:""}},isVisible:function(a,d){return c.Dom.isVisible(a)},validateCompletionPageCondition:function(a,d){c.log("Evaluating page load condition in completion criteria...");
var b=a.steps[d].completedWhen,e=this.config.locator.whereAreWe(!1,b.iframe);c.log("Comparing "+e+" against "+b.target);return 192>Number(a.version||"186.0")?RegExp(b.target).test(e):SfdcApp.Walkthrough.Core.Runtime.Util.URI.test(b.target,e)},validateCompletionValueCondition:function(a){c.log("Evaluating value entered condition in completion criteria...");a=a.completedWhen;var d=a.target;c.isArray(d)||(d=[d]);c.log("There are "+d.length+" selectors to test...");for(var b=0;b<d.length;b++)if(!this.config.locator.hasValue(d[b],
a.iframe,a.exactMatch))return!1;return!0},validateCompletionVisibleCondition:function(a,d){c.log("Evaluating visibility condition in completion criteria...");c.log("Querying DOM using selector: "+a.completedWhen.target);var b=this.config.locator.findElements(a.completedWhen.target,a.completedWhen.iframe);c.log("There are "+b.length+" element(s) that match that selector.");return(b.length&&this.isVisible(b[0],a.completedWhen.isModal))==d},validateStartsOnPageCondition:function(a,d){c.log("Evaluating page condition in start criteria...");
var b=a.steps[d].startsOn.page;if(!b)return!0;var e=this.config.locator.whereAreWe(!1,b.iframe);c.log("Comparing "+e+" against "+b.path);c.log("We're hoping we "+(b.match?"find":"don't find")+" a match.");return(192>Number(a.version||"186.0")?RegExp(b.path).test(e):SfdcApp.Walkthrough.Core.Runtime.Util.URI.test(b.path,e))==b.match},validateStartsOnTargetCondition:function(a,d){c.log("Evaluating target condition in start criteria...");var b=a.steps[d].startsOn.target;if(!b)return!0;c.log("Searching the DOM with selector "+
b.path);c.log("We're hoping we "+(b.match?"find":"don't find")+" a match.");var e=this.config.locator.findElements(b.path,b.iframe);c.log("There are "+e.length+" element(s) that match that selector.");return 0<e.length==b.match}}))})(Sfdc,this);
(function(f,p){f.provide("SfdcApp.Walkthrough.Core.Ui.Steps.StepView",new f.Class({$constructor:function(h){function g(){e&&e.hide()}h=h||{};var d=new SfdcApp.Walkthrough.Core.Ui.Steps.Callout({cloud:h.cloud}),k=new f.Event.EventManager("onstart","onstop","onfinish","onredraw"),l=new SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.Border,q={"border-b":l,"border-l":l,"border-t":l,"border-r":l,window:SfdcApp.Walkthrough.Core.Ui.Steps.Highlights.Window.newInstance()},e=null,b=h.player,m,n;this.hashCode=
function(){return"SfdcApp.Walkthrough.Core.Ui.Steps.StepView"};this.attach=function(a,c){k.add(this,a,c)};this.detach=function(a,c){k.remove(this,a,c)};this.notify=function(a,c){k.fireEvent(this,a,{data:c})};this.attach("onstart",function(a,c){d.show(c);if(c&&c.highlight){var b=c.highlight;b&&q.hasOwnProperty(b)&&(b=q[b],e&&e.getHashCode()===b.getHashCode()||(g(),e=b),e.show(c))}else g()});this.attach("onstop",function(a,b){d.hide();g()});this.attach("onfinish",function(a,c){if(h.suppressTransitions||
c.definition.type==WalkthroughTypes.TOUR&&!c.definition.followedBy)d.hide(),g();else try{b.findNextWalkthroughDefinition(c,function(a){if(a){var c=null;a.type==WalkthroughTypes.TOUR?(c=SfdcApp.Walkthrough.Core.Runtime.Util.Link.generate(a,!1),c=f.String.format("window.location \x3d '{link}'",{link:c})):c=f.String.format("walkthrough.trials.player.startWalkthroughInstance('{id}')",a);a={player:b,stepindex:-1,stepcount:0,autocomplete:!0,controls:{custom:{label:a.label,command:c}},position:null,highlight:null,
detached:!0,title:LC.getLabel("walkthroughs","transition_step_title"),description:LC.getLabel("walkthroughs","transition_step_desc"),targets:[]}}else a={player:b,stepindex:-1,stepcount:0,autocomplete:!0,controls:{},position:null,highlight:null,detached:!0,title:LC.getLabel("walkthroughs","all_done_title"),description:LC.getLabel("walkthroughs","all_done_desc"),targets:[]};d.show(a);g()})}catch(e){f.log("Could not determine the next walkthrough for this role. "+e),d.hide(),g()}});this.attach("onredraw",
function(a){d&&(a=b.getActiveInstance())&&b.getCurrentStepUI(a,function(a){d.show(a,{skipScroll:!0,tryFocus:!1,isRedraw:!0})});e&&e.align()});b.subscribe("stepstarted",this,function(a){b.getCurrentStepUI(a,this.notify.bind(this,"onstart"))});b.subscribe("instancestopped",this,function(a){this.notify("onstop",a)});b.subscribe("instancefinished",this,function(a){this.notify("onfinish",a)});b.subscribe("instancefailed",this,function(a){f.resolve("current",a)?d.error():(d.hide(),g(),a=a.definition.type==
WalkthroughTypes.TOUR?"tours":"trials",f.resolve("walkthrough."+a+".player")||(a="authoring"),a={player:b,stepindex:-1,stepcount:0,autocomplete:!0,controls:{custom:{label:"Ok",command:"walkthrough."+a+".player.stopWalkthroughInstance()"}},stateCssClass:"walkthrough-callout-error",altIcon:"-black",position:null,highlight:null,detached:!0,title:LC.getLabel("walkthroughs","fatal_error_title"),description:LC.getLabel("walkthroughs","fatal_error_desc"),targets:[]},d.show(a))});b.subscribe("stepfailed",
this,function(a){d.error()});d.attach("onnext",function(){b.nextStep()});d.attach("onclose",function(){b.getActiveInstance()?b.stopWalkthroughInstance():(d.hide(),g())});k.add(p,"resize",function(){m&&clearTimeout(m);m=setTimeout(this.notify.bind(this,"onredraw"),500)},this);k.add(p,"scroll",function(){n&&clearTimeout(n);n=setTimeout(this.notify.bind(this,"onredraw"),500)},this)}}))})(Sfdc,this);
(function(a,b){walkthrough={log:function(){a.ClientLogging.addRelay(new a.ClientLogging.ConsoleLogger,!0);a.log("Console logging is ON.")}};a.onReady(function(){b.UserContext.initializeFromServlet(!0,function(){a.log("The walkthrough platform is loaded and ready; applications can now invoke its APIs.");a.provide("SfdcApp.Walkthrough.Core.Ready",{})})})})(Sfdc,this);

//# sourceMappingURL=/javascript/1417772649000/sfdc/source/WalkthroughCorePlatform.js.map
