/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
(function(c,f){function h(){(new SfdcApp.Walkthrough.Core.Runtime.TaskQueue({id:"Init.bootstrapWalkthroughApp",tasks:[function(a){walkthrough.trials.player.loadRoleDefinitions(a())},function(a,b){var d=a();c.assert(b.length,"Zero roles found on the server - something has gone terribly wrong!");1==b.length?d.success(b[0].id):(c.log("Opening role selection dialog..."),(new SfdcApp.Walkthrough.Core.Ui.RoleSelector({roles:b,callback:d.success})).show(document.body))},function(a,b){walkthrough.trials.player.updateRoleOnly(b,
a())},function(a,b){walkthrough.trials.player.loadWalkthroughDefinitions(b,a())},function(a){walkthrough.trials.player.setInitialized(!0);a=walkthrough.trials.player.getSelectedRoleDefinition();c.log("The introductory walkthrough for role '"+a.id+"' is '"+a.introduction+"'.");walkthrough.trials.player.startWalkthroughInstance(a.introduction)}]})).execute(this)}function g(a){c.log("Failed to initialize walkthrough application. Some of the walkthrough features may not be available, but the rest of the page will operate normally.");
c.log("The original error was: "+a);sendWalkthroughGack(a.message?a:{message:a})}function k(){c.log("Evaluating current page's URL against those in the sidebar exclusion list...");for(var a=f.location.pathname+f.location.search,b=0;b<SidebarExcludedPages.length;b++)if(RegExp(SidebarExcludedPages[b]).test(a))return c.log("The URL matches "+SidebarExcludedPages[b]+" - the sidebar will not be loaded."),!0;return!1}function l(a){try{var b=c.Url.getUrlParameters(a);b.wt?c.log("URL includes request for walkthrough: "+
b.wt):c.log("No walkthrough referenced in the URL - we will try to restart per usual.");walkthrough.trials.player.reload(b.wt)}catch(d){g(d)}}function m(){c.log("Initializing walkthrough trial application...");var a=f.UserContext.cloud;a?c.log("The walkthrough cloud is: "+a):(c.log("Walkthrough cloud not specified - defaulting to Sales Cloud."),a=SalesforceClouds.SALES);if(window.top!=window.self)c.log("Walkthrough application is running in an iframe - short-circuiting.");else{var b=new SfdcApp.Walkthrough.Core.Runtime.Definitions.StaticFileProvider({cloud:a,
collection:"definitions"}),d=new SfdcApp.Walkthrough.Core.Runtime.Instances.LocalStorageProvider({collection:"trials"}),e=null;"Theme3"==f.UserContext.uiSkin?e=new SfdcApp.Walkthrough.Core.Runtime.Locators.TraditionalWebLocator:(e=new SfdcApp.Walkthrough.Core.Runtime.Locators.AuraLocator,walkthrough.aura=e);var g=new SfdcApp.Walkthrough.Core.Runtime.Validators.LocalStepValidator({locator:e});walkthrough.trials={player:new SfdcApp.Walkthrough.Core.Runtime.Player({definitions:b,instances:d,locator:e,
validator:g})};c.log("Checking walkthrough application for new code or requirements...");b=new SfdcApp.Walkthrough.Core.Runtime.Upgrader({player:walkthrough.trials.player});b.hasNewVersion()&&b.patch();walkthrough.importwizard=new SfdcApp.Walkthrough.Core.Ui.ImportWizard;walkthrough.importwizard.attach("onclose",function(){try{walkthrough.trials.player.nextStep()}catch(a){c.log("Failed to start next step after closing import wizard: "+a)}});k()||(new SfdcApp.Walkthrough.Core.Ui.Sidebar({container:f.document.body,
player:walkthrough.trials.player,importWizard:walkthrough.importwizard})).draw();new SfdcApp.Walkthrough.Core.Ui.Steps.StepView({player:walkthrough.trials.player,cloud:a});new SfdcApp.Walkthrough.Core.Runtime.Analytics({importWizard:walkthrough.importwizard,player:walkthrough.trials.player});walkthrough.trials.player.isInitialized()?(a=e.whereAreWe(),setTimeout(l.bind(this,a),500)):h()}}c.onReady(function(){try{c.require("SfdcApp.Walkthrough.Core.Ready",m)}catch(a){g(a)}})})(Sfdc,this);

//# sourceMappingURL=/javascript/1417772649000/sfdc/source/WalkthroughTrials.js.map
