//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient._ui.core.chatter.files {
    
    
    public partial class detail {
        
        /// <summary>
        /// SesstionTimeout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.SesstionTimeout SesstionTimeout1;
        
        /// <summary>
        /// FileMainNav1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebClient.UIControls.ZenPageHeader FileMainNav1;
        
        /// <summary>
        /// ZenPageFooter1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.ZenPageFooter ZenPageFooter1;
    }
}
