//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.home {
    
    
    public partial class personhome {
        
        /// <summary>
        /// PageTitle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.PageTitle PageTitle1;
        
        /// <summary>
        /// TopRight1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebClient.UIControls.TopNav TopRight1;
        
        /// <summary>
        /// MainNav1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebClient.UIControls.MainNav MainNav1;
        
        /// <summary>
        /// HomeTaskListBlock1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.HomeTaskListBlock HomeTaskListBlock1;
        
        /// <summary>
        /// HomeThisWeekEventList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.HomeThisWeekEventList HomeThisWeekEventList;
        
        /// <summary>
        /// SmallCalendar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.SmallCalendar SmallCalendar1;
        
        /// <summary>
        /// CalendarQuickButtons1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.CalendarQuickButtons CalendarQuickButtons1;
        
        /// <summary>
        /// SiteFooter1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.PageFooter SiteFooter1;
    }
}
