/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
(function(h){if(!h.Sfdc||!h.Sfdc.canvas||!h.Sfdc.canvas.module){var s={};if(h.Sfdc&&h.Sfdc.canvas)for(var p in h.Sfdc.canvas)h.Sfdc.canvas.hasOwnProperty(p)&&(s[p]=h.Sfdc.canvas[p]);var t=Object.prototype,l=Array.prototype,q=h.document,e={hasOwn:function(a,b){return t.hasOwnProperty.call(a,b)},isUndefined:function(a){return void 0===a},isNil:function(a){return e.isUndefined(a)||null===a||""===a},isNumber:function(a){return!!(0===a||a&&a.toExponential&&a.toFixed)},isFunction:function(a){return!(!a||
!a.constructor||!a.call||!a.apply)},isArray:Array.isArray||function(a){return"[object Array]"===t.toString.call(a)},isArguments:function(a){return!(!a||!e.hasOwn(a,"callee"))},isObject:function(a){return null!==a&&"object"===typeof a},isString:function(a){return null!==a&&"string"==typeof a},appearsJson:function(a){return/^\{.*\}$/.test(a)},nop:function(){},invoker:function(a){e.isFunction(a)&&a()},identity:function(a){return a},each:function(a,b,c){if(!e.isNil(a)){var d=l.forEach,f=0,g,m;g=a.length;
c=c||a;if(d&&d===a.forEach)a.forEach(b,c);else if(e.isNumber(g))for(;f<g&&!1!==b.call(c,a[f],f,a);)f+=1;else for(m in a)if(e.hasOwn(a,m)&&!1===b.call(c,a[m],m,a))break}},startsWithHttp:function(a,b){return!e.isString(a)?a:"http"===a.substring(0,4)?a:b},map:function(a,b,c){var d=[],f=l.map;if(e.isNil(a))return d;if(f&&a.map===f)return a.map(b,c);c=c||a;e.each(a,function(a,e,f){d.push(b.call(c,a,e,f))});return d},values:function(a){return e.map(a,e.identity)},slice:function(a,b,c){return l.slice.call(a,
e.isUndefined(b)?0:b,e.isUndefined(c)?a.length:c)},toArray:function(a){return!a?[]:a.toArray?a.toArray:e.isArray(a)?a:e.isArguments(a)?e.slice(a):e.values(a)},size:function(a){return e.toArray(a).length},indexOf:function(a,b){var c=l.indexOf,d;if(!a)return-1;if(c&&a.indexOf===c)return a.indexOf(b);c=0;for(d=a.length;c<d;c+=1)if(a[c]===b)return c;return-1},isEmpty:function(a){if(null===a)return!0;if(e.isArray(a)||e.isString(a))return 0===a.length;for(var b in a)if(e.hasOwn(a,b))return!1;return!0},
remove:function(a,b){var c=e.indexOf(a,b);0<=c&&a.splice(c,1)},param:function(a,b){function c(a,f){e.isNil(f)||(f=e.isFunction(f)?f():f,e.isArray(f)?e.each(f,function(b,d){c(a,b)}):d[d.length]=b?encodeURIComponent(a)+"\x3d"+encodeURIComponent(f):a+"\x3d"+f)}var d=[];b=b||!1;if(e.isArray(a))e.each(a,function(a,b){c(b,a)});else for(var f in a)e.hasOwn(a,f)&&c(f,a[f]);return d.join("\x26").replace(/%20/g,"+")},objectify:function(a){var b={},c,d,f,g;if(e.isNil(a))return b;"?"==a.substring(0,1)&&(a=a.substring(1));
a=a.split("\x26");for(c=0;c<a.length;c+=1)d=a[c].split("\x3d"),f=d[0],d=d[1],g=b[f],e.isNil(g)?b[f]=d:e.isArray(g)?g[g.length]=d:(b[f]=[],b[f][0]=g,b[f][1]=d);return b},stripUrl:function(a){return e.isNil(a)?null:a.replace(/([^:]+:\/\/[^\/\?#]+).*/,"$1")},query:function(a,b){if(e.isNil(b))return a;a=a.replace(/#.*$/,"");return a+=/^\#/.test(b)?b:(/\?/.test(a)?"\x26":"?")+b},extend:function(a){e.each(e.slice(arguments,1),function(b,c){e.each(b,function(b,c){a[c]=b})});return a},endsWith:function(a,
b){return-1!==a.indexOf(b,a.length-b.length)},capitalize:function(a){return a.charAt(0).toUpperCase()+a.slice(1)},uncapitalize:function(a){return a.charAt(0).toLowerCase()+a.slice(1)},decode:function(a){var b=[],c,d,f="",g,h="",k=0;a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");do c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(k++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(k++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(k++)),
h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(k++)),c=c<<2|d>>4,d=(d&15)<<4|g>>2,f=(g&3)<<6|h,b.push(String.fromCharCode(c)),64!==g&&b.push(String.fromCharCode(d)),64!==h&&b.push(String.fromCharCode(f));while(k<a.length);return e.escapeToUTF8(b.join(""))},escapeToUTF8:function(a){for(var b="",c=0;c<a.length;){var d=a.charCodeAt(c++),f;if(128>d)b+=String.fromCharCode(d);else if(191<d&&224>d)f=a.charCodeAt(c++),b+=String.fromCharCode((d&31)<<6|f&63);else{f=
a.charCodeAt(c++);var e=a.charCodeAt(c++),b=b+String.fromCharCode((d&15)<<12|(f&63)<<6|e&63)}}return b},validEventName:function(a,b){var c,d=a.split(/\./),f=/^[$A-Z_][0-9A-Z_$]*$/i,g={sfdc:!0,canvas:!0,force:!0,salesforce:!0,chatter:!0};e.each(e.isArray(b)?b:[b],function(a){g[a]=!1});return 2<d.length?1:2===d.length&&(c=d[0].toLowerCase(),g[c])?2:!f.test(d[0])||!f.test(d[1])?3:0},prototypeOf:function(a){var b=Object.getPrototypeOf;return e.isFunction(b)?b.call(Object,a):"object"===typeof{}.__proto__?
a.__proto__:a.constructor.prototype},module:function(a,b){var c=a.split("."),d=h.Sfdc.canvas,f,g;"canvas"===c[1]&&(c=c.slice(2));g=c.length;for(f=0;f<g;f+=1)e.isUndefined(d[c[f]])&&(d[c[f]]={}),d=d[c[f]];e.isFunction(b)&&(b=b());return e.extend(d,b)},document:function(){return q},byId:function(a){return q.getElementById(a)},byClass:function(a){return q.getElementsByClassName(a)},attr:function(a,b){var c=a.attributes,d;for(d=0;d<c.length;d+=1)if(b===c[d].name)return c[d].value},onReady:function(a){e.isFunction(a)&&
n.push(a)},console:function(){function a(){try{return"sessionStorage"in window&&null!==window.sessionStorage}catch(a){return!1}}function b(){}function c(){}function d(){Function.prototype.bind?(b=Function.prototype.bind.call(console.log,console),c=Function.prototype.bind.call(console.error,console)):(b=function(){Function.prototype.apply.call(console.log,console,arguments)},c=function(){Function.prototype.apply.call(console.error,console,arguments)})}function f(){b=function(){};c=function(){}}var e=
!1;window&&!window.console&&(window.console={});window&&!window.console.log&&(window.console.log=function(){});window&&!window.console.error&&(window.console.error=function(){});(e=a()&&"true"===sessionStorage.getItem("canvas_console"))?d():f();return{enable:function(){e=!0;a()&&sessionStorage.setItem("canvas_console","true");d()},disable:function(){e=!1;a()&&sessionStorage.setItem("canvas_console","false");f()},log:b,error:c}}()},n=[],r=function(a){e.isFunction(a)&&n.push(a)};(function(){function a(){c||
(c=!0,a=e.nop,e.each(n,e.invoker),n=[])}function b(){if(!c)try{document.documentElement.doScroll("left"),a()}catch(d){setTimeout(b,30)}}var c=!1,d,f;if(document.addEventListener)document.addEventListener("DOMContentLoaded",a,!1);else if(document.attachEvent){try{d=self!==top}catch(g){}document.documentElement.doScroll&&!d&&b();document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&a()})}window.addEventListener?window.addEventListener("load",a,!1):window.attachEvent?
window.attachEvent("onload",a):(f=window.onload,window.onload=function(){f&&f();a()})})();e.each(e,function(a,b){r[b]=a});e.each(s,function(a,b){r[b]=a});(function(){for(var a,b=function(){},c="assert clear count debug dir dirxml error exception group groupCollapsed groupEnd info log markTimeline profile profileEnd table time timeEnd timeStamp trace warn".split(" "),d=c.length,e="undefined"!==typeof window&&window.console?window.console:{};d--;)a=c[d],e[a]||(e[a]=b)})();h.Sfdc||(h.Sfdc={});h.Sfdc.canvas=
r}})(this);
(function(b,a){var g=function(){var e;return{post:function(f,d,c){var h=Sfdc.JSON||JSON;if(b.isNil(d))throw"ERROR: target_url was not supplied on postMessage";d=b.stripUrl(d);c=c||parent;a.postMessage&&(b.isObject(f)&&(f.targetModule="Canvas"),f=h.stringify(f),b.console.log("Sending Post Message ",f),c.postMessage(f,d))},receive:function(f,d){a.postMessage&&(f&&(e=function(c){var a,e,g=Sfdc.JSON||JSON;b.console.log("Post Message Got callback",c);if(!b.isNil(c)){if("string"===typeof d&&c.origin!==
d)return b.console.log("source origin's don't match",c.origin,d),!1;if(b.isFunction(d)&&(e=d(c.origin,c.data),!1===e))return b.console.log("source origin's function returning false",c.origin,c.data),!1;if(b.appearsJson(c.data)){try{a=g.parse(c.data)}catch(k){}if(!b.isNil(a)&&(b.isNil(a.targetModule)||"Canvas"===a.targetModule))b.console.log("Invoking callback"),f(a,e)}}}),a.addEventListener?a.addEventListener("message",e,!1):a.attachEvent("onmessage",e))},remove:function(){a.postMessage&&(a.removeEventListener?
a.removeEventListener("message",e,!1):a.detachEvent("onmessage",e))}}}();b.module("Sfdc.canvas.xd",g)})(Sfdc.canvas,this);
(function(k){var p=function(){function l(d,a,e,g,b){m(d,a,a,function(a,c,d){a.appendChild(document.createTextNode(e));c.appendChild(document.createTextNode(g));d.appendChild(document.createTextNode(b))})}function m(d,a,e,g){if(!k.isNil(d)){var b,f,c,h;b=k.byId("canvas-notify-styles");k.isNil(b)&&(b=document.createElement("style"),b.setAttribute("name","canvas-notify-styles"),b.setAttribute("id","canvas-notify-styles"),b.type="text/css",window.attachEvent&&!window.opera?b.styleSheet.cssText=n:(f=document.createTextNode(n),
b.appendChild(f)),document.getElementsByTagName("head")[0].appendChild(b));b=document.createElement("div");b.setAttribute("class","canvas-notify-block");f=document.createElement("div");f.setAttribute("class","top-line");c=document.createElement("img");c.setAttribute("src",a);c.setAttribute("width","16");c.setAttribute("height","16");c.setAttribute("class","title-image");a=document.createElement("div");a.setAttribute("class","title-text");f.appendChild(c);f.appendChild(a);b.appendChild(f);f=document.createElement("div");
f.setAttribute("class","content");c=document.createElement("div");c.setAttribute("class","contentIcon");h=document.createElement("img");h.setAttribute("src",e);h.setAttribute("width","32");h.setAttribute("height","32");c.appendChild(h);f.appendChild(c);e=document.createElement("div");e.setAttribute("class","notify-message");c=document.createElement("div");c.setAttribute("class","subject-text");h=document.createElement("div");h.setAttribute("class","body-text");k.isFunction(g)&&g(a,c,h);e.appendChild(c);
e.appendChild(h);f.appendChild(e);for(b.appendChild(f);d.firstChild;)d.removeChild(d.firstChild);d.appendChild(b)}}var n="#canvas-notify-block {background: none repeat scroll 0 0 #FFFFFF;border-radius: 5px 5px 5px 5px;margin-bottom: 20px;overflow: hidden;position: relative;top: 1px;color: #222222;font-family: Arial,Helvetica,sans-serif;padding-left: 10px;}.canvas-notify-block .top-line{background-color: #DEDEDE;border: 1px solid #CCCCCC;border-radius: 5px 5px 0 0;padding-bottom: 15px;color: #222222;font-size: 10px;font-weight: bold;margin-bottom: 0px;margin-top: 0px;padding-left: 5px;padding-top: 0px;height: 10px;}.canvas-notify-block .top-line .title-image{float:left;padding-top:5px;}.canvas-notify-block .top-line .title-text{padding-left:20px;margin-top:8px;display:block;}.canvas-notify-block .content{border-bottom: 1px solid #CCCCCC;border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;border-left: 1px solid #CCCCCC;border-right: 1px solid #CCCCCC;font-size: 15px;padding-right: 4px;}.canvas-notify-block .content .contentIcon{float: left;height: 40px;margin-bottom: 3px;margin-left: 20px;margin-top: 6px;padding-top: 6px;width: 40px;}.canvas-notify-block .content .notify-message .subject-text{font-weight: bold;}.canvas-notify-block .content .notify-message .body-text{padding-top: 10px;}.canvas-notify-block .content .notify-message{padding-left:80px;padding-top:20px;padding-bottom:20px;font-size: 11px;}";
return{warning:function(d,a,e,g){l(d,"/img/msg_icons/warning32.png",a,e,g)},error:function(d,a,e,g){l(d,"/img/msg_icons/error32.png",a,e,g)},info:function(d,a,e,g){l(d,"/img/msg_icons/info32.png",a,e,g)},show:l,custom:m}}();k.module("Sfdc.canvas.notify",p)})(Sfdc.canvas);
(function(c){var M=function(){var G,m;function v(a,d,b,e){var g=LC.getLabel("CanvasParentJs","defaultNotifyTitle",b);b=LC.getLabel("CanvasParentJs","defaultRenderSummary",b);var h=w(1,f[a]);c.isNil(h)?c.notify.show(d,t("/img/msg_icons/error32.png"),g,b,e):h({title:g,summary:b,detail:e});c.isNil(f[a])||(H({name:"render",type:"ERROR",namespace:f[a].app.namespace,canvas:f[a].app.developerName,referenceId:f[a].app.referenceId,startTime:f[a].startTime,authType:f[a].app.authenticationType,payload:{canvasUrl:f[a].url,
localizedMessage:c.isObject(e)?q.stringify(e):e},cversion:f[a].cversion}),A(a));if(!c.isNil(f[a])&&c.isFunction(f[a].options.onCanvasAppError))f[a].options.onCanvasAppError()}function M(a,d,b,e,g,h){var k=t("/img/msg_icons/info32.png"),l=LC.getLabel("CanvasParentJs","defaultNotifyTitle",b),p=LC.getLabel("CanvasParentJs","defaultRenderSummary",b);b=w(2,f[a]);c.isNil(b)?c.notify.custom(d,k,k,function(a,b,d){a.appendChild(document.createTextNode(l));b.appendChild(document.createTextNode(p));d.appendChild(document.createTextNode(e));
c.isNil(h)||(a=document.createElement("a"),a.setAttribute("href",t(h)),a.setAttribute("title",g),a.appendChild(document.createTextNode(g)),d.appendChild(document.createElement("p")),d.appendChild(a))}):b({title:l,summary:p,detail:e});if(!c.isNil(f[a])){H({name:"render",type:"ERROR",namespace:f[a].app.namespace,canvas:f[a].app.developerName,referenceId:f[a].app.referenceId,startTime:f[a].startTime,authType:f[a].app.authenticationType,payload:{canvasUrl:f[a].url,localizedMessage:e},cversion:f[a].cversion});
if(c.isFunction(f[a].options.onCanvasAppError))f[a].options.onCanvasAppError();A(a)}}function w(a,d){var b=Z[a];return!c.isNil(d)&&(d.options&&!c.isNil(d.options.customCanvasRenderer)&&!c.isNil(d.options.customCanvasRenderer[b]))&&c.isFunction(d.options.customCanvasRenderer[b])?d.options.customCanvasRenderer[b]:null}function N(a,d){var b=f[a],e;e=w(0,b);var g=c.isNil(b.app.name)?"":b.app.name,g=LC.getLabel("CanvasParentJs","loadingStatus",g);b.options&&b.options.showLoadingStatus&&(c.isNil(e)?(A(a),
e=c.byId("loading-"+a),c.isNil(e)?(e=document.createElement("div"),e.setAttribute("id","loading-"+a),e.setAttribute("style","position:relative;width:25%;height:30px;margin-top:20px;margin-bottom:30px;"),e.style.display="block",d.appendChild(e)):e.style.display="block",b.loadingScreen=new LoadingScreen(e,Sfdc.String.escapeToHtml(g)),b.loadingScreen.show()):e(!0,g))}function A(a){var d=f[a],b=w(0,d);c.isNil(b)?(c.isNil(d.loadingScreen)||(d.loadingScreen.hide(),d.loadingScreen=null),a=c.byId("loading-"+
a),c.isNil(a)||(a.style.display="none",O(a))):b(!1)}function O(a){if(!c.isNil(a))for(;a.firstChild;)a.removeChild(a.firstChild)}function P(a){var d={},b,e;if(!c.isNil(a.record)&&!c.isNil(a.record.Id)&&(d.Id=a.record.Id,!c.isNil(a.record.fields))){a=a.record.fields.split(",");for(b=0;b<a.length;b+=1)e=a[b].trim(),c.isUndefined(d[e])&&(d[e]=null)}return d}function D(a,c){var b,e,f,h=c?c+a:a;f=window.document.getElementsByTagName("iframe");e=f.length;for(b=0;b<e;b+=1)try{if(f[b].name===h)return f[b].contentWindow}catch(k){}return frames[h]}
function t(a,d){var b=null,e=a;c.isNil(I)?c.isNil(J)||(e=J+e):(b=I+a,e=location.protocol+"//"+location.hostname+":"+location.port+"/services/proxy",d.headers["SalesforceProxy-Endpoint"]=b);UserContext&&UserContext.getUrl&&(e=UserContext.getUrl(e),UserContext.isDefaultNetwork||(e=Sfdc.Url.generateUrl(e)));return e}function $(a,d){var b=d.id;if(c.isNil(b))throw c.console.error(LC.getLabel("CanvasParentJs","missingIdInContext")),LC.getLabel("CanvasParentJs","missingIdInContext");if(a&&a.body){var e=
a.body.type,g=a.seq,h=f[b];h&&(h.cversion=a.clientVersion,h.oauthToken=a.body.config.client.oauthToken);c.console.log("xdCallback type [%s] seq [%d] id [%s]",e,g,b);"ctx"===e?n.services(g,b).ctx(a,h):"ajax"===e?n.services(g,b).ajax(a):"resize"===e?n.frame.childResize(a,h):"subscribe"===e?n.events.subscribe(a.body.subscriptions,h):"unsubscribe"===e?n.events.unsubscribe(a.body.subscriptions,h):"publish"===e?n.events.publishClient(a.body.event,h):"refresh"===e?n.services(g,b).refresh(a,h):"repost"===
e&&n.services(g,b).repost(a,h)}}function Q(){K&&c.xd.remove();c.xd.receive($,function(a,d){if(c.appearsJson(d)){d=q.parse(d);if(c.isNil(d.body)||c.isNil(d.body.config)||c.isNil(d.body.config.client))return c.console.error("JSON from postMessage invalid",d),!1;if(d.body.config.client.isVF)return c.console.log("can't find canvas, instanceId [%s] assuming from VF page",d.body.config.client.instanceId),{id:d.body.config.client.instanceId};var b=f[d.body.config.client.instanceId];if(!c.isNil(b))return c.console.log("post url: c.url "+
b.url),c.console.log("actual canvas url, c.app.canvasUrl"+b.app.canvasUrl),"refresh"===d.body.config.type&&c.stripUrl(b.app.canvasUrl)!==a?(c.console.error("Source origin and canvas url are from different domains",b.app.canvasUrl,a),!1):{id:d.body.config.client.instanceId}}return!1});K=!0}function R(a,d,b,e){var g=f[a].app.namespace,h=f[a].app.developerName,k=f[a].app.referenceId,l=P(d),g="/services/data/v"+r+"/platformconnect/signedrequest?"+(!c.isNil(k)?"referenceId\x3d"+k:"canvas\x3d"+h+(!c.isNil(g)?
"\x26namespace\x3d"+g:""));a={success:b,failure:e,headers:{Authorization:"OAuth "+C,Accept:"application/json"},contentType:"application/json",method:"PUT",data:q.stringify({canvasRequest:{context:{environment:{dimensions:{height:d.height.value,width:d.width.value,maxHeight:d.height.max,maxWidth:d.width.max,clientWidth:d.clientWidth,clientHeight:d.clientHeight},parameters:d.parameters,displayLocation:d.displayLocation,sublocation:d.sublocation,record:l}},client:{targetOrigin:document.location.protocol+
"//"+document.location.host,instanceId:a}}})};g=t(g,a);Sfdc.Ajax.request(g,a)}function H(a){var d=c.isNil(a.type)?null:a.type.toUpperCase();if(c.isNil(d)||-1===c.indexOf(["FINISH","ERROR"],d))throw LC.getLabel("CanvasParentJs","invalidTraceEventType");if(c.isNil(a.name))throw LC.getLabel("CanvasParentJs","invalidTraceEventName");if(c.isNil(a.canvas)&&c.isNil(a.referenceId))throw LC.getLabel("CanvasParentJs","invalidTraceCanvasAppNameOrId");var b="/services/data/v"+r+"/platformconnect/traceevent";
a={headers:{Authorization:"OAuth "+C,Accept:"application/json"},contentType:"application/json",data:q.stringify({eventName:a.name,eventType:d,namespace:a.namespace,canvas:a.canvas,referenceId:a.referenceId,payload:a.payload,authType:a.authType,startTime:a.startTime,endTime:(new Date).getTime(),parentVersion:r,clientVersion:a.cversion})};b=t(b,a);Sfdc.Ajax.post(b,function(){},a)}function x(a,d,b){f[a].startTime&&(H({name:"render",type:"FINISH",namespace:f[a].app.namespace,canvas:f[a].app.developerName,
referenceId:f[a].app.referenceId,startTime:f[a].startTime,authType:f[a].app.authType,payload:{canvasUrl:f[a].url},cversion:f[a].cversion}),f[a].startTime=null,A(a),d.style.display="inline");if(c.isFunction(b.onCanvasAppLoad))b.onCanvasAppLoad()}function aa(a,d,b,e,g){var h,k,l;h=document.createElement("form");h.setAttribute("name","canvas-hidden-form-"+a);h.setAttribute("style","display:none");h.setAttribute("action",f[a].url);h.setAttribute("target",y+a);h.setAttribute("method","post");k=document.createElement("input");
k.setAttribute("type","hidden");k.setAttribute("name","signed_request");k.value=d;d=document.createElement("input");d.setAttribute("type","submit");d.setAttribute("post","post");h.appendChild(k);h.appendChild(d);b.appendChild(h);e=S(a,e,g);f[a].frameElement=e;b.appendChild(e);e.addEventListener?e.onload=function(){x(a,this,g);this.onload=null}:e.attachEvent&&(l=function(){var b=event.srcElement;c.isNil(b)||(x(a,b,g),b.detachEvent("onload",l))},e.attachEvent("onload",l));c.isNil(document.forms["canvas-hidden-form-"+
a])||document.forms["canvas-hidden-form-"+a].submit()}function S(a,c,b){var e=document.createElement("iframe");e.setAttribute("id",c);e.setAttribute("name",y+a);e.setAttribute("title",LC.getLabel("CanvasParentJs","iframeTitle",f[a].app.name));e.style.display="none";e.frameBorder=b.frameborder;e.width=b.width.value;e.height=b.height.value;e.scrolling=b.scrolling;return e}function ba(a,d,b,e){var g,h;b=S(a,b,e);f[a].frameElement=b;d=d.appendChild(b);b.addEventListener?b.onload=function(){x(a,this,e);
this.onload=null}:b.attachEvent&&(h=function(){var b=event.srcElement;c.isNil(b)||(x(a,b,e),b.detachEvent("onload",h))},b.attachEvent("onload",h));d.contentDocument?g=d.contentDocument:d.contentWindow&&(g=d.contentWindow.document);g.location.replace(f[a].url)}function T(a,d,b){var e=y+a,g,h=f[a].sr.split(".");g={};if(2!==h.length)throw LC.getLabel("CanvasParentJs","invalidSignedRequestFormat");h=q.parse(c.decode(h[1]));if(c.isNil(h)||c.isNil(h.context.application))throw LC.getLabel("CanvasParentJs",
"unableToParseApp");f[a].app=h.context.application;f[a].loginUrl=h.context.links.loginUrl;"OAUTH"!=f[a].app.authType&&c.isNil(h.client.oauthToken)&&(g._sfdc_canvas_auth="user_approval_required");f[a].authStatus=g;N(a,d);!c.isNil(f[a].aux)&&!c.isNil(f[a].aux.idpInitiatedUrl)?(c.console.log("IdpInitiated Request..."),g=f[a].aux.idpInitiatedUrl):g=decodeURIComponent(f[a].app.canvasUrl);h=document.location.protocol+"//"+document.location.host;if("OAUTH"===f[a].app.authType||!c.isEmpty(f[a].authStatus)){var k=
c.param(f[a].authStatus);!c.isNil(f[a].loginUrl)&&"https://login.salesforce.com"!==f[a].loginUrl&&(k+=(0<k.length?"\x26":"")+c.param({loginUrl:encodeURIComponent(f[a].loginUrl)}));k+="#target_origin\x3d"+encodeURIComponent(h)+"\x26instance_id\x3d"+a;f[a].url=c.query(g,k);ba(a,d,e,b)}else f[a].url=g,aa(a,f[a].sr,d,e,b)}function U(a,d,b){c.isNil(f[a].sr)?(V(d,b),R(a,b,function(c){c=q.parse(c);f[a].sr=c.response;f[a].aux=c.auxiliary;T(a,d,b)},function(b){var g=q.parse(b);b=f[a].app.name||f[a].app.developerName||
f[a].app.referenceId||"undefined";if(!c.isNil(g)&&1<=g.length)switch(g=g[0],g.errorCode){case "APP_NOT_FOUND":case "NO_ACCESS":case "UNSUPPORTED_LOCATION":case "ACCESS_TOKEN_RETRIEVAL_ERROR":case "APEX_CONFIGURATION_EXCEPTION":case "ADMIN_AUTH_REQUIRED":v(a,d,b,g.message);break;case "INVALID_SESSION_ID":v(a,d,b,LC.getLabel("CanvasParentJs","sessionInvalid"));break;case "NO_ACCESS_SETUP_ALLOWED":case "UNSUPPORTED_LOCATION_SETUP_ALLOWED":case "ADMIN_AUTH_REQUIRED_SETUP_ALLOWED":g=g.message.split("#");
M(a,d,b,g[0],LC.getLabel("CanvasParentJs","configureLabel"),1<g.length?g[1]:null);break;default:v(a,d,b,LC.getLabel("CanvasParentJs","signedRequestRetrievalError",g.errorCode+":"+g.message))}else v(a,d,b,LC.getLabel("CanvasParentJs","signedRequestRetrievalError",""))})):T(a,d,b)}function V(a,d){var b,e,f;c.isNil(a)||(c.isNil(d.clientWidth)&&(b=a.clientWidth,0===b&&(e=a.offsetParent,c.isNil(e)||(b=e.clientWidth)),d.clientWidth=b+"px"),c.isNil(d.clientHeight)&&(b=a.clientHeight,0===b&&(e=a.offsetParent,
f=a.offsetTop,c.isNil(e)||(b=e.clientHeight-f),0>b&&(b=0)),d.clientHeight=b+"px"))}function L(a,d){return(!c.isNil(a.developerName)?(c.isNil(a.namespace)?"_":a.namespace)+":"+a.developerName:a.referenceId)+(c.isNil(d)?":":":"+d)}function W(a,d,b){var e={frameborder:"0",width:{value:"800px",max:"1000px"},height:{value:"900px",max:"2000px"},scrolling:"no",displayLocation:"NONE",showLoadingStatus:!0};b&&(!c.isObject(b.width)&&!c.isNil(b.width)&&(b.width=c.extend(e.width,{value:b.width})),!c.isObject(b.height)&&
!c.isNil(b.height)&&(b.height=c.extend(e.height,{value:b.height})),b.width=c.extend(e.width,b.width||{}),b.height=c.extend(e.height,b.height||{}));b=c.extend(e,b||{});b.height.value=n.frame.minPixels(b.height.value,b.height.max);b.width.value=n.frame.minPixels(b.width.value,b.width.max);e=c.isObject(d)?d:c.byId(d);if(c.isNil(e))window.alert(LC.getLabel("CanvasParentJs","containerElementNotFound",d));else{d=L(a.app,b.canvasId);try{if(c.isNil(a)||c.isNil(a.sr)&&(c.isNil(a.app)||c.isNil(a.app.developerName)&&
c.isNil(a.app.referenceId)))throw LC.getLabel("CanvasParentJs","insufficientAppContainerInfo");if(c.isNil(a.version))throw LC.getLabel("CanvasParentJs","missingParentVersionInfo");C=a.sid||C;if(c.isNil(C))throw LC.getLabel("CanvasParentJs","missingSid");if(!c.isNil(Sfdc.userAgent)&&(Sfdc.userAgent.isIE6||Sfdc.userAgent.isIE7||Sfdc.userAgent.isOpera||Sfdc.userAgent.isNetscape))throw LC.getLabel("CanvasParentJs","unsupportedBrowser");u(e,d);f[d]={instanceId:d,app:a.app,sr:a.sr,cversion:null,options:b,
startTime:(new Date).getTime(),onCanvasSubscribed:b.onCanvasSubscribed,parentElem:e};r=a.version;I=b.salesforceBaseUrl;J=b.customPathPrefix;N(d,e);U(d,e,b);Q()}catch(g){a=!c.isNil(a.app)?a.app.developerName||a.app.referenceId||"undefined":"undefined",v(d,e,a,g)}}}function u(a,d,b){n.events.unsubscribeAll(f[d]);a=c.isObject(a)?a:c.byId(a);O(a);c.isNil(b)&&delete f[d]}var K=!1;G="canvas.scroll";m="sfdc.streamingapi";var Z=["toggleLoadingScreen","renderError","renderInfo","renderCanvas"],f={},r,C,I,
J,y="canvas-frame-",q=Sfdc.JSON||JSON,n=function(){var a=function(){function b(a,b){var d,e=a.name;c.isNil(b)||(e===m?!c.isNil(b.handlers)&&!c.isNil(b.handlers[e])&&(d=b.handlers[e][a.params.topic]):!c.isNil(b.handlers)&&!c.isNil(b.handlers[e])&&(d=b.handlers[e]));return d}function d(a){var e=!1;c.each(f,function(d){c.isNil(b(a,d))||(e=!0)});return e}function g(a,d){var e;if(c.isNil(a.target)&&c.isNil(d))c.console.log("Targeting all canvas apps"),c.each(f,function(d,h){e=b(a,d);c.isNil(e)||(c.isFunction(e)?
e(a.payload):c.xd.post({parentVersion:r,clientVersion:d.cversion,payload:a,type:"event"},c.stripUrl(d.url),D(h,y)))});else if(!c.isNil(a.target)&&!c.isNil(a.target.canvas)&&"parent"===a.target.canvas)e=b(a,f.parent),c.isFunction(e)&&e(a.payload);else if(c.isNil(d))if(c.isNil(a.target.iframe))c.isNil(a.target.canvas)?c.console.error("Nothing to target"):(c.console.log("Targeting single canvas ",a.target.canvas),c.each(f,function(d,h){var f=h.split(":");f[f.length-1]===a.target.canvas&&(c.console.log("Found targeted canvas app"),
e=b(a,d),c.isNil(e)?c.console.log("Canvas app has no handler"):c.xd.post({parentVersion:r,clientVersion:d.cversion,payload:a,type:"event"},c.stripUrl(d.url),D(h,y)))}));else{c.console.log("Targeting single iframe");var h=D(a.target.iframe);c.isNil(h)||c.xd.post({parentVersion:r,clientVersion:r,payload:a,type:"event"},"*",h)}else c.console.log("Targeting canvas object"),e=b(a,d),(!c.isNil(e)||a.name===m)&&c.xd.post({parentVersion:r,clientVersion:d.cversion,payload:a,type:"event"},c.stripUrl(d.url),
D(d.instanceId,y))}function h(a,c,b,d){a="/services/data/v"+a.cversion;c={success:b,failure:d,headers:c,method:"HEAD"};a=t(a,c);Sfdc.Ajax.request(a,c)}function k(){var a;s.current===s.ninitd&&(s.current=s.initd,a="/cometd/"+r+"/",Sfdc.cometd.init({url:location.protocol+"//"+location.hostname+":"+location.port+a,requestHeaders:{Authorization:"OAuth "+C},appendMessageTypeToURL:!1}),z=Sfdc.cometd,c.isNil(u)&&(s.current=s.hs,u=z.addListener("/meta/handshake",function(a){a.successful?(!x&&X()&&z.batch(function(){var a,
b=c.toArray(f),d,e,h,k;for(h=0;h<b.length;h+=1){a=e=b[h];d=[];k=m;!c.isNil(a.handlers)&&!c.isNil(a.handlers[k])&&(d=a.handlers[k],d=c.toArray(d));a=d;for(k=0;k<a.length;k+=1)d=a[k][0],Y(d,e)}}),x=!1,s.current=s.hsdone,B()):s.current=s.hs})))}function l(a,c){var b=v(a[m]);if(b)p(b,c);else throw"["+m+"] Streaming subscription has no params or topic";}function p(a,b){var d,e=m;b.handlers=b.handlers||{};d=b.handlers;c.isNil(d[e])&&(d[e]={});c.isNil(d[e][a])&&h(b,{Authorization:"OAuth "+b.oauthToken},
function(){n(a,b)},function(c,d){var h;h=401===d.status?LC.getLabel("CanvasParentJs","subscribeRequiresAPI",e):LC.getLabel("CanvasParentJs","subscribeGenericError",d.status,e);g({name:e,params:{topic:a},method:"onComplete",payload:{success:!1,errorMessage:h}},b)})}function n(a,c){var b,d,e=m,h;k();h=function(){b=z.subscribe(a,function(b){g({name:e,params:{topic:a},method:"onData",payload:b},c)});d={success:!0,handle:b};b&&(c.handlers[e][a]=b,g({name:e,params:{topic:a},method:"onComplete",payload:d},
c))};s.current===s.hsdone?h():E.push(h)}function B(){var a;for(a=0;a<E.length;a+=1)if(c.isFunction(E[a]))E[a]();E=[]}function Y(a,c){var b,d=m;(b=z.subscribe(a,function(b){g({name:d,params:{topic:a},method:"onData",payload:b},c)}))&&(c.handlers[d][a]=b)}function q(a){z.unsubscribe(a);X()||(z.removeListener(u),u=null,x=!0,s.current=s.ninitd,z.disconnect())}function X(){var a=!1;c.each(f,function(b){return!c.isNil(b.handlers)&&!c.isNil(b.handlers[m])?(a=!0,!1):!0});return a}function v(a){return!c.isNil(a.params)&&
!c.isNil(a.params.topic)?a.params.topic:null}function w(a,b){var d,e=c.validEventName(a,b);if(0!==e)throw d={1:LC.getLabel("CanvasParentJs","eventMultipleNamespaces"),2:LC.getLabel("CanvasParentJs","eventNamespaceReserved"),3:LC.getLabel("CanvasParentJs","eventInvalidCharacters")},d[e];}function A(a){var b,h=m,f,k,g;c.isNil(a)||(b=a.handlers,c.isNil(b)||(k=b[h],c.each(k,function(a,d){f=b[h][d];delete b[h][d];0>=c.size(b[h])&&delete b[h];q(f)}),a.handlers={},c.each(b,function(a,b){g=F[b];!c.isNil(g)&&
!d(b)&&g.unsubscribe()})))}var z,x=!0,s={ninitd:"notInitialized",initd:"initialized",hs:"handshake",hsdone:"handshakeDone",current:"notInitialized"},u,E=[],F=[];F[G]=function(){function a(){g({name:G,method:"onData",payload:{heights:{contentHeight:document.documentElement.scrollHeight,pageHeight:document.documentElement.clientHeight,scrollTop:document.documentElement&&document.documentElement.scrollTop||document.body.scrollTop},widths:{contentWidth:document.documentElement.scrollWidth,pageWidth:document.documentElement.clientWidth,
scrollLeft:document.documentElement&&document.documentElement.scrollLeft||document.body.scrollLeft}}})}var c=!1;return{subscribe:function(b){!0!==c&&(c=!0,window.addEventListener?window.addEventListener("scroll",a,!1):window.attachEvent&&window.attachEvent("onscroll",a))},unsubscribe:function(){!1!==c&&(window.removeEventListener?window.removeEventListener("scroll",a,!1):window.detachEvent&&window.detachEvent("onscroll",a),c=!1)}}}();F["canvas.orientation"]=function(){var a=!1,b;return{subscribe:function(d){!0!==
a&&(a=!0,b=function(){var a={},b;c.isNil(d.parentElem)||V(d.parentElem,a);b={orientation:window.orientation};c.isNil(a.clientHeight)||(b.clientHeight=a.clientHeight);c.isNil(a.clientWidth)||(b.clientWidth=a.clientWidth);g({name:"canvas.orientation",method:"onData",payload:b})},window.addEventListener?window.addEventListener("orientationchange",b,!1):window.attachEvent&&window.attachEvent("orientationchange",b,!1))},unsubscribe:function(){!1!==a&&(window.removeEventListener?window.removeEventListener("orientationchange",
b,!1):window.detachEvent&&window.detachEvent("orientationchange",b),a=!1,b=null)}}}();return{subscribe:function(a,b){var d=b.handlers||{},e,h;c.console.log("Subscribing ",b);if(c.isNil(a[m])){if(c.each(a,function(a,e){c.isNil(e)||(d[e]=a,h=F[e],c.isNil(h)||h.subscribe(b))}),b.handlers=d,c.isFunction(b.onCanvasSubscribed))b.onCanvasSubscribed()}else c.isNil(Sfdc.CometD)?(e=t("/jslibrary/SfdcExtended.js"),Sfdc.Resource.addJavaScript(e,function(){l(a,b)})):l(a,b)},unsubscribe:function(a,h){var f,k;if(c.isNil(a[m])){if(!c.isNil(h))for(f in a)a.hasOwnProperty(f)&&
!c.isNil(h.handlers[f])&&(delete h.handlers[f],k=F[f],!c.isNil(k)&&!d(f)&&k.unsubscribe())}else{var g;k=m;var l;if(f=v(a[k]))g={name:k,params:{topic:f}},g=b(g,h),c.isNil(g)||(g=h.handlers,l=g[k][f],delete g[k][f],0>=c.size(g[k])&&delete g[k],q(l));else throw"["+m+"] unsubscribe has no params or topic";}},unsubscribeAll:function(a){A(a)},parentSubscribe:function(b){var d,e={};K||Q();c.isNil(f.parent)&&(f.parent={});d=f.parent;c.each(c.isArray(b)?b:[b],function(a){c.isNil(a.name)||(w(a.name,"canvas"),
e[a.name]=a.onData)});c.console.log("Parent subscribing");a.subscribe(e,d)},parentUnsubscribe:function(b){var d,e={};c.isNil(f.parent)&&(f.parent={});d=f.parent;c.each(c.isArray(b)?b:[b],function(a){c.isNil(a.name)||(w(a.name),e[a.name]=a.onData)});a.unsubscribe(e,d)},publish:function(a,b){g({name:a.name,method:"onData",payload:a.payload,target:a.target},b)},publishClient:function(b){!c.isNil(b.target)&&!c.isNil(b.target.iframe)&&(b.target.iframe=null);a.publish(b)},parentPublish:function(b){w(b.name);
a.publish(b)}}}(),d=function(){function a(b,d){return c.isNil(b)||c.isNil(d)||"final"===d?!1:!0}function d(a,b){if(c.endsWith(a,"%")||"infinite"===b||"final"===b)return c.endsWith(a,"%")||c.endsWith(a,"px")?a:a+"px";a=Number(a.split("px")[0]);b=Number(b.split("px")[0]);return(a<b?a:b)+"px"}function g(h,f){var g,p;!c.isNil(f)&&!c.isNil(f.frameElement)&&(a(h.height,f.options.height.max)&&(p=d(h.height,f.options.height.max),f.frameElement.height=p),a(h.width,f.options.width.max)&&(g=d(h.width,f.options.width.max),
f.frameElement.width=g));return{height:p,width:g}}return{minPixels:d,childResize:function(f,k){var l,p=f.body.config.client.instanceId;c.console.log("Child asking to be resized, id: [%s]",p);if(c.isNil(k)){l=f.body.size;var m,B,q,r,t;c.console.log("Resizing VF [%s] to ",p,l);m=c.byId(p);B=m.getAttribute("data-max-canvas-width")||"final";q=m.getAttribute("data-max-canvas-height")||"infinite";c.console.log("Max Width [%s] Max Height [%s]",B,q);a(l.height,q)&&(t=d(l.height,q),m.style.height=t);a(l.width,
B)&&(r=d(l.width,B),m.style.width=r);l={height:t,width:r};n.events.publish({name:"sfdc.resize",payload:l,target:{iframe:p}});n.events.publish({name:"sfdc.resize",payload:l,target:{canvas:"parent"}})}else l=g(f.body.size,k),n.events.publish({name:"canvas.resize",payload:l},k),n.events.publish({name:"canvas.resize",payload:l,target:{canvas:"parent"}})},parentResize:function(a,b){c.isNil(b)?(c.each(f,function(b){c.isNil(b.instanceId)||(g(a,b),n.events.publish({name:"canvas.resize",payload:a},b))}),n.events.publish({name:"canvas.resize",
payload:a,target:{canvas:"parent"}})):c.isNil(b.canvas)||c.each(f,function(c,d){var e=d.split(":");e[e.length-1]===b.canvas&&(g(a,c),n.events.publish({name:"canvas.resize",payload:a,target:b}),n.events.publish({name:"canvas.resize",payload:a,target:{canvas:"parent"}}))})}}}();return{events:a,services:function(a,d){function g(h,g){var l=g.getResponseHeader("Content-Type"),p={};p.seq=a;p.parentVersion=r;p.clientVersion=f[d].cversion;p.payload=l&&h&&0<=l.indexOf("application/json")?q.parse(h):h;p.status=
g.status;p.statusText=g.statusText;p.responseHeaders=g.getAllResponseHeaders();p.type="callback";c.xd.post(p,c.stripUrl(f[d].app.canvasUrl),D(d,y))}return{ctx:function(a,b){var f=b.app.namespace,p=b.app.developerName,n=b.app.referenceId,m=c.byId(y+d),u=c.isNil(b.cversion)?r:b.cversion,v=P(b.options),f="/services/data/v"+u+"/platformconnect/canvascontext?"+(!c.isNil(n)?"referenceId\x3d"+n:"canvas\x3d"+p+(!c.isNil(f)?"\x26namespace\x3d"+f:"")),m={success:g,failure:g,headers:{Authorization:"OAuth "+
a.body.accessToken,Accept:"application/json"},contentType:"application/json",method:"PUT",data:q.stringify({environment:{dimensions:{height:m&&m.height||null,width:m&&m.width||null},parameters:b.options.parameters,displayLocation:b.options.displayLocation,sublocation:b.options.sublocation,record:v}})},f=t(f,m);Sfdc.Ajax.request(f,m)},ajax:function(a){var b;a.body.config.success=g;a.body.config.failure=g;b=a.body.url;a=a.body.config;b=t(b,a);Sfdc.Ajax.request(b,a)},refresh:function(a,b){var d,e,f;
if("OAUTH"===b.app.authType)throw LC.getLabel("CanvasParentJs","authTypeMismatch");R(b.instanceId,b.options,function(a,b){200==b.status?(d=q.parse(a),f=d.response.split("."),e=q.parse(c.decode(f[1])),c.isNil(e.client.oauthToken)?g("{}",{status:403,statusText:LC.getLabel("CanvasParentJs","userApprovalRequired"),getAllResponseHeaders:function(){return b.getAllResponseHeaders()},getResponseHeader:function(a){return b.getResponseHeader(a)}}):g(a,b)):g(a,b)},g)},repost:function(a,b){var c=a.body.refresh||
!1;if("OAUTH"===b.app.authType)throw LC.getLabel("CanvasParentJs","authTypeMismatch");c&&(b.sr=null);u(b.parentElem,b.instanceId,!1);b.options.showLoadingStatus=null;b.startTime=(new Date).getTime();U(b.instanceId,b.parentElem,b.options)}}},frame:d}}();return{render:W,feed:function(a,d,b){var e=c.byId(d),g=c.byId("canvas-icon-"+b.canvasId),h;h=L(a.app,b.canvasId);e&&"block"===e.style.display?(e.style.display="none",g.style.display="block",u(d,h)):c.isNil(f[h])&&(b.onCanvasAppLoad=function(){e.style.display=
"block";g.style.display="none"},b.onCanvasAppError=b.onCanvasAppLoad,b.parameters=q.parse(b.parameters),W(a,e,b))},subscribe:n.events.parentSubscribe,unsubscribe:n.events.parentUnsubscribe,publish:n.events.parentPublish,resize:n.frame.parentResize,close:function(a,c,b){a=L(a,b);u(c,a)}}}();c.module("Sfdc.canvas.parent",M)})(Sfdc.canvas);

//# sourceMappingURL=/javascript/1411635697000/canvas/source/CanvasRendering.js.map
