/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Ext.namespace("sfdc.analytics.framework.PaletteType");sfdc.analytics.framework.PaletteType.PALETTE_PAGE=0;sfdc.analytics.framework.PaletteType.PALETTE_CHART=1;
sfdc.analytics.framework.ColorField=Ext.extend(Ext.form.TriggerField,{paletteType:sfdc.analytics.framework.PaletteType.PALETTE_CHART,triggerConfig:{tag:"a",title:"Choose a Color (New Window)",children:[{tag:"img",src:"/s.gif",cls:"colorPickerIcon",style:"vertical-align: middle",title:"Choose a Color (New Window)",alt:"Choose a Color (New Window)"}]},setValue:function(b){function a(b,c){var a=Number(b).toString(16);for(c="undefined"===typeof c||null===c?c=2:c;a.length<c;)a="0"+a;return a}sfdc.analytics.framework.ColorField.superclass.setValue.call(this,
b);this.sampleBlock&&this.sampleBlock.setStyle("background-color","#"+a(b,6))},initComponent:function(){Ext.apply(this,{autoCreate:{tag:"input",type:"hidden"}});sfdc.analytics.framework.ColorField.superclass.initComponent.call(this);this.on({render:function(b){b.el.dom.setValue=function(a){this.el.dom.value=a;this.fireEvent("change",this)}.createDelegate(b)}})},initTrigger:function(){this.mon(this.trigger,"click",this.showColorPopup,this,{preventDefault:!0});this.sampleBlock=this.trigger.insertSibling({tag:"span",
id:this.id+"cell",cls:"analyticsColorPicker"},"before")},showColorPopup:function(b){if(!0!==this.disabled){var a=this.paletteType===sfdc.analytics.framework.PaletteType.PALETTE_PAGE?250:128,d=this.paletteType===sfdc.analytics.framework.PaletteType.PALETTE_PAGE?175:128,c=this.findParentByType("form").form.id;setLastMousePosition(b.browserEvent);openPopupFocus(UserContext.getUrl("/widg/colorpicker.jsp?field\x3d"+this.id+"\x26form\x3d"+c+"\x26p\x3d"+this.paletteType),this.id,300,300,"width\x3d"+a+",height\x3d"+
d+",resizable\x3dno,toolbar\x3dno,status\x3dno,scrollbars\x3dno,menubar\x3dno,directories\x3dno,location\x3dno,dependant\x3dno,",!0,!0)}}});Ext.reg("sfdc.analytics.framework.colorfield",sfdc.analytics.framework.ColorField);
Ext.namespace("sfdc.analytics.framework.ColumnLookupHelper");sfdc.analytics.framework.ColumnLookupHelper.isColumnFilterLookupSupported=function(b,a){return null!==a&&"Case.BusinessHours"===b||"MEMBER_STATUS"!==b&&"CAMPAIGN_MEMBER.STATUS"!==b&&"Lead.CampaignMemberStatus"!==b&&"StaticEnum"===a||"DynamicEnum"===a||"EnumOrId"===a||"Division"===a||"RecordType"===a||"Boolean"===a?!0:!1};
sfdc.analytics.framework.CustomFieldDatatypesEnum={TEXT:"S",DATE:"D",CURRENCY:"C",PERCENT:"P",NUMBER:"N",PICKLIST:"L",PHONE:"H",URL:"U",TEXTAREA:"X",EMAIL:"E",DATE_TIME:"F",FOREIGN_KEY:"Y",CHECKBOX:"B",MULTI_PICKLIST:"Q",AUTO_NUMBER:"V",LONG_TEXT_AREA:"J",HTML:"z",FORMULA:"Z",BUCKET:"b",SFDC_ENCRYPTED_TEXT:"T",ENCRYPTED_TEXT:"6",SUMMARY:"1",TIME:"f",FILE:"l",isNumeric:function(a){return sfdc.analytics.framework.CustomFieldDatatypesEnum.CURRENCY===a||sfdc.analytics.framework.CustomFieldDatatypesEnum.PERCENT===
a||sfdc.analytics.framework.CustomFieldDatatypesEnum.NUMBER===a||sfdc.analytics.framework.CustomFieldDatatypesEnum.PERCENT===a||sfdc.analytics.framework.CustomFieldDatatypesEnum.AUTO_NUMBER===a},isDate:function(a){return sfdc.analytics.framework.CustomFieldDatatypesEnum.DATE===a||sfdc.analytics.framework.CustomFieldDatatypesEnum.DATETIME===a}};
Ext.namespace("sfdc.analytics.framework");sfdc.analytics.framework.DataView=Ext.extend(Ext.DataView,{enable:function(){this.el.unmask();sfdc.analytics.framework.DataView.superclass.enable.call(this)},disable:function(){sfdc.analytics.framework.DataView.superclass.disable.call(this);this.el.mask().setStyle("opacity","0")}});Ext.reg("sfdc.analytics.framework.DataView",sfdc.analytics.framework.DataView);
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.FieldSetLayout=Ext.extend(Ext.layout.FormLayout,{getTemplateArgs:function(a){var b=!a.fieldLabel||a.hideLabel;return{id:a.id,label:a.fieldLabel,labelStyle:this.getLabelStyle(a.labelStyle),elementStyle:this.elementStyle||"",labelSeparator:b?"":"undefined"==typeof a.labelSeparator?this.labelSeparator:a.labelSeparator,itemCls:(a.itemCls||this.container.itemCls||"")+(a.hideLabel?" x-hide-label":""),clearCls:a.clearCls||"x-form-clear-left",infoIcon:a.infoIcon?!0:!1,removeButton:a.removeButton?
!0:!1,removeHandler:a.removeButton&&a.removeHandler?a.removeHandler:void 0}},renderItem:function(a,b,d){if(a&&!a.rendered&&(a.isFormField||a.fieldLabel)&&"hidden"!=a.inputType){var c=this.getTemplateArgs(a);Ext.isNumber(b)&&(b=d.dom.childNodes[b]||null);a.itemCt=b?this.fieldTpl.insertBefore(b,c,!0):this.fieldTpl.append(d,c,!0);a.getItemCt||Ext.apply(a,{getItemCt:function(){return a.itemCt},customItemCt:!0});a.label=a.getItemCt().child("label.x-form-item-label");a.rendered?this.isValidParent(a,d)||
Ext.fly("x-form-el-"+a.id).appendChild(a.getPositionEl()):a.render("x-form-el-"+a.id,0);if(this.trackLabels){if(a.hidden)this.onFieldHide(a);a.on({scope:this,show:this.onFieldShow,hide:this.onFieldHide})}this.configureItem(a);if(a.removeButton&&a.removeHandler&&(c=Ext.get(a.id+"DelLink")))c.on("click",a.removeHandler);if(a.lookupHandler&&(c=Ext.get(a.id+"LookupIcon")))c.on("click",a.lookupHandler)}else Ext.layout.FormLayout.superclass.renderItem.apply(this,arguments)}});
sfdc.analytics.framework.FieldSetLayout.FIELD_TPL=new Ext.XTemplate('\x3ctpl for\x3d"."\x3e','\x3cdiv class\x3d"x-form-item {itemCls}" tabIndex\x3d"-1" style\x3d"overflow:hidden"\x3e','\x3clabel for\x3d"{id}" style\x3d"{labelStyle}" class\x3d"x-form-item-label"\x3e{label}{labelSeparator}\x3c/label\x3e','\x3cdiv class\x3d"x-form-element" id\x3d"x-form-el-{id}" style\x3d"{elementStyle}"\x3e','\x3ctpl if\x3d"infoIcon"\x3e','\x3cspan id\x3d"{id}Info" class\x3d"mouseOverInfoOuter" style\x3d"padding-left:4px"\x3e\x3cimg class\x3d"infoIcon" src\x3d"/s.gif"/\x3e\x3c/span\x3e',
"\x3c/tpl\x3e","\x3c/div\x3e",'\x3cdiv class\x3d"{clearCls}"\x3e\x3c/div\x3e',"\x3c/div\x3e","\x3c/tpl\x3e");sfdc.analytics.framework.FieldSetLayout.FIELD_TPL.compile();Ext.Container.LAYOUTS.analytics_formlayout=sfdc.analytics.framework.FieldSetLayout;
sfdc.analytics.framework.Dialog=function(a){Ext.apply(this,a);this.id=a.id;this.alignToEl=a.alignToEl;this.alignToPosition=a.alignToPosition?a.alignToPosition:"tr-br";this.DialogRecordClass=Ext.data.Record.create(this.fields);this.waitSpinner=new Ext.Toolbar.TextItem({autoEl:"span",text:a.waitText,cls:"rb_spinner16"});this.closeOnExit=!0;var b=[];if(a.buttons&&0<a.buttons.length)for(var d=0;d<a.buttons.length;d++)b.push(a.buttons[d]);a.hideCancel||b.push({name:"cancel",text:LC.getLabel("AnalyticsDialog",
"cancelButton"),id:this.id+"CancelBtn",dialog:this,handler:function(a){a.onCancel()}.createCallback(this)});var d=a.labelWidth?a.labelWidth:150,c=this.getContentItems(a);this.formPanel=new Ext.FormPanel({labelAlign:a.labelAlign||this.labelAlign,labelWidth:d,autoWidth:!0,autoHeight:!1===a.formPanelAutoHeight?!1:!0,height:a.formPanelHeight,autoScroll:!0===a.formPanelAutoScroll?!0:!1,border:!1,buttonAlign:"left",buttons:!0!==a.hideFormButtons?[this.waitSpinner,{xtype:"tbfill"}]:null,applyTo:a.applyTo,
monitorValid:a.monitorValid?a.monitorValid:!0,monitorPoll:1E3,items:c,layout:a.layout?a.layout:"form",layoutConfig:a.layoutConfig});var f=this;this.formPanel.on({clientvalidation:function(a,b){f.onFormValid(a,b)}});b={id:a.id,layout:"fit",closeAction:"hide",items:this.formPanel,plain:!0,resizable:!1,width:a.width||this.width,modal:!1===a.modal?!1:!0,buttons:b,buttonAlign:"center",autoHeight:!0,constrain:!0,draggable:!0===a.draggable?!0:!1,title:a.title,header:!1===a.header?!1:!0,shadow:!1===a.shadow?
!1:!0,closable:!1===a.closable?!1:!0,unstyled:!0===a.unstyled?!0:!1};a.extraCls&&(b.cls=a.extraCls);Ext.isDefined(a.shadow)&&(b.shadow=a.shadow);this.helpUrl&&(a=LC.getLabel("Buttons","page_help"),d=a+" "+LC.getLabel("Global","new_window"),b.toolTemplate=new Ext.XTemplate("\x3ctpl if\x3d\"id\x3d\x3d'dialogHelp'\"\x3e",'\x3ca href\x3d"javascript:void(null)" onclick\x3d"{href}" class\x3d"helpLink" title\x3d"'+d+'"\x3e\x3cdiv style\x3d"display:inline;" class\x3d"dialogHelpText"\x3e'+a+"\x3c/div\x3e",
'\x3cimg class\x3d"helpIcon" src\x3d"/s.gif"/\x3e\x3c/a\x3e',"\x3c/tpl\x3e","\x3ctpl if\x3d\"id!\x3d\x3d'dialogHelp'\"\x3e",'\x3cdiv class\x3d"x-tool x-tool-{id}"\x3e\x26#160;\x3c/div\x3e',"\x3c/tpl\x3e"),b.tools||(b.tools=[]),b.tools.push({id:"dialogHelp",href:this.helpUrl}));a=new Ext.Window(b);a.on("beforeshow",this.onBeforeShow.createDelegate(this));a.on("show",this.onShow.createDelegate(this));a.on("beforehide",this.onBeforeHide.createDelegate(this));this.form=this.formPanel.getForm();this.form.trackResetOnLoad=
!0;this.extDialog=a;this.extDialog.on("afterlayout",this.onAfterLayout.createDelegate(this));this.waitSpinner.hide()};
sfdc.analytics.framework.Dialog.prototype={setTitle:function(a){this.extDialog.setTitle(a)},load:function(){this.dialogRecord=new this.DialogRecordClass(this.data);this.form.loadRecord(this.dialogRecord)},showDialog:function(a){this.waitSpinner.hide();!0!==a&&(this.form.reset(),this.form.clearInvalid());this.extDialog.show();this.alignToEl?(a=Ext.get(this.alignToEl),this.extDialog.alignTo(a,this.alignToPosition)):this.extDialog.center()},postShowDialog:function(){},close:function(){this.extDialog.hide()},
isVisible:function(){return this.extDialog.isVisible()},setCancelDisabled:function(a){if(this.extDialog.buttons)for(var b=0,d=this.extDialog.buttons.length;b<d;b++){var c=this.extDialog.buttons[b];"cancel"==c.name&&(a?c.disable():c.enable())}},apply:function(){return this.form.isValid()?(this.form.updateRecord(this.dialogRecord),!0):!1},applyAndClose:function(){this.waitSpinner.show();this.apply();this.onOk&&this.onOk.call(this,this.dialogRecord);this.closeOnExit&&this.extDialog.hide()},setErrors:function(a){for(var b=
!1,d=0;d<a.length;d++){var c=this.getFieldId(a[d].field);if(c=Ext.getCmp(c))c.markInvalid(a[d].message),b=!0}return b},getFieldId:function(a){return this.id?this.id+"_"+a:"_"+a},onAfterLayout:function(a,b){},onBeforeShow:function(a){return!0},onShow:function(a){this.load();this.extDialog.center()},onCancel:function(){this.close()},onBeforeHide:function(){if(this.extDialog.buttons)for(var a=this.extDialog.buttons,b=0,d=a.length;b<d;b++){var c=a[b];if("cancel"==c.name&&c.disabled)return!1}return!0},
onFormValid:function(a,b){if(this.extDialog.buttons)for(var d=this.extDialog.buttons,c=0,f=d.length;c<f;c++){var e=d[c];!0===e.initialConfig.formBind&&e.disabled===b&&e.setDisabled(!b)}},getContentItems:function(a){this.augmentFieldIds(a.fieldConfigs,a.id);return a.contentItems?a.contentItems:{xtype:"fieldset",defaultType:"textfield",hideBorders:!0,border:!1,anchor:"100%",defaults:a.fieldDefaults||this.fieldDefaults,hidden:a.applyTo?!0:!1,layout:"analytics_formlayout",layoutConfig:{fieldTpl:a.fieldTemplate?
a.fieldTemplate:sfdc.analytics.framework.FieldSetLayout.FIELD_TPL,labelSeparator:""},items:a.fieldConfigs}},augmentFieldIds:function(a,b){Ext.each(a,function(a){if(a.getId&&a.setId){var c=config.id+"_"+a.getId();a.setId(c)}else a.id&&(a.id=b+"_"+a.id)})},setHelpUrl:function(a){if(this.helpUrl!==a){var b=this.extDialog.getTool("dialogHelp");b&&(b.set({onclick:a}),this.helpUrl=a)}}};
Ext.namespace("sfdc.analytics.framework");sfdc.analytics.framework.EntityDeleter=function(b,a,d){this.url=UserContext.getUrl("/_ui/analytics/reporting/ui/home/DeleterServlet");this.id=b;this.csrf=a;this.onSuccess=d};
sfdc.analytics.framework.EntityDeleter.prototype={deleteEntity:function(){var b={id:this.id};b[CSRFConstants.CSRF_TOKEN]=this.csrf;Sfdc.Ajax.post(this.url,this._handleDeleteResponse.createDelegate(this),{data:b,escape:encodeURIComponent})},_handleDeleteResponse:function(b){var a;try{a=Util.evalAjaxServletOutput(b)}catch(d){window.location.reload()}if(a.success)this.onSuccess(a);else if(a.errors){var c=[];Ext.each(a.errors,function(a){c.push(a.msg);a.relatedItems&&c.push("\x3cbr/\x3e\x3cbr/\x3e"+a.relatedItems)});
sfdc.analytics.framework.WARNING(a.errorTitle,c.join(""),!0,600)}}};
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.ErrorDialog=Ext.extend(sfdc.analytics.framework.Dialog,{constructor:function(a){var b={xtype:"displayfield",id:"serverErrorOccured",name:"serverErrorOccured",value:LC.getLabel("Exception","UnhandledException_desc")};this.initialConfig=a;a.id||(a.id="errorDlg");this.fields=[{name:"errorMessage"},{name:"gackId"},{name:"stackTrace"}];a.width=550;a.fieldConfigs=[];a.labelWidth=5;a.title=LC.getLabel("Exception","UnhandledException");a.exception?!0!==a.exception.isHandledException?
a.hideDisplayField||a.fieldConfigs.push(b):a.title=a.exception.title:a.hideDisplayField||a.fieldConfigs.push(b);a.fieldConfigs.push({xtype:"displayfield",id:"errorMessage",name:"errorMessage"});a.fieldConfigs.push({xtype:"displayfield",id:"gackId",name:"gackId"});a.debugMode&&a.fieldConfigs.push({xtype:"fieldset",title:"Stack Trace",collapsible:!0,collapsed:!0,items:[{xtype:"textarea",height:300,width:500,name:"stackTrace",value:a.stackTrace}]});a.buttons=[{id:"returnBtn",text:LC.getLabel("AnalyticsDialog",
"gotoOverviewPage"),formBind:!0,handler:function(a){a.onReturnToOverview()}.createCallback(this)}];sfdc.analytics.framework.ErrorDialog.superclass.constructor.call(this,a);this.closeOnExit=!0},load:function(){this.data={errorMessage:this.exception.errorMessage,gackId:this.exception.gackId?LC.getLabel("Exception","UnhandledException_errorid")+this.exception.gackId:"",stackTrace:this.exception.stackTrace};this.setTitle(this.exception.title?this.exception.title:LC.getLabel("Exception","UnhandledException"));
sfdc.analytics.framework.ErrorDialog.superclass.load.call(this)},onReturnToOverview:function(){}});
sfdc.analytics.framework.FilterDateField=Ext.extend(Ext.form.TriggerField,{triggerClass:"x-form-date-trigger",initComponent:function(){this.menu=sfdc.analytics.framework.DateFieldUtil.createDateMenu();this.format=UserContext.dateFormat;sfdc.analytics.framework.FilterDateField.superclass.initComponent.call(this)},onTriggerClick:function(){if(!this.disabled){this.onFocus();var a=Date.parseDate(this.getValue(),this.format);this.menu.picker.setValue(a||new Date);this.menu.show(this.el,"tl-bl?");this.menuEvents("on")}},
menuEvents:function(a){this.menu[a]("select",this.onSelect,this);this.menu[a]("hide",this.onMenuHide,this);this.menu[a]("show",this.onFocus,this)},onSelect:function(a,b){this.setValue(b.dateFormat(this.format));this.fireEvent("select",this,b);this.menu.hide()},onMenuHide:function(){this.focus(!1,60);this.menuEvents("un")}});Ext.reg("rb_filterdatefield",sfdc.analytics.framework.FilterDateField);
Ext.namespace("sfdc.analytics.framework");sfdc.analytics.framework.FilterLookupField=Ext.extend(Ext.form.TriggerField,{constructor:function(a){this.addEvents("triggerclick");sfdc.analytics.framework.FilterLookupField.superclass.constructor.call(this,a)},triggerConfig:{tag:"a",cls:"rb_lookupIcon",children:[{tag:"img",src:"/s.gif"}]},onTriggerClick:function(a){setLastMousePosition(a.browserEvent);this.fireEvent("triggerclick")}});Ext.reg("FilterLookupField",sfdc.analytics.framework.FilterLookupField);
Ext.override(Ext.form.ComboBox,{initList:function(){if(!this.list){this.list=new Ext.Layer({parentEl:this.getListParent(),shadow:this.shadow,cls:["x-combo-list",this.listClass].join(" "),constrain:!1});this.innerList=this.list.createChild({cls:"x-combo-list-inner"});this.mon(this.innerList,"mouseover",this.onViewOver,this);this.mon(this.innerList,"mousemove",this.onViewMove,this);this.pageSize&&(this.footer=this.list.createChild({cls:"x-combo-list-ft"}),this.pageTb=new Ext.PagingToolbar({store:this.store,
pageSize:this.pageSize,renderTo:this.footer}),this.assetHeight+=this.footer.getHeight());this.tpl||(this.tpl='\x3ctpl for\x3d"."\x3e\x3cdiv class\x3d"x-combo-list-item"\x3e{'+this.displayField+":htmlEncode}\x3c/div\x3e\x3c/tpl\x3e");this.view=new Ext.DataView({applyTo:this.innerList,tpl:this.tpl,singleSelect:!0,selectedClass:this.selectedClass,itemSelector:this.itemSelector||".x-combo-list-item",emptyText:this.listEmptyText});this.mon(this.view,"click",this.onViewClick,this);this.bindStore(this.store,
!0);var a;if(!Ext.isDefined(this.dontOverrideListWidth))if(Ext.isDefined(this.resizable)||"auto"===this.listWidth){if(a=this._setAutoWidth(),"auto"===this.listWidth&&this.store)this.store.on({scope:this,load:this._setAutoWidth})}else this.listWidth&&(a=this.listWidth||Math.max(this.wrap.getWidth(),this.minListWidth),this.list.setSize(a,0));this.list.swallowEvent("mousewheel");this.assetHeight=0;!1!==this.syncFont&&this.list.setStyle("font-size",this.el.getStyle("font-size"));this.title&&(this.header=
this.list.createChild({cls:"x-combo-list-hd",html:this.title}),this.assetHeight+=this.header.getHeight());this.innerList.setWidth(a-this.list.getFrameWidth("lr"));this.resizable&&(this.resizer=new Ext.Resizable(this.list,{pinned:!0,handles:"se"}),this.mon(this.resizer,"resize",function(a,c,d){this.maxHeight=d-this.handleHeight-this.list.getFrameWidth("tb")-this.assetHeight;this.listWidth=c;this.innerList.setWidth(c-this.list.getFrameWidth("lr"));this.restrictHeight()},this),this[this.pageSize?"footer":
"innerList"].setStyle("margin-bottom",this.handleHeight+"px"))}},_setAutoWidth:function(){Ext.fly(this.list.id).dom.style.width="";Ext.fly(this.innerList.id).dom.style.width="";var a=0;Ext.isIE?(this.innerList.addClass("list-auto-width-IE"),a=this.list.getBox(),this.innerList.removeClass("list-auto-width-IE")):a=this.list.getBox();a=Math.max(this.wrap.getWidth(),a.width)+(this.list.getHeight()>this.maxHeight?15:0);this.list.setSize(a,0);this.innerList.setWidth(a);return a},beforeBlur:function(){var a=
this.getRawValue(),b;this.valueField&&Ext.isDefined(this.value)&&(b=this.findRecord(this.valueField,this.value));if(!b||b.get(this.displayField)!=a)b=this.findRecord(this.displayField,a);if(!b&&this.forceSelection)0<a.length&&a!=this.emptyText?(this.el.dom.value=Ext.value(this.lastSelectionText,""),this.applyEmptyText()):this.clearValue();else{if(b&&this.valueField&&(a=b.get(this.valueField),this.value==a))return;this.setValue(a)}},onKeyUp:function(a){var b=a.getKey();if(!1!==this.editable&&!0!==
this.readOnly&&(b==a.BACKSPACE||b==a.DELETE||!a.isSpecialKey()))this.lastKey=b,this.dqTask.delay(this.queryDelay);Ext.form.ComboBox.superclass.onKeyUp.call(this,a)}});
Ext.override(Ext.form.Field,{markInvalid:function(a){a=LC.getLabel("AnalyticsDialog","error",a);if(this.rendered&&!this.preventMark){a=a||this.invalidText;var b=this.getMessageHandler();if(b)b.mark(this,a);else if(this.msgTarget&&(this.el.addClass(this.invalidClass),b=Ext.getDom(this.msgTarget)))b.innerHTML=a,b.style.display=this.msgDisplay;this.activeError=a;this.fireEvent("invalid",this,a)}}});
Ext.override(Ext.form.NumberField,{processValue:function(a){return Ext.form.NumberField.superclass.processValue.call(this,Ext.util.Format.htmlEncode(a))}});Ext.override(Ext.form.DateField,{onMenuHide:function(){this.focus();this.focus(!1,60);this.menuEvents("un")}});
Ext.override(Ext.menu.DateMenu,{initComponent:function(){this.on("beforeshow",this.onBeforeShow,this);if(this.strict=Ext.isIE7&&Ext.isStrict)this.on("show",this.onShow,this,{single:!0,delay:20});Ext.apply(this,{plain:!0,showSeparator:!1,items:this.picker=new Ext.DatePicker(Ext.apply({internalRender:this.strict||!Ext.isIE,ctCls:"x-menu-date-item"},this.initialConfig))});this.picker.purgeListeners();this.relayEvents(this.picker,["select"]);this.on("show",this.picker.focus,this.picker);Ext.menu.DateMenu.superclass.initComponent.call(this)}});
Ext.override(Ext.Component,{onShow:function(){this.getVisibilityEl().removeClass("x-hide-"+this.hideMode);Ext.isWebKit&&this.getVisibilityEl().show()}});
Ext.override(Ext.Element,{setOpacity:function(a,b){var c=this.dom.style;if(!b||!this.anim){var d="undefined"!=typeof document.createElement("div").style.opacity;if(Ext.isIE&&!d){var d=1>a?"alpha(opacity\x3d"+100*a+")":"",e=c.filter.replace(/alpha\(opacity=(.*)\)/i,"").replace(/^\s+|\s+$/g,"");c.zoom=1;c.filter=e+(0<e.length?" ":"")+d}else c.opacity=a}else this.anim({opacity:{to:a}},this.preanim(arguments,1),null,0.35,"easeIn");return this}});
Ext.dd.DragDropMgr.getLocation=function(a){if(!this.isTypeOfDD(a))return null;var b=a.getEl(),c,d,e;try{c=Ext.lib.Dom.getXY(b)}catch(f){}if(!c)return null;d=c[0];e=d+b.offsetWidth;c=c[1];return new Ext.lib.Region(c-a.padding[0],e+a.padding[1],c+b.offsetHeight+a.padding[2],d-a.padding[3])};
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.LinkButton=Ext.extend(Ext.Button,{template:(new Ext.Template('\x3ctable cellspacing\x3d"0" class\x3d"x-btn {3}"\x3e\x3ctbody class\x3d"{4}"\x3e','\x3ctr\x3e\x3ctd class\x3d"x-btn-tl"\x3e\x3ci\x3e\x26amp;#160;\x3c/i\x3e\x3c/td\x3e\x3ctd class\x3d"x-btn-tc"\x3e\x3c/td\x3e\x3ctd class\x3d"x-btn-tr"\x3e\x3ci\x3e\x26amp;#160;\x3c/i\x3e\x3c/td\x3e\x3c/tr\x3e','\x3ctr\x3e\x3ctd class\x3d"x-btn-ml"\x3e\x3ci\x3e\x26amp;#160;\x3c/i\x3e\x3c/td\x3e\x3ctd class\x3d"x-btn-mc"\x3e\x3cem class\x3d"{5}" unselectable\x3d"on"\x3e\x3ca href\x3d"#" class\x3d"x-btn-text {2}"\x3e\x3cbutton\x3e{0}\x3c/button\x3e\x3c/a\x3e\x3c/em\x3e\x3c/td\x3e\x3ctd class\x3d"x-btn-mr"\x3e\x3ci\x3e\x26amp;#160;\x3c/i\x3e\x3c/td\x3e\x3c/tr\x3e','\x3ctr\x3e\x3ctd class\x3d"x-btn-bl"\x3e\x3ci\x3e\x26amp;#160;\x3c/i\x3e\x3c/td\x3e\x3ctd class\x3d"x-btn-bc"\x3e\x3c/td\x3e\x3ctd class\x3d"x-btn-br"\x3e\x3ci\x3e\x26amp;#160;\x3c/i\x3e\x3c/td\x3e\x3c/tr\x3e',
"\x3c/tbody\x3e\x3c/table\x3e")).compile(),buttonSelector:"a:first",getTemplateArgs:function(){return Ext.Button.prototype.getTemplateArgs.apply(this).concat([this.href,this.target])},onClick:function(a){0===a.button&&!this.disabled&&(this.fireEvent("click",this,a),this.handler&&this.handler.call(this.scope||this,this,a))}});
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.LookupField=Ext.extend(Ext.form.ComboBox,{lookupWidth:670,enableKeyEvents:!0,initComponent:function(){this.loadingText=LC.getLabel("Global","loading");this.store=new Ext.data.Store({proxy:new Ext.data.HttpProxy({url:this.servletUrl}),reader:new Ext.data.JsonReader({root:"results",totalProperty:"count"},[{name:"value",mapping:"value"},{name:"display",mapping:"display"},{name:"disabled",mapping:"disabled",type:"boolean"}])});sfdc.analytics.framework.LookupField.superclass.initComponent.call(this)},initEvents:function(){sfdc.analytics.framework.LookupField.superclass.initEvents.call(this);
this.keyNav.down=function(a){this.isExpanded()&&(this.inKeyMode=!0,this.selectNext())}},queryParam:"searchParam",tpl:'\x3ctpl for\x3d"."\x3e\x3cdiv class\x3d"\x3ctpl if\x3d"disabled\x3d\x3dfalse"\x3ex-combo-list-item\x3c/tpl\x3e"\x3e{[escapeHTML(values.display)]}\x3c/div\x3e\x3c/tpl\x3e',displayField:"display",valueField:"value",onSelect:function(a,b){var c=a.data;this.setValue({value:c[this.valueField],display:c[this.displayField]});this.collapse();this.fireEvent("select",this,a,b)},triggerConfig:{tag:"a",
children:[{tag:"img",src:"/s.gif",cls:"lookupIcon",style:"vertical-align:middle;"}]},initTrigger:function(){this.mon(this.trigger,"click",this.onTriggerClick,this,{preventDefault:!0});this.trigger.first().addClassOnOver("lookupIconOn")},onRender:function(a,b){sfdc.analytics.framework.LookupField.superclass.onRender.call(this,a,b);this.idField=this.el.insertSibling({tag:"input",type:"hidden",name:this.name+"_lkid",id:this.name+"_lkid",value:this.idValue},"before",!0);this.el.insertSibling({tag:"input",
type:"hidden",name:this.name+"_lkold",id:this.name+"_lkold"},"before",!0).value=this.value.display},onTriggerClick:function(a){var b=Ext.isDefined(this.additionalParams)?this.additionalParams:"",b=UrlMap.convertClassNameToUrl("common.data.LookupPage","?lknm\x3d"+this.name+"\x26lktp\x3d"+this.lookupType+b),c="\x26lksrch\x3d"+encodeURIComponent(getElementByIdCS(encodeURIComponent(this.id)).value).substring(0,80);setLastMousePosition(a.browserEvent);openLookup(b,this.lookupWidth,1,c)},setValue:function(a){this.value=
a;this.rendered&&(this.el.dom.value=Ext.isEmpty(a)?"":a.display,this.idField.value=Ext.isEmpty(a)?"":a.value,this.validate(),this.originalValue=a);return this},getValue:function(){if(!this.rendered)return this.value;var a=this.el.getValue();if(a===this.emptyText||void 0===a)a={display:"",value:""};return{display:a,value:this.idField.value}},postBlur:function(){if(this.validateOnBlur){var a=this.store;1==a.getCount()&&(a=a.getAt(0),a.data.disabled&&this.markInvalid(a.data.display))}},validate:function(){if(!this.el.getValue())return this.markInvalid(this.blankText),
!1;var a=this.store;if(1==a.getCount()&&a.getAt(0).data.disabled)return!1;a=this.getValue();if(a.display&&!a.value)return!1;this.clearInvalid();return!0},isValid:function(){return this.validate()},beforeBlur:Ext.emptyFn,listeners:{keypress:function(a,b){if(b.getKey()==b.BACKSPACE||!b.isSpecialKey())a.idField.value=""}},isDirty:function(){if(this.disabled||!this.rendered)return!1;var a=this.getValue();return a.value!==this.originalValue.value||a.display&&!a.value}});Ext.reg("lookupfield",sfdc.analytics.framework.LookupField);
Ext.namespace("sfdc.analytics.framework");sfdc.analytics.framework.CONFIRM=function(a,b,c,d,e){Ext.Msg.show({title:a,cls:"confirm_dialog",msg:b,buttons:{yes:LC.getLabel("Buttons","yes"),no:LC.getLabel("Buttons","no")},fn:function(a){"yes"==a?d():"no"==a&&Ext.isDefined(e)&&e()},modal:c,width:330});return this};sfdc.analytics.framework.WARNING=function(a,b,c,d){Ext.Msg.show({title:a,cls:"warning_dialog",msg:b,buttons:{yes:LC.getLabel("Buttons","ok")},modal:c,width:d||330});return this};
sfdc.analytics.framework.SAVE_AND_CLOSE=function(a,b,c,d){return Ext.Msg.show({title:a,cls:"save_and_close_dialog",msg:b,buttons:{yes:LC.getLabel("Buttons","save_and_close"),no:LC.getLabel("Buttons","close"),cancel:LC.getLabel("Buttons","cancel")},fn:function(a){"yes"==a?c():"no"==a&&d()},modal:!0,width:600})};
Ext.ux.NumericField=function(a){Ext.ux.NumericField.superclass.constructor.call(this,Ext.apply({style:"text-align:right;"},a));this.useThousandSeparator&&","==this.decimalSeparator&&Ext.isEmpty(a.thousandSeparator)?this.thousandSeparator=".":this.allowDecimals&&("."==this.thousandSeparator&&Ext.isEmpty(a.decimalSeparator))&&(this.decimalSeparator=",");this.onFocus=Ext.ux.NumericField.superclass.onFocus.createSequence(this.onFocus)};
Ext.extend(Ext.ux.NumericField,Ext.form.NumberField,{currencySymbol:null,useThousandSeparator:!0,thousandSeparator:",",alwaysDisplayDecimals:!1,setValue:function(a){Ext.ux.NumericField.superclass.setValue.call(this,a);this.setRawValue(this.getFormattedValue(this.getValue()))},getFormattedValue:function(a){if(Ext.isEmpty(a)||!this.hasFormat())return a;var c=null;a=(c=0>a)?-1*a:a;a=this.allowDecimals&&this.alwaysDisplayDecimals?a.toFixed(this.decimalPrecision):a;if(this.useThousandSeparator){if(this.useThousandSeparator&&
Ext.isEmpty(this.thousandSeparator))throw"NumberFormatException: invalid thousandSeparator, property must has a valid character.";if(this.thousandSeparator==this.decimalSeparator)throw"NumberFormatException: invalid thousandSeparator, thousand separator must be different from decimalSeparator.";a=String(a);a=a.split(".");a[1]=a[1]?a[1]:null;for(var b=a[0],d=/(\d+)(\d{3})/,e=this.thousandSeparator;d.test(b);)b=b.replace(d,"$1"+e+"$2");a=b+(a[1]?this.decimalSeparator+a[1]:"")}return String.format("{0}{1}{2}",
c?"-":"",Ext.isEmpty(this.currencySymbol)?"":this.currencySymbol+" ",a)},parseValue:function(a){return Ext.ux.NumericField.superclass.parseValue.call(this,this.removeFormat(a))},removeFormat:function(a){!Ext.isEmpty(a)&&this.hasFormat()&&(a=a.replace(this.currencySymbol+" ",""),a=this.useThousandSeparator?a.replace(RegExp("["+this.thousandSeparator+"]","g"),""):a);return a},getErrors:function(a){return Ext.ux.NumericField.superclass.getErrors.call(this,this.removeFormat(a))},hasFormat:function(){return"."!==
this.decimalSeparator||!0===this.useThousandSeparator||!Ext.isEmpty(this.currencySymbol)||this.alwaysDisplayDecimals},onFocus:function(){this.setRawValue(this.removeFormat(this.getRawValue()))}});Ext.reg("numericfield",Ext.ux.NumericField);
Ext.namespace("sfdc.analytics.framework");sfdc.analytics.framework.SaveButtonGroup=Ext.extend(Ext.ButtonGroup,{id:"saveButtonGroup",frame:!1,bubbleEvents:["enable"],onSaveComplete:function(){this.cascade(function(){this.enable()})}});
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.SaveDialogFieldConfigHelper={NAME_FIELD_NAME:"NAME_FIELD_NAME",NAME_FIELD_ID:"NAME_FIELD_ID",DEVELOPER_NAME_FIELD_NAME:"DEVELOPER_NAME_FIELD_NAME",DEVELOPER_NAME_FIELD_ID:"DEVELOPER_NAME_FIELD_ID",NAMESPACE_FIELD_NAME:"NAMESPACE_FIELD_NAME",INSTALLED_BY_FIELD_NAME:"INSTALLED_BY_FIELD_NAME",createGenericErrorConfig:function(){return{id:"genericError",xtype:"label",hidden:!0,cls:"errorMsg"}},createNameConfig:function(a){return{id:sfdc.analytics.framework.SaveDialogFieldConfigHelper.NAME_FIELD_ID,xtype:"rb_textfield",
fieldLabel:a,name:sfdc.analytics.framework.SaveDialogFieldConfigHelper.NAME_FIELD_NAME,allowBlank:!1,validateOnBlur:!1,msgTarget:"under",vtype:"nameNonWhiteSpace",maxLength:80,blankText:LC.getLabel("AnalyticsDialog","requiredError"),itemCls:"rb_required"}},createDeveloperNameConfig:function(a,b){return{id:sfdc.analytics.framework.SaveDialogFieldConfigHelper.DEVELOPER_NAME_FIELD_ID,xtype:"rb_textfield",fieldLabel:a,name:sfdc.analytics.framework.SaveDialogFieldConfigHelper.DEVELOPER_NAME_FIELD_NAME,
allowBlank:!1,validateOnBlur:!1,msgTarget:"under",vtype:"devUniqueName",maxLength:80,blankText:LC.getLabel("AnalyticsDialog","requiredError"),infoIcon:!0,infoText:LC.getLabel("DeveloperNameInputElement","mouseOverHelpText",a),itemCls:"rb_required",readOnly:!1===b,disabled:!1===b}},createNamespaceConfig:function(){return{xtype:"displayfield",name:sfdc.analytics.framework.SaveDialogFieldConfigHelper.NAMESPACE_FIELD_NAME,fieldLabel:LC.getLabel("Global_Entity","namespacePrefix")}},createInstalledByLinkConfig:function(){return{xtype:"displayfield",
name:sfdc.analytics.framework.SaveDialogFieldConfigHelper.INSTALLED_BY_FIELD_NAME,fieldLabel:LC.getLabel("Global_Entity","InstalledBy")}},createFolderPanelConfig:function(){return{xtype:"panel",html:"\x3cb\x3e"+LC.getLabel("udd_Dashboard","Folder")+"\x3c/b\x3e\x3cbr/\x3e"+LC.getLabel("PropertiesDialog","folderSecurity"),width:"auto",border:!1}},createFolderListConfig:function(a,b,c){return{id:"folderId",xtype:"rb_dropdown",fieldLabel:a,name:"folderId",msgTarget:"under",listValues:b,value:c}}};
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.SubComponentSelector=Ext.extend(sfdc.analytics.framework.DataView,{constructor:function(a){a||(a={});this.addEvents("componentSelected");this.items=a.items;var d=new Ext.data.JsonStore({fields:["id","ctype","label","iconURL","paletteURL"],data:this.items});a=Ext.apply(a,{id:"chart_subsel",store:d,tpl:sfdc.analytics.framework.SubComponentSelector.ITEM_TEMPLATE,autoHeight:!0,singleSelect:!0,itemSelector:".componentTypeSelectorItem",overClass:"componentTypeSelectorItemOver",
selectedClass:"componentTypeSelectorItemSel",listeners:{containerclick:function(a,c,b){return!1},selectionchange:function(a,c){var b=c[0].id,b=b.substring(b.indexOf("~")+1);this.fireEvent("componentSelected",b)}}});sfdc.analytics.framework.SubComponentSelector.superclass.constructor.call(this,a)},selectComponentType:function(a){this.select("subComponentSelector~"+a,!1,!1)},disable:function(){sfdc.analytics.framework.DataView.superclass.disable.call(this);var a=this.el.mask();a.setStyle({opacity:"0",
filter:"alpha(opacity\x3d0)"});(Ext.isIE6||Ext.isIE7)&&a.setWidth(0)}});Ext.reg("subComponentSelector",sfdc.analytics.framework.SubComponentSelector);sfdc.analytics.framework.SubComponentSelector.ITEM_TEMPLATE=new Ext.XTemplate('\x3ctpl for\x3d"."\x3e','\x3cimg src\x3d"{iconURL}" id\x3d"subComponentSelector~{id}" class\x3d"componentTypeSelectorItem" title\x3d"{label}"/\x3e',"\x3c/tpl\x3e",{compiled:!0});
Ext.namespace("sfdc.analytics.framework.TestContext");sfdc.analytics.framework.TestContext={init:function(b){this.isRunningTests=b},getTestValue:function(b){if(this.isRunningTests){var a=new XMLHttpRequest;a.open("GET",UserContext.getUrl("/qa/analytics/testContext.apexp?key\x3d"+b),!1);for(a.send(null);200!=a.status;);return a.responseText}}};
Ext.namespace("sfdc.analytics.framework");sfdc.analytics.framework.Toolbar=Ext.extend(Ext.Toolbar,{id:"mainToolbar",enableOverflow:!1,cls:"mainToolBar"});
Ext.namespace("sfdc.analytics.framework");sfdc.analytics.framework.BaseButton=Ext.extend(Ext.Button,{constructor:function(a){this.disabled=a?a.isDisabled:!1;sfdc.analytics.framework.BaseButton.superclass.constructor.call(this,a)}});sfdc.analytics.framework.SaveButton=Ext.extend(sfdc.analytics.framework.BaseButton,{constructor:function(a){this.text=LC.getLabel("Toolbar","save");sfdc.analytics.framework.SaveButton.superclass.constructor.call(this,a)},id:"saveBtn"});
sfdc.analytics.framework.SaveAsButton=Ext.extend(sfdc.analytics.framework.BaseButton,{constructor:function(a){this.text=LC.getLabel("Toolbar","saveAs");sfdc.analytics.framework.SaveAsButton.superclass.constructor.call(this,a)},id:"saveAsBtn"});
sfdc.analytics.framework.PropertiesButton=Ext.extend(sfdc.analytics.framework.BaseButton,{constructor:function(a){this.text=LC.getLabel("Toolbar","properties",a.entityName);sfdc.analytics.framework.PropertiesButton.superclass.constructor.call(this,a)},id:"propertiesBtn",cls:"x-btn-text-icon",iconCls:"properties-btn-icon"});
sfdc.analytics.framework.AddFilterButton=Ext.extend(sfdc.analytics.framework.BaseButton,{constructor:function(a){this.text=LC.getLabel("FilterBar","addFilterButton");sfdc.analytics.framework.AddFilterButton.superclass.constructor.call(this,a)},id:"addFilterButton"});
sfdc.analytics.framework.RunButton=Ext.extend(sfdc.analytics.framework.BaseButton,{constructor:function(a){this.text=LC.getLabel("Toolbar","run",a.entityName);sfdc.analytics.framework.RunButton.superclass.constructor.call(this,a)},cls:"x-btn-text-icon",iconCls:"run-report-btn-icon",id:"runBtn",overCls:"runReportBtn-hover"});
sfdc.analytics.framework.CloseButton=Ext.extend(sfdc.analytics.framework.BaseButton,{constructor:function(a){this.text=LC.getLabel("Toolbar","close");sfdc.analytics.framework.CloseButton.superclass.constructor.call(this,a)},id:"closeBtn"});
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.initTreeSearchQuickfindInput=function(){sfdc.analytics.framework.TreeSearchQuickfindInput=Ext.extend(Sfdc.html.QuickfindInput,{constructor:function(a){a.searchFunction=this._delayedSearchFunction;a.clearFunction=this.clearSearchFilter;this._delayedSearchTask=new Ext.util.DelayedTask(this._performSearch,this);this._filterQuery=this._pendingQuery="";this._maxNodesAtLevel=a.maxNodesAtLevel;this._showMoreIncrement=a.showMoreIncrement||20;Ext.isNumber(this._maxNodesAtLevel)&&a.treeRoot.addListener("load",
this.clearSearchFilter,this);this._noMatchNode=new Ext.tree.TreeNode({text:LC.getLabel("analyticsHome","treeSearchNoMatch",a.pluralItemsText),leaf:!0,disabled:!0,cls:"noMatchNode"});sfdc.analytics.framework.TreeSearchQuickfindInput.superclass.constructor.call(this,a)},_delayedSearchFunction:function(a){this._pendingQuery=a.trim();this._delayedSearchTask.delay(200)},_performSearch:function(){if(this._pendingQuery!==this._filterQuery)if(""===this._pendingQuery)this.clearSearchFilter();else{this.clearNoMatch();
this._filterQuery=this._pendingQuery;var a=this._buildSearchRegex(this._pendingQuery);if(!this.filterByFunc(this.filterNode.createDelegate(this,[a],!0)))this.onNoMatch()}},onNoMatch:function(){this.treeRoot.contains(this._noMatchNode)||this.treeRoot.appendChild(this._noMatchNode);this._noMatchNode.getUI().show()},clearNoMatch:function(){this._noMatchNode.getUI().hide()},_buildSearchRegex:function(a){a=Ext.escapeRe(a.trim());return RegExp(a,"i")},filterNode:function(a,b){return a!=this._noMatchNode&&
-1!==a.attributes.text.search(b)},filterByFunc:function(a,b){b=b||this.treeRoot;var c=!1;if(b.isLeaf())return c=a.apply(a,[b]),this.setNodeVisibility(b,c),c;var k=0,h,f=0,d=this._maxNodesAtLevel,g;b.eachChild(function(b){b.isLeaf()||b.expand();Ext.isNumber(d)&&f<this._maxNodesAtLevel?((b=this.filterByFunc(a,b))&&f++,c=c||b):b.attributes.isMoreElementNode?h=b:(g=Ext.value(g,k),this.setNodeVisibility(b,!1));k++},this);Ext.isDefined(h)&&b.removeChild(h);if(Ext.isNumber(d)&&f===d){var e=this.showMore.createDelegate(this),
e=new Ext.tree.TreeNode({text:LC.getLabel("ReportBuilder","seeMoreResults"),isMoreElementNode:!0,fn:a,moreNodeIndex:g,leaf:!0,cls:"moreItemsNode",iconCls:"moreInfoIcon",listeners:{click:e}});b.appendChild(e);this.setNodeVisibility(e,!0)}b.isRoot||this.setNodeVisibility(b,c);return c},setNodeVisibility:function(a,b){b?a.getUI().show():a.getUI().hide()},clearSearchFilter:function(){this.clearNoMatch();this._delayedSearchTask.cancel();this._filterQuery="";this.filterByFunc(function(a){return a!=this._noMatchNode}.createDelegate(this));
this.treeRoot.collapse(!0,!1)},showMore:function(a){for(var b=a.parentNode.childNodes,c=b.length,k=a.attributes.moreNodeIndex,h=a.attributes.fn,f=this._showMoreIncrement,d=0,g,e=k;e<c;e++)if(g=b[e],h.apply(h,[g]))if(d<f)g.getUI().show(),d++;else{d++;break}d<=f?a.remove():a.attributes.moreNodeIndex=k+f;return!1}})};
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.ValidationGroup=Ext.extend(Object,{constructor:function(a){sfdc.analytics.framework.ValidationGroup.superclass.constructor.call(this);this.items=[];this.enabledFn=a},add:function(a,d,b){this.items.push({fieldId:a,isValidFn:d,errorMessage:b});return this.validate.createDelegate(this,[a],!0)},validate:function(a,d){if(this.enabledFn&&!this.enabledFn())return!0;var b=null;Ext.each(this.items,function(a){var e=Ext.getCmp(a.fieldId),c=e.getValue();(c=!a.isValidFn(c)?a.errorMessage:
null)&&(a.fieldId==d?b=c:e.markInvalid(c))});return b?b:!0}});
Ext.namespace("sfdc.analytics.framework.validators");
sfdc.analytics.framework.validators.initSaveDialogValidators=function(d){Ext.apply(Ext.form.VTypes,{devUniqueName:function(a,c){var b=RegExp("[_]{2}| |_$|^_|\\W|^\\d","gi"),d=RegExp("[A-Z|a-z|0-9|_]","gi").test(a),b=b.test(a);return d&&!b},devUniqueNameText:LC.getLabel("Global_Entity","InvalidDeveloperNameOnEntity",d)});Ext.apply(Ext.form.VTypes,{nameNonWhiteSpace:function(a,c){return""!==a.trim()},nameNonWhiteSpaceText:LC.getLabel("AnalyticsDialog","requiredFieldError"),positiveint:function(a,c){return RegExp("^[1-9][0-9]*$",
"gi").test(a)},positiveintText:LC.getLabel("AnalyticsDialog","positiveIntError"),positiveintbounded:function(a,c){return RegExp("^[1-9][0-9]?$","gi").test(a)&&0!==a.trim().length},positiveintboundedText:LC.getLabel("AnalyticsDialog","positiveIntBoundedError"),url:function(a,c){var b=RegExp("[-_,!.~:;$(){}|^#+%\x3d*?\\\\/@\x26\\[\\]\\p{L}\\p{N}]+","gi");return RegExp("^([Hh][Tt][Tt][Pp][Ss]?|[Ff][Tt][Pp])://([-_,\\w\\d!.~:;$(){}|^#+\x3d*%?\\\\/@\x26\\[\\]])+","gi").test(a)||b.test(a)},urlText:LC.getLabel("Edit",
"InvalidUrl")})};
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.Viewport=Ext.extend(Ext.Viewport,{initComponent:function(){var a=[];this.globalHeaderId&&a.push({contentEl:Ext.get(this.globalHeaderId),bodyStyle:"overflow: visible",bwrapStyle:"overflow: visible",style:{zIndex:2,position:"relative"}});a.push({contentEl:Ext.get(this.miniHeaderId||"AppBodyHeader"),bodyStyle:"overflow: visible",bwrapStyle:"overflow: visible",style:{zIndex:1,position:"relative"}});this.sectionHeaderId&&a.push({contentEl:Ext.get(this.sectionHeaderId)});this.items=
[{xtype:"container",region:"north",autoHeight:!0,style:{zIndex:1},items:new Ext.Panel({items:a,bodyStyle:"overflow: visible",bwrapStyle:"overflow: visible"})},{xtype:"container",layout:"border",region:"center",style:{zIndex:0},items:this.items}];sfdc.analytics.framework.Viewport.superclass.initComponent.call(this)}});
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.WarningDialog=Ext.extend(sfdc.analytics.framework.Dialog,{TITLE:"title",MESSAGE:"message",STACK_TRACE:"stackTrace",constructor:function(a){this.warnings=[];LC.getLabel("Exception","UnhandledException_desc");this.initialConfig=a;a.id||(a.id="warningDlg");this.fields=[{name:this.MESSAGE},{name:this.STACK_TRACE}];a.width=550;a.fieldConfigs=[];a.labelWidth=5;a.title=a.warning?a.warning.title:LC.getLabel("Exception","UnhandledException");a.fieldConfigs.push({xtype:"displayfield",
id:this.MESSAGE,name:this.MESSAGE});a.debugMode&&a.fieldConfigs.push({xtype:"fieldset",title:"Stack Trace",collapsible:!0,collapsed:!0,items:[{xtype:"textarea",height:300,width:500,name:this.STACK_TRACE,value:a.stackTrace}]});a.hideCancel=!0;a.buttons=[{id:"okBtn",text:LC.getLabel("ReportBuilder","okButton"),formBind:!0,handler:function(a){a.onOk()}.createCallback(this)}];sfdc.analytics.framework.WarningDialog.superclass.constructor.call(this,a);this.closeOnExit=!0},load:function(){var a=this.warnings.shift();
this.data={};this.data[this.TITLE]=a.title;this.data[this.MESSAGE]=a.message;this.data[this.STACK_TRACE]=a.stackTrace;a.title&&this.setTitle(a.title);sfdc.analytics.framework.WarningDialog.superclass.load.call(this)},addWarning:function(a){a&&this.warnings.push(a)},addWarnings:function(a){if(a)for(var b=0;b<a.length;b++)this.addWarning(a[b])},onOk:function(){0<this.warnings.length?(this.close(),this.showDialog()):this.close()}});
window.Ext&&(window.Ext.form&&window.Ext.form.TriggerField)&&(Ext.ns("Sfdc.html"),Sfdc.html.QuickfindInput=Ext.extend(Ext.form.TriggerField,{cls:"quickfindInput",ctCls:"quickfindContainer",enableKeyEvents:!0,hideTrigger:!0,buffer:!1,initComponent:function(){var b=this.scope||this;this.on("keyup",function(a){a=a.getRawValue();0<a.length?this.trigger.show():this.trigger.hide();this.searchFunction&&this.searchFunction.call(b,a)},this,this.buffer?{buffer:this.buffer}:null);Sfdc.html.QuickfindInput.superclass.initComponent.call(this)},
onTriggerClick:function(){this.trigger.hide();this.reset();this.focus();this.clearFunction&&this.clearFunction.call(this.scope||this)}}));
Ext.namespace("sfdc.analytics.framework");sfdc.analytics.framework.TextField=Ext.extend(Ext.form.TextField,{constructor:function(a){a.autoCreate={tag:"input",type:"text",maxlength:a.maxLength,autocomplete:"off"};sfdc.analytics.framework.TextField.superclass.constructor.call(this,a);a.infoIcon&&(this.infoIcon=a.infoIcon,this.infoText=a.infoText,this.on({afterrender:function(a){this.toolTip||(this.toolTip=new Ext.ToolTip({target:a.id+"Info",html:this.infoText}))}}))}});Ext.reg("rb_textfield",sfdc.analytics.framework.TextField);
sfdc.analytics.framework.ToolTip=Ext.extend(Ext.BoxComponent,{constructor:function(a){a.autoEl={tag:"img",cls:"infoIcon",src:"/s.gif"};sfdc.analytics.framework.ToolTip.superclass.constructor.call(this,a);this.on("afterrender",function(a){this.toolTip||(this.toolTip=new Ext.ToolTip({target:a.id,html:this.text}))},this)}});Ext.reg("rb_ToolTip",sfdc.analytics.framework.ToolTip);
sfdc.analytics.framework.SimpleDropDown=Ext.extend(Ext.form.ComboBox,{constructor:function(a){var b=Ext.apply({},a),c=a.dataStore?a.dataStore:new Ext.data.ArrayStore({fields:a.fields?a.fields:["value","display"],data:a.listValues});if(0<c.getCount())if(a.value&&null!==a.value||0===a.value)0>c.find("value",a.value)&&(b.value=c.getAt(0).get("value"));else if(null===a.value||void 0===a.value)b.value=c.getAt(0).get("value");b.mode="local";b.listWidth="auto";b.disableKeyFilter=!0;b.editable=Ext.isDefined(a.editable)?
a.editable:!1;b.triggerAction="all";b.selectOnFocus=b.editable?!0:!1;b.store=c;b.valueField="value";b.displayField="display";b.hiddenName=a.name;b.forceSelection=!1;b.tpl=Ext.value(a.tpl,'\x3ctpl for\x3d"."\x3e\x3cdiv class\x3d"x-combo-list-item"\x3e{[escapeHTML(values.'+b.displayField+")]}\x3c/div\x3e\x3c/tpl\x3e");sfdc.analytics.framework.SimpleDropDown.superclass.constructor.call(this,b);a.infoIcon&&(this.infoIcon=a.infoIcon,this.infoText=a.infoText,this.on({afterrender:function(a){this.toolTip||
(this.toolTip=new Ext.ToolTip({target:a.id+"Info",html:this.infoText}))}}))},setFieldLabel:function(a){this.rendered&&this.el.up(".x-form-item",10,!0).child(".x-form-item-label").update(a);this.fieldLabel=a},setVisible:function(a){sfdc.analytics.framework.SimpleDropDown.superclass.setVisible.call(this,a);if(this.fieldLabel&&0<this.fieldLabel.length){var b=this.el.up(".x-form-item",10,!0).child(".x-form-item-label");b&&(b.dom.style.display=a?"block":"none")}},setValue:function(a){var b=a;this.valueField&&
(this.getStore().clearFilter(),(b=this.findRecord(this.valueField,a))?b=b.data[this.displayField]:Ext.isDefined(this.valueNotFoundText)?b=this.valueNotFoundText:(b=this.store.getAt(0),a=b.get("value"),b=b.data[this.displayField]));this.lastSelectionText=b;this.hiddenField&&(this.hiddenField.value=Ext.value(a,""));Ext.form.ComboBox.superclass.setValue.call(this,b);this.value=a;return this},onLoad:function(){"auto"===this.listWidth&&this._setAutoWidth();sfdc.analytics.framework.SimpleDropDown.superclass.onLoad.apply(this);
if(0===this.store.getCount()&&"auto"===this.listWidth)Ext.isIE6||(this.list.setWidth("auto"),this.innerList.setWidth("auto"));else{var a=this.findRecord(this.displayField,this.getRawValue());a&&this.selectByValue(a.get(this.valueField))}}});Ext.reg("rb_dropdown",sfdc.analytics.framework.SimpleDropDown);
sfdc.analytics.framework.LimitedMixedCollection=Ext.extend(Ext.util.MixedCollection,{constructor:function(a){this.limitCount=a.limitCount;this.limitMsg=a.limitMsg||LC.getLabel("AnalyticsFinder","searchForMore");this.callback=a.searchLimitCallback;this.callbackTarget=a.target;sfdc.analytics.framework.LimitedMixedCollection.superclass.constructor.call(this,a)},filterBy:function(a,b){var c=new Ext.util.MixedCollection;c.getKey=this.getKey;for(var e=this.keys,f=this.items,d=0,g=f.length;d<g;d++){if(c.getCount()>=
this.limitCount){c.insert(c.getCount(),this.getMessageItem());break}a.call(b||this,f[d],e[d])&&c.add(e[d],f[d])}return c},getRange:function(a,b){a=a||0;b=b||this.getCount();var c=!1;b-a>this.limitCount&&(b=a+this.limitCount-1,c=!0);var e=sfdc.analytics.framework.LimitedMixedCollection.superclass.getRange.call(this,a,b);c&&e.push(this.getMessageItem());return e},getMessageItem:function(){return{data:{display:this.limitMsg,value:"errMsg"},id:"limitItem"}}});
sfdc.analytics.framework.LimitedArrayStore=Ext.extend(Ext.data.ArrayStore,{constructor:function(a){var b=a.data;sfdc.analytics.framework.LimitedArrayStore.superclass.constructor.call(this,a);this.data=new sfdc.analytics.framework.LimitedMixedCollection(a);this.loadData(b);this.init=!0},clearData:function(){this.init&&sfdc.analytics.framework.LimitedArrayStore.superclass.clearData.call(this)}});
sfdc.analytics.framework.FinderDropDown=Ext.extend(sfdc.analytics.framework.SimpleDropDown,{constructor:function(a){var b=function(a){var b=a.combo.getStore(),c=a.query.trim();Ext.isEmpty(c)&&b.clearFilter();a.query=c;b.filterOrig||(b.filterOrig=b.filter,b.filter=function(){b.filterCount=0;if(2===arguments.length){var a=Array.prototype.slice.call(arguments,0);a.push(!0);b.filterOrig.apply(b,a)}else b.filterOrig.call(b,arguments)})},c=function(){};if(a.validateEmpty){this.doQuery=this.doQuery.createSequence(function(){0===
this.dataStore.data.length?(this.markInvalid(LC.getLabel("AnalyticsDialog","requiredError")),this.noMatchingResults=!0):this.noMatchingResults=!1},this);var c=function(a){this.clearInvalid();this.noMatchingResults=!1},e=this.validateValue;this.validateValue=function(a){return!0!==this.noMatchingResults&&e.call(this,a)}}var f=this,d=function(b,c,d){d===a.limitCount&&(f.clearValue(),f.focus(!0))};Ext.apply(a,{editable:!0,typeAhead:!1,forceSelection:!0,allowBlank:!1,blankText:LC.getLabel("AnalyticsDialog",
"requiredError"),selectOnFocus:!0,emptyText:LC.getLabel("AnalyticsFinder","finderGhostText"),listEmptyText:'\x3cdiv class\x3d"x-combo-list-item x-combo-selected"\x3e'+(a.listEmptyText?a.listEmptyText:LC.getLabel("AnalyticsFinder","finderListEmptyText"))+"\x3c/div\x3e"});a.dataStore=a.limitCount?new sfdc.analytics.framework.LimitedArrayStore({fields:a.fields?a.fields:["value","display"],data:a.listValues,limitCount:a.limitCount,limitMsg:a.limitMsg}):new Ext.data.ArrayStore({fields:a.fields?a.fields:
["value","display"],data:a.listValues});Ext.isDefined(a.listeners)?(a.listeners.beforequery=a.listeners.beforequery?b.createSequence(a.listeners.beforequery,this):b,a.listeners.select=a.listeners.select?d.createSequence(a.listeners.select,this):d,a.listeners.blur=a.listeners.blur?c.createSequence(a.listeners.blur,this):c):a.listeners={beforequery:b,select:d,blur:c};sfdc.analytics.framework.FinderDropDown.superclass.constructor.call(this,a)}});Ext.reg("rb_finderDropdown",sfdc.analytics.framework.FinderDropDown);
sfdc.analytics.framework.DateFieldUtil={};
sfdc.analytics.framework.DateFieldUtil.createDateMenu=function(){return new Ext.menu.DateMenu({hideOnClick:!1,monthNames:Date.monthNames,dayNames:Date.dayNames,cancelText:LC.getLabel("ReportBuilder","cancelButton"),disabledDatesText:LC.getLabel("ReportBuilder","datePickerDisabledDayText"),disabledDaysText:LC.getLabel("ReportBuilder","datePickerDisabledDayText"),monthYearText:LC.getLabel("ReportBuilder","datePickerMonthChooseText"),nextText:LC.getLabel("ReportBuilder","datePickerNextText"),prevText:LC.getLabel("ReportBuilder",
"datePickerPrevText"),okText:LC.getLabel("ReportBuilder","ok"),todayText:LC.getLabel("ReportBuilder","datePickerTodayText"),startDay:Number(UserContext.startOfWeek)-1})};
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.EitherOrLookupField=Ext.extend(sfdc.analytics.framework.LookupField,{constructor:function(a){sfdc.analytics.framework.EitherOrLookupField.superclass.constructor.call(this,a)},otherLookupId:"",onBlurAfterValidate:Ext.emptyFn,onBlur:function(){this.focusClass&&this.el.removeClass(this.focusClass);var a=!0;this.hasFocus=!1;if(!1!==this.validationEvent&&(this.validateOnBlur||"blur"==this.validationEvent))a=this.validate();if(!a&&this.onBlurAfterValidate)this.onBlurAfterValidate();a=
this.store;if(1==a.getCount()&&(a=a.getAt(0),a.data.disabled)){var b=this.getValue();!Ext.isEmpty(b.display)&&(this.idField&&(""===this.idField.value||"0"===this.idField.value))&&this.markInvalid(a.data.display)}Ext.getCmp(this.otherLookupId).isValid()&&(a=this.el.getValue(),Ext.isEmpty(a.display)&&this.clearInvalid())},validate:function(){if(!this.el.getValue()){var a=Ext.getCmp(this.otherLookupId).getValue(),b=Ext.getDom(this.otherLookupId+"_lkid");(Ext.isEmpty(a.display)||b&&(""===b.value||"0"===
b.value))&&this.markInvalid(LC.getLabel("ReportBuilder","requiredError"));return!1}if(this.idField&&(""===this.idField.value||"0"===this.idField.value))if(a=this.store,1==a.getCount()&&a.getAt(0).data.disabled)return!1;this.clearInvalid();return!0}});Ext.reg("eitherOrLookupfield",sfdc.analytics.framework.EitherOrLookupField);
Ext.namespace("sfdc.analytics.framework");
sfdc.analytics.framework.SaveDialog=Ext.extend(sfdc.analytics.framework.Dialog,{constructor:function(a){a.waitText=LC.getLabel("AnalyticsDialog","savingWaitText",a.entityName);this.addButtons(a);sfdc.analytics.framework.SaveDialog.superclass.constructor.call(this,a);var b=Ext.getCmp(this.getFieldId(sfdc.analytics.framework.SaveDialogFieldConfigHelper.NAME_FIELD_ID)),c=Ext.getCmp(this.getFieldId(sfdc.analytics.framework.SaveDialogFieldConfigHelper.DEVELOPER_NAME_FIELD_ID));if(!a.hideDevName)b.on("blur",
function(b,d,e){DeveloperNameInputElement.setName(b.el.dom,c.el.dom,a.defaultDevName);c.clearInvalid()})},labelAlign:"right",width:480,fieldDefaults:{width:245,autoScroll:!1},addButtons:function(a){a.buttons=[{text:LC.getLabel("Buttons","save"),formBind:!0,handler:function(a){a.save(!0===a.saveAndClose)}.createCallback(this)},{id:a.id+"_saveAndRun",text:LC.getLabel("AnalyticsDialog","saveAndRunEntity",a.entityName),formBind:!0,handler:function(a){a.save(!0)}.createCallback(this)}]},save:function(a){this.apply()&&
this.saveAfterValidate(a)},saveAfterValidate:function(a){this.disableAllButtons();this.waitSpinner.show();this.onSave(a)},onSave:function(a){},onSaveComplete:function(){this.waitSpinner.hide();this.close()},disableAllButtons:function(){Ext.each(this.extDialog.buttons,function(a){a.oldFormBind=a.formBind;a.formBind=!1;a.disable()})},enableAllButtons:function(){Ext.each(this.extDialog.buttons,function(a){a.enable();a.formBind=a.oldFormBind;delete a.oldFormBind})},onError:function(a){this.waitSpinner.hide();
this.enableAllButtons();this.setErrors(a.errors)?(this.showDialog(!0),this.setErrors(a.errors)):this.close()},setErrors:function(a){var b=!1,c=[];Ext.each(a,function(a){if(a.field)switch(a.field){case "developerName":a.field=sfdc.analytics.framework.SaveDialogFieldConfigHelper.DEVELOPER_NAME_FIELD_ID;break;case "name":a.field=sfdc.analytics.framework.SaveDialogFieldConfigHelper.NAME_FIELD_ID}else c.push(a.message)});0<c.length&&(b=c.join("\n"),Ext.getCmp(this.getFieldId("genericError")).setText(b+
"\x3cbr/\x3e\x3cbr/\x3e",!1).show(),b=!0);c.length<a.length&&(b=b||sfdc.analytics.framework.SaveDialog.superclass.setErrors.call(this,a));return b}});

//# sourceMappingURL=/javascript/1410512610000/sfdc/source/AnalyticsFramework.js.map
