/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
function PeopleListViewport(f,g,e,h,k,l,m){function n(b,c){if(d&&c){if("RECENT"==d.additionalParams.peopleFilterType){var a=chatter.getChatterTab();a&&a.isOnChatterTab()&&(a=Sfdc.select("#000000000000000_topNav h2.title")[0],Sfdc.Dom.setText(a,LC.getLabel("page_ColleagueList","all")),a=0,"ALL"!=k&&(a=1),chatter.getNavigationGroups().changeNavigationItemState("chatterTabNavigation","mainNavigation",1,a))}d.additionalParams.peopleFilterType="ALL"}}Perf.mark("Sfdc.ChatterPeople:Start");var d;Sfdc.onload(function(){var b=
Sfdc.String.format('\x3csfdc:listView class\x3d"PeopleListView zen-listViewMedium zen-listViewFixed" contentClass\x3d"{contentClass}"\x3e\x3cdata:provider type\x3d"ListServlet" pageSize\x3d"{pageSize}" resourceUri\x3d"{resourceUri}" viewType\x3d"{viewType}" additionalParams\x3d"{additionalParams}" autoProvide\x3d"false"\x3e\x3c/data:provider\x3e\x3cfacet:header\x3e\x3c/facet:header\x3e\x3cfacet:navigation\x3e\x3cui:searchbox labelText\x3d"" labelClass\x3d"zen-assistiveText" placeholder\x3d"{searchBoxPlaceholder}" title\x3d"{searchBoxTitle}"\x3e\x3c/ui:searchbox\x3e\x3c/facet:navigation\x3e\x3cfacet:footer\x3e\x3cui:pagerPageInfo\x3e\x3c/ui:pagerPageInfo\x3e\x3cui:pagerNextPrevious\x3e\x3c/ui:pagerNextPrevious\x3e\x3cui:pagerJumpToPage\x3e\x3c/ui:pagerJumpToPage\x3e\x3c/facet:footer\x3e\x3c/sfdc:listView\x3e',
{contentClass:m,additionalParams:Sfdc.String.escapeToHtml(Sfdc.JSON.stringify({peopleFilterType:l})),pageSize:e&&e.rowsPerPage||25,resourceUri:UserContext.getUrl("/_ui/core/chatter/people/ChatterPeopleListServlet"),viewType:g,searchBoxPlaceholder:LC.getLabel("page_ColleagueList","quickfindDefault"),searchBoxTitle:LC.getLabel("Filter","quickfindInputLabel")}),c=Sfdc.get(f+"_listBody");Sfdc.Dom.updateHTML(c,b);SfdcCmp.init(c);b=SfdcCmp.findInstance(c,SfdcCmp.Sfdc.ListView);b.labels.listView.emptyMessage=
h?LC.getLabel("List","none"):LC.getLabel("page_ColleagueList","noDataText");b.attach("onbeforesearch",n);d=b.getProvider();d.setPayload(e);Perf.endMark("Sfdc.ChatterPeople:Start")})};

//# sourceMappingURL=/javascript/1457082225000/sfdc/source/ChatterPeople.js.map
