/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
function TopicListViewport(d,e,b){function f(b,a){if(provider&&a&&(1==a.searchTerm.length||2==a.searchTerm.length))a.cancel=!0}Perf.mark("Sfdc.Topics:Start");Sfdc.onload(function(){var c=Sfdc.String.format(['\x3cchatter:combomenu searchLabelText\x3d"search" searchPlaceHolder\x3d"{placeHolder}" searchBoxTitle\x3d"{searchBoxTitle}"\x3e\x3cui:dropdown data-autoCollapse\x3d"true"\x3e\x3cfacet:trigger\x3e{triggerView}\x3cspan id\x3d"filterDisplay"\x3e{all}\x3c/span\x3e {triggerSort}\x3cspan id\x3d"sortDisplay"\x3e{talkingAbout}\x3c/span\x3e\x3cb class\x3d"zen-selectArrow"\x3e\x3c/b\x3e\x3c/facet:trigger\x3e\x3cui:optgroup type\x3d"radiogroup" value\x3d"filter" class\x3d"combomenu-filter"\x3e\x3cfacet:header\x3e\x3ch4\x3e{triggerView}\x3c/h4\x3e\x3c/facet:header\x3e\x3cui:option value\x3d"Default" isSelected\x3d"true"\x3e{all}\x3c/ui:option\x3e',
b.filter.includeFavoriteFilter?'\x3cui:option value\x3d"Favorites"\x3e{favorites}\x3c/ui:option\x3e':"",'\x3cui:option value\x3d"MyTopics"\x3e{myTopics}\x3c/ui:option\x3e\x3c/ui:optgroup\x3e\x3cui:optgroup type\x3d"radiogroup" value\x3d"sortBy" class\x3d"combomenu-sortBy"\x3e\x3cfacet:header\x3e\x3ch4\x3e{triggerSort}\x3c/h4\x3e\x3c/facet:header\x3e\x3cui:option value\x3d"TalkingAbout" isSelected\x3d"true"\x3e{talkingAbout}\x3c/ui:option\x3e\x3cui:option value\x3d"TopicName"\x3e{name}\x3c/ui:option\x3e\x3c/ui:optgroup\x3e\x3c/ui:dropdown\x3e\x3c/chatter:combomenu\x3e'].join(""),
{placeHolder:LC.getLabel("TopicListView","placeHolder"),searchBoxTitle:LC.getLabel("TopicListView","title"),triggerView:LC.getLabel("TopicListView","searchFilterLabel"),triggerSort:LC.getLabel("TopicListView","sortLabel"),all:LC.getLabel("TopicListView","all"),favorites:LC.getLabel("TopicListView","favorites"),myTopics:LC.getLabel("TopicListView","myTopics"),talkingAbout:LC.getLabel("TopicListView","talkingAbout"),name:LC.getLabel("TopicListView","name")}),c=Sfdc.String.format('\x3csfdc:listView class\x3d"TopicListView zen-listViewMedium zen-listViewFixed zen-listViewHeaderless"\x3e\x3cdata:provider type\x3d"ListServlet" pageSize\x3d"{pageSize}" resourceUri\x3d"{resourceUri}" viewId\x3d"{viewId}" viewType\x3d"{viewType}" autoProvide\x3d"false"\x3e\x3c/data:provider\x3e\x3cfacet:header\x3e\x3c/facet:header\x3e\x3cfacet:navigation\x3e{header}\x3c/facet:navigation\x3e\x3cfacet:footer\x3e\x3cui:pagerPageInfo\x3e\x3c/ui:pagerPageInfo\x3e\x3cui:pagerNextPrevious\x3e\x3c/ui:pagerNextPrevious\x3e\x3cui:pagerJumpToPage\x3e\x3c/ui:pagerJumpToPage\x3e\x3c/facet:footer\x3e\x3c/sfdc:listView\x3e',
{pageSize:b&&b.rowsPerPage||25,resourceUri:UserContext.getUrl("/_ui/sbi/topics/ui/TopicListServlet"),viewId:"",viewType:e,header:c}),a=Sfdc.get(d+"_listBody");Sfdc.Dom.updateHTML(a,c);SfdcCmp.init(a);listView=SfdcCmp.findInstance(a,SfdcCmp.Sfdc.ListView);listView.labels.listView.emptyMessage=LC.getLabel("TopicSearch","noTopics");listView.attach("onbeforesearch",f);provider=listView.getProvider();provider.setPayload(b)});Perf.endMark("Sfdc.Topics:Start")};

//# sourceMappingURL=/javascript/1457082225000/sfdc/source/ChatterTopics.js.map
