/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Sfdc.ns("SfdcApp.DataDotCom.CleanDialog");SfdcApp.DataDotCom.CleanDialog.LOADING_ID="StareAndCompareLoadingOverlay";SfdcApp.DataDotCom.CleanDialog.SAVING_ID="StareAndCompareSavingOverlay";SfdcApp.DataDotCom.CleanDialog.MESSAGE_ID="StareAndCompareMessageDialog";SfdcApp.DataDotCom.CleanDialog.SERVLET_URL="/_ui/datacloud/datadotcom/clean/ui/StareAndCompareAjaxServlet";
SfdcApp.DataDotCom.CleanDialog.showDialog=function(c){SfdcApp.DataDotCom.CleanDialog.entityId=c.entityId;SfdcApp.DataDotCom.CleanDialog.cleanStatus=c.cleanStatus;var d=sfdcPage.getDialogById(SfdcApp.DataDotCom.CleanDialog.LOADING_ID);d||(d=new LoadingOverlay(SfdcApp.DataDotCom.CleanDialog.LOADING_ID,LC.getLabel("DataDotComCleanOverlay","loading"),LC.getLabel("DataDotComCleanOverlay","loadingComplete")),d.register());d.show();Sfdc.Ajax.request(UserContext.getUrl(SfdcApp.DataDotCom.CleanDialog.SERVLET_URL),
{method:"POST",data:{entityId:c.entityId,action:"match",_CONFIRMATIONTOKEN:c.csrf},complete:function(a){d.hide();if(a=SfdcApp.DataDotCom.CleanDialog.parseAndHandleErrors(a,!1,SfdcApp.DataDotCom.CleanDialog.entityId,SfdcApp.DataDotCom.CleanDialog.cleanStatus)){var f;f="6"===a.cleanStatus?sfdcPage.getDialogById(SfdcApp.DataDotCom.SelectMatchDialog.ID):sfdcPage.getDialogById(SfdcApp.DataDotCom.StareAndCompareDialog.ID);f||(a.messageTitle&&(c.title=a.messageTitle),f="6"===a.cleanStatus?new SfdcApp.DataDotCom.SelectMatchDialog(c):
new SfdcApp.DataDotCom.StareAndCompareDialog(c),f.register());var e=document.getElementById(f.getContentId());e.innerHTML=a.success;f.show();f.bindEvents(e)}}})};SfdcApp.DataDotCom.CleanDialog.refreshPage=function(c,d){if(c){var a="/"+c;d&&(a+="?pcs\x3d"+d);Sfdc.Url.navigateTo(UserContext.getUrl(a))}};
SfdcApp.DataDotCom.CleanDialog.parseAndHandleErrors=function(c,d,a,f){var e;if(c){var g;try{e=Sfdc.JSON.parseWithCSRF(c),g=e.error}catch(h){g=LC.getLabel("DataDotComOverlay","genericError")}if(g)return SfdcApp.DataDotCom.CleanDialog.showMessageDialog(a,f,g,d,!0,e.shouldRefreshOnError),null;if(e.message)return SfdcApp.DataDotCom.CleanDialog.showMessageDialog(a,f,e.message,d,!1,!1,e.messageTitle,e.cleanStatus),null}return e};
SfdcApp.DataDotCom.CleanDialog.showMessageDialog=function(c,d,a,f,e,g,h,k){h=h||LC.getLabel("DataDotComCleanOverlay","error");var b=sfdcPage.getDialogById(SfdcApp.DataDotCom.CleanDialog.MESSAGE_ID);b||(b=new OverlayDialog,b.title=h,b.useCSS=!0,b.id=SfdcApp.DataDotCom.CleanDialog.MESSAGE_ID,b.width=400,b.shouldRefresh=!0,b.entityId=c,b.cleanStatus=d,b.hide=function(){OverlayDialog.prototype.hide.call(b);this.shouldRefresh&&SfdcApp.DataDotCom.CleanDialog.refreshPage(this.entityId,this.cleanStatus)},
b.register());b.setTitle(h);document.getElementById(b.getContentId()).innerHTML=a;b.shouldRefresh=f||!e||g;b.show()};
Sfdc.ns("SfdcApp.DataDotCom.DandBRefresh");SfdcApp.DataDotCom.DandBRefresh.SERVLET_URL="/_ui/datacloud/datadotcom/clean/ui/DandBRefreshServlet";
SfdcApp.DataDotCom.DandBRefresh.refresh=function(a){SfdcApp.DataDotCom.DandBRefresh.entityId=a.entityId;var b=sfdcPage.getDialogById(SfdcApp.DataDotCom.CleanDialog.LOADING_ID);b||(b=new LoadingOverlay(SfdcApp.DataDotCom.CleanDialog.LOADING_ID,LC.getLabel("DataDotComCleanOverlay","loading"),LC.getLabel("DataDotComCleanOverlay","loadingComplete")),b.register());b.show();Sfdc.Ajax.request(UserContext.getUrl(SfdcApp.DataDotCom.DandBRefresh.SERVLET_URL),{method:"POST",data:{entityId:a.entityId,action:"refresh",
_CONFIRMATIONTOKEN:a.csrf},complete:function(a){b.hide();SfdcApp.DataDotCom.CleanDialog.parseAndHandleErrors(a,!0,SfdcApp.DataDotCom.DandBRefresh.entityId,null)}})};
Sfdc.ns("SfdcApp.DataDotCom.SelectMatchDialog");SfdcApp.DataDotCom.SelectMatchDialog=function(a){OverlayDialog.call(this,a||{});this.id=SfdcApp.DataDotCom.SelectMatchDialog.ID;this.displayX=!0;this.width=UserContext&&UserContext.uiSkin==UiSkin.ALOHA.apiValue?730:732;this.useCSS=!0;this.focusPointElement=null;this.title=a.title;this.dataDotComDataDiv=this.candidates=null;this.csrfParam=a.csrf;this.cleanStatus=a.cleanStatus};SfdcApp.DataDotCom.SelectMatchDialog.ID="SelectMatchDialog";
SfdcApp.DataDotCom.SelectMatchDialog.prototype=new OverlayDialog;SfdcApp.DataDotCom.SelectMatchDialog.prototype.hide=function(){this.unbindEvents();OverlayDialog.prototype.hide.call(this)};SfdcApp.DataDotCom.SelectMatchDialog.prototype.cancel=function(){OverlayDialog.prototype.cancel.call(this);SfdcApp.DataDotCom.CleanDialog.refreshPage(SfdcApp.DataDotCom.CleanDialog.entityId,SfdcApp.DataDotCom.CleanDialog.cleanStatus)};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.bindEvents=function(a){this.content=a;if(this.candidates=Sfdc.select(".candidateList .candidate",a))for(var b=0,c=this.candidates.length;b<c;b++)Sfdc.on(this.candidates[b],"click",this.onCandidateClick,this);this.dataDotComDataDiv=Sfdc.select(".dataDotCom",a);if((this.saveButton=Sfdc.get("selectMatchSaveButton",a))&&!Sfdc.Dom.hasClass(this.saveButton,"btnDisabled"))Sfdc.on(this.saveButton,"click",this.onSaveClick,this);if(this.cancelButton=Sfdc.get("selectMatchCancelButton",
a))Sfdc.on(this.cancelButton,"click",this.onCancelClick,this);if(this.confidenceBars=Sfdc.select(".candidateList .candidate .confidenceBar",a)){b=0;for(c=this.confidenceBars.length;b<c;b++)Sfdc.on(this.confidenceBars[b],"mouseover",this.onConfidenceBarsHover,this);this.matchedInfoOpend=!1}};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.unbindEvents=function(a){if(this.candidates){a=0;for(var b=this.candidates.length;a<b;a++)Sfdc.un(this.candidates[a],"click",this.onCandidateClick)}this.saveButton&&!Sfdc.Dom.hasClass(this.saveButton,"btnDisabled")&&Sfdc.un(this.saveButton,"click",this.onSaveClick);this.cancelButton&&Sfdc.un(this.cancelButton,"click",this.onCancelClick);if(this.confidenceBars){a=0;for(b=this.confidenceBars.length;a<b;a++)Sfdc.un(this.confidenceBars[a],"mouseover",this.onConfidenceBarsHover)}};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.onCancelClick=function(a){this.hide();SfdcApp.DataDotCom.CleanDialog.refreshPage(SfdcApp.DataDotCom.CleanDialog.entityId,this.cleanStatus)};SfdcApp.DataDotCom.SelectMatchDialog.prototype.hide=function(){this.unbindEvents();OverlayDialog.prototype.hide.call(this)};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.onSaveClick=function(){for(var a=null,b=null,c=null,d=Sfdc.get("SelectMatchDialogContent"),d=Sfdc.select(".radioInput",d),e=0;null!==d&&e<d.length;e++)if(d[e].checked){a=d[e].value;b=Sfdc.Dom.getAttribute(d[e],"data-sfdc-datadotcom-confidenceScore");c=Sfdc.Dom.getAttribute(d[e],"data-sfdc-datadotcom-matchGrade");break}this.hide();var f=sfdcPage.getDialogById(SfdcApp.DataDotCom.CleanDialog.SAVING_ID);f||(f=new LoadingOverlay(SfdcApp.DataDotCom.CleanDialog.SAVING_ID,
LC.getLabel("DataDotComCleanOverlay","saving"),LC.getLabel("DataDotComCleanOverlay","savingComplete")),f.register());f.show();d=Sfdc.get("entitySysModDateParamSM").value;e=Sfdc.get("csrfParamSM").value;Sfdc.Ajax.request(UserContext.getUrl(SfdcApp.DataDotCom.CleanDialog.SERVLET_URL),{method:"POST",data:{entityId:SfdcApp.DataDotCom.CleanDialog.entityId,action:"select",entitySysModDate:d,dunsNumber:a,matchConfidenceScore:b,matchGrade:c,_CONFIRMATIONTOKEN:e},complete:function(a){f.hide();if(a=SfdcApp.DataDotCom.CleanDialog.parseAndHandleErrors(a,
!1,SfdcApp.DataDotCom.CleanDialog.entityId,SfdcApp.DataDotCom.CleanDialog.cleanStatus))Sfdc.get("csrfParamSM").value=a.csrf,SfdcApp.DataDotCom.CleanDialog.showDialog({entityId:SfdcApp.DataDotCom.CleanDialog.entityId,cleanStatus:a.cleanStatus,csrf:Sfdc.get("csrfParamSM").value,title:this.title})}})};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.onCandidateClick=function(a){var b=Sfdc.Event.getSrcElement(a);a=Sfdc.Event.getEventTarget(a);null===Sfdc.Dom.getParent(a,".matchInfoOuter")&&(a=Sfdc.get(".radioInput",b),this.currentDunsNumber=a.value,a.checked=!0,this.changeDataTableData(b),this.changeSelectedCandidate(b))};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.changeSelectedCandidate=function(a){for(var b=0,c=this.candidates.length;b<c;b++)Sfdc.Dom.removeClass(this.candidates[b],"selected");Sfdc.Dom.addClass(a,"selected")};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.changeDataTableData=function(a){a=a.className.match(/candidate[0-9]/)[0];for(var b=0,c=this.dataDotComDataDiv.length;b<c;b++)Sfdc.Dom.hasClass(this.dataDotComDataDiv[b],a)?(Sfdc.Dom.show(this.dataDotComDataDiv[b]),this.changeSfdcElementDifferentClass(this.dataDotComDataDiv[b])):Sfdc.Dom.hideByDisplay(this.dataDotComDataDiv[b])};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.changeSfdcElementDifferentClass=function(a){var b=Sfdc.Dom.hasClass(a,"different");a=Sfdc.Dom.getParent(a,".dataRow");a=Sfdc.get(".sfdcColumn .data",a);b?Sfdc.Dom.addClass(a,"different"):Sfdc.Dom.removeClass(a,"different")};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.onConfidenceBarsHover=function(a){if(!this.matchedInfoOpend&&(a=Sfdc.Event.getSrcElement(a),a=Sfdc.Dom.getParent(a,".candidate"),this.confidenceInfo=Sfdc.get(".matchInfoOuter",a))){this.matchedInfoOpend=!0;Sfdc.Dom.removeClass(this.confidenceInfo,"hidden");Sfdc.on(document.documentElement,"mousemove",this.onMoveIfCandidateInfoOpen,this);this.matchGradeLetters=Sfdc.select(".matchGradeListItem",this.confidenceInfo);this.matchGradeLetterInfos=Sfdc.select(".matchGradeInfo",
this.confidenceInfo);a=0;for(var b=this.matchGradeLetters.length;a<b;a++)Sfdc.on(this.matchGradeLetters[a],"mouseover",this.onMouseOverGradeLetter,this)}};SfdcApp.DataDotCom.SelectMatchDialog.prototype.onMoveIfCandidateInfoOpen=function(a){a=Sfdc.Event.getEventTarget(a);var b=Sfdc.Dom.getParent(a,".matchInfoOuter");!Sfdc.Dom.hasClass(a,"confidenceBar")&&null===b&&this.closeCandidateInfo()};
SfdcApp.DataDotCom.SelectMatchDialog.prototype.closeCandidateInfo=function(){if(null!==this.matchGradeLetters)for(var a=0,b=this.matchGradeLetters.length;a<b;a++)Sfdc.un(this.matchGradeLetters[a],"mouseover",this.onMouseOverGradeLetter);a=0;for(b=this.matchGradeLetterInfos.length;a<b;a++)Sfdc.Dom.addClass(this.matchGradeLetterInfos[a],"hidden");Sfdc.un(document.documentElement,"mousemove",this.onMoveIfCandidateInfoOpen);Sfdc.Dom.addClass(this.confidenceInfo,"hidden");this.matchGradeLetterInfos=this.matchGradeLetters=
this.confidenceInfo=null;this.matchedInfoOpend=!1};SfdcApp.DataDotCom.SelectMatchDialog.prototype.onMouseOverGradeLetter=function(a){a=Sfdc.Event.getSrcElement(a).className.match(/gradeLetter[0-9]/)[0];for(var b=0,c=this.matchGradeLetterInfos.length;b<c;b++)Sfdc.Dom.hasClass(this.matchGradeLetterInfos[b],a)?Sfdc.Dom.removeClass(this.matchGradeLetterInfos[b],"hidden"):Sfdc.Dom.addClass(this.matchGradeLetterInfos[b],"hidden")};
Sfdc.ns("SfdcApp.DataDotCom.StareAndCompareDialog");SfdcApp.DataDotCom.StareAndCompareDialog=function(a){OverlayDialog.call(this,a||{});this.id=SfdcApp.DataDotCom.StareAndCompareDialog.ID;this.displayX=!0;this.width=700;this.useCSS=!0;this.focusPointElement=null;this.differentCells=[];this.identicalRows=[];this.cancelButton=this.saveButton=this.clearAllLink=this.selectAllLink=null;this.numChecked=0;this.title=a.title;this.entityClaim=null};SfdcApp.DataDotCom.StareAndCompareDialog.ID="StareAndCompareDialog";
SfdcApp.DataDotCom.StareAndCompareDialog.prototype=new OverlayDialog;SfdcApp.DataDotCom.StareAndCompareDialog.prototype.hide=function(){this.unbindEvents();this.numChecked=0;OverlayDialog.prototype.hide.call(this)};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.cancel=function(){OverlayDialog.prototype.cancel.call(this);SfdcApp.DataDotCom.CleanDialog.refreshPage(SfdcApp.DataDotCom.CleanDialog.entityId,SfdcApp.DataDotCom.CleanDialog.cleanStatus)};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.bindEvents=function(a){if(this.focusPointElement=Sfdc.get(this.focusPointId))Sfdc.on(this.focusPointElement,"keyup",this.onFocusPointKey,this);this.differentCells=Sfdc.select(".differentRow .dataDotComColumn",a);this.identicalRows=Sfdc.select(".toggleRow",a);if(this.selectAllLink=Sfdc.get("cleanSelectAllLink",a))Sfdc.on(this.selectAllLink,"click",this.onSelectAllClick,this);if(this.clearAllLink=Sfdc.get("cleanClearAllLink",a))Sfdc.on(this.clearAllLink,
"click",this.onClearAllClick,this);if(this.toggleIdenticalLink=Sfdc.get("cleanToggleIdenticalLink",a))this.showIdentical=!0,Sfdc.on(this.toggleIdenticalLink,"click",this.onToggleIdenticalClick,this);if(this.wrongMatchLink=Sfdc.get("wrongMatchLink",a))Sfdc.on(this.wrongMatchLink,"click",this.onWrongMatchClick,this);for(var b=0,c=this.differentCells.length;b<c;b++){var d=this.differentCells[b];Sfdc.on(d,"click",this.onDifferentClick,this);Sfdc.on(d,"keydown",this.onDifferentClick,this);Sfdc.on(d,"mouseover",
this.onDifferentOver,this);Sfdc.on(d,"mouseout",this.onDifferentOut,this)}if(this.reportBadOpenButtons=Sfdc.select(".jsReportBadData",a)){this.reportBadDialogs=Sfdc.select(".jsReportBadDataContainer",a);b=0;for(c=this.reportBadOpenButtons.length;b<c;b++)Sfdc.on(this.reportBadOpenButtons[b],"click",this.onReportBadOpenButtonClick,this);this.reportBadLinks=Sfdc.select(".jsReportBadDataLink",a);b=0;for(c=this.reportBadLinks.length;b<c;b++)Sfdc.on(this.reportBadLinks[b],"click",this.onReportBadLinkClick,
this);this.reportGoodLinks=Sfdc.select(".jsReportGoodDataLink",a);b=0;for(c=this.reportGoodLinks.length;b<c;b++)Sfdc.on(this.reportGoodLinks[b],"click",this.onReportGoodLinkClick,this);this.dataFact={}}if(this.saveButton=Sfdc.get("cleanSaveButton",a))Sfdc.on(this.saveButton,"click",this.onSaveClick,this);if(this.cancelButton=Sfdc.get("cleanCancelButton",a))Sfdc.on(this.cancelButton,"click",this.onCancelClick,this);this.inactiveLink=Sfdc.get(".jsInactiveLink",a);this.activeLink=Sfdc.get(".jsActiveLink",
a);if(this.inactiveLink)Sfdc.on(this.inactiveLink,"click",this.onInactiveLinkClick,this);if(this.activeLink)Sfdc.on(this.activeLink,"click",this.onActiveLinkClick,this);this.inactiveMessage=Sfdc.get(".jsInactiveMessage",a);this.hasPreInactiveMessage=!0;Sfdc.Dom.hasClass(this.inactiveMessage,"hidden")&&(this.hasPreInactiveMessage=!1)};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.unbindEvents=function(a){this.focusPointElement&&Sfdc.un(this.focusPointElement,"keyup",this.onFocusPointKey);this.selectAllLink&&Sfdc.un(this.selectAllLink,"click",this.onSelectAllClick);this.clearAllLink&&Sfdc.un(this.clearAllLink,"click",this.onClearAllClick);this.toggleIdenticalLink&&Sfdc.un(this.toggleIdenticalLink,"click",this.onToggleIdenticalClick);if(this.wrongMatchLink)Sfdc.on(this.wrongMatchLink,"click",this.onWrongMatchClick);a=0;for(var b=
this.differentCells.length;a<b;a++){var c=this.differentCells[a];Sfdc.un(c,"click",this.onDifferentClick);Sfdc.un(c,"keydown",this.onDifferentClick);Sfdc.un(c,"mouseover",this.onDifferentOver);Sfdc.un(c,"mouseout",this.onDifferentOut)}if(this.reportBadOpenButtons){a=0;for(b=this.reportBadOpenButtons.length;a<b;a++)Sfdc.un(this.reportBadOpenButtons[a],"click",this.onReportBadOpenButtonClick);a=0;for(b=this.reportBadLinks.length;a<b;a++)Sfdc.un(this.reportBadLinks[a],"click",this.onReportBadLinkClick)}this.saveButton&&
Sfdc.un(this.saveButton,"click",this.onSaveClick);this.cancelButton&&Sfdc.un(this.cancelButton,"click",this.onCancelClick);this.inactiveLink&&Sfdc.un(this.inactiveLink,"click",this.onInactiveLinkClick,this);this.activeLink&&Sfdc.un(this.activeLink,"click",this.onActiveLinkClick,this)};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onSelectAllClick=function(){this.toggleAllSelected(!0)};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onClearAllClick=function(){this.toggleAllSelected(!1)};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onToggleIdenticalClick=function(a){var b="";if(this.showIdentical)for(var b=LC.getLabel("DataDotComCleanOverlay","hideidentical"),c=0,d=this.identicalRows.length;c<d;c++)Sfdc.Dom.removeClass(this.identicalRows[c],"hidden");else{b=LC.getLabel("DataDotComCleanOverlay","showidentical");c=0;for(d=this.identicalRows.length;c<d;c++)Sfdc.Dom.addClass(this.identicalRows[c],"hidden")}Sfdc.Dom.setText(Sfdc.Event.getSrcElement(a),b);this.showIdentical=!this.showIdentical};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onWrongMatchClick=function(a){this.hide();var b=sfdcPage.getDialogById(SfdcApp.DataDotCom.StareAndCompareDialog.LOADING_ID);b||(b=new LoadingOverlay(SfdcApp.DataDotCom.StareAndCompareDialog.LOADING_ID,LC.getLabel("DataDotComCleanOverlay","loading"),LC.getLabel("DataDotComCleanOverlay","loadingComplete")),b.register());b.show();a=Sfdc.get("csrfParamSnC").value;Sfdc.Ajax.request(UserContext.getUrl(SfdcApp.DataDotCom.CleanDialog.SERVLET_URL),{method:"POST",
data:{entityId:SfdcApp.DataDotCom.CleanDialog.entityId,action:"wrongMatch",_CONFIRMATIONTOKEN:a},complete:function(a){b.hide();if(a=SfdcApp.DataDotCom.CleanDialog.parseAndHandleErrors(a,!1,SfdcApp.DataDotCom.CleanDialog.entityId,SfdcApp.DataDotCom.CleanDialog.cleanStatus)){var d=sfdcPage.getDialogById(SfdcApp.DataDotCom.SelectMatchDialog.ID);d||(d=new SfdcApp.DataDotCom.SelectMatchDialog({entityId:SfdcApp.DataDotCom.CleanDialog.entityId,cleanStatus:a.cleanStatus,csrf:Sfdc.get("csrfParamSnC").value,
title:a.messageTitle}),d.register());var e=document.getElementById(d.getContentId());e.innerHTML=a.success;d.show();d.bindEvents(e)}}})};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onDifferentClick=function(a){if(!(a.keyCode&&a.keyCode!==Sfdc.Event.keyCode.ENTER||this.ieDoubleToggleGuard)&&!Sfdc.Event.getEventTarget(a,".jsReportBadData")&&!Sfdc.Event.getEventTarget(a,".jsReportBadDataContainer")){var b=Sfdc.Event.getEventTarget(a,".dataDotComColumn"),b=Sfdc.get(".differentCheckbox",b);if(!b||!Sfdc.Dom.hasClass(b,"hidden")){if(Sfdc.Event.getEventTarget(a,"label")){Sfdc.Event.stop(a);if(Sfdc.userAgent.isIE){this.ieDoubleToggleGuard=
!0;var c=this;setTimeout(function(){c.ieDoubleToggleGuard=!1},0)}if(b=Sfdc.Event.getEventTarget(a,"a"))if(b=b.getAttribute("href")){window.open(b);return}}this.toggleSelected(Sfdc.Event.getEventTarget(a,".dataDotComColumn"))}}};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.toggleAllSelected=function(a){for(var b=0,c=this.differentCells.length;b<c;b++)this.toggleSelected(this.differentCells[b],a)};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.toggleSelected=function(a,b){var c=Sfdc.get(".differentCheckbox",a);if(c&&!Sfdc.Dom.hasClass(c,"hidden")){var d=Sfdc.Dom.getParent(a,".differentRow"),e=Sfdc.Dom.hasClass(d,"selected");void 0===b&&(b=!e);b!==e&&(b?(Sfdc.Dom.addClass(d,"selected"),Sfdc.Dom.set(c,"checked","checked")):(Sfdc.Dom.removeClass(d,"selected"),Sfdc.Dom.set(c,"checked","")))}};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onDifferentOver=function(a){Sfdc.Dom.addClass(Sfdc.Event.getEventTarget(a,".dataDotComColumn"),"over")};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onDifferentOut=function(a){Sfdc.Dom.removeClass(Sfdc.Event.getEventTarget(a,".dataDotComColumn"),"over")};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onSaveClick=function(){this.hide();this.save()};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onCancelClick=function(){this.hide();SfdcApp.DataDotCom.CleanDialog.refreshPage(SfdcApp.DataDotCom.CleanDialog.entityId,SfdcApp.DataDotCom.CleanDialog.cleanStatus)};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onFocusPointKey=function(a){a.keyCode&&(a.keyCode===Sfdc.Event.keyCode.TAB&&a.shiftKey&&this.cancelButton)&&this.cancelButton.focus()};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onReportBadOpenButtonClick=function(a){a=Sfdc.Event.getSrcElement(a);Sfdc.Dom.hasClass(a,"jsOpen")?this.openReportBadDataDialog(a):this.closeReportBadDataDialog()};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.closeReportBadDataDialog=function(){for(var a=0,b=this.reportBadDialogs.length;a<b;a++){Sfdc.Dom.addClass(this.reportBadDialogs[a],"hidden");var c=Sfdc.Dom.getParent(this.reportBadDialogs[a],".dataDotComColumn");Sfdc.Dom.removeClass(c,"reportBadOpened")}a=0;for(b=this.reportBadOpenButtons.length;a<b;a++)Sfdc.Dom.removeClass(this.reportBadOpenButtons[a],"close"),Sfdc.Dom.removeClass(this.reportBadOpenButtons[a],"jsClose"),Sfdc.Dom.addClass(this.reportBadOpenButtons[a],
"open"),Sfdc.Dom.addClass(this.reportBadOpenButtons[a],"jsOpen")};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.openReportBadDataDialog=function(a){this.closeReportBadDataDialog();Sfdc.Dom.addClass(a,"close");Sfdc.Dom.addClass(a,"jsClose");Sfdc.Dom.removeClass(a,"open");Sfdc.Dom.removeClass(a,"jsOpen");a=Sfdc.Dom.getParent(a,".dataDotComColumn");Sfdc.Dom.addClass(a,"reportBadOpened");a=Sfdc.get(".jsReportBadDataContainer",a);Sfdc.Dom.removeClass(a,"hidden");if(a=Sfdc.select(".reportDataLink",a))for(var b=0,c=a.length;b<c;b++)Sfdc.Dom.hasClass(a[b],"hidden")||
Sfdc.Dom.focus(a[b],!0)};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onReportBadLinkClick=function(a){a=Sfdc.Event.getSrcElement(a);this.reportData(a,!0)};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onReportGoodLinkClick=function(a){a=Sfdc.Event.getSrcElement(a);this.reportData(a,!1)};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.reportData=function(a,b){var c=Sfdc.Dom.getParent(a,".dataDotComColumn"),d=Sfdc.get(".checkImg",c),e=Sfdc.get(".differentCheckbox",c),f=Sfdc.get(".jsBadDataIcon",c),k=Sfdc.get(".jsBadDataLinkIcon",c),l=Sfdc.get(".jsReportBadDataLink",c),m=Sfdc.get(".jsReportGoodDataLink",c),g=Sfdc.get(".jsBadDataInfo",c),h=Sfdc.get(".jsReportBadDataContainer",c);d&&this.hideOrShowElement(d,b);e&&(this.hideOrShowElement(e,b),e.checked&&b&&this.toggleSelected(c));f&&
this.hideOrShowElement(f,!b);g&&(this.hideOrShowElement(g,!b),b?Sfdc.Dom.addClass(h,"reportBadDataContainerWithUserInfo"):Sfdc.Dom.removeClass(h,"reportBadDataContainerWithUserInfo"));this.hideOrShowElement(l,b);this.hideOrShowElement(m,!b);this.hideOrShowElement(k,b);c=f.id;this.dataFact[c]?delete this.dataFact[c]:this.dataFact[c]=b?"report_as_bad":"report_as_good";this.closeReportBadDataDialog()};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.hideOrShowElement=function(a,b){b?Sfdc.Dom.addClass(a,"hidden"):Sfdc.Dom.removeClass(a,"hidden")};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.save=function(){var a=sfdcPage.getDialogById(SfdcApp.DataDotCom.CleanDialog.SAVING_ID);a||(a=new LoadingOverlay(SfdcApp.DataDotCom.CleanDialog.SAVING_ID,LC.getLabel("DataDotComCleanOverlay","saving"),LC.getLabel("DataDotComCleanOverlay","savingComplete")),a.register());a.show();for(var b={},c=0,d=this.differentCells.length;c<d;c++){var e=Sfdc.get(".differentInput",this.differentCells[c]);Sfdc.Dom.hasClass(e,"hidden")||(b[e.id]=e.checked?"accept":
"reject")}c=Sfdc.get("entitySysModDateParamSnC").value;d=Sfdc.get("cleanSysModDateParamSnC").value;e=Sfdc.get("csrfParamSnC").value;Sfdc.Ajax.request(UserContext.getUrl(SfdcApp.DataDotCom.CleanDialog.SERVLET_URL),{method:"POST",data:{entityId:SfdcApp.DataDotCom.CleanDialog.entityId,action:"update",fields:Sfdc.JSON.stringify(b),dataFact:Sfdc.JSON.stringify(this.dataFact),entityClaim:this.entityClaim,entitySysModDate:c,cleanSysModDate:d,_CONFIRMATIONTOKEN:e},complete:function(b){SfdcApp.DataDotCom.CleanDialog.parseAndHandleErrors(b,
!0,SfdcApp.DataDotCom.CleanDialog.entityId)?SfdcApp.DataDotCom.CleanDialog.refreshPage(SfdcApp.DataDotCom.CleanDialog.entityId,SfdcApp.DataDotCom.CleanDialog.cleanStatus):a.hide()}})};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onActiveLinkClick=function(a){this.reportInactive(!1)};SfdcApp.DataDotCom.StareAndCompareDialog.prototype.onInactiveLinkClick=function(a){this.reportInactive(!0)};
SfdcApp.DataDotCom.StareAndCompareDialog.prototype.reportInactive=function(a){Sfdc.Dom.toggleClass(this.inactiveLink,"hidden");Sfdc.Dom.toggleClass(this.activeLink,"hidden");this.entityClaim=null===this.entityClaim?a?"inactive":"active":null;this.hasPreInactiveMessage?Sfdc.Dom.toggleClass(Sfdc.get(".jsPreInfoParagraph",this.inactiveMessage),"hidden"):Sfdc.Dom.toggleClass(this.inactiveMessage,"hidden");Sfdc.Dom.toggleClass(Sfdc.get(".jsActionInfoParagraph",this.inactiveMessage),"hidden")};
SfdcCmp.provide("SfdcApp.DataDotCom.CleanStatusOnRefresh",{bind:function(){var a=this;a.element=document.getElementById("cleanStatusOnRefresh");a.element&&setTimeout(function(){a.element.style.backgroundColor="#ffffdc";a.color=16777180;a.endColor=16777215;a.interval=setInterval(function(){a.updateColor(a)},100)},2E3)},updateColor:function(a){a.color+=5;a.element.style.backgroundColor="#"+a.color.toString(16);a.color>=a.endColor&&(a.element.style.backgroundColor="#ffffff",clearInterval(a.interval))}});
Sfdc.onReady(function(){var a=Sfdc.get("cleanStatusOnRefresh");a&&SfdcCmp.init(a.parentNode)});
(function(c,n){function z(r,k,h,n){var q={};h&&(q.limit=1);return SfdcCmp.find(r,function(r,h){for(var n=0;n<k.length;n++)if(c.isAssignableFrom(k[n],r))return!0;return!1},q,n)}function D(r){var k={attributes:{}};k.attributes[E]=!0;k=c.Dom.create(null,k,"span");k.innerHTML=r;return k.childNodes}function F(c){if(!c)return null;var k=null,h=null,h=null;-1<c.nodeName.indexOf(":")?(h=c.nodeName.split(":"),k=h[0],h=h[1]):c.getAttribute(SfdcCmp.SFDC_NODE_ATTRIBUTE)?(h=c.getAttribute(SfdcCmp.SFDC_NODE_ATTRIBUTE).split(":"),
k=h[0],h=h[1]):(k=c.scopeName,h=c.tagName);"HTML"===k&&(k=null);return{prefix:k,localName:h,qualifiedName:k+":"+h}}function G(c){if(!c)return!1;var k=c.indexOf(":");return-1!==k&&0!==k&&k!==c.length-1}function H(){function r(a,d){a&&(G(a)&&(a=a.toLowerCase()),c.isArray(l[a])||(l[a]=[]),l[a].push(d))}function k(a,d,b){p[a]?p[a].push(d):p[a]=[d];b&&c.Data.set(b,I,d)}function h(a,d){if(!a||!c.Dom.isNode(d))return null;for(var b=null,e=0,f=v.length;e<f;e++)(b=d.getAttribute(v[e]))&&c.isFunction(b=c.resolve(b))&&
s.add(a,v[e],b)}function A(a,d){s.fireEvent(a,J,{data:[d]});k(a.constructor.SFDC_TYPE,a,d)}function B(a,d,b){h(a,b);k(a.constructor.SFDC_TYPE,a,d);s.fireEvent(a,w,{data:[d,b]});s.fireEvent(d,w,{context:a})}var C=!1,p={},t={},l={},u={},x={},s=new c.Event.EventManager(v),y=null,K=null,L=null;if(n.document&&"namespaces"in n.document)c.onload(function(){for(var a in x)x.hasOwnProperty(a)&&n.document.namespaces.add(a,x[a])});y=function(){return n.document&&n.document.documentElement||{}};K=function(a,
d){d=d||y();var b=d.getAttributeNode&&d.getAttributeNode("xmlns:"+a);return b?b.nodeValue:null};L=function(a,d,b){b=b||y();b.setAttribute&&b.setAttribute("xmlns:"+a,d);n.document&&"namespaces"in n.document&&(x[a]=d)};return c.apply(function(){return H()},{FRAMEWORK_URI:"http://www..com/ui/accent/",SFDC_TYPE_ATTRIBUTE:"data-sfdc-widget",SFDC_TYPE_PARAMS_ATTRIBUTE:"data-sfdc-widget-param",SFDC_NODE_ATTRIBUTE:"data-sfdc-type",declarativeModeEnabled:!0,bind:function(a){var d=a.getAttribute(this.SFDC_TYPE_ATTRIBUTE);
if(!d)return null;var b=this.getInstance(a);if(b)return b;if(b=t[d])try{var e;var f=a.getAttribute(SfdcCmp.SFDC_TYPE_PARAMS_ATTRIBUTE);e=f?c.JSON.parse(f):null;var g=new b;c.isArray(e)?g.bind.apply(g,[a].concat(e)):g.bind(a);B(g,a);return g}catch(k){if(c.error(["Failed to create instance of zen component ",d," with error ",k]),c.isDebug)throw k;}else r(d,a);return null},dispose:function(){if(p)for(var a in p)if(p.hasOwnProperty(a))for(var d=p[a],b=0;b<d.length;b++){var e=d[b];if(c.implies(c.IDisposable,
e))try{e.dispose()}catch(f){if(c.error("SfdcCmp: Component failed during dispose. ("+f+")"),c.isDebug)throw f;}}t=p=l=null},find:function(a,d,b,e){if(!c.Dom.isElement(a))throw Error("SfdcCmp.find(): 'container' must be a valid Node.");var f=[];if(a.hasChildNodes()){b||(b={});c.apply(b,{cancel:!1,current:null,index:-1},!0);for(var g=0,k=a.childNodes.length;g<k;g++){var m=a.childNodes[g];if(c.Dom.isElement(m)){var h=SfdcCmp.getInstance(m);if(h){b.current=m;b.index=g;d(h,b)&&f.push(h);if(b.cancel)break;
if(f.length===b.limit)break}e&&(f=f.concat(SfdcCmp.find(a.childNodes[g],d,b,e)))}}}return f},findInstances:function(a,d,b,e,f){if(!c.Dom.isElement(a))throw Error("SfdcCmp.findInstances(): 'container' must be a valid Element.");var g=Array.prototype.slice.call(arguments,1);f=c.isBoolean(g[g.length-1])?g.pop():!1;return z(a,g,!1,f)},findInstance:function(a,d,b,e,f){if(!c.Dom.isElement(a))throw Error("SfdcCmp.find(): 'container' must be a valid Element.");var g=Array.prototype.slice.call(arguments,1);
f=c.isBoolean(g[g.length-1])?g.pop():!1;return z(a,Array.prototype.slice.call(arguments,1),!0,f)[0]},findSingle:function(a,d,b,c){b||(b={});b.limit=1;return SfdcCmp.find(a,function(a,b){return d(a,b)},b,c)[0]||null},generate:function(a){c.isString(a)?a=D(a):!c.isArray(a)&&!c.Dom.isNodeList(a)&&(a=[a]);for(var d=[],b=null,e=null,f=null,g=0,k=a.length;g<k;g++)if(b=null,e=a[g],c.Dom.isElement(e)){var f=F(e).qualifiedName,m=this.resolve(f,e);m&&(b=new m,c.Data.set(b,M,e));b?(f=b,m=e,h(f,m),s.fireEvent(f,
N,{data:[m]}),c.isFunction(b.generate)&&(b=b.generate(e)||b,A(b,e)),d.push(b)):r(f,e)}return d},getInstance:function(a){return c.Data.get(a,I)},getTypeInstances:function(a){return c.isString(a)?p[a]||[]:p},init:function(a){this.isInitialized()||(c.on(n,"unload",this.dispose),C=!0);a=c.select(this.declarativeModeEnabled?q:q+"["+SfdcCmp.SFDC_TYPE_ATTRIBUTE+"]",a);return this.render(a)},isInitialized:function(){return C},onBind:function(a,c){var b=this.getInstance(a);b?c.call(b):s.add(a,w,c)},provide:function(a,
d){var b=new c.Class(d||{});b.SFDC_TYPE=a;this.register(a,b);this.render(l[a]);delete l[a]},register:function(a,d){var b=t[a];b!==d&&!(b&&b.SFDC_TYPE===d.SFDC_TYPE)&&(t[a]&&c.error("Type already registered."),t[a]=d,c.provide(a,d))},registerComponent:function(a,d,b){c.assert(G(d),"The tag parameter was missing the prefix or localName. Please specify your tag with the format prefix:localName.");d=d.toLowerCase();b=b?this.NamespaceManager.generateUri(b,!0):this.NamespaceManager.generateUri(a);var e=
u[b],f=d.split(":"),g=f[0],f=f[1];this.NamespaceManager.register(g,b);e||(e=u[b]);f===q&&(e=e[q]||(e[q]={}),f=g);e[f]&&e[f]!=a&&c.error(c.String.format("The nodeName ({0}) has already been defined in the URI ({1}) to Type ({2})",[f,b,a]));e[f]=a;c.isArray(l[d])&&(c.isArray(l[a])?l[a]=l[a].concat(l[d]):(l[a]=l[d],delete l[d]))},render:function(a,d){if(c.isEmpty(a))return[];c.Dom.isNode(d)||(d=null);c.isString(a)?a=D(a):!c.isArray(a)&&!c.Dom.isNodeList(a)&&(a=[a]);for(var b=[],e=[],f=[],g=null,h=null,
m=0,n=null,l=null,g=null,m=0,n=a.length;m<n;m++)h=a[m],c.isObject(h)&&h.constructor&&"SFDC_TYPE"in h.constructor?(g=h,g={templateNode:c.Data.get(g,M),component:g},e.push(g),A(g.component,g.templateNode)):c.Dom.isElement(h)&&F(h).prefix?(g=this.generate(h)[0])&&e.push({templateNode:h,component:g}):c.Dom.isElement(h)&&!c.isEmpty(h.getAttribute(SfdcCmp.SFDC_TYPE_ATTRIBUTE))&&b.push(h);m=0;for(n=e.length;m<n;m++)if(g=e[m].component,h=e[m].templateNode,d||c.Dom.isNode(h.parentNode)&&c.isFunction(g.render)){var l=
document.createDocumentFragment(),l=g.render(l)||l,p=g,q=l;s.fireEvent(p,O,{data:[q,h]});k(p.constructor.SFDC_TYPE,p,q);l&&(d?d.appendChild(l):l=c.Dom.replace(l,h),f.push(l),f=f.concat(this.render(c.select("*",l))),c.isFunction(g.bind)&&g.bind(l));B(g,l,h)}m=0;for(n=b.length;m<n;m++)this.bind(b[m]),f.push(b[m]);return f},resolve:function(a,d){var b=a.split(":");if(2!=b.length)return null;var e=b[0].toLowerCase(),b=b[1].toLowerCase(),f=this.NamespaceManager.getUriByPrefix(e,d);if(!f)return null;f=
u[f];if(c.isEmpty(f))return null;b=f[b];c.isEmpty(b)&&f.hasOwnProperty(q)&&(b=f[q][e]);return t[b]||null},updateHTML:function(a,d,b,e){e?c.Dom.updateHTML(a,d,b,function(){this.init(a);e()}.bind(this)):(c.Dom.updateHTML(a,d,b),this.init(a))},NamespaceManager:{generateUri:function(a,d){if(c.isEmpty(a))return SfdcCmp.FRAMEWORK_URI;var b=a.split(".");d||b.pop();return SfdcCmp.FRAMEWORK_URI+b.join("/").toLowerCase()},getUriByPrefix:function(a,d){for(var b=null,e=d;!b&&c.Dom.isElement(e)&&!0!==c.Dom.getAttribute(e,
E);)b=this.getPrefixOnElement(a,e),e=e.parentNode;b||(b=this.getPrefixOnElement(a,y()));return b},getPrefixOnElement:K,register:function(a,d,b){var e=this.getPrefixOnElement(a,b);e&&e!==d&&c.error(["Prefix '",a,":' already defined at this scope to URI '",e,"'"].join(""));u[d]||(u[d]={});this.setUriByPrefix(a,d,b)},setUriByPrefix:function(a,d,b){var e=this.getPrefixOnElement(a,b);if(e&&e!=d)c.error("Attempt to redefine prefix - "+a);else if(e)return;this.setPrefixOnElement(a,d,b)},setPrefixOnElement:L}})}
var q="*",N="oncreate",w="onbind",J="ongenerate",O="onrender",v=[N,J,O,w],I="SfdcCmp:Instance",E="data-sfdccmp-fragment",M="SfdcCmp:Template";c.resolve("SfdcCmp")||c.provide("SfdcCmp",H())})(Sfdc,this);
SfdcCmp.provide("SfdcCmp.DataDotComCallout",{bind:function(a){this.callout=a;this.context=Sfdc.get(DetailElement.DEFAULT_DETAIL_ELEMENT_ID);this.links=Sfdc.select(".dataDotComCleanStatusLink",this.context);this.icons=[];this.offset=[-18,-1];for(a=0;a<this.links.length;a++){var b=this.links[a];Sfdc.on(b,"keydown",this.onClick,this);Sfdc.on(b.firstChild,"click",this.onClick,this);this.icons[a]=b.firstChild}b=Sfdc.select(".close a",this.callout);for(a=0;a<b.length;a++)Sfdc.on(b[a],"keydown",this.onClickClose,
this),Sfdc.on(b[a].firstChild,"click",this.onClickClose,this)},onClick:function(a){if(!(window.sfdcPage&&window.sfdcPage.dirtyState!==GenericSfdcPage.STATE_CLEAN)&&!(a.keyCode&&a.keyCode!==KEY_ENTER)){var b=Sfdc.Event.getSrcElement(a);this.caller=b;this.positionCallout();var c=this;Sfdc.on(window,"resize",c.positionCallout,this);Sfdc.Dom.isVisible(this.callout,!1)||(Sfdc.Dom.show(c.callout),a.keyCode?(a=Sfdc.select(".dataDotComCleanStatusIcon",b)[0],Sfdc.Dom.addClass(a,"dataDotComCleanStatusIconSelected")):
Sfdc.Dom.addClass(b,"dataDotComCleanStatusIconSelected"),setTimeout(function(){Sfdc.on(document.body,"click",c.onClickOut,c)},50))}},onClickOut:function(a){a=Sfdc.Event.getEventTarget(a);null===Sfdc.Dom.getParent(a,".dataDotComCallout")&&this.closeCallout()},onClickClose:function(a){a.keyCode&&a.keyCode!==KEY_ENTER||this.closeCallout()},closeCallout:function(){Sfdc.Dom.hideByVisibility(this.callout);for(var a=0;a<this.icons.length;a++)Sfdc.Dom.removeClass(this.icons[a],"dataDotComCleanStatusIconSelected");
Sfdc.un(document.body,"click",this.onClickOut);Sfdc.un(window,"resize",this.positionCallout)},positionCallout:function(){var a=Sfdc.Dom.getPositionXY(this.caller),b=Sfdc.Dom.getPositionXY(this.callout),c=a[0]-b[0],a=a[1]-b[1],b=Sfdc.Dom.getLocalOffsetXY(this.callout),c=b.x+c+this.offset[0],d=0,d=b.y+a,d=d-Sfdc.Dom.getHeight(this.callout)+this.offset[1];this.callout.style.left=c+"px";this.callout.style.top=d+"px"}});Sfdc.onReady(function(){var a=Sfdc.get("cleanCallOut");a&&SfdcCmp.init(a.parentNode)});

//# sourceMappingURL=/javascript/1413622217000/sfdc/source/DataDotComClean.js.map
