/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
var directMessage=function(){function v(h){if(h){var g=chatter.getToolbox(),p=Ext.select(".directMessage .count");"0"==h?g.hide(p):(p.update(h),g.show(p))}}function t(h,g){chatter.getToolbox();var p=g.success;g.success=function(d,c){v(c.unread);p(d,c)};"get"==h&&chatter.getToolbox().get(g);"post"==h&&chatter.getToolbox().post(g)}function E(){function h(a){g(a,!0)}function g(a,f){t("get",{url:u+"list",params:{lastMessageId:a,searchString:e.getCurrentSearch()},success:function(a,r){var l=r.lastMessageId,
h=r.matches;k.update(r.html);c=l;p();b.hide();e.update(h);f&&d.resetPage(c)},failure:function(){k.update(e.xssSearchErrorMessage);c=null;p();b.hide();e.update("");f&&d.resetPage(c)}})}function p(){var a=chatter.getToolbox(),e=!1;c?(n.removeClass("disabled"),e=!0):n.addClass("disabled");0<f.length?(l.removeClass("disabled"),e=!0):l.addClass("disabled");e?a.show(r):a.hide(r)}var d=this,c,f,b,k,l,n,r,e;this.updateStreamListAndHighlightNewStream=function(a){v(a.unread);k.update(a.html);d.resetPage(a.lastMessageId);
a.lastMessageId&&chatter.getToolbox().show(Ext.select(".paging"));e.reset();Ext.select(".stream_"+a.newStreamId).highlight()};this.goToStream=function(a){omnitureWrapper.trackEvent("pm-message-detail");var f=chatter.getToolbox(),c=Ext.get(F),r=new LoadingScreen(c.parent().dom,LC.getLabel("Global","loading"));r.show();t("get",{url:u+a,params:{searchString:e.getCurrentSearch()},success:function(a,e){f.updateHTML(c,e.html,!0,function(){r.hide()})},failure:function(){directMessage.renderInbox()}})};this.showOlder=
function(){chatter.getToolbox();c&&!(b.opaqueElement&&"block"==b.opaqueElement.style.display)&&(b.show(),f.push(c),g(c,!1))};this.showNewer=function(){chatter.getToolbox();if(!(b.opaqueElement&&"block"==b.opaqueElement.style.display)&&f.pop()){b.show();var a;0<f.length&&(a=f[f.length-1]);g(a,!1)}};this.resetPage=function(a){c=a;f=[];p()};this.initializeView=function(a){k=Ext.get("streamListContainer");l=Ext.select(".newer");n=Ext.select(".older");r=Ext.select(".paging");d.resetPage(a);Ext.select(".newer").on("click",
d.showNewer);Ext.select(".older").on("click",d.showOlder);e=new A({doSearch:h});b=new LoadingScreen(k.parent().dom,LC.getLabel("Global","loading"))}}function G(h){function g(){function c(m,a){Sfdc.Dom.hasClass(a,"directMessage")&&l.removeFixedPositionThePage()}function e(m){return m-n.getTop()}function a(){if(p){var m=p.getBottom()-k.getBottom(),a=Math.max(document.documentElement.clientHeight-e(y.getBottom()),0);return Math.min(m,a)}return 0}function b(){var a=Ext.get(document).getScroll().top;f.scrollTo("top",
a,!1);var c=m,e=document.documentElement.clientHeight-h.getTop()-k.getHeight(),e=a+e-f.dom.scrollHeight;m=0<e?e:0;c!=m&&(l.adjustListContainerHeight(),f.scrollTo("top",a+m,!1))}function d(){q=a();l.adjustShadowContentHeight();b();l.adjustListContainerHeight()}var l=this,h,n,g,p,y,q,m=0,B,C,D=0;this.adjustShadowContentHeight=function(){h.dom.style.height=f.dom.scrollHeight+k.getHeight()+q+"px"};this.removeFixedPositionThePage=function(){Ext.EventManager.un(window,"resize",d);Ext.EventManager.un(window,
"scroll",b);window.scroll(g.getScroll().left,0);Ext.DomHelper.applyStyles(n,{position:"static"});g.setStyle("background-attachment","");h&&(h.remove(),h=null);chatter.getEventBus().removeEventListener("chatter:navigation","onAfterLeavingItem",c)};this.storedAdjustListHeight=function(){D=m};this.scrollToBottomOfTheList=function(m){m?(Ext.get("bottomPadding").dom.scrollIntoView(!1),m=g.dom.scrollHeight):(m=g.dom.scrollHeight-q-document.documentElement.clientHeight+D,m+=300);window.scroll(g.getScroll().left,
m)};this.adjustListContainerHeight=function(){var a=document.documentElement.clientHeight-h.getTop()-k.getHeight()-m;f.setStyle("max-height",a+"px")};this.beforeAdjustingScrollHeight=function(){B=g.getScroll().top;C=g.dom.scrollHeight};this.afterAdjustingScrollHeight=function(){var m=g.dom.scrollHeight-C+B;window.scroll(g.getScroll().left,m)};this.flagAsInappropriate=function(m){var a=Ext.get(m.target),e=a.getAttribute("data-messageId"),a=a.parent(),c=a.parent().select(".reportedAsAbuse");a.setVisibilityMode(Ext.Element.DISPLAY).hide();
chatter.getToolbox().post({url:u+e+"/flag",success:function(m){c.show()},failure:function(m){alert(LC.getLabel("Feeds","GenericFailureNoGack"))}});Sfdc.Event.preventDefault(m);return!1};chatter.getEventBus().addEventListener("chatter:navigation","onAfterLeavingItem",c);h=Ext.DomHelper.insertFirst(Ext.getBody()||document.body,{tag:"div",id:"messageShadowContent",style:"position:relative; margin-top: "+f.getTop()+"px; margin-left: "+f.getLeft()+"px;","class":"shadowContent"},!0);n=Ext.get("page")||
Ext.get("contentWrapper")||Ext.get(Ext.select(".chatterPage").elements[0]);g=Ext.get(document.body);p=Ext.get(Ext.select(".bPageFooter").elements[0]);y=Ext.get(Ext.select(".leftContent").elements[0]);Ext.DomHelper.applyStyles(n,{position:"fixed",top:"0px"});g.setStyle("background-attachment","fixed");q=a();m=0;Ext.EventManager.on(window,"resize",d);Ext.EventManager.on(window,"scroll",b);Ext.select(".reportAbuseLink a").on("click",l.flagAsInappropriate)}function p(){var c=chatter.getToolbox();f.dom.scrollHeight>
f.getHeight()&&(f.on("scroll",function(){f.getScroll().top<d?c.hide(b):c.show(b)}),c.show(b),b.dom.style.width=Ext.get(Ext.select(".messageRow").elements[0]).getWidth()+"px")}var d=6,c=10,f,b,k,l,n;this.leaveDetailView=function(){l.removeFixedPositionThePage()};this.initializeReplyInput=function(c,e,a,f){Ext.onReady(function(){var b=chatter.getToolbox(),d=Ext.get("replyBody"),g=Ext.get("sendReplyButton"),k=Ext.get("replyGuestWarning");d.getValue();var q=Ext.get("replyErrorMessage");b.disableButton(g);
b.hide(k);d.removeClass("replyBodyWithGuestUser");var s=new directMessage.ExpandableTextArea("replyBody",15,200,function(a){a=b.stringTrim(d.getValue()).length;f&&d.hasClass("focus")?(b.show(k),d.addClass("replyBodyWithGuestUser")):(b.hide(k),d.removeClass("replyBodyWithGuestUser"));a>e?(b.show(q),b.disableButton(g)):(b.hide(q),0===a||!d.hasClass("focus")?b.disableButton(g):b.enableButton(g));l.beforeAdjustingScrollHeight();l.adjustListContainerHeight();l.adjustShadowContentHeight();l.afterAdjustingScrollHeight()});
g.on("click",function(){omnitureWrapper.trackEvent("pm-reply");b.disableButton(g);b.disable(d);var e=""!==n.getCurrentSearch();t("post",{url:u+h+"/"+c+";new",params:{message:d.getValue(),newestMessageId:e?"":a},success:function(c,m){l.storedAdjustListHeight();e||Ext.get("emptyMessageList")?(b.updateHTML(Ext.get("messageListContainer"),m.html,!0),n.reset()):Ext.get("bottomPadding").insertHtml("beforeBegin",m.html);p();Ext.get(Ext.query(".message_"+a+" ~ li[class^\x3dmessage]")).highlight();a=m.newestMessageId;
d.dom.value="";s.forceAdjustHeight();b.enable(d);l.scrollToBottomOfTheList();l.adjustShadowContentHeight()}})})})};this.initializeMessageList=function(d){Ext.onReady(function(){var e=chatter.getToolbox(),a="idle";f=Ext.get("messageContainer");l||(l=new g);l.adjustListContainerHeight();l.adjustShadowContentHeight();l.scrollToBottomOfTheList(!0);b=Ext.get("messageListGradient");p();var k=Ext.get("showMoreContainer");if(k){var n=Ext.get("showMoreLink"),q=Ext.get("showMoreLoading"),s=function(){200>f.getScroll().top&&
0<c&&"idle"==a&&(a="processing",c--,w())},w=function(){e.hide(n);e.show(q);t("get",{url:u+h+"/list",params:d,success:function(c,b){d.lastMessageId=b.lastMessageId;l.beforeAdjustingScrollHeight();k.insertHtml("afterEnd",b.html);d.lastMessageId?(e.hide(q),e.show(n)):(f.un("scroll",s),k.remove());p();l.adjustShadowContentHeight();l.afterAdjustingScrollHeight();a="idle"}})};f.on("scroll",s);Ext.select(".showMoreLink").on("click",function(){omnitureWrapper.trackEvent("pm-detail-show-older");w()})}Ext.select(".showInbox").on("click",
function(){directMessage.renderInbox()})})};this.initializeView=function(c,b){Ext.onReady(function(){var a=chatter.getToolbox();k=Ext.get("streamReplyInputContainer");var d=Ext.get("streamDetailContent"),f=Ext.get("messageListContainer"),g;n=new A({initialString:c,matchText:b,doSearch:function(){g||(g=new LoadingScreen(d.dom,LC.getLabel("Global","loading")));g.show();t("get",{url:u+h+"/container",params:{searchString:n.getCurrentSearch()},success:function(c,b){n.update(b.matches);""!==n.getCurrentSearch()&&
""===b.matches?a.hide(k):a.show(k);a.updateHTML(f,b.html,!0);g.hide()},failure:function(){n.update("");a.updateHTML(f,n.xssSearchErrorMessage);a.hide(k);g.hide()}})}})})}}function A(h){function g(){c.disableButton(b);r=d.getValue();Perf.mark("MessageSearchStart");h.doSearch();Perf.endMark("MessageSearchStart")}function p(){f.addClass("ghost");f.dom.value=n;c.hide(k)}var d=this,c=chatter.getToolbox(),f=Ext.get("messageSearchInput"),b=Ext.get("messageSearchButton"),k=Ext.get("messageSearchCancel"),
l=Ext.get("searchMatches"),n=f.getValue(),r="";this.getValue=function(){var a=c.stringTrim(f.getValue());return a==n?"":a};this.getCurrentSearch=function(){return r};this.searchChanged=function(){return r!=d.getValue()};this.update=function(a){l.update(a);c.enableButton(b)};this.reset=function(){p();r="";l.update("")};var e=LC.getLabel("DirectMessage","yourSearchTerm");this.xssSearchErrorMessage='\x3cdiv class\x3d"messageSearchNoResult"\x3e'+LC.getLabel("DirectMessage","cantFindMessageWith",e)+'\x3c/div\x3e\x3cdiv class\x3d"messageSearchTip"\x3e\x3ch4\x3e'+
LC.getLabel("DirectMessage","searchTip")+"\x3c/h4\x3e\x3cul\x3e\x3cli\x3e"+LC.getLabel("DirectMessage","checkSpellingOfYourSearch")+"\x3c/li\x3e\x3cli\x3e"+LC.getLabel("DirectMessage","needLongerSearchTerm")+"\x3c/li\x3e\x3c/ul\x3e\x3c/div\x3e";f.on({focus:function(){f.hasClass("ghost")&&(f.removeClass("ghost"),f.dom.value="")},blur:function(){var a=c.stringTrim(f.getValue());(""===a||a==n)&&p()},keydown:function(a){a.keyCode==KEY_ENTER&&g()},keyup:function(a){0<c.stringTrim(f.getValue()).length?
c.show(k):c.hide(k)}});k.on("click",function(){f.dom.value="";c.hide(k);g();f.focus()});b.on("click",g);h.initialString&&(r=f.dom.value=h.initialString,f.removeClass("ghost"),c.show(k),l.update(h.matchText))}var q={},u="/directmessages/",x,s,F="directMessageContainer";q.getInboxView=function(){x||(x=new E);return x};q.removeFixedPosition=function(){s&&s.leaveDetailView()};q.getDetailView=function(){return s};q.createDetailView=function(h){return s=new G(h)};q.renderInbox=function(){omnitureWrapper.trackEvent("pm-message-inbox");
chatter.getChatterTab().refresh("DirectMessages",{})};q.renderInboxOnSuccess=function(h){v(h.unread);s&&s.leaveDetailView()};q.ExpandableTextArea=function(h,g,p,d){function c(b){f(b.browserEvent.type)}function f(c){var e;e=b.getValue();n.update(e.replace(/<br \/>&nbsp;/,"\x3cbr /\x3e").replace(/<|>/g," ").replace(/&/g,"\x26amp;").replace(/\n/g,"\x3cbr /\x3e\x26nbsp;"));""===e&&"blur"==c?e=g:(e=n.getHeight(!0),0===e&&(e=g),e+=g);"focus"==c&&(b.getValue()==k&&!b.hasClass("focus"))&&(b.dom.value="",
b.addClass("focus"));"blur"==c&&""===b.getValue()&&(b.dom.value=k,b.removeClass("focus"));e<l?e=l:p&&e>p&&(e=p);e!=b.getHeight(!0)&&(b.dom.style.height=e+"px");d&&d(c)}var b=Ext.get(h),k=b.getValue(),l=b.getHeight(!0),n=Ext.DomHelper.append(Ext.getBody()||document.body,{tag:"div",style:"position: absolute; top: -100000px; left: -100000px;","class":"shadowDiv"},!0);h=chatter.getToolbox().getStyles(b,"padding-top padding-bottom padding-left padding-right line-height font-size font-family font-weight font-style".split(" "));
h.width=b.getWidth()+"px";Ext.DomHelper.applyStyles(n,h);b.on({keyup:c,click:c,focus:c,blur:c});this.forceAdjustHeight=function(){f("blur")}};q.DirectMessageComposeHelper=function(h,g,p){var d=this,c=chatter.getToolbox(),f=window.opener?window.opener:window.parent,b=f.getOpenDialog();b.positioned=!0;var k=[],l=[],n=Ext.get("messageBody"),r=Ext.get("recipientInputBox"),e=Ext.get("recipientsList"),a=Ext.get("recipientsContainer"),q=Ext.get("sendMessageButton"),s=Ext.get("guestWarning"),u=Ext.get("topPadding"),
t=Ext.get("messageMaxErrorMessage"),w=Ext.get("recipientsFullMessage"),v=Ext.fly(f.document).child("#conversationComposeDialogContentId");v&&v.dom.setAttribute("scrolling","no");directMessage.ExpandableTextArea("messageBody",15,300,function(){d.validateForm(!0);d.updateDialogHeight()},!1);Ext.get("closeDialogButton").on("click",function(){d.closeDialog()});c.disableButton(q);q.on("click",function(){d.sendMessage()});e.on("click",function(){r.focus()});var x=a.getX(),y=a.getWidth()-2,z=new UserAndGroupAutoCompleteInputElement({elementId:"recipientInputBox",
inDialog:!0,disableGhostText:!0,entityType:UserAndGroupAutoCompleteInputElement.ENTITY_TYPE_USER,fixedACYPosition:0,handleSelect:function(m){d.addRecipient(m.itemId,m.itemName,m.badgeHtml,m.isExternalUserOrGroup);this.complete()},handleBlur:function(){this.clearSuggestions()},getMinimumWidth:function(){return y},getACXPosition:function(){return x},getACYPosition:function(){return d.getACYPosition()}});z.isValidSuggestion=function(m,a){return a.ItemId===UserContext.userId?!1:UserAndGroupAutoCompleteInputElement.prototype.isValidSuggestion.call(this,
m,a)};r.on({keydown:{fn:function(a){a.keyCode==KEY_BACKSPACE&&""===r.getValue()?(a=e.last(".item"))&&d.removeRecipient(a.dom.getAttribute("userid")):a.keyCode==KEY_TAB?n.focus():a.keyCode!=KEY_ENTER&&k.length==h&&(d.checkRecipientFull(),a.stopEvent())}},keyup:{fn:function(a){d.updateRecipientInputSize();d.updateDialogHeight()}},focus:{fn:function(){e.addClass("focus")}},blur:{fn:function(){e.removeClass("focus");d.clearInputTextInternal()}}});this.getACYPosition=function(){return a.getY()+a.getHeight()};
this.checkRecipientFull=function(){k.length==h&&(c.show(w),e.addClass("error"))};this.updateDialogHeight=function(){var a=Ext.getBody().getHeight()+5;b.resize(a,b.width)};this.updateRecipientInputSize=function(){r.dom.setAttribute("size",r.getValue().length+2);z.acBox&&z.acBox.setStyle("top",d.getACYPosition()+"px")};this.closeDialog=function(){b.close()};this.validateMessage=function(a){var b=c.stringTrim(n.getValue());if(b.length>g)return a&&"none"===t.getStyle("display")&&(c.show(t),n.addClass("error")),
!1;"none"!==t.getStyle("display")&&(c.hide(t),n.removeClass("error"));return 0===b.length?!1:!0};this.validateForm=function(a){(a=d.validateMessage(a)&&0!==k.length)?c.enableButton(q):c.disableButton(q);return a};this.clearInputText=function(){r.blur();d.clearInputTextInternal();r.focus()};this.clearInputTextInternal=function(){r.dom.value=""};this.addRecipient=function(a,b,f,g){if(-1==k.indexOf(a)&&a!=UserContext.userId){k.push(a);var h=r.parent(),n=0<f.length?" guestItem":"",p=e.dom.ownerDocument.createElement("span");
p.className="item_"+a+" item"+n;p.userid=a;p.innerHTML=["\x3cspan\x3e",b,"\x3c/span\x3e",f,'\x3ca href\x3d"#" class\x3d"remove"\x3e\x3cimg src\x3d"/s.gif"/\x3e\x3c/a\x3e'].join("");e.dom.insertBefore(p,h.dom);Sfdc.on(Sfdc.get(".remove",p),"click",function(){d.removeRecipient(a)});e.createChild({tag:"span",html:" "},h);d.validateForm(!1);g&&(l.push(a),c.show(s),c.hide(u))}UserAndGroupAutoCompleteInputElement.needDefer()?d.clearInputText.defer(100):d.clearInputText();d.updateRecipientInputSize();d.updateDialogHeight()};
this.removeRecipient=function(a){if(-1!=k.indexOf(a)){k.length==h&&(c.hide(w),e.removeClass("error"));k.remove(a);var b=Ext.get(e.child(".item_"+a+""));b.next().remove();b.remove();d.validateForm(!1);d.updateDialogHeight();-1!=l.indexOf(a)&&(l.remove(a),1>l.length&&(c.hide(s),c.show(u)))}};this.sendMessage=function(){d.validateForm(!0)&&(omnitureWrapper.trackEvent("pm-send-message"),c.disableButton(q),c.post({url:"/directmessages;new",params:{recipients:k,message:n.getValue(),source:p},success:function(a,
g){g.invalidids?(Ext.select(".item").removeClass("invalid"),Ext.each(g.invalidids,function(a){Ext.get(e.child(".item_"+a+"")).addClass("invalid")}),alert(LC.getLabel("DirectMessage","errorInvalidUsers")),c.enableButton(q)):(d.closeDialog(),"I"==p?f.directMessage.getInboxView().updateStreamListAndHighlightNewStream(g):d.showSuccessfulMessage(g.html,b.fixedX+b.width/2,b.fixedY+b.height/2))},failure:function(a,b){403==a.status&&c.refresh()}}))};this.showSuccessfulMessage=function(a,b,c){var d=Ext.get(f.document.body),
e=d.child(".sendMessageSuccessElement");e&&e.remove();a=d.createChild('\x3cdiv class\x3d"sendMessageSuccessElement"\x3e'+a+"\x3c/div\x3e").child(":first-child");a.dom.style.left=b-a.getWidth()/2+"px";a.dom.style.top=c-a.getHeight()/2+"px";a.pause(4);a.fadeOut({endOpacity:0,duration:1,remove:!0})};d.updateDialogHeight()};return q}();

//# sourceMappingURL=/javascript/1457082225000/sfdc/source/DirectMessage.js.map
