/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Sfdc.ns("Sfdc.EntityFeed");
(function(){function A(){return window.top===window&&"undefined"!==typeof isServiceDeskPage&&isServiceDeskPage}function x(d,c,e){if(!(3<e))for(var a in d)d.hasOwnProperty(a)&&("object"===typeof d[a]?x(d[a],c+"   ",e+1):Sfdc.log(c+a+": "+d[a]))}function L(){function d(a,b,n){this.frameWindow=a;this.name=b;this.origin=n;this.equals=function(c){return c&&"object"===typeof c&&c.name===b&&c.frameWindow===a&&c.origin===n};this.equalsAllowUndefinedWindow=function(c){return c&&"object"===typeof c&&c.name===
b&&(c.frameWindow===a||!c.frameWindow||!a)&&c.origin===n};this.toString=function(){return a?b+" ["+n?n:"unknown, "+c(a)+"]":b}}function c(a){if(a===window.self){var b=a.location.href.indexOf("?");return 0<b?a.location.href.substring(0,b):a.location.href}return"Unvailable (different domain)"}function e(a,b,n){n={message:n,sourceFrameName:window.name};b?n.connect=b:n.nonce=B;return a+Sfdc.JSON.stringify(n)}function a(a,b){f&&(a?Sfdc.log("+++   POST from "+window.name+" ["+c(window)+"] to "+a.toString()):
Sfdc.log("+++   POST broadcast from "+window.name+" ["+c(window)+"]"),x(b,"         ",0))}function g(a,b,n,c,d){if(a)try{a.postMessage(e(b,n,c),d)}catch(g){g.description&&-1!==g.description.toLowerCase().indexOf("permission denied")?Sfdc.log("Permission denied to call postMessage on frame"):Sfdc.log("PostMessage failed:"+(g.description||g))}else Sfdc.log("Cannot call postMessage on null window")}function b(){var a=window.location.toString(),b=["/","?","#"],n="";if(-1!==a.indexOf("://"))for(var a=
a.split("://"),n=a[0]+"://",a=a[1],c=0;c<b.length;c++){var d=a.indexOf(b[c]);if(-1!==d){a=a.substring(0,d);break}}return n+a+"/crossDomainProxy.html"}function k(a,c){var n={};n.pathToTargetProxy=Sfdc.xdomain.sfdcXDomainProxy;n.name=a;n.args=c;n.calleeName=l;n.txn_id=H;n.pathToOriginProxy=b();H++;setTimeout(function(){Sfdc.xdomain.Caller.call(n)},25)}function h(a,b,c,d){b=e(b,c,d);if(b.length>v){c=[];d=0;for(var g=b.length;d<g;d+=v){var f=b.slice(d,Math.min(d+v,b.length));c.push(f)}d=0;for(g=c.length;d<
g;d++)p(a,c[d],d,c.length,b.length)}else p(a,b)}function p(a,b,c,d,g){b={message:b,sourceFrameName:window.name,origin:window.location.href};d&&(b.chunkIndex=c,b.chunkCount=d,b.messageLength=g);a&&(b.targetFrameName=a);k("postEntityFeedMessage",b)}function u(a,b){a.push(b);for(var c=0,d=b.frames.length;c<d;c++)a.push(b.frames[c])}function q(a,b,d){if((b=r(b))&&b.messageHandler)f&&(Sfdc.log("+++   RECEIVED "+window.name+" ["+c(window)+"] from "+a.toString()),x(d,"         ",0)),b.messageHandler(a,d)}
function m(a,b,c){setTimeout(function(){a.frameWindow.entityFeedFrameMessageHandler(new d(window,window.name,window.location.href),b,c)},25)}function M(a,b){if(a===window.self)return!0;if(!y)return!1;var c=b.toLowerCase(),c=c.split("?")[0];-1!=c.indexOf("://")&&(c=c.split("://")[1]);b=c=c.split("/")[0];for(var c=0,d=y.length;c<d;c++)if(-1!==b.indexOf(y[c]))return!0;return!1}function r(a){if(Sfdc.isString(a))for(var b=0,c=t.length;b<c;b++)if(0===a.indexOf(t[b].prefix))return t[b];return null}function s(a){for(var b=
0,c=t.length;b<c;b++)if(t[b].prefix===a)return t[b];a={prefix:a};t.push(a);return a}var l="sfdc-console",f=!1,H=0,I={},v=2E3,t=[];this.connect=function(b,c){a(null,c);if(z){var d=N?window.parent:window,f=[];if(C){for(var e=d.parent.frames,r=0,k=e.length;r<k;r++)u(f,e[r]);u(f,d.parent);d.top.opener&&u(f,d.top.opener)}else u(f,d);r=0;for(k=f.length;r<k;r++)f[r]!==window.self&&g(f[r],b,!0,c,"*")}else h(null,b,!0,c)};this.postMessage=function(b,c,d){a(b,d);if(z)g(b.frameWindow,c,!1,d,b.origin);else{var f;
try{if(!b.frameWindow)for(var e=window.parent.frames,r=0,k=e.length;r<k;r++)if(e[r].name===b.name){b.frameWindow=e[r];break}!b.name&&b.frameWindow&&(b.name=b.frameWindow.name);f=b.frameWindow&&b.frameWindow.entityFeedFrameMessageHandler}catch(s){f=!1}f?m(b,c,d):h(b.name,c,!1,d)}};this.callXdomainAddEventHandler=function(a,b,c){Sfdc.xdomain.CrossDomainApiRegistry.getFunction(a)||Sfdc.xdomain.CrossDomainApiRegistry.registerFunction(a,function(a){c.call(this,a)},this);b.event=!0;k(a,b)};z||(window.entityFeedFrameMessageHandler=
q);this.setConnectionHandler=function(a,b){s(a).connectionHandler=b};this.setMessageHandler=function(a,b,c){a=s(a);a.handleMessagesToSelf=c;a.messageHandler=b};this.isSameOrigin=function(a){try{return a&&a.frameWindow&&a.frameWindow.document&&a.frameWindow.document.domain}catch(b){return!1}};(function(){var a=function(a,b,g){var e=r(g);if(e&&(e.handleMessagesToSelf||a!==window.self)){var h=Sfdc.JSON.parse(g.substr(e.prefix.length));if(h.connect)e=e.connectionHandler;else{if(h.nonce!==B){Sfdc.log("Error: Invalid or missing nonce in frame post. Message discarded.");
return}e=e.messageHandler}if(e){a=new d(a,h.sourceFrameName,b);f&&(Sfdc.log("+++   RECEIVED "+window.name+" ["+c(window)+"] from "+a.toString()),x(h.message,"         ",0));try{e(a,h.message)}catch(k){Sfdc.log("Error processing message: "+g+". Exception: "+k.message)}}}};if(z){var b=function(b){b.data&&M(b.source,b.origin)&&a(b.source,b.origin,b.data)};window.attachEvent?window.attachEvent("onmessage",function(a){var c={data:a.data,source:a.source,origin:a.origin};setTimeout(function(){b(c)},25)}):
window.addEventListener("message",b,!1)}else this.callXdomainAddEventHandler("onEntityFeedMessage",{frameName:window.name,event:!0},function(b){var c;a:{var d=b.message;if(b.chunkIndex){c=I[d.sourceFrameName];c||(c={},I[d.sourceFrameName]=c);var g=c[b.messageLength];g||(g=[],g.length=b.chunkCount,c[b.messageLength]=g);g[b.chunkIndex]=d;for(var d=0,e=g.length;d<e;d++)if(!g[d]){c=null;break a}d=g.join("");delete c[b.messageLength]}c=d}c&&a.call(this,null,b.origin,c)})})()}function m(){D||(D=new L);
return D}function O(){function d(a,c,b,d){chatter.getEventBus().addEventListener(a,c,b,d)}function c(a,c,b){return function(d,e){if(!c||e.isObjectEvent&&e.objectId==c)(!b||!isExternalFrameEvent(e))&&a(d,e)}}var e=[];this.addEventListener=function(a,g,b,k){d(a,g,b,(k?k.scope:null)||this);var h=k&&k.isLocalFrameEvent,p=k&&k.filterObjectId;(h||p)&&c(b,k.filterObjectId,k.isLocalFrameEvent);if(!h){b=0;for(k=e.length;b<k;b++)if(e[b].namespace==a&&e[b].eventname==g)return;a={namespace:a,eventname:g};e.push(a);
Sfdc.EntityFeed.FrameProxies.subscribeToEvent(a)}};this.addConsoleEventListener=function(a,c,b){if(C&&b&&b.fields)for(var e=function(b){var c="onAfter"+a+b.field;chatter.getEventBus().fireEvent("entityFeed:console",c,b)},h=0,p=b.fields.length;h<p;h++)d("entityFeed:console","onAfter"+a+b.fields[h],c),m().callXdomainAddEventHandler(a,{field:b.fields[h]},e)};this.fireEvent=function(a,c,b,d){d&&(b=b||{},d.objectId&&(b.isObjectEvent=b.isObjectEvent||!0,b.objectId=b.objectId||d.objectId),d.isLocalFrameEvent&&
(b.isLocalFrameEvent=b.isLocalFrameEvent||!0));chatter.getEventBus().fireEvent(a,c,b)};this.removeEventListener=function(a,c,b){chatter.getEventBus().removeEventListener(a,c,b)};this.getGlobalListenerEventDefs=function(){return e};this.dispatchEventFromExternalFrame=function(a,c,b){b=b||{};b.fromExternalFrame=!0;chatter.getEventBus().fireEvent(a,c,b)};this.isEventFromExternalFrame=function(a){return a&&!0===a.fromExternalFrame};this.isLocalFrameEvent=function(a){return a&&!0===a.isLocalFrameEvent}}
function P(){function d(a){return{objectId:a.objectId,componentKey:a.componentKey,componentContext:a.componentContext,inExternalFrame:!0,componentState:a.componentState}}var c=[],e={};Sfdc.EntityFeed.getEventBus().addEventListener("entityFeed:componentRegistry","onAfterComponentStateChange",function(a,c){var b=e[c.objectId];if(b&&(b=b.lookup[c.componentKey]))b.componentState=c.componentState});Sfdc.EntityFeed.getEventBus().addEventListener("entityFeed:componentRegistry","onAfterComponentUpdates",
function(a,d){var b;a:{for(b=0;b<c.length;b++)if(c[b].inLocalFrame&&c[b].objectId===d.objectId){b=!0;break a}b=!1}b&&(ForeignKeyInputElement.reload(),"undefined"!==typeof picklist&&(picklist.initialized=!1,picklist.initAll()))});this.register=function(a){if(!a.objectId||!a.componentKey)Sfdc.log("Error: Invalid config for component registry [objectId\x3d"+a.objectId+", componentKey\x3d"+a.componentKey+"]. Component skipped");else{if(a.onUpdateCallback){if(a.inExternalFrame){Sfdc.log("Error: Callbacks not allowed for external frame components [objectId\x3d"+
a.objectId+", componentKey\x3d"+a.componentKey+"]. Component skipped");return}if(!Sfdc.isFunction(a.onUpdateCallback)){Sfdc.log("Error: Component config.onUpdateCallback not a function but a "+a.onUpdateCallback+" for [objectId\x3d"+a.objectId+", componentKey\x3d"+a.componentKey+"]. Component skipped");return}}var g=e[a.objectId];g||(g={updateKeys:[],lookup:{}},e[a.objectId]=g);var b=g.lookup[a.componentKey];if(b){if(a.inExternalFrame){b.inExternalFrame=!0;b.refCount++;return}if(b.inLocalFrame){Sfdc.log("Entity feed: local component already registered [objectId\x3d"+
a.objectId+", componentKey\x3d"+a.componentKey+"]. Component skipped.");return}a=Sfdc.apply(b,a);a.inLocalFrame=!0;a.refCount++}else a=Sfdc.clone(a),a.refCount=1,a.inLocalFrame=!a.inExternalFrame,g.lookup[a.componentKey]=a,b={key:a.componentKey},a.componentContext&&(b.context=a.componentContext),g.updateKeys.push(b),c.push(a);a.inLocalFrame&&(a.onUpdateCallback&&Sfdc.EntityFeed.getEventBus().addEventListener("entityFeed:object","onAfterUpdate",a.onUpdateCallback),Sfdc.EntityFeed.FrameProxies.registerComponent(d(a)))}};
this.unregister=function(a){if(!a.objectId||!a.componentKey)Sfdc.log("Error: Invalid config for component registry [objectId\x3d"+a.objectId+", componentKey\x3d"+a.componentKey+"]. Component skipped.");else{var g=e[a.objectId];if(g){var b=g.lookup[a.componentKey];if(b&&(b.refCount--,b.inLocalFrame&&!a.inExternalFrame&&(b.inLocalFrame=!1,b.onUpdateCallback&&(Sfdc.EntityFeed.getEventBus().removeEventListener("entityFeed:object","onAfterUpdate",b.onUpdateCallback),b.onUpdateCallback=null),Sfdc.EntityFeed.FrameProxies.unregisterComponent(d(b))),
1>b.refCount)){var k,b=0;for(k=g.updateKeys.length;b<k;b++)if(g.updateKeys[b].key===a.componentKey){g.updateKeys.splice(b,1);break}b=0;for(k=c.length;b<k;b++)if(c[b].componentKey===a.componentKey&&c[b].objectId===a.objectId){c.splice(b,1);break}delete g.lookup[a.componentKey];0===g.updateKeys.length&&delete e[a.objectId]}}}};this.getLocalComponentsForExternalFrame=function(){for(var a=[],e=0,b=c.length;e<b;e++)c[e].inLocalFrame&&a.push(d(c[e]));return a};this.getUpdateComponentKeys=function(a){return(a=
e[a])?a.updateKeys:null};this.getComponentState=function(a,c){var b=e[a];return b&&(b=b.lookup[c])?b.componentState:null};this.refreshComponents=function(a,d,b,e,h){if((d||b||e)&&0<c.length){var p=[];d&&p.push("Fields");b&&p.push("RelatedObjects");e&&p.push("Feed");d={url:"/entityfeed/"+a,params:{updateTypes:Sfdc.JSON.stringify(p)}};h&&(d.context=h.context,d.success=h.success,d.failure=h.failure);Sfdc.EntityFeed.getObjectUpdate(a,d)}}}function Q(d){var c={context:{isApiRefreshCall:!0}};d&&(c.success=
d.success?function(){d.success(d.context)}:null,c.failure=d.failure?function(){d.failure(d.context)}:null);return c}function J(d,c){var e=E(d,c);e.params.retURL="/"+d;var a=Sfdc.EntityFeed.getComponentRegistry().getUpdateComponentKeys(d);if(a&&0<a.length){e.params.updateComponents=Sfdc.JSON.stringify({componentKeys:a});var g=e.success;e.success=function(a,k){if(k.objectUpdates){var h=Sfdc.JSON.parse(k.objectUpdates);if(h.fullPageRefresh)return C||A()?(Sfdc.EntityFeed.getEventBus().fireEvent("entityFeed:object",
"onFullRefresh",{objectId:d,source:{frame:window.name},forceFullRefresh:!Sfdc.isDefAndNotNull(h.nonFeedBasedLayout)}),A()&&g&&g(a,k)):self.location.reload(),e;h.objectId=d;h.source={frame:window.name};c.context&&(h.source.context=c.context);Sfdc.EntityFeed.getEventBus().fireEvent("entityFeed:object","onAfterUpdate",h);h.componentUpdates&&Sfdc.EntityFeed.getEventBus().fireEvent("entityFeed:componentRegistry","onAfterComponentUpdates",h)}g&&g(a,k)}}return e}function E(d,c){c=c||{};c.params=c.params||
{};c.params.isAjaxRequest="true";c.params.contextObjectId=d;return c}var C=-1!=window.location.href.lastIndexOf("isdtp\x3dvw"),N=-1!=window.location.href.lastIndexOf("isCEFP\x3d1"),z="undefined"!=typeof window.postMessage,B,y,K=!1;Sfdc.EntityFeed.init=function(d){K||(K=!0,B=d.nonce,y=d.trustedOrigins,Sfdc.ClientLogging.addRelay(new Sfdc.ClientLogging.ConsoleLogger,!0))};window.Perf&&window.Perf.enabled?(Sfdc.EntityFeed.perfMark=function(d){Perf.mark(d)},Sfdc.EntityFeed.perfEndMark=function(d){Perf.endMark(d)}):
Sfdc.EntityFeed.perfMark=Sfdc.EntityFeed.perfEndMark=function(){};var D;Sfdc.EntityFeed.getXDomain=function(){return m()};Sfdc.provide("Sfdc.EntityFeed.FrameProxies",new function(){function d(a,b){return function(c,d){if(!d||!Sfdc.EntityFeed.getEventBus().isEventFromExternalFrame(d)&&!Sfdc.EntityFeed.getEventBus().isLocalFrameEvent(d)){var f={namespace:b.namespace,eventname:b.eventname,payload:d};m().postMessage(a,e,{key:k,event:f})}}}function c(c,d,k){var l,f;f=0;for(len=h.length;f<len;f++)if(h[f].equals(c))if(k){l=
!0;break}else return;l||(h.push(c),d&&d.key&&(u[d.key]={frameContext:d,frameRefName:c.name}));f={key:a};q&&(f.frameContext=q);m().postMessage(c,e,f);(f=Sfdc.EntityFeed.getEventBus().getGlobalListenerEventDefs())&&0<f.length&&m().postMessage(c,e,{key:g,eventDefs:f});(f=Sfdc.EntityFeed.getComponentRegistry().getLocalComponentsForExternalFrame())&&0<f.length&&m().postMessage(c,e,{key:b,components:f});for(f=0;f<w.length;f++)if(k=w[f],k.onRegister)k.onRegister(c,d)}var e="Entity_Feed_Page_Event:",a="registerFrame",
g="subscribeToEvent",b="registerComponent",k="fireEvent",h=[],p={},u={},q,w=[];this.addRegistrationHandler=function(a){w.push(a)};this.subscribeToEvent=function(a){for(var b=0,c=h.length;b<c;b++)m().postMessage(h[b],e,{key:g,eventDefs:[a]})};this.registerComponent=function(a){for(var c=0,d=h.length;c<d;c++)m().postMessage(h[c],e,{key:b,components:[a]})};this.unregisterComponent=function(a){for(var b=0,c=h.length;b<c;b++)m().postMessage(h[b],e,{key:"unregisterComponent",components:[a]})};this.setCurrentFrameContext=
function(a){q&&Sfdc.log("Error: Frame context already set for current frame.");a.key||Sfdc.log("Error: A key must be specified for the frame context.");q=a};this.getCurrentFrameContext=function(){return q};this.getFrameContext=function(a){return(a=u[a])?a.frameContext:null};Sfdc.onload(function(){window.name||(window.name="EntityFeedFrameProxy_"+Sfdc.newUID());m().setConnectionHandler(e,function(b,d){d.key===a?c(b,d.frameContext,!0):Sfdc.log("Error: Invalid connect key: "+d.key)});m().setMessageHandler(e,
function(e,s){if(s.key===a)c(e,s.frameContext,!1);else if("unregisterFrame"===s.key){var l,f;for(f=0;f<h.length;f++)if(h[f].equalsAllowUndefinedWindow(e)){h.splice(f,1);for(l in p)if(p.hasOwnProperty(l)&&(f=p[l])&&f.listeners[e.name])Sfdc.EntityFeed.getEventBus().removeEventListener(f.namespace,f.eventname,f.listeners[e.name]),delete f.listeners[e.name];break}for(l in u)u.hasOwnProperty(l)&&(f=u[l])&&f.frameRefName===e.name&&delete u[l];for(f=0;f<w.length;f++)if(l=w[f],l.onUnregister)l.onUnregister(e)}else if(s.key===
g){l=s.eventDefs;f=0;for(var m=l.length;f<m;f++){var q=l[f],v=q.namespace+":"+q.eventname,t=p[v];t||(t={namespace:q.namespace,eventname:q.eventname,listeners:{}},p[v]=t);t.listeners[e.name]||(t.listeners[e.name]=d(e,q),Sfdc.EntityFeed.getEventBus().addEventListener(q.namespace,q.eventname,t.listeners[e.name]))}}else if(s.key===k)l=s.event,Sfdc.EntityFeed.getEventBus().dispatchEventFromExternalFrame(l.namespace,l.eventname,l.payload);else if(s.key===b){l=s.components;f=0;for(m=l.length;f<m;f++)Sfdc.EntityFeed.getComponentRegistry().register(l[f])}else if("unregisterComponent"===
s.key){l=s.components;f=0;for(m=l.length;f<m;f++)Sfdc.EntityFeed.getComponentRegistry().unregister(l[f])}else Sfdc.log("Error: Invalid message key: "+s.key)});var x={key:a};q&&(x.frameContext=q);m().connect(e,x);Sfdc.on(window,"unload",function(){for(var a=Sfdc.EntityFeed.getComponentRegistry().getLocalComponentsForExternalFrame(),b=0,c=h.length;b<c;b++){a&&0<a.length&&m().postMessage(h[b],e,{key:"unregisterComponent",components:a});m().postMessage(h[b],e,{key:"unregisterFrame"});for(var d=0;d<w.length;d++){var g=
w[d];if(g.onUnregister)g.onUnregister(h[b])}}for(var k in p)if(p.hasOwnProperty(k)&&(a=p[k]))for(var v in a.listeners)a.listeners.hasOwnProperty(v)&&Sfdc.EntityFeed.getEventBus().removeEventListener(a.namespace,a.eventname,a.listeners[v]);h=[];p={};u={};q=null;w=[]})})});Sfdc.EntityFeed.ENTITY_FEED_PAGE_PREFIX="EntityFeedPage.";Sfdc.EntityFeed.hasFeedBasedLayout=function(d){d=ApiUtils.to15CharId(d);return Sfdc.isDefAndNotNull(Sfdc.EntityFeed.FrameProxies.getFrameContext(Sfdc.EntityFeed.ENTITY_FEED_PAGE_PREFIX+
d))};Sfdc.EntityFeed.onFeedBasedLayoutLoad=function(d){Sfdc.assert(Sfdc.isFunction(d),"Invalid callback!");Sfdc.EntityFeed.FrameProxies.addRegistrationHandler({onRegister:function(c,e){try{if(e&&e.key&&0===e.key.indexOf(Sfdc.EntityFeed.ENTITY_FEED_PAGE_PREFIX)){var a=e.key.substring(Sfdc.EntityFeed.ENTITY_FEED_PAGE_PREFIX.length);d(a)}}catch(g){Sfdc.log("Error in onFeedBasedLayoutLoad callback: "+(g.stack||g))}}})};var F;Sfdc.EntityFeed.getEventBus=function(){F||(F=new O);return F};var G;Sfdc.EntityFeed.getComponentRegistry=
function(){G||(G=new P);return G};Sfdc.EntityFeed.refreshComponents=function(d,c,e,a,g){Sfdc.EntityFeed.getComponentRegistry().refreshComponents(d,c,e,a,g)};Sfdc.EntityFeed.refreshEntityFeedPage=function(d,c,e,a,g){d=ApiUtils.to15CharId(d);if(!Sfdc.EntityFeed.hasFeedBasedLayout(d))return!1;Sfdc.EntityFeed.getComponentRegistry().refreshComponents(d,c,e,a,Q(g));return!0};Sfdc.EntityFeed.addEntityFeedPageRefreshListener=function(d,c){Sfdc.assert(d,"No objectId specified!");Sfdc.assert(!c||Sfdc.isFunction(c),
"Invalid callback!");Sfdc.EntityFeed.getEventBus().addEventListener("entityFeed:object","onAfterUpdate",function(e,a){(!a.source||!a.source.context||!a.source.context.isApiRefreshCall)&&a.objectId===d&&c(a.objectId)})};Sfdc.EntityFeed.removeEntityFeedPageRefreshListener=function(d){Sfdc.assert(!d||Sfdc.isFunction(d),"Invalid callback!");Sfdc.EntityFeed.getEventBus().removeEventListener("entityFeed:object","onAfterUpdate",d)};Sfdc.EntityFeed.registerOnUpdateComponent=function(d,c){var e=Sfdc.get(d),
a={objectId:c.objectId,componentKey:c.componentKey,componentContext:c.componentContext,updateableElementClass:c.updateableElementClass,componentState:c.componentState||{},onUpdateCallback:function(a,b){if(b.componentUpdates&&b.objectId===c.objectId){var d=b.componentUpdates[c.componentKey];if(d){if(c.updateableElementClass){var h=Sfdc.get("."+c.updateableElementClass,e);if(h){var p=h.parentNode;Sfdc.Dom.removeChild(h);Sfdc.Dom.insertHTML(p,d);if(h=Sfdc.get("."+c.updateableElementClass,p)){var h=Sfdc.Resource.getScriptsFromHtml(h),
m=[];Sfdc.Array.map(h,function(a){a.src||m.push(a)});Sfdc.Resource.execScripts(m)}}else Sfdc.log("Component update failed. Element to update '."+c.updateableElementClass+"' is not present in dom ")}if(c.onUpdateCallback)try{c.onUpdateCallback(d,c.componentContext)}catch(q){Sfdc.log("Error in update component callback ["+c.componentKey+"]: "+(q.stack||q))}}}}};Sfdc.EntityFeed.getComponentRegistry().register(a)};Sfdc.EntityFeed.getComponentState=function(d,c){return Sfdc.EntityFeed.getComponentRegistry().getComponentState(d,
c)};Sfdc.onload(function(){A()&&Sfdc.resolve("Sfdc.support.servicedesk.ApiHandler")&&Sfdc.EntityFeed.getEventBus().addEventListener("entityFeed:object","onFullRefresh",function(d,c){var e=Sfdc.support.servicedesk.ApiHandler,a=c.forceFullRefresh?{forceFullRefresh:!0}:{forceFullRefreshOnDirty:!0};e.getFocusedPrimaryTabObjectId().id===c.objectId?e.refreshActivePrimaryTab(a):e.getFocusedSubtabObjectId().id===c.objectId&&e.refreshActiveSubtab(a)})});Sfdc.EntityFeed.postObjectUpdate=function(d,c){chatter.getToolbox().post(J(d,
c))};Sfdc.EntityFeed.getObjectUpdate=function(d,c){chatter.getToolbox().get(J(d,c))};Sfdc.EntityFeed.postWithObjectContext=function(d,c){chatter.getToolbox().post(E(d,c))};Sfdc.EntityFeed.getWithObjectContext=function(d,c){chatter.getToolbox().get(E(d,c))};Sfdc.EntityFeed.post=function(d){chatter.getToolbox().post(d)};Sfdc.EntityFeed.get=function(d){chatter.getToolbox().get(d)}})();
Sfdc.ns("Sfdc.EntityFeed");Sfdc.EntityFeed.toPixels=function(a){return Sfdc.userAgent.isIE7||Sfdc.userAgent.isIE8?a+"px":Sfdc.Units.Pixel.fromInt(a)};Sfdc.EntityFeed.fromPixels=function(a){return Sfdc.userAgent.isIE7||Sfdc.userAgent.isIE8?"auto"===a?0:parseInt(a,10):Sfdc.Units.Pixel.toInt(a)};Sfdc.EntityFeed.hasScrollbarX=function(a){if(a){var g=Sfdc.userAgent.isIE8?a.currentStyle.overflowX:getComputedStyle(a).overflowX;return a.clientWidth<a.scrollWidth&&("auto"===g||"scroll"===g)}return!1};
Sfdc.EntityFeed.SCROLLBAR_WIDTH=function(){var a=Sfdc.Dom.create(document.body||document.documentElement,{style:{overflow:"scroll",visibility:"hidden",width:"100px",height:"100px",position:"absolute"}}),g=a.offsetWidth-a.clientWidth;a.parentNode.removeChild(a);return g}();
Sfdc.provide("Sfdc.EntityFeed.Splitter",new Sfdc.Class({$implements:[Sfdc.IDisposable,Sfdc.IObservable],$constructor:function(a){function g(a){B=!0;var d=Sfdc.Event.getMouseX(a),d=Sfdc.Labels.isRtlPage()?t-d:d-t;null!==p&&(d=d<p?p:d);null!==u&&(d=d>u?u:d);this.notify(Sfdc.EntityFeed.Splitter.EVENT.DRAG,{splitter:this,value:d});Sfdc.Event.preventDefault(a)}function v(a){B&&(B=!1,this.notify(Sfdc.EntityFeed.Splitter.EVENT.DRAG_END,{splitter:this}));Sfdc.un(document,"mousemove",g);Sfdc.un(document,"mouseup",
v)}this.name=a.name||null;var w=a.leftData||null,l=a.rightData||null,x=a.dragElem,p=a.minValue||null,u=a.maxValue||null,t=null,B=!1,q=new Sfdc.Event.EventManager;q.addExpectedEvent(Sfdc.EntityFeed.Splitter.EVENT.DRAG_START);q.addExpectedEvent(Sfdc.EntityFeed.Splitter.EVENT.DRAG);q.addExpectedEvent(Sfdc.EntityFeed.Splitter.EVENT.DRAG_END);q.addExpectedEvent(Sfdc.EntityFeed.Splitter.EVENT.DOUBLE_CLICK);this.toString=function(){return"Splitter: "+Sfdc.JSON.stringify({name:this.name,startPos:t,minValue:p,
maxValue:u})};this.dispose=function(){q&&q.dispose();q=null};this.attach=function(a,d){q.add(x,a,d)};this.detach=function(a,d){q.remove(this,a,d)};this.notify=function(a,d){q.fireEvent(x,a,{data:d})};this.doBeforeDrag=function(){t=null};this.setMinValue=function(a){p=a};this.setMaxValue=function(a){u=a};this.getLeftData=function(){return w};this.getRightData=function(){return l};Sfdc.on(x,"mousedown",function(a){this.notify(Sfdc.EntityFeed.Splitter.EVENT.DRAG_START,{splitter:this});null===t&&(t=Sfdc.Event.getMouseX(a));
Sfdc.on(document,"mouseup",v,this);Sfdc.on(document,"mousemove",g,this);Sfdc.Event.preventDefault(a)},this);Sfdc.on(x,"dblclick",function(){this.notify(Sfdc.EntityFeed.Splitter.EVENT.DOUBLE_CLICK,{splitter:this})},this)},getName:function(){return this.name}}));Sfdc.EntityFeed.Splitter.EVENT={DRAG:"splitter::drag",DRAG_START:"splitter::dragstart",DRAG_END:"splitter::dragend",DOUBLE_CLICK:"splitter::doubleclick"};
Sfdc.provide("Sfdc.EntityFeed.HighlightPanelContainer",new Sfdc.Class({$constructor:function(a){if(null===a.el)Sfdc.log("Invalid DOM element for the highlight panel container: "+a.selector,Sfdc.Logging.LogLevel.ERROR);else if(this.el=a.el,null===a.type)Sfdc.log("Invalid container type: "+a.selector,Sfdc.Logging.LogLevel.ERROR);else{var g=a.index,v=a.type;this.getIndex=function(){return g};this.isCollapsed=function(){return Sfdc.Dom.hasClass(this.el,"efhpCollapsed")};this.isExpanded=function(){return!this.isCollapsed()};
this.getType=function(){return v};this.toString=function(){return"HighlightPanelContainer: "+Sfdc.JSON.stringify({index:g,type:v,state:this.isCollapsed()?"collapsed":"expanded"})}}},getWidth:function(){var a=this.el.offsetWidth,a=a-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(this.el,"paddingLeft"));return a-=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(this.el,"paddingRight"))},setWidth:function(a){this.el.style.width=Sfdc.EntityFeed.toPixels(a)},getComputedWidth:function(){return Sfdc.Dom.getWidth(this.el,
!0)},resetToDefault:function(){Sfdc.Dom.setStyle(this.el,"width",null)},getElement:function(){return this.el},forceAutoWidth:function(){this.el.style.width="auto"}}));Sfdc.EntityFeed.HighlightPanelContainer.TYPE={LEFT:"left",CENTER:"center",RIGHT:"right"};
Sfdc.provide("Sfdc.EntityFeed.HighlightPanel",new Sfdc.Class({$constructor:function(a){function g(){Sfdc.assert(f.isExpanded(),"This method should not be called if the center column is collapsed");null===I&&(I=null===Sfdc.get(".efhpNoDescription",f.getElement()));if(I){var b=C,c;Sfdc.assert("div"===b.tagName.toLowerCase(),"Unsupported reference element \x3c"+b.tagName.toLowerCase()+"\x3e");m||(m=document.createElement("div"),(document.body||document.documentElement).appendChild(m),Sfdc.Dom.setStyles(m,
{position:"absolute",overflow:"hidden"}),Sfdc.Dom.setElementXY(m,[-1E3,-1E3]),Sfdc.Dom.hideByVisibility(m));if(b){c=Sfdc.Dom.getStyles(b,"fontSize fontStyle fontWeight fontFamily textTransform letterSpacing lineHeight wordWrap".split(" "));var e={};if(Sfdc.userAgent.isIE7||Sfdc.userAgent.isIE8){if(c.fontSize){var a=parseFloat(c.fontSize);if(1>a){var h=parseFloat(document.body.currentStyle.fontSize);e.fontSize=a/h+"em"}else e.fontSize=c.fontSize}}else c.fontSize&&(e.fontSize=c.fontSize);c.fontStyle&&
(e.fontStyle=c.fontStyle);c.fontWeight&&(e.fontWeight=c.fontWeight);c.fontFamily&&(e.fontFamily=c.fontFamily);c.textTransform&&(e.textTransform=c.textTransform);c.letterSpacing&&(e.letterSpacing=c.letterSpacing);c.lineHeight&&(e.lineHeight=c.lineHeight);c.wordWrap&&(e.wordWrap=c.wordWrap);Sfdc.Dom.setStyles(m,e);m.style.height=Sfdc.EntityFeed.toPixels(Sfdc.Dom.getHeight(b));m.style.width=Sfdc.EntityFeed.toPixels(Sfdc.Dom.getWidth(b))}c=m;e=C;b=b.title;a=b.replace(/[&]/g,"B");a=a.replace(/[<>]/g,"~");
c.innerHTML=a;if(c.offsetHeight>=c.scrollHeight)b=Sfdc.String.escapeToHtml(b,!1);else{for(var h=1,d=a.length+1,g=h,k;4<d-h;)currentLength=Math.floor((d+h)/2),k=a.substr(0,currentLength)+"\x26hellip;",c.innerHTML=k,c.offsetHeight>=c.scrollHeight?(g=currentLength,h=currentLength+1):d=currentLength-1;b=Sfdc.String.escapeToHtml(b.substr(0,g))+"\x26hellip;"}e.innerHTML=b;c.innerHTML=""}}function v(b){var c=0;b=Sfdc.get(b);var a=!0;do c+=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(b,"marginRight"))||0,
a||(c+=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(b,"borderRightWidth"))||0,c+=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(b,"paddingRight"))||0),b=b.parentNode,a=!1;while(null!==b.parentNode);return c}function w(){Sfdc.assert(s.isExpanded(),"This method should not be called if the right column is collapsed");var b,c=Sfdc.Dom.getWidth(Sfdc.get(".efhpRightContent td:nth-child(1)",n));if(Sfdc.userAgent.isIE7){s.forceAutoWidth();var a=0;Sfdc.each(Sfdc.select(".efhpBody \x3e tbody \x3e tr \x3e td",
n),function(b){Sfdc.Dom.isVisible(b,k)&&(b!==s.getElement()&&(a+=Sfdc.Dom.getWidth(b,!0)),a+=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(b,"paddingLeft")),a+=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(b,"paddingRight")))});var d=Math.max(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,x())-a-Sfdc.Dom.getElementXY(k).x-v(k),h=Math.max(c+J,K),d=Math.max(h,d);b=Math.max(d-c,J)}else b=Math.max(s.getWidth()-c,J);Sfdc.each(Sfdc.select(".efhpLabeledFieldValue",s.getElement()),
function(c){Sfdc.Dom.setStyle(c,"width",Sfdc.EntityFeed.toPixels(b))})}function l(){return r[r.length-1]}function x(){var b=Sfdc.Dom.getStyle(k,"minWidth");return Sfdc.EntityFeed.fromPixels(b)}function p(b,c,a){b=b||k.offsetWidth;c=c||l().getWidth();a=a||0;l().getElement().offsetLeft+K>Math.max(Sfdc.Window.getWindowWidth(),x())?k.style.width=Sfdc.EntityFeed.toPixels(b-c+a+K):k.style.width=null}function u(b,c){var a=c.splitter,d=a.getLeftData(),a=a.getRightData();d.setWidth(z[d.getType()]+c.value);
l()!==a?a.setWidth(z[a.getType()]-c.value):p(O,z[a.getType()],c.value);(d.getType()===Sfdc.EntityFeed.HighlightPanelContainer.TYPE.CENTER||a.getType()===Sfdc.EntityFeed.HighlightPanelContainer.TYPE.CENTER)&&g();a.getType()===Sfdc.EntityFeed.HighlightPanelContainer.TYPE.RIGHT&&w();D&&L()}function t(b,a){var e=a.splitter,d=e.getLeftData(),h=e.getRightData();z={};Sfdc.each(r,function(b){z[b.getType()]=b.getWidth()});O=Sfdc.get(k).offsetWidth;Sfdc.each(r,function(b){l()!==b&&b.setWidth(z[b.getType()])});
e.doBeforeDrag();var g=Sfdc.userAgent.isIE7?2:1,f;f=g+Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(d.getElement(),"paddingLeft"));f+=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(d.getElement(),"paddingRight"));f=Math.max(10,f)-d.getComputedWidth();e.setMinValue(f);l()===h?e.setMaxValue(null):(d=g+Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(h.getElement(),"paddingLeft")),d+=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(h.getElement(),"paddingRight")),d=h.getComputedWidth()-Math.max(10,d),e.setMaxValue(d))}
function B(){k.style.width=null;Sfdc.each(H,function(b){l()===b?b.forceAutoWidth():b.resetToDefault()});f.isExpanded()&&g();s.isExpanded()&&w();E||(E=!0,Sfdc.Cookie.deleteCookie(y),A('Deleted cookie [name: "'+y+'"]',Sfdc.Logging.LogLevel.INFO))}function q(b){B()}function N(){return Sfdc.userAgent.isIE7||Sfdc.userAgent.isIE8||Sfdc.userAgent.isIE9||Sfdc.userAgent.isIE10||Sfdc.userAgent.isIE11}function d(){if(F&&0<F.length&&N()){var b=Sfdc.EntityFeed.toPixels(Sfdc.Dom.getHeight(k));Sfdc.each(Sfdc.select("."+
G,n),function(a){Sfdc.Dom.setStyle(a,"height",b)});Sfdc.each(Sfdc.select("."+G+" div",n),function(a){Sfdc.Dom.setStyle(a,"height",b)})}}function A(b,a,d){null===a&&(a=Sfdc.Logging.LogLevel.INFO);Sfdc.log("[HighlightPanel] "+b,a,d)}function P(){var b=Sfdc.Cookie.getCookie(y);return b?Sfdc.JSON.parse(b):null}function V(){var b=P();if(b){var a;Sfdc.each(r,function(d){l()!==d&&(a="container"+d.getIndex(),b[a]&&d.setWidth(b[a]))});E=!1;A('Restored state from cookie [name: "'+y+'"]',Sfdc.Logging.LogLevel.INFO)}}
function W(){if(!E){var b=P();b||(b={version:X});Sfdc.each(r,function(a){a.isExpanded()&&l()!==a&&(b["container"+a.getIndex()]=a.getWidth())});var a=new Date;a.setDate(a.getDate()+180);Sfdc.Cookie.setCookie(y,Sfdc.JSON.stringify(b),a);A('Saved state to cookie [name: "'+y+'"]',Sfdc.Logging.LogLevel.INFO)}}function Y(){E=!1;W()}function Z(){N()&&(Sfdc.each(Sfdc.select("."+G,n),function(b){Sfdc.Dom.setStyle(b,"height",null)}),Sfdc.each(Sfdc.select("."+G+" div",n),function(b){Sfdc.Dom.setStyle(b,"height",
null)}));f.isExpanded()&&(C.style.height="0px")}function L(){Z();Q();d();f.isExpanded()&&(R(),g())}function $(b){D?l().getType()===s.getType()?setTimeout(function(){p();L();w()},100):l().getType()===f.getType()&&setTimeout(function(){p();L()},100):M?l().getType()===s.getType()?(p(),w()):l().getType()===f.getType()&&(p(),g()):f.isExpanded()&&g()}function R(){Sfdc.assert(f.isExpanded(),"This method should not be called if the center column is collapsed");var b=f.getElement().offsetHeight,b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(f.getElement(),
"paddingTop")),b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(f.getElement(),"paddingBottom")),a=Sfdc.get(".efhpCenterContentBody .efhpRow",f.getElement()),b=b-a.offsetTop,b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"paddingTop")),b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"paddingBottom")),b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"marginBottom")),a=a.parentNode,b=b-a.offsetTop,b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"paddingBottom")),b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,
"marginBottom"));C.style.height=Sfdc.EntityFeed.toPixels(b)}function Q(){var b=Sfdc.Window.getWindowHeight();D&&Sfdc.EntityFeed.hasScrollbarX(window.document.body)&&(b-=Sfdc.EntityFeed.SCROLLBAR_WIDTH);Sfdc.Dom.setStyle(n,"height",Sfdc.EntityFeed.toPixels(b));var a=Sfdc.get(".efhpContainer",n),b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"paddingTop")),b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"paddingBottom")),b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"marginTop")),b=b-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,
"marginBottom"));Sfdc.Dom.setStyle(a,"height",Sfdc.EntityFeed.toPixels(b));b-=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(k,"paddingTop"));b-=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(k,"paddingBottom"));b-=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(k,"marginTop"));b-=Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(k,"marginBottom"));Sfdc.Dom.setStyle(k,"height",Sfdc.EntityFeed.toPixels(b))}function aa(){Sfdc.each(F,function(a){a.dispose()});F=[];H=[];r=[]}function S(){aa();n=Sfdc.get(T);k=Sfdc.get(".efhpBody",
n);U=new Sfdc.EntityFeed.HighlightPanelContainer({el:Sfdc.get(".efhpLeftContent",n),index:0,type:Sfdc.EntityFeed.HighlightPanelContainer.TYPE.LEFT});f=new Sfdc.EntityFeed.HighlightPanelContainer({el:Sfdc.get(".efhpCenterContent",n),index:1,type:Sfdc.EntityFeed.HighlightPanelContainer.TYPE.CENTER});s=new Sfdc.EntityFeed.HighlightPanelContainer({el:Sfdc.get(".efhpRightContent",n),index:2,type:Sfdc.EntityFeed.HighlightPanelContainer.TYPE.RIGHT});H.push(U,f,s);C=Sfdc.get(".efhpDescription",f.getElement());
if(M){Sfdc.each(H,function(a){a.isExpanded()&&r.push(a)});if(1<r.length)for(var a=Sfdc.Template.render('\x3cdiv class\x3d"efhpDragHandle" title\x3d"{{tooltip}}" \x3e\x3cdiv class\x3d"efhpDragHandleDisplay" /\x3e\x3c/div\x3e',{tooltip:LC.getLabel("EntityFeed","HighlightPanelResetSizeTooltip")}),c=0;c<r.length-1;c++){var e=r[c],m=r[c+1],h=Sfdc.Dom.create(null,{className:G},"td",null);Sfdc.Dom.insertHTML(h,a);Sfdc.Dom.getParent(e.getElement()).insertBefore(h,m.getElement());h=new Sfdc.EntityFeed.Splitter({name:e.getType()+
"-"+m.getType()+"-splitter",dragElem:h,leftData:e,rightData:m});F.push(h);h.attach(Sfdc.EntityFeed.Splitter.EVENT.DRAG_START,t);h.attach(Sfdc.EntityFeed.Splitter.EVENT.DRAG,u);h.attach(Sfdc.EntityFeed.Splitter.EVENT.DRAG_END,Y);h.attach(Sfdc.EntityFeed.Splitter.EVENT.DOUBLE_CLICK,q);A("Splitter created between panels "+e.getType().toUpperCase()+" (WEST) and "+m.getType().toUpperCase()+" (EAST).",Sfdc.Logging.LogLevel.INFO)}V();l().forceAutoWidth();p();D&&Q();d()}f.isExpanded()&&(R(),g());s.isExpanded()&&
w();Sfdc.on(window,"resize",$)}var T,n,k,M,D,U,f,s,H=[],r=[],z={},O=null,K=200,J=20,F=[],G="efhpContainerSeparator",m=null,C=null,I=null,y=null,X=1,E=!0;this.refresh=function(){S()};(function(a){Sfdc.assert(null!==a.componentId&&""!==Sfdc.String.trim(a.componentId),"No component id specified");Sfdc.assert(null!==a.cookieName&&""!==Sfdc.String.trim(a.cookieName),"Invalid cookie name:"+a.cookieName);T=a.componentId;y=a.cookieName;D=a.isVerticallyResizable||!1;M=a.isResizable||!1;A("Initialization started",
Sfdc.Logging.LogLevel.INFO);S();A("Initialization successful",Sfdc.Logging.LogLevel.INFO)})(a)}}));
Sfdc.provide("SfdcApp.EntityFeedInlineFilters",function(){function e(){if(c){var h=[];Sfdc.Dom.show(Sfdc.select(".effInline li",g));for(var d=0;d<c.length;d++){var k=c[d];h.push(k.offsetWidth+parseInt(Sfdc.Dom.getStyle(k,"marginLeft"),10)+parseInt(Sfdc.Dom.getStyle(k,"marginRight"),10))}n(c.length,h)}}function n(h,d){if(c)for(var k=g.clientWidth-Sfdc.get(".feedsupermenu",g).offsetWidth,e=0,l=!1,f=0;f<h;f++){var b=c[f],e=e+d[f];if(e<k&&!l){Sfdc.Dom.show(b);var a=m(f);a&&Sfdc.Dom.hideByDisplay(a);Sfdc.Dom.hasClass(b.firstElementChild,
"effSelected")&&(a=LC.getLabel("EntityFeed","MoreMenu"),Sfdc.get("filterDisplay").innerHTML=a,Sfdc.Dom.set(Sfdc.get(".triggerTitleText",Sfdc.get("feedFilterDropDownElement")),"title",a),Sfdc.Dom.removeClass(Sfdc.get("feedFilterDropDownElement"),"effSelected"),Sfdc.Dom.removeClass(Sfdc.get(".inlineContainer #feedFilterDropDownElement .zen-selectArrow"),"verticalBar"))}else if(l=!0,Sfdc.Dom.hasClass(b.firstElementChild,"effSelected")){a=Sfdc.String.trim(Sfdc.get(".effFilterItemLabel",b).innerHTML);
Sfdc.get("filterDisplay").innerHTML=a;Sfdc.Dom.set(Sfdc.get(".triggerTitleText",Sfdc.get("feedFilterDropDownElement")),"title",a);Sfdc.Dom.addClass(Sfdc.get("feedFilterDropDownElement"),"effSelected");Sfdc.Dom.addClass(Sfdc.get(".inlineContainer #feedFilterDropDownElement .zen-selectArrow"),"verticalBar");for(b=f;b<c.length;b++)Sfdc.Dom.hideByDisplay(c[b]),(a=m(b))&&Sfdc.Dom.show(a);n(f,d)}else Sfdc.Dom.hideByDisplay(b),(a=m(f))&&Sfdc.Dom.show(a);a=l;b=Sfdc.get(".sortByLine",g);a?Sfdc.Dom.show(b):
Sfdc.Dom.hideByDisplay(b)}}function m(c){return Sfdc.select("li",Sfdc.get(".feedfilters"))[c]}var g,c;Sfdc.Event.add(window,"resize",function(){e()});return{initialize:function(){g=Sfdc.get(".inlineContainer");c=Sfdc.select(".effInline li",g);var h=Sfdc.select(".facet.facetheader",g)[1],d=document.createElement("div");Sfdc.Dom.addClass(d,"sortByLine");Sfdc.get(".inlineContainer .zen-options").insertBefore(d,h);e()},organizeInlineFilters:function(){e()},expandSearchHideFilters:function(){chatter.getFeed().expandSearchAndHideMenu();
Sfdc.Dom.hideByVisibility(Sfdc.get(".effInline"))},showFilters:function(){Sfdc.Dom.show(Sfdc.get(".effInline"))},shiftFiltersRight:function(){Sfdc.Dom.addClass(Sfdc.get(".inlineContainer"),"shift");e()}}}());
Sfdc.provide("SfdcApp.EntityHtmlFeedItem",function(){var k={isLocalFrameEvent:!0};Sfdc.EntityFeed.getEventBus().addEventListener("chatter:publisher","onAfterFeedLoad",function(b,a){chatter&&chatter.getFeed().getConfig().isCompactFeed&&a&&a.objectId===chatter.getFeed().getConfig().subjectId&&SfdcApp.EntityHtmlFeedItem.showAllImagesForFirstFeedItemFound(2E6,"EmailMessageEvent")},k);Sfdc.EntityFeed.getEventBus().addEventListener("chatter:feed","onAfterNewPostFeedUpdate",function(b,a){if(chatter&&chatter.getFeed().getConfig().isCompactFeed&&
a&&a.feedItem){var c=chatter.getFeed().getFeedItemData(a.feedItem);c.parentid===chatter.getFeed().getConfig().subjectId&&"EmailMessageEvent"===c.feedItemType&&SfdcApp.EntityHtmlFeedItem.showImagesForFeedItem(a.feedItem,0,null)}},k);return{showImage:function(b){var a=Sfdc.Dom.getAttribute(b,"data-src",null),c=Sfdc.select('[data-tagId\x3d"originalImage"]',b),c=null===c?null:c[0];Sfdc.Dom.set(c,"src",a);Sfdc.Dom.replace(c,b);Sfdc.Dom.show(c)},showImagesForFeedItem:function(b,a,c){b=Sfdc.select(".clickImage",
b);for(var d=b.length,e=0;e<d;e++){var g=b[e],f=Number(Sfdc.Dom.getAttribute(g,"data-size",null));if(!Sfdc.isDefAndNotNull(c)||a+f<=c)SfdcApp.EntityHtmlFeedItem.showImage(g),a+=f;else if(a+f>c)break;if(a===c)break}return a},showAllImagesForFirstFeedItemFound:function(b,a){var c=Sfdc.get(".cxfeedcontainer",Sfdc.get("feedwrapper"));if(c)for(var d=0,c=Sfdc.select(".cxfeeditem",c),d=0;d<c.length;d++)if(chatter.getFeed().getFeedItemData(c[d]).feedItemType===a)return d=SfdcApp.EntityHtmlFeedItem.showImagesForFeedItem(c[d],
0,b)},mailTo:function(b,a,c){var d=Sfdc.Dom.getAttribute(b,"data-href",null);if((b=caseInteraction.getEmailPublisher(a))&&!b.isLocked&&confirm(LC.getLabel("EmailMessageFeedItem","MailToConfirm"))){entityFeedPage.getPublisher().expand("efpPublishers_"+a);b.showPublisher();b.clearPublisher();var e,g,f,h;if((a=d.match(/^(\w+):(.*)$/))&&"mailto"==a[1])if(a=a[2].match(/^([^\?]+)\??(.+)?/))e=a[1],a[2]&&((d=a[2].match(/(^|^\?|&)subject=([^&]+)/i))&&(g=decodeURIComponent(d[2].replace(/\+/g," "))),(d=a[2].match(/(^|^\?|&)body=([^&]+)/i))&&
decodeURIComponent(d[2].replace(/\+/g," ")),(d=a[2].match(/(^|^\?|&)cc=([^&]+)/i))&&(f=decodeURIComponent(d[2].replace(/\+/g," "))),(d=a[2].match(/(^|^\?|&)bcc=([^&]+)/i))&&(h=decodeURIComponent(d[2].replace(/\+/g," "))));Sfdc.isDefAndNotNull(e)&&b.setTo(e,!0);Sfdc.isDefAndNotNull(f)&&b.setCc(f,!0);Sfdc.isDefAndNotNull(h)&&b.setBcc(h,!0);Sfdc.isDefAndNotNull(g)?b.setSubject(g,!0):b.setSubject(c,!0)}}}}());
Sfdc.provide("Sfdc.EntityFeed.PublisherApi",function(){function g(c,a,b,d){Sfdc.assert(c,"No contextId specified!");Sfdc.assert(a,"No eventName specified!");Sfdc.assert(!d||Sfdc.isFunction(d),"Invalid callback!");c=ApiUtils.to15CharId(c);try{var e=f[c];if(e){if(e.localHandler){e.localHandler(c,a,b,d);return}if(!Sfdc.isEmpty(e.remoteEndPoints)){var g=e.remoteEndPoints[0];b={messageType:n,contextId:c,eventName:a,payload:b};d&&(l++,m[l]=d,b.callId=l);k(g.frameRef,b);return}}d&&d({success:!1,unavailablePublisher:!0})}catch(h){Sfdc.log("Error calling publisher API: contextId\x3d"+
c+", eventName\x3d"+a+". Exception: "+h.message)}}function k(c,a){Sfdc.EntityFeed.getXDomain().postMessage(c,p,a)}function h(c,a,b){b.messageType=q;b.callId=a.callId;k(c,b)}function r(c,a){if(a.contextId){var b=f[a.contextId];b&&b.localHandler?Sfdc.isDefAndNotNull(privateapi)?privateapi.console.hasEnclosingSubtabFocus(function(d){d.success&&d.hasFocus?b.localHandler(a.contextId,a.eventName,a.payload,function(b){h(c,a,{result:b})}):h(c,a,{windowNotVisible:!0,originalMessage:a})}):h(c,a,{windowNotVisible:!0,
originalMessage:a}):h(c,a,{noLocalHandler:!0,originalMessage:a})}else Sfdc.log("Error: Invalid message format for PublisherAPI.CALL. contextId\x3d"+contextId)}var p="efPublisherApi/",n="call",q="callback",f={},l=0,m={};Sfdc.EntityFeed.FrameProxies.addRegistrationHandler({onRegister:function(c,a){for(var b in f)f.hasOwnProperty(b)&&f[b].localHandler&&k(c,{messageType:"register",contextId:b})},onUnregister:function(c,a){for(var b in f)if(f.hasOwnProperty(b)){var d=f[b];if(!d.localHandler){for(var e=
0;e<d.remoteEndPoints.length;e++)if(d.remoteEndPoints[e].frameRef.equalsAllowUndefinedWindow(c)){d.remoteEndPoints.splice(e,1);break}0===d.remoteEndPoints.length&&delete f[b]}}}});Sfdc.EntityFeed.getXDomain().setMessageHandler(p,function(c,a){if(a.messageType)if("register"===a.messageType)a:{var b=f[a.contextId];if(b){if(!b.localHandler&&b.remoteEndPoints){for(var d=0;d<b.remoteEndPoints.length;d++)if(b.remoteEndPoints[d].frameRef.equals(c))break a;b.remoteEndPoints.push({frameRef:c})}}else f[a.contextId]=
{remoteEndPoints:[{frameRef:c}]}}else if(a.messageType===n)r(c,a);else if(a.messageType===q)a:{b=a.result;if(a.windowNotVisible||a.noLocalHandler){for(var b=a.originalMessage&&f[a.originalMessage.contextId],d=!1,e=0;b&&e<b.remoteEndPoints.length;e++)if(d){k(b.remoteEndPoints[e].frameRef,a.originalMessage);break a}else!d&&b.remoteEndPoints[e].frameRef.equals(c)&&(d=!0);b={success:!1}}if(a.callId&&(d=m[a.callId]))delete m[a.callId],d(b)}else Sfdc.log("Error: Invalid messageType to publisherApi: "+a.messageType)},
!0);return{callApi:function(c,a,b,d){g(c,a,b,d)},selectAction:function(c,a,b){g(c,"publisher.selectAction",a,b)},getSelectedAction:function(c,a){g(c,"publisher.getSelectedAction",{},a)},setActionInputValues:function(c,a,b){g(c,"publisher.setActionInputValues",a,b)},invokeAction:function(c,a,b){g(c,"publisher.invokeAction",a,b)},close:function(c,a,b){g(c,"publisher.close",a,b)},registerLocalEndPoint:function(c,a){var b;(b=ApiUtils.to15CharId(c))&&Sfdc.isFunction(a)?f[b]={localHandler:a}:Sfdc.log("Error failed to register local publisher end point contextId \x3d"+
b+", publisherEndPoint\x3d"+a)}}}());
Sfdc.ns("Sfdc.EntityFeed.SelectPanel");
(function(){var x=".dropdownOption .dropdownOptionItem",r=".dropdownContainer",d={};SelectPanelComponent=function(b){function e(a,b){Ext.isEmpty(a)||(a.setVisibilityMode(Ext.Element.DISPLAY),a.setVisible(b))}function f(a){var b=Sfdc.get(a);b&&(Sfdc.Dom.getParent(b,r)?(p(!0),d(a)):p(!1))}function d(a){if("DropDown"===b.selectStyle){var c=Sfdc.get(b.componentId),c=Sfdc.get(".dropdownOptionItem .optionLabel",c);a=Sfdc.get(a);a=Sfdc.get(".optionLabel",a);Sfdc.Dom.setText(c,Sfdc.Dom.getText(a))}}function u(a){var b=
Sfdc.get(".dropdownOption",a),h=a.offsetWidth,h=h-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"paddingLeft")),h=h-Sfdc.EntityFeed.fromPixels(Sfdc.Dom.getStyle(a,"paddingRight")),h=h-b.offsetWidth-7,e=Sfdc.get(".optionContainer",a),d=Sfdc.get(r,a),g=Sfdc.select("li",d),k,q;k=0;for(len=g.length;k<len;k++)q=g[k],d.removeChild(q),e.insertBefore(q,b);var g=Sfdc.select(".optionContainer \x3e li",a),l=0,p=!1,m;k=0;for(len=g.length;k<len;k++)q=g[k],0>q.className.indexOf("dropdownOption")&&(m=!0,p?m=!1:
(l+=q.offsetWidth,l>h&&(m=!1,p=!0)),m||(e.removeChild(q),d.appendChild(q)));p?(Sfdc.Dom.show(b),d.style.right="auto",d.getBoundingClientRect().right>a.getBoundingClientRect().right&&(d.style.right="0")):Sfdc.Dom.hideByVisibility(b);f(n)}function B(a){for(var c=a.query(".optionContainer")[0],h=Ext.get(c).query("li"),l=Ext.get(a.query(r)[0]),v=0,m=h.length;v<m;v++){var k=h[v];0>k.className.indexOf("dropdownOption")&&(c.removeChild(k),l.appendChild(k),k=Sfdc.get(".optionItem",k),Sfdc.Dom.hasClass(k,
"selected")&&d(k.id))}c=Ext.get(a.query(".dropdownOption")[0]);e(c,!0);f(n);if(b.dropDownToggleEnabled&&0<h.length&&(h=Sfdc.get(".dropdownOption .dropDownToggle",a.dom)))Sfdc.on(h,"click",y),a=Sfdc.get(".dropdownOption .optionLabel",a.dom),Sfdc.on(a,"click",y)}function y(a){var c=Sfdc.get(r,Sfdc.get(b.componentId)),h=Sfdc.select(".optionItem",c),c=Sfdc.get(".optionItem.selected",c),d=0;if(c)for(var e=0,f=h.length-1;e<f;e++)if(h[e]===c){d=e+1;break}z.selectOption(h[d].id);Sfdc.Event.stopPropagation(a)}
function p(a){var c=Ext.get(b.componentId);(c=Ext.get(c.query(x)[0]))&&m(c.id,a)}function A(a){var c=Sfdc.get(b.componentId);(c=Sfdc.get(r,c))&&(a?Sfdc.Dom.show(c):Sfdc.Dom.hideByVisibility(c))}function m(a,b){var d=Sfdc.get(a);d&&(b?Sfdc.Dom.addClass(d,"selected"):Sfdc.Dom.removeClass(d,"selected"))}function s(a,b){a&&Sfdc.each(a,function(a,d){var f=Ext.get(a);e(f,b)})}var z=this,n,l=!1,t=!1,w=0;this.init=function(){var a=Ext.get(b.componentId);n=a.query(".selected")[0].id;if("TopTabs"===b.selectStyle){u(a.dom);
w=Sfdc.Dom.getWidth(a.dom,!0);var c=function(){var c=Sfdc.Dom.getWidth(a.dom,!0);if(c!==w){Sfdc.Dom.isVisible(a.dom,!0)?u(a.dom):t=!0;if(b.onResizeScript)b.onResizeScript();w=c}};Sfdc.onload(function(){c();Sfdc.Event.add(window,"resize",c);Sfdc.Dom.isVisible(a.dom,!0)||(t=!0)})}else"DropDown"===b.selectStyle&&B(a);Sfdc.Event.add(document.body,"click",function(a){var c=Sfdc.get(b.componentId);if((c=null!==c?Sfdc.get(x,c):null)&&Sfdc.Dom.isVisible(c))a=Sfdc.Event.getEventTarget(a),!Sfdc.Dom.isMatch(a,
".dropdownOptionItem")&&!Sfdc.Dom.getParent(a,".dropdownOptionItem")&&l&&(l=!1,A(!1),Sfdc.Dom.getParent(a,r)||p(!1),0>a.className.indexOf("optionItem")&&n&&m(n,!0))})};this.getId=function(){return b.componentId};this.onShow=function(){t&&(t=!1,u(Sfdc.get(b.componentId)))};this.showOptionsDropdown=function(){l=!l;p(l);A(l)};this.hidePanel=function(a){a=b.options[a];var c=Ext.get(a.panelId);e(c,!1);s(a.hiddenPanels,!0);s(a.visiblePanels,!1);a.cssClass&&(c=Sfdc.get(b.componentId),Sfdc.Dom.removeClass(c,
a.cssClass))};this.showPanel=function(a){var c=b.options[a],d=Ext.get(c.panelId);e(d,!0);f(a);a=Sfdc.get(b.componentId);c.cssClass&&Sfdc.Dom.addClass(a,c.cssClass);b.stateCookie&&(c.selectionKey?Sfdc.Cookie.setCookie(b.stateCookie,c.selectionKey):Sfdc.Cookie.deleteCookie(b.stateCookie));if(c.onShowScript)c.onShowScript();s(c.hiddenPanels,!1);s(c.visiblePanels,!0)};this.selectOption=function(a){if(b.options[a]){this.hidePanel(n);m(n,!1);this.showPanel(a);m(a,!0);if(b.onSelectOptionScript)b.onSelectOptionScript(a);
n=a}};this.isOptionSelected=function(a){return a==n};this.getOptionByPanel=function(a){for(var c in b.options)if(b.options.hasOwnProperty(c)&&b.options[c].panelId==a)return c;return null};this.getOptionByName=function(a){for(var c in b.options)if(b.options.hasOwnProperty(c)&&b.options[c].name==a)return c;return null};this.hasOption=function(a){return b.options.hasOwnProperty(a)};this.getOptionName=function(a){return(a=b.options[a])?a.name:null};this.getLastSelectedOptionId=function(){return n};if(window.Perf&&
window.Perf.enabled){var C=this.selectOption;this.selectOption=function(a){if(b.options[a]){var c=b.options[a].panelId;Sfdc.EntityFeed.perfMark("selectMenuItem: "+c);C.call(z,a);Sfdc.EntityFeed.perfEndMark("selectMenuItem: "+c)}}}};Sfdc.EntityFeed.SelectPanel.init=function(b){if(b){var e=new SelectPanelComponent(b);e.init();d[b.componentId]=e}};Sfdc.EntityFeed.SelectPanel.selectOptionById=function(b){for(var e in d)if(d.hasOwnProperty(e)){var f=d[e];if(f.hasOption(b)){f.selectOption(b);break}}};Sfdc.EntityFeed.SelectPanel.selectOptionByPanel=
function(b){for(var e in d)if(d.hasOwnProperty(e)){var f=d[e],g=f.getOptionByPanel(b);if(g){f.selectOption(g);break}}};Sfdc.EntityFeed.SelectPanel.getOptionByPanel=function(b){for(var e in d)if(d.hasOwnProperty(e))return d[e].getOptionByPanel(b)};Sfdc.EntityFeed.SelectPanel.getOptionByName=function(b,e){var f=d[b];return f?f.getOptionByName(e):null};Sfdc.EntityFeed.SelectPanel.selectOptionByName=function(b,e){var f=d[b];if(f){var g=f.getOptionByName(e);if(g)return f.selectOption(g),!0}return!1};Sfdc.EntityFeed.SelectPanel.getSelectedOptionName=
function(b){return(b=d[b])?b.getOptionName(b.getLastSelectedOptionId()):null};Sfdc.EntityFeed.SelectPanel.isOptionPanelSelected=function(b){for(var e in d)if(d.hasOwnProperty(e)){var f=d[e],g=f.getOptionByPanel(b);if(g)return f.isOptionSelected(g)}return!1};Sfdc.EntityFeed.SelectPanel.isOptionPanelSelectedByName=function(b,e){var f=d[b];if(f){var g=f.getOptionByName(e);if(g)return f.isOptionSelected(g)}return!1};Sfdc.EntityFeed.SelectPanel.showOptionsDropdown=function(b){(b=d[b])&&b.showOptionsDropdown()};
Sfdc.EntityFeed.SelectPanel.onShow=function(b){if(b=d[b])b.onShow()};Sfdc.EntityFeed.SelectPanel.getComponent=function(b){return d[b]};Sfdc.EntityFeed.SelectPanel.selectComponentWithOption=function(b){for(var e in d)if(d.hasOwnProperty(e)){var f=d[e].getOptionByName(b);if(f){d[e].selectOption(f);break}}}})();
Sfdc.ns("Sfdc.EntityFeedPage");
Sfdc.EntityFeedPage=function(){function n(){var f=Sfdc.EntityFeed.FrameProxies.getCurrentFrameContext();return f?f.objectId:null}function p(){return Sfdc.EntityFeed.getXDomain()}function w(){function f(d,b){function m(){if(b.isCompactFeed){var a=chatter.getFeed().isCompactFeedFullyExpanded(),m=Sfdc.select(".expandStateToggle",Sfdc.get(d));Sfdc.each(m,function(b){a?Sfdc.Dom.addClass(b,"fullyExpanded"):Sfdc.Dom.removeClass(b,"fullyExpanded")})}}function k(a){var k=chatter.getFeed();if(a.innerContent){k=
Sfdc.get(d);if(b.isDropDown||b.isInline){var c=Sfdc.get(".feedUpdateContainer",k);a=a.innerContent;var e=c.parentNode;e.removeChild(c);Sfdc.Dom.insertHTML(e,a)}else a=a.innerContent,Sfdc.Dom.isVisible(k)||(c=Sfdc.Dom.create(),Sfdc.Dom.insertHTML(c,a),Sfdc.Dom.setStyle(c.firstChild,"display","none"),a=c.innerHTML),c=k.parentNode,c.removeChild(k),Sfdc.Dom.insertHTML(c,a),k=Sfdc.get(d);Sfdc.Resource.execScripts(Sfdc.Resource.getScriptsFromHtml(k))}else{if(a.newFeedItems)for(var s=chatter.getEventBus(),
c=0,e=a.newFeedItems.length;c<e;c++)s.fireEvent("chatter:publisher","onAfterUpdateStatus",{json:a.newFeedItems[c]});if(a.deletedFeedItems){c=0;for(e=a.deletedFeedItems.length;c<e;c++)(s=Sfdc.get(a.deletedFeedItems[c]))&&k.removeItemElement(s)}}m()}l.registerOnUpdateComponent(b.parentId,{objectId:b.objectId,componentKey:b.componentKey,componentContext:b.componentContext,onUpdateCallback:function(d){var a=chatter.getFeed();a.getConfig()&&a.getConfig().subjectId===b.objectId&&k(d)}});if(b.isCompactFeed){var c=
function(b,d){m()},e=Sfdc.EntityFeed.getEventBus(),f={isLocalFrameEvent:!0};Sfdc.each(a,function(b){e.addEventListener(b.ns,b.name,c,f)})}this.getConfig=function(){return b};this.getDomId=function(){return d};this.renderFeed=function(){var a=Sfdc.get(d),c=new LoadingScreen(a,LC.getLabel("Global","loading"));c.show();l.postWithObjectContext(b.objectId,{url:"/entityfeed/"+b.objectId+"/feed;edit",params:{objectId:b.objectId,filtername:b.filter,sortby:b.sort,searchStr:b.searchString,str:b.searchString},
success:function(d,a){k(Sfdc.JSON.parse(a.updates));b.searchString?(chatter.getFeed().expandSearchAndShowMenu(b.searchString),b.isInline&&SfdcApp.EntityFeedInlineFilters.shiftFiltersRight()):chatter.getFeed().closeSearchBox();if(b.isDropDown){var m=Sfdc.get("filterDisplay");if(m&&b.filter){var e=Sfdc.String.escapeToHtml(Sfdc.Dom.getText(Sfdc.get(b.filter)));Sfdc.Dom.updateHTML(m,e)}}c.hide()},failure:function(b,d){c.hide()}})};this.filterFeed=function(d,a){var c;b.isDropDown||(c=Sfdc.Dom.getParent(d,
".entityFeedFilter"));c=Sfdc.select(".effFilterItem",c);Sfdc.Array.forEach(c,function(b,a){b==d?Sfdc.Dom.addClass(b,"effSelected"):Sfdc.Dom.removeClass(b,"effSelected")});c=Sfdc.select(".entityFeedFilter .floatableContainer");Sfdc.Array.forEach(c,function(b){b&&Sfdc.Dom.hasClass(b,"scrollFixed")&&(Sfdc.Dom.removeClass(b,"scrollFixed"),window.scrollTo(0,0))});b.filter=a;this.renderFeed()};this.sortFeed=function(d){b.sort=d;this.renderFeed()};this.searchFeed=function(d){b.searchString=d;b.findInFeedType=
b.filter;this.renderFeed()};this.removeFeedItemElement=function(b){chatter.getFeed().removeItemElement(b)};this.clearSearch=function(){b.searchString?(b.searchString=null,b.filter=b.findInFeedType,b.findInFeedType=null,this.renderFeed()):chatter.getFeed().closeSearchBox()}}function g(d){d=Sfdc.select(".entityFeedFilter .floatableContainer");Sfdc.each(d,function(b){if((b=Ext.get(b))&&b.isVisible(!0)){var d=window.pageYOffset;d||(d=Ext.query("html")[0].scrollTop);for(var a=b.parent().dom,c=0;a.offsetParent;)c+=
a.offsetTop,a=a.offsetParent;c<d?b.addClass("scrollFixed"):b.removeClass("scrollFixed")}})}function h(d){Sfdc.Event.getEventTarget(d,".entityFeedFilterDropDown")||(d=Sfdc.select(".entityFeedFilterDropDown"),Sfdc.Array.forEach(d,function(b){e.hideFilter(b)}))}var a=[{ns:"chatter:feed",name:"onAfterExpandedStateChange"},{ns:"chatter:feed",name:"onAfterFeedRefresh"},{ns:"chatter:feed",name:"onAfterNewPostFeedUpdate"},{ns:"chatter:feed",name:"onAfterDeleteFeedItem"},{ns:"chatter:feed",name:"onAuxBodyChange"},
{ns:"chatter:FeedSort",name:"onAfterSortFeed"},{ns:"chatter:feed",name:"onAfterShowMoreFeedItems"}],c=[],e=this;l.getEventBus().addEventListener("entityFeed:object","onAfterUpdate",function(d,b){var a=chatter.getFeed();0===c.length&&(a.getConfig()&&a.getConfig().subjectId===b.objectId&&b.feedChanges)&&a.refresh({params:{subjectId:b.objectId},feedType:a.getConfig().feedType})});this.onFeedSearchClick=function(d,b){b&&Sfdc.Event.preventDefault(b);var a=this.getEntityFeedComponentByObjectId(d),c=Sfdc.get(".feedSearchTerm").value;
Sfdc.String.trim(c||"")?a&&a.searchFeed(c):chatter.getFeed().clearSearch()};this.onFeedClearSearchClick=function(d){d=this.getEntityFeedComponentByObjectId(d);d.clearSearch();d.getConfig().isInline&&SfdcApp.EntityFeedInlineFilters.showFilters()};this.initEntityFeed=function(d,b){var a=Ext.id(d);if(!c[a]){var e=new f(a,b);c[a]=e;c.push(e)}};this.getEntityFeedComponent=function(a){a=Ext.get(a);a.hasClass("entityFeed")||(a=a.parent(".entityFeed"));return null!==a?c[a.id]:null};this.getEntityFeedComponentByObjectId=
function(a){for(var b=0,e=c.length;b<e;b++)if(c[b].getConfig().objectId==a)return c[b];return null};this.forEachFeedComponent=function(a){for(var b=0,e=c.length;b<e;b++)a(c[b])};this.onFeedFilterClick=function(a,b,c){(b=this.getEntityFeedComponentByObjectId(b))&&b.filterFeed(a,c)};this.initFeedFilter=function(){Ext.EventManager.on(window,"scroll",g)};this.onFeedSortClick=function(a,b){var c=this.getEntityFeedComponent(a);c&&c.sortFeed(b)};this.renderFilter=function(a){a=Sfdc.get(".effListDropDown",
a);Sfdc.Dom.show(a);Sfdc.on(document.body,"click",h)};this.hideFilter=function(a){a=Sfdc.get(".effListDropDown",a);Sfdc.Dom.hideByDisplay(a);Sfdc.un(document.body,"click",h)}}function x(){function f(a){function c(b){b==k.getLastSelectedOptionId()&&a.collapsedPanelId&&!Sfdc.Dom.isVisible(Sfdc.get(a.collapsedPanelId),!0)?(k.hidePanel(b),e(b)):d(b)}function e(b){b=a.options[b];var d=Sfdc.get(a.collapsedPanelId);Sfdc.get(".publishertextarea",d).value=LC.getLabel("EntityFeed","AutocollapseGhostLabel",
b.label);l.getUtil().setElementDisplay(Ext.get(a.collapsedPanelId),!0);b=Sfdc.get("autocollapseCollapse_"+a.entityId);d=Sfdc.get("autocollapseExpand_"+a.entityId);Sfdc.Dom.hideByDisplay(b);Sfdc.Dom.setStyle(d,"display","block")}function d(b){k.showPanel(b);if(a.collapsedPanelId){Sfdc.Dom.hideByDisplay(Sfdc.get(a.collapsedPanelId));var d=Sfdc.get("autocollapseCollapse_"+a.entityId),c=Sfdc.get("autocollapseExpand_"+a.entityId);Sfdc.Dom.setStyle(d,"display","block");Sfdc.Dom.hideByDisplay(c)}d=a.options[b];
d.focusScript&&d.focusScript();b=a.options[b];l.getEventBus().fireEvent("entityFeed:publisher","onShow",{objectId:a.entityId,name:b.name})}function b(b,d){d.json.subjectId==a.entityId&&("FeedItem.RypplePost"===a.options[k.getLastSelectedOptionId()].name?setTimeout(this.collapse,25):this.collapse())}function m(b,a,d,c){var e=function(b){Sfdc.isFunction(c)&&(b=b||{},b.success=Sfdc.isDefAndNotNull(b.success)?b.success:!0,c(b))};try{var k;if("publisher.selectAction"===a){l.views.selectFeedView(b);b="efpPublishers_"+
b;var m=d.actionName;d={success:!0};l.getPanelSelectors().isOptionPanelSelectedByName(b,m)?l.getPublisher().getComponentByPanelSelectorComponent(b).expand():l.getPanelSelectors().selectOptionByName(b,m)||(d.success=!1,d.unavailableAction=!0);e(d)}else if("publisher.getSelectedAction"===a){var g=Sfdc.EntityFeed.SelectPanel.getSelectedOptionName("efpPublishers_"+b);e({success:Sfdc.isDefAndNotNull(g),actionName:g})}else if("publisher.setActionInputValues"===a)if(k=f[d.actionName])k.onSetInputValues(d,
e);else e({success:!1,unavailableAction:!0});else if("publisher.invokeAction"===a)if(k=f[d.actionName])k.onInvoke(d,e);else e({success:!1,unavailableAction:!0});else"publisher.close"===a?chatter.getFeed().close({params:{subjectId:b}},{refresh:d.refresh,refreshTarget:l.getApi(),refreshPayload:d,feed:d.feed,successMessage:d.successMessage}):(Sfdc.log("Error: Invalid event name for publisher API call"),e({success:!1,internalError:!0}))}catch(h){Sfdc.log("Error performing publisher API call: "+(h&&h.message?
h.message:"Unknown error")),e({success:!1,internalError:!0})}}var k,f={};this.init=function(){a.onSelectOptionScript=Sfdc.Function.bind(c,this);l.getPanelSelectors().init(a);k=l.getPanelSelectors().getComponent(a.componentId);a.autocollapse&&chatter.getEventBus().addEventListener("chatter:publisher","onAfterQuickActionSuccess",Sfdc.Function.bind(b,this));Sfdc.EntityFeed.PublisherApi.registerLocalEndPoint(a.entityId,function(b,a,d,c){m(b,a,d,c)});Sfdc.resolve("Sfdc.EntityFeed.QuickAction")&&Sfdc.EntityFeed.QuickAction.register({actionName:"FeedItem.TextPost",
actionId:"TextPost",handlerId:"TextPost",formId:null,contextId:a.entityId})};this.getObjectId=function(){return a.entityId};this.registerActionHandler=function(b){!b||!b.actionName||!Sfdc.isFunction(b.onInvoke)||!Sfdc.isFunction(b.onSetInputValues)?Sfdc.log("Error: Invalid arguments to registerActionHandler: "+b.actionName):f[b.actionName]?Sfdc.log("Error: Action handler already registered: "+b.actionName):f[b.actionName]=b};this.collapse=function(){var b=k.getLastSelectedOptionId();k.hidePanel(b);
e(b)};this.expand=function(){d(k.getLastSelectedOptionId())};this.getPanelSelectorComponent=function(){return k}}var g=this,h={};this.init=function(a){if(a){var c=g.getComponentByObjectId(a.entityId);c||(c=new f(a),h[a.componentId]=c,c.init())}};this.registerActionHandler=function(a,c){var e=g.getComponentByObjectId(a);e&&e.registerActionHandler(c)};this.selectActionByPanel=function(a){l.getPanelSelectors().isOptionPanelSelected(a)?l.getPublisher().getComponentByPanel(a).expand():l.getPanelSelectors().selectOptionByPanel(a)};
this.isPanelSelected=function(a){return l.getPanelSelectors().isOptionPanelSelected(a)};this.fireResizeEvent=function(a){l.getEventBus().fireEvent("entityFeed:publisher","onResize",{objectId:a})};this.getPanelWrapperId=function(a){return"efpPublisherWrapper_"+a};this.collapse=function(a){(a=h[a])&&a.collapse()};this.expand=function(a){(a=h[a])&&a.expand()};this.getComponent=function(a){return h[a]};this.getComponentByObjectId=function(a){for(var c in h)if(h.hasOwnProperty(c)){var e=h[c];if(e.getObjectId()===
a)return e}return null};this.getComponentByPanel=function(a){for(var c in h)if(h.hasOwnProperty(c)){var e=h[c];if(e.getPanelSelectorComponent().getOptionByPanel(a))return e}return null};this.getComponentByPanelSelectorComponent=function(a){for(var c in h)if(h.hasOwnProperty(c)){var e=h[c];if(e.getPanelSelectorComponent().getId()==a)return e}return null}}function y(f,g,h){var a=this;this.drawerHandleEvent=function(a,e,d){a=Sfdc.get(f);e=Sfdc.get(g);d=Sfdc.get(".efpDrawerIcon",a);if(Sfdc.Dom.isVisible(e))Sfdc.Dom.hideByDisplay(e),
Sfdc.Dom.removeClass(d,"efpdExpandedIcon"),Sfdc.Dom.addClass(d,"efpdCollapsedIcon"),Sfdc.Dom.set(d,"title",LC.getLabel("EntityFeed","Expand"));else if(Sfdc.Dom.show(e),Sfdc.Dom.removeClass(d,"efpdCollapsedIcon"),Sfdc.Dom.addClass(d,"efpdExpandedIcon"),Sfdc.Dom.set(d,"title",LC.getLabel("EntityFeed","Collapse")),h.onOpenCallback)h.onOpenCallback(a)};this.drawerKeyHandler=function(c,e,d){(13==c.keyCode||32==c.keyCode)&&a.drawerHandleEvent(c,e,d)};this.drawerClickHandler=function(c,e,d){a.drawerHandleEvent(c,
e,d)};(function(){var c=Sfdc.get(f);Sfdc.get(g);var e=Sfdc.get(c,"div");Sfdc.on(e,"click",a.drawerClickHandler);c=Sfdc.get(".efpDrawerIcon",c);Sfdc.on(c,"keypress",a.drawerKeyHandler)})()}function z(){var f={};this.init=function(g){if(g){var h=new Sfdc.EntityFeed.HighlightPanel(g);f[g.componentId]=h}};this.onUpdate=function(g){f[g].refresh()}}function A(){this.setElementDisplay=function(f,g){Ext.isEmpty(f)||(f.setVisibilityMode(Ext.Element.DISPLAY),f.setVisible(g))}}var B="undefined"!=typeof window.postMessage;
window.location.href.lastIndexOf("isdtp\x3dvw");var l=this;this.getEventBus=function(){return Sfdc.EntityFeed.getEventBus()};this.refreshComponents=function(f,g,h,a,c){Sfdc.EntityFeed.getComponentRegistry().refreshComponents(f,g,h,a,c)};this.registerOnUpdateComponent=function(f,g){Sfdc.EntityFeed.registerOnUpdateComponent(f,g)};this.getComponentState=function(f,g){return Sfdc.EntityFeed.getComponentState(f,g)};var C=new function(){function f(a,b){Sfdc.EntityFeed.getComponentRegistry().refreshComponents(ApiUtils.to15CharId(b.objectId),
b.refreshFields,b.refreshRelatedLists,b.refreshFeed,{context:{apiSource:a.name},success:function(){var c=b.method;p().postMessage(a,h,{method:c,fromApi:!0,result:!0})},failure:function(){var c=b.method;p().postMessage(a,h,{method:c,fromApi:!0,result:!1})}})}function g(d,b,c){var e=a[d];c={frameRef:b,callback:c};if(e){d=0;for(var f=e.length;d<f;d++)if(b===e[d].frameRef||"function"===typeof e[d].frameRef.equals&&e[d].frameRef.equals(b))return;e.push(c)}else a[d]=[c]}var h="entityFeedApi/",a={},c={},
e=this;this.refresh=function(a,b){Sfdc.EntityFeed.getComponentRegistry().refreshComponents(a,b.objectFields,b.objectRelatedLists,b.feed)};this.registerEventListener=function(a,b){Sfdc.canvas.parent.subscribe({name:a,onData:b})};this.onRefresh=function(a,b){g("onObjectUpdate",a,function(a){var d={};a.fieldsUpdated&&(d.objectFields={});a.relatedListsUpdated&&(d.objectRelatedLists={});a.feedUpdated&&(d.feed=!0);b(d)})};this.reloadVisualForceFrame=function(a,b){var c={url:"/entityfeed/"+a,params:{updateTypes:Sfdc.JSON.stringify(["InlineApexPageImpl."+
b])}};Sfdc.EntityFeed.getObjectUpdate(a,c)};this.hasBeenPartiallyUpdated=function(a){return Sfdc.isDefAndNotNull(c[a])};B&&(p().setConnectionHandler(h,function(a,b){b.toApi&&("connect"===b.method?(!b.objectId||ApiUtils.to15CharId(b.objectId)===n())&&p().postMessage(a,h,{method:"connect",fromApi:!0,objectId:n()}):Sfdc.log("Error: Invalid connect key: "+b.key))}),p().setMessageHandler(h,function(d,b){if(b.toApi)if(b.method&&0===b.method.indexOf("refreshObject"))f(d,b);else if("reloadFrame"===b.method)e.reloadVisualForceFrame(ApiUtils.to15CharId(b.objectId),
b.frameName);else if("onObjectUpdate"===b.method)g(b.method,d);else if("disconnect"===b.method)for(var c in a){if(a.hasOwnProperty(c)){var k=a[c];if(k)for(var h=0,l=k.length;h<l;h++)if(d===k[h].frameRef||"function"===typeof k[h].frameRef.equalsAllowUndefinedWindow&&k[h].frameRef.equalsAllowUndefinedWindow(d)){k.splice(h,1);break}}}else Sfdc.log("Error: Invalid message key: "+b.method)},!0),l.getEventBus().addEventListener("entityFeed:object","onAfterUpdate",function(d,b){var e=b.objectId,f=b.fieldChanges,
g=b.relatedListsChanges,l=b.feedChanges,n=b.source.context;if(f||g||l)if(c[e]=!0,e={method:"onObjectUpdate",objectId:e,fieldsUpdated:f||!1,relatedListsUpdated:g||!1,feedUpdated:l||!1},f=a[e.method]){e.fromApi=!0;g=0;for(l=f.length;g<l;g++){var q=f[g],r="string"===typeof q.frameRef?q.frameRef:q.frameRef.name;if(!n||!n.apiSource||n.apiSource!==r)q.callback?q.callback(e):"object"===typeof q.frameRef&&p().postMessage(q.frameRef,h,e)}}}),Sfdc.onload(function(){var a=Sfdc.EntityFeed.FrameProxies.getCurrentFrameContext();
a&&a.feedLayout&&p().connect(h,{method:"available",fromApi:!0,objectId:n()})}),Sfdc.on(window,"unload",function(){a={}}))};this.getApi=function(){return C};this.postObjectUpdate=function(f,g){Sfdc.EntityFeed.postObjectUpdate(f,g)};this.getObjectUpdate=function(f,g){Sfdc.EntityFeed.getObjectUpdate(f,g)};this.postWithObjectContext=function(f,g){Sfdc.EntityFeed.postWithObjectContext(f,g)};this.getWithObjectContext=function(f,g){Sfdc.EntityFeed.getWithObjectContext(f,g)};this.post=function(f){Sfdc.EntityFeed.post(f)};
this.get=function(f){Sfdc.EntityFeed.get(f)};this.views=new function(){function f(c){this.getName=function(){return c.viewName};c.viewName===a&&(this.onAfterUpdate=function(a,b){var c=Sfdc.JSON.parse(b),e=Sfdc.get("efDetails_"+c.objectId);if(e&&(c=Sfdc.JSON.parse(a))){var f=Sfdc.get(".efdRLHover",e);f&&c.rlhovers&&Sfdc.Dom.updateHTML(f,c.rlhovers,!0);(f=Sfdc.get(".efdFields",e))&&c.fields&&Sfdc.Dom.updateHTML(f,c.fields,!0);if((f=Sfdc.get(".efdIled",e))&&c.iled)Sfdc.resolve("sfdcPage.revert")&&sfdcPage.revert(),
Sfdc.Dom.updateHTML(f,c.iled,!0);if((e=Sfdc.get(".efdRelatedLists",e))&&c.rl)sfdcPage.relatedLists=[],sfdcPage.relatedListsById={},Sfdc.Dom.updateHTML(e,c.rl,!0),sfdcPage.relatedListPanel&&sfdcPage.relatedListPanel.addListsToPanel&&sfdcPage.relatedListPanel.addListsToPanel(!0)}})}function g(a,d){var b=c[a];return b?b[d]:null}function h(a,c){g(a,c)&&Sfdc.EntityFeed.SelectPanel.selectOptionByName("efpViews_"+a,c)}var a="DetailsView",c={};this.initView=function(a){Sfdc.assert(a&&a.objectId&&a.viewName);
var d=c[a.objectId];d||(d={},c[a.objectId]=d);d[a.viewName]=new f(a)};this.selectFeedView=function(a){h(a,"FeedView")};this.selectDetailView=function(c){h(c,a)};this.getDetailView=function(c){return g(c,a)}};var r;this.getEntityFeed=function(){r||(r=new w);return r};var t;this.getPublisher=function(){t||(t=new x);return t};this.getPanelSelectors=function(){return Sfdc.EntityFeed.SelectPanel};this.initDrawer=function(f,g){var h=Sfdc.get(".efpDrawerHeader",f),a=Sfdc.get(".efpDrawerContent",f);new y(h,
a,g)};var u;this.getHighlightPanels=function(){u||(u=new z);return u};var v;this.getUtil=function(){v||(v=new A);return v};this.isElementInFeedLayout=function(f){return null!==Sfdc.Dom.getParent(f,".entityFeedLayout")}};var entityFeedPage=new Sfdc.EntityFeedPage;
Sfdc.ns("Sfdc.EntityFeed.QuickAction");
(function(){function e(a,c){return{isSingleInput:a,allowedTags:c}}function u(a,c,b){if(c.tagName===f.Input){if("hidden"!==c.getAttribute("type")){if("checkbox"===c.getAttribute("type"))return c.checked=!0===b.value,!0;if("text"===c.getAttribute("type"))return Sfdc.EntityFeed.QuickAction.insertIntoTextField(c,b.value,b.insertType);c.value=b.value;return!0}}else{if(c.tagName===f.TextArea)return"undefined"!==typeof CKEDITOR&&CKEDITOR.instances[c.name]?Sfdc.EntityFeed.QuickAction.insertIntoRichTextField(c,b.value,
b.insertType):Sfdc.EntityFeed.QuickAction.insertIntoTextField(c,b.value,b.insertType);if(c.tagName===f.Select)return p(c,b.value)}return!1}function v(a,c,b,d){if("EntityId"===a){if(d.value)if(1===c.length&&c[0].tagName===f.Div&&c[0].id){if(b=c[0].id.lastIndexOf("_top"),-1!==b)return b=c[0].id.substring(0,b),d.type&&(c=Sfdc.get(b+"_mlktp"),!p(c,d.type,!0))?!1:s(Sfdc.get(b),d.value,d.id)}else{if(1===b.length&&b[0].tagName===f.Input)return s(b[0],d.value,d.id);if(1===b.length&&b[0].tagName===f.Select)return p(b[0],
d.value)}}else if("MultiEnum"===a&&Sfdc.isArray(d.values)&&1===b.length&&b[0].tagName===f.Select){c=[];for(a=0;a<b[0].options.length;a++){for(var h=!1,m=0;m<d.values.length;m++)if(b[0].options[a].value===d.values[m]){h=!0;c.push(d.values[m]);break}b[0].options[a].selected=h}MultiSelectPicklist.handleMSPChange(b[0]);return c.length===d.values.length}return!1}function s(a,c,b){if(a&&c){a.value=c;if(b){var d=Sfdc.get(a.id+"_lkid");a=Sfdc.get(a.id+"_lkold");d&&a&&(d.value=b,a.value=c)}return!0}return!1}
function p(a,c,b){if(a&&c){c=c.toLowerCase();for(var d=0;d<a.options.length;d++){var h=a.options[d].value;b&&Sfdc.resolve("Sfdc.EntityFeed.LookupTypes")&&(h=Sfdc.EntityFeed.LookupTypes[h]||h);if(h.toLowerCase()===c)return a.options[d].selected=!0,Sfdc.Event.fireEvent(a,"change"),!0}}return!1}function w(a){if(Sfdc.isEmpty(a))return"";var c=document.createElement("div");c.innerHTML=a;var b=Sfdc.Resource.getScriptsFromHtml(c);if(!Sfdc.isEmpty(b)){a=0;for(var d=b.length;a<d;a++)b[a].parentNode.removeChild(b[a]);
a=c.innerHTML}return a}function q(a,c){var b=a.createRange();b.moveToPosition(b.root,c);a.getSelection().selectRanges([b])}function x(a,c){for(var b=["input","select","textarea"],d=document.getElementById(a),h="undefined"!==typeof CKEDITOR,f=0;f<b.length;f++)for(var g=d.getElementsByTagName(b[f]),e=0;e<g.length;e++)if("checkbox"!=g[e].getAttribute("type")||g[e].checked)if("TEXTAREA"==g[e].tagName&&(h&&CKEDITOR.instances[g[e].name])&&(CKEDITOR.instances[g[e].name].updateElement(),CKEDITOR.instances[g[e].name].destroy(!0)),
"SELECT"==g[e].tagName){for(var l=[],r=g[e].options,n=0;n<r.length;n++)r[n].selected&&l.push(r[n].value);c[g[e].name]=l}else c[g[e].name]=g[e].value;return c}function t(a,c){if(c.quickActionElement){var b=Sfdc.get(a);if(b){var d=b.parentNode;Sfdc.Dom.removeChild(b);Sfdc.Dom.insertHTML(d,c.quickActionElement);if(b=Sfdc.get(a))b=Sfdc.Resource.getScriptsFromHtml(b),Sfdc.Resource.execScripts(b,y)}}}function y(){window.picklist&&(picklist.initialized=!1,picklist.initAll())}var f={Input:"INPUT",Select:"SELECT",
TextArea:"TEXTAREA",Div:"DIV"},z={Text:e(!0,[f.Input]),Phone:e(!0,[f.Input]),Email:e(!0,[f.Input]),Url:e(!0,[f.Input]),Boolean:e(!0,[f.Input]),Currency:e(!0,[f.Input]),Integer:e(!0,[f.Input]),Double:e(!0,[f.Input]),Percent:e(!0,[f.Input]),DateTime:e(!0,[f.Input]),TimeOnly:e(!0,[f.Input]),DateOnly:e(!0,[f.Input]),DueDate:e(!0,[f.Input]),Birthday:e(!0,[f.Input]),AddressState:e(!0,[f.Input,f.Select]),AddressCountry:e(!0,[f.Input,f.Select]),Fax:e(!0,[f.Input]),TextEnum:e(!0,[f.Input]),DynamicEnum:e(!0,
[f.Select]),StaticEnum:e(!0,[f.Select]),MultiLineText:e(!0,[f.TextArea]),StringPlusClob:e(!0,[f.TextArea]),HtmlStringPlusClob:e(!0,[f.TextArea]),EntityId:e(!1,[f.Input,f.Select]),MultiEnum:e(!1,[f.Select])};Sfdc.EntityFeed.QuickAction.register=function(a){if(Sfdc.isDefAndNotNull(entityFeedPage)){a=Sfdc.clone(a);var c=!a.formId,b=!1,d=null,e=chatter.getPublisher().getHandler(a.handlerId),f=e.onSuccess;e.onSuccess=function(a,c){try{Sfdc.isFunction(f)&&f.call(e,a,c),d&&d({success:!0})}finally{d=null,
b=!1}};var g=e.onFailure;e.onFailure=function(a,c){try{Sfdc.isFunction(g)&&g.call(e,a,c),d&&d({success:!1})}finally{d=null,b=!1}};var k=e.onValidationFailure;e.onValidationFailure=function(a,c){try{Sfdc.isFunction(k)&&k.call(e,a,c),d&&d({success:!1})}finally{d=null,b=!1}};entityFeedPage.getPublisher().registerActionHandler(a.contextId,{actionName:a.actionName,onInvoke:function(e,f){var g=!0;c&&(g=Sfdc.get(entityFeedPage.getPublisher().getPanelWrapperId(a.contextId)),g=(g=Sfdc.get("publishersharebutton",
g))&&!g.disabled);chatter.getPublisher().getCurrentActionId()!==a.actionId?(Sfdc.log("Action '"+a.actionName+"' must be selected before it can be invoked."),f({success:!1,actionNotSelected:!0})):b?(Sfdc.log("Action '"+a.actionName+"' is already being performed."),f({success:!1,actionAlreadyInProgress:!0})):g?(b=!0,d=f,chatter.getPublisher().submit()):(Sfdc.log("Action '"+a.actionName+"' cannot be submitted."),f({success:!1}))},onSetInputValues:function(b,d){var e=a.formId?Sfdc.get(a.formId):null,
f=e&&(!a.excludeClass||!Sfdc.Dom.hasClass(e,a.excludeClass));(c||f)&&chatter.getPublisher().getCurrentActionId()===a.actionId?c?(e=Sfdc.get(entityFeedPage.getPublisher().getPanelWrapperId(a.contextId)),e=Sfdc.EntityFeed.QuickAction.setChatterActionInputValues(e,b)):e=Sfdc.EntityFeed.QuickAction.setActionFormInputValues(e,b):(Sfdc.log("Action '"+a.actionName+"' must be selected before field values can be set."),e={success:!1,actionNotSelected:!0});d&&d(e)}})}};Sfdc.EntityFeed.QuickAction.setActionFormInputValues=
function(a,c){if(!a||!c.targetFields)return!1;var b={success:!0,targetFieldErrors:{}},d;for(d in c.targetFields)c.targetFields.hasOwnProperty(d)&&!Sfdc.EntityFeed.QuickAction.setFormFieldValue(a,d,c.targetFields[d])&&(b.success=!1,b.targetFieldErrors[d]=!0);return b};Sfdc.EntityFeed.QuickAction.setFormFieldValue=function(a,c,b){a=Sfdc.select('[data-fieldname\x3d"'+c.toLowerCase()+'"]',a);if(Sfdc.isEmpty(a))Sfdc.log("Field '"+c+"' not found.");else{var d=a[0].getAttribute("data-fieldtype"),e=d?z[d]:
null;if(e){for(var f=[],g=0;g<a.length;g++)if(-1!=e.allowedTags.indexOf(a[g].tagName))f.push(a[g]);else for(var k=0;k<e.allowedTags.length;k++){var l=Sfdc.Array.toArray(a[g].getElementsByTagName(e.allowedTags[k]));Sfdc.isEmpty(l)||(f=f.concat(l))}if(e.isSingleInput){if(1==f.length&&u(d,f[0],b))return!0}else if(v(d,a,f,b))return!0}Sfdc.log("Field '"+c+"' of type '"+(d||"Undefined")+"'not supported. Field was not set.")}return!1};Sfdc.EntityFeed.QuickAction.setChatterActionInputValues=function(a,c){if(!a||
!c.targetFields)return!1;var b={success:!0,targetFieldErrors:{}},d;for(d in c.targetFields)if(c.targetFields.hasOwnProperty(d)){var e;a:{e=c.targetFields[d];if("body"===d.toLowerCase()){var f=chatter.getPublisher().getTextArea();if(f&&Sfdc.Dom.isVisible(f,!0)){Sfdc.EntityFeed.QuickAction.insertIntoTextField(f,e.value,e.insertType);Sfdc.Dom.addClass(f,"publishertextareafocus");e=!0;break a}}e=!1}e||(b.success=!1,b.targetFieldErrors[d]=!0)}return b};Sfdc.EntityFeed.QuickAction.insertIntoTextField=function(a,
c,b){var d=a.tagName;if(!("INPUT"==d&&"text"==a.attributes.type.value||"TEXTAREA"==d))return!1;c=c||"";b=b?b.toLowerCase():"replace";if("cursor"===b)document.selection?(a.focus(),sel=document.selection.createRange(),sel.text=c):a.selectionStart||"0"==a.selectionStart?(d=a.selectionEnd,b=a.value.substring(0,a.selectionStart),d=a.value.substring(d,a.value.length),a.value=b+c+d):a.value+=c;else if("begin"===b)a.value=c+a.value;else if("end"===b)a.value+=c;else if("replace"===b)a.value=c;else return!1;
Sfdc.Event.fireEvent(a,"input");return!0};Sfdc.EntityFeed.QuickAction.insertIntoRichTextField=function(a,c,b){if("undefined"==typeof CKEDITOR)return!1;var d=CKEDITOR.instances[a.name];if(!d)return!1;b=b?b.toLowerCase():"replace";c=w(c);if("replace"===b)return d.setData(c,function(){q(d,CKEDITOR.POSITION_BEFORE_END)}),!0;if(!Sfdc.isEmpty(c)){if("begin"===b)q(d,CKEDITOR.POSITION_AFTER_START);else if("end"===b)q(d,CKEDITOR.POSITION_BEFORE_END);else if("cursor"!==b)return!1;d.insertHtml(c);return!0}return!1};
Sfdc.EntityFeed.QuickAction.submit=function(a,c,b,d){var e="editPage__"+b.formSuffix;b=x(e,Sfdc.clone(b,!0));Sfdc.EntityFeed.postObjectUpdate(a,{url:c,params:b,failure:function(a,b){b.errors?alert(b.errors.message):t(e,b);d.failure&&d.failure(a,b)},success:function(a,b){t(e,b);d.success&&d.success(a,b)}})}})();

//# sourceMappingURL=/javascript/1522834981000/sfdc/source/EntityFeedPage.js.map
