/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
(function(a){function e(f){this.element=f.element;this.isEndorse="1"===a.Dom.getAttribute(this.element,b.ENDORSE_DATA_ATTRIB);this.userId=a.Dom.getAttribute(this.element,b.USER_ID_DATA_ATTRIB);this.topicId=a.Dom.getAttribute(this.element,b.TOPIC_ID_DATA_ATTRIB);this.endorseCtx=a.Dom.getAttribute(this.element,b.ATTR_ENDORSE_CTX);this.requestInProgress=!1;a.on(this.element,"click",this.onClick,this)}var b={ATTR_ENDORSE_CTX:"data-endorsectx",ENDORSE_DATA_ATTRIB:"data-endorse",ENDORSE_URL:"/topics/endorse/",
USER_ID_DATA_ATTRIB:"data-userid",TOPIC_ID_DATA_ATTRIB:"data-topicid",TYPE:"TopicEndorseButton"};e.prototype={onClick:function(f){var d=this;a.Event.getEventTarget(f,"a")&&!this.requestInProgress&&(chatter.getToolbox().post({url:b.ENDORSE_URL+this.userId+"/"+this.topicId+";"+(this.isEndorse?"create":"delete"),params:{endorseCtx:this.endorseCtx},success:function(f,e){var c,g;d.requestInProgress=!1;SfdcApp.TopicUtils.unwireInstance(b.TYPE,d.element);c=d.element.ownerDocument.createElement("div");c.innerHTML=
e.html;g=d.element.hasFocus;c=a.select("["+b.ENDORSE_DATA_ATTRIB+"]",c)[0];d.element.parentNode.replaceChild(c,d.element);c=SfdcApp.TopicUtils.wireInstance(b.TYPE,c);g&&c.focus()},failure:function(){d.requestInProgress=!1}}),this.requestInProgress=!0)},focus:function(){a.Dom.focus(a.select("a",this.element)[0])},destroy:function(){a.un(this.element,"click",this.onClick)}};SfdcApp.TopicUtils.registerWidgetType(b.TYPE,e)})(Sfdc);
(function(a){function c(){if(!d){var b=a.get("knowledgeableAbout");null!==b&&(SfdcApp.TopicUtils.wireDescendents(b,"TopicInfoBubble"),SfdcApp.TopicUtils.wireDescendents(b,"TopicEndorseButton"),d=!0)}}var d=!1;a.onReady(c);a.on(window,"load",c)})(Sfdc);
SfdcApp.TopicUtils.registerWidgetType("TopicInfoBubble",function(a){function d(b){b=b.element;if(this.button=a.get("."+c.CSS_INFO_BUBBLE_BUTTON,b))this.bubble=a.get("."+c.CSS_INFO_BUBBLE,b),a.on(this.button,"click",this.buttonOnClick,this)}var c={CSS_HIDDEN:"hidden",CSS_INFO_BUBBLE:"topic-infoBubble",CSS_INFO_BUBBLE_BUTTON:"iconParent"};d.prototype={buttonOnClick:function(b){a.Dom.hasClass(this.bubble,c.CSS_HIDDEN)?(a.Dom.removeClass(this.bubble,c.CSS_HIDDEN),a.on(document,"click",this.documentOnClick,
this),a.on(this.bubble,"keydown",this.onKeyDown,this),a.on(this.bubble,a.userAgent.isIE?"focusout":"blur",this.hide,this,!a.userAgent.isIE),a.Event.stopPropagation(b)):this.hide()},destroy:function(){this.button&&this.bubble&&(a.un(this.button,"click",this.buttonOnClick),this.removeInfoBubbleEvents())},documentOnClick:function(b){a.Event.getEventTarget(b,"."+c.CSS_INFO_BUBBLE)||this.hide()},hide:function(){a.Dom.addClass(this.bubble,c.CSS_HIDDEN);this.removeInfoBubbleEvents()},onKeyDown:function(a){27===
a.keyCode&&this.hide()},removeInfoBubbleEvents:function(){a.un(document,"click",this.documentOnClick);a.un(this.bubble,"keydown",this.onKeyDown);a.un(this.bubble,a.userAgent.isIE?"focusout":"blur",this.hide)}};return d}(Sfdc));

//# sourceMappingURL=/javascript/1413796312000/sfdc/source/KnowledgeableAbout.js.map
