/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
var ProfileBreadcrumbs={hideAll:function(b){Ext.select(".pc_breadcrumbMenu").each(function(a){ProfileBreadcrumbs.hideBreadcrumbMenu(a)});Ext.select(".pc_breadcrumbMenuOpen").each(function(a){a.removeClass("pc_breadcrumbMenuOpen")})},showHide:function(b,a,d,e){var c=Ext.get(e);Ext.select(a).each(function(a){a.isVisible()?ProfileBreadcrumbs.hideBreadcrumbMenu(a,c):ProfileBreadcrumbs.showBreadcrumbMenu(a,c)});Ext.select(d).each(function(a){ProfileBreadcrumbs.hideBreadcrumbMenu(a,c)});eventCancelBubble(getEvent(b))},
hideBreadcrumbMenu:function(b,a){b.hide();Ext.isIE7&&b.parent().removeClass("pc_breadcrumbSections");a&&a.removeClass("pc_breadcrumbMenuOpen")},showBreadcrumbMenu:function(b,a){a.addClass("pc_breadcrumbMenuOpen");Ext.isIE7&&b.parent().addClass("pc_breadcrumbSections");b.show()}};Ext.EventManager.on(document,"click",ProfileBreadcrumbs.hideAll);
Ext.namespace("sfdc.common.guidedtour");
sfdc.common.guidedtour.getHeader=function(b,a,c){return new Sfdc.GuidedTour({closeIntroLabel:LC.getLabel("GuidedTour","closeIntro"),closeOutroLabel:LC.getLabel("GuidedTour","closeOutro"),showLaterLabel:LC.getLabel("GuidedTour","showLater"),startTourLabel:LC.getLabel("GuidedTour","startTour"),continueLabel:LC.getLabel("GuidedTour","continue"),endTourLabel:LC.getLabel("GuidedTour","endTour"),previousLabel:LC.getLabel("GuidedTour","previous"),replayLabel:LC.getLabel("GuidedTour","replay"),shouldShowHandler:function(){return"1"!==
Ext.util.Cookies.get(a)},closeForeverHandlerIntercept:function(){Ext.util.Cookies.set(a,"1");UserContext.userPreferences.setBoolean(c,!0)},showLaterHandlerIntercept:function(){Ext.util.Cookies.set(a,"1")},steps:[{width:425,title:LC.getLabel("ProfileTour","IntroTitle"),content:LC.getLabel("ProfileTour","IntroContent"),countStep:!1,toolbarItems:sfdc.common.guidedtour.starttools},{locator:"div.pc_find",position:"tl-b",useArrow:!0,offsets:[-20,0],arrowOffset:20,title:LC.getLabel("ProfileTour","Step1Title"),
content:"\x3cp\x3e"+LC.getLabel("ProfileTour","Step1Content")+'\x3c/p\x3e\x3cimg src\x3d"/s.gif" class\x3d"pc_headerstep1"/\x3e',width:325,countStep:!0,toolbarItems:sfdc.common.guidedtour.steptools},{locator:"#button_edit_properties",position:"t-b",useArrow:!0,width:350,title:LC.getLabel("ProfileTour","Step2Title"),content:"\x3cp\x3e"+LC.getLabel("ProfileTour","Step2Content")+'\x3c/p\x3e\x3cimg src\x3d"/s.gif" class\x3d"pc_headerstep2"/\x3e',countStep:!0,toolbarItems:sfdc.common.guidedtour.steptools},
{locator:"input.pc_assignedUsers_btn",position:"t-b",offsets:[0,0],arrowOffset:-15,useArrow:!0,width:250,title:LC.getLabel("ProfileTour","Step3Title"),content:LC.getLabel("ProfileTour","Step3Content"),countStep:!0,toolbarItems:sfdc.common.guidedtour.steptools},{locator:".pc_sectionApps .pc_sectionContents",position:"r-l",useArrow:!0,offsets:[0,0],arrowOffset:0,width:335,title:LC.getLabel("ProfileTour","Step4Title"),content:LC.getLabel("ProfileTour","Step4Content"),countStep:!0,toolbarItems:sfdc.common.guidedtour.steptools},
{locator:".pc_sectionSystem .pc_sectionContents",position:"r-l",useArrow:!0,width:365,title:LC.getLabel("ProfileTour","Step5Title"),content:LC.getLabel("ProfileTour","Step5Content"),countStep:!0,toolbarItems:sfdc.common.guidedtour.steptools},{width:350,title:LC.getLabel("ProfileTour","ExitTitle"),content:LC.getLabel("ProfileTour","ExitContent",b),countStep:!1,toolbarItems:sfdc.common.guidedtour.exittools}]})};
sfdc.common.guidedtour.getObjectsAndTabs=function(b,a,c){return new Sfdc.GuidedTour({closeIntroLabel:LC.getLabel("GuidedTour","closeIntro"),closeOutroLabel:LC.getLabel("GuidedTour","closeOutro"),showLaterLabel:LC.getLabel("GuidedTour","showLater"),startTourLabel:LC.getLabel("GuidedTour","startTour"),continueLabel:LC.getLabel("GuidedTour","continue"),endTourLabel:LC.getLabel("GuidedTour","endTour"),previousLabel:LC.getLabel("GuidedTour","previous"),replayLabel:LC.getLabel("GuidedTour","replay"),shouldShowHandler:function(){return"1"!==
Ext.util.Cookies.get(a)},closeForeverHandlerIntercept:function(){Ext.util.Cookies.set(a,"1");UserContext.userPreferences.setBoolean(c,!0)},showLaterHandlerIntercept:function(){Ext.util.Cookies.set(a,"1")},steps:[{width:450,title:LC.getLabel("ProfileObjectsAndTabsTour","IntroTitle"),content:LC.getLabel("ProfileObjectsAndTabsTour","IntroContent"),countStep:!1,toolbarItems:sfdc.common.guidedtour.starttools},{locator:"div.pc_breadcrumbAlign.pc_breadcrumb",position:"tl-b",useArrow:!0,offsets:[-20,0],arrowOffset:30,
title:LC.getLabel("ProfileObjectsAndTabsTour","Step1Title"),content:"\x3cp\x3e"+LC.getLabel("ProfileObjectsAndTabsTour","Step1Content")+'\x3c/p\x3e\x3cimg src\x3d"/s.gif" class\x3d"pc_objectsandtabsstep1"/\x3e',width:321,countStep:!0,toolbarItems:sfdc.common.guidedtour.steptools},{locator:"td.pbTitle",position:"l-r",useArrow:!0,offsets:[-150,80],arrowOffset:0,width:350,title:LC.getLabel("ProfileObjectsAndTabsTour","Step2Title"),content:"\x3cp\x3e"+LC.getLabel("ProfileObjectsAndTabsTour","Step2ContentA")+
'\x3c/p\x3e\x3cimg src\x3d"/s.gif" class\x3d"pc_objectsandtabsstep2"/\x3e',countStep:!0,toolbarItems:sfdc.common.guidedtour.steptools},{locator:"td.pbTitle",position:"b-t",useArrow:!0,offsets:[150,50],width:425,title:LC.getLabel("ProfileObjectsAndTabsTour","Step3Title"),content:"\x3cp\x3e"+LC.getLabel("ProfileObjectsAndTabsTour","Step3Content")+'\x3c/p\x3e\x3cimg src\x3d"/s.gif" class\x3d"pc_objectsandtabsstep3"/\x3e',countStep:!0,toolbarItems:sfdc.common.guidedtour.steptools},{width:450,title:LC.getLabel("ProfileObjectsAndTabsTour",
"ExitTitle"),content:LC.getLabel("ProfileObjectsAndTabsTour","ExitContent",b),countStep:!1,toolbarItems:sfdc.common.guidedtour.exittools}]})};
function LoginIpRangeDelete(a,b){this.isMovable=this.isModal=!0;this.width=400;this.id=a;this.title=b;this.setupDefaultButtons();this.addEvents()}LoginIpRangeDelete.prototype=new OverlayDialog;
LoginIpRangeDelete.prototype.createContent=function(){var a=document.getElementById(this.id+"_content"),b=[];b.push(a.innerHTML);a.parentNode.removeChild(a);this.overrideButton(0,LC.getLabel("Buttons","delete"),"LoginIpRangeDelete.doDelete()");this.overrideButton(1,LC.getLabel("Buttons","cancel"),"LoginIpRangeDelete.doCancel()");this.createButtons(b);document.getElementById(this.getContentId()).innerHTML=b.join("")};LoginIpRangeDelete.doDelete=function(){deleteIpRange();return!1};
LoginIpRangeDelete.doCancel=function(){return!0};var deletePopup;LoginIpRangeDelete.prototype.afterDelete=function(){document.getElementById(LoginIpRangeDeleteFields.messagesId)||deletePopup.hide()};
LoginIpRangeDelete.showDialog=function(a,b,c){deletePopup||(deletePopup=new LoginIpRangeDelete(a,LC.getLabel("ProfileConsole","LoginIpRanges")),deletePopup.register());document.getElementById(LoginIpRangeDeleteFields.messagesId)&&Ext.get(LoginIpRangeDeleteFields.messagesId).setDisplayed(!1);Ext.get(LoginIpRangeDeleteFields.infoMsgId).dom.innerHTML=c;Ext.get(LoginIpRangeDeleteFields.rangeIdId).dom.value=b;deletePopup.show()};
function LoginIpRangeEdit(a,b){this.isMovable=this.isModal=!0;this.width=600;this.id=a;this.title=b;this.setupDefaultButtons();this.addEvents()}LoginIpRangeEdit.prototype=new OverlayDialog;
LoginIpRangeEdit.prototype.createContent=function(){var a=document.getElementById(this.id+"_content"),b=[];b.push(a.innerHTML);a.parentNode.removeChild(a);this.overrideButton(0,LC.getLabel("Buttons","save"),"LoginIpRangeEdit.doSave()");this.overrideButton(1,LC.getLabel("Buttons","save_and_new"),"LoginIpRangeEdit.doSaveAndNew()");this.overrideButton(2,LC.getLabel("Buttons","cancel"),"LoginIpRangeEdit.doCancel()");this.createButtons(b);document.getElementById(this.getContentId()).innerHTML=b.join("")};
LoginIpRangeEdit.doSave=function(){save();return!1};LoginIpRangeEdit.doSaveAndNew=function(){saveAndNew();return!1};LoginIpRangeEdit.doCancel=function(){this.clearInputs();return!0};LoginIpRangeEdit.clearInputs=function(){Ext.get(LoginIpRangeEditFields.rangeIdId).dom.value="";Ext.get(LoginIpRangeEditFields.startIpId).dom.value="";Ext.get(LoginIpRangeEditFields.endIpId).dom.value="";Ext.get(LoginIpRangeEditFields.descriptionId).dom.value=""};var editPopup;
LoginIpRangeEdit.prototype.afterSave=function(){document.getElementById(LoginIpRangeEditFields.messagesId)||editPopup.hide()};LoginIpRangeEdit.showEditDialog=function(a,b,c,d,e){this.initDialog(a);b&&(Ext.get(LoginIpRangeEditFields.rangeIdId).dom.value=b,Ext.get(LoginIpRangeEditFields.startIpId).dom.value=c,Ext.get(LoginIpRangeEditFields.endIpId).dom.value=d,Ext.get(LoginIpRangeEditFields.descriptionId).dom.value=e);editPopup.show()};
LoginIpRangeEdit.showNewDialog=function(a){this.initDialog(a);this.clearInputs();editPopup.show()};LoginIpRangeEdit.initDialog=function(a){editPopup||(editPopup=new LoginIpRangeEdit(a,LC.getLabel("ProfileConsole","LoginIpRanges")),editPopup.register());document.getElementById(LoginIpRangeEditFields.messagesId)&&Ext.get(LoginIpRangeEditFields.messagesId).setDisplayed(!1)};
var RecordTypeRow=function(a,b,c,d){this.scope=b;this.recordTypeId=c;this.displayName=d;this.rowId=a.replace(/(:rt_assign|:radio:\d)$/,"");this.assignedElt=document.getElementById(this.rowId+":rt_assign");this.defaultElt=document.getElementById(this.rowId+":radio:0");this.notDefaultElt=document.getElementById(this.rowId+":radio:1");this.isMasterRecordType=function(){return this._strEndsWith(this.rowId,":0")};this.isAssigned=function(){return this.assignedElt.checked};this.isDefault=function(){return this.defaultElt.checked};
this.assign=function(a){(this.assignedElt.checked=a)||this.markDefault(!1)};this.markDefault=function(a){this.defaultElt.checked=a;this.notDefaultElt.checked=!a;a&&this.assign(!0)};this._strEndsWith=function(a,b){return a.match(b+"$")==b}},RecordTypeRowMgr=function(){this.masterMessage=LC.getLabel("ProfileConsole","ConfirmMasterRecordType");this.customMessage=LC.getLabel("ProfileConsole","ConfirmCustomRecordType");this.registerRow=function(a){void 0===this.scopedRows&&(this.scopedRows={});void 0===
this.allRows&&(this.allRows={});void 0===this.scopedRows[a.scope]&&(this.scopedRows[a.scope]={});this.scopedRows[a.scope][a.rowId]=a;this.allRows[a.rowId]=a;a.isMasterRecordType()&&(this.masterRow=a)};this.handleAssignClick=function(a,b){var c=this.allRows[(new RecordTypeRow(a)).rowId];if((c.isAssigned()||b)&&0<this.countAssigned(!c.isMasterRecordType()))if(confirm(c.isMasterRecordType()?this.masterMessage:this.customMessage))this.clearRows(!c.isMasterRecordType());else return void 0===b&&c.assign(!1),
!1;void 0===b&&(b=c.isAssigned());c.assign(b);this.ensureAllListsUpdated();this.maybeSetDefault();return!0};this.handleDefaultClick=function(a){var b=this.allRows[(new RecordTypeRow(a)).rowId];this.handleAssignClick(a,!0)?((a=this.getDefault(b))&&a.markDefault(!1),this.maybeSetDefault()):b.markDefault(!1)};this.countAssigned=function(a,b){if(a)return this.masterRow.isAssigned()?1:0;var c=0,d;d=b?this.scopedRows[b]:this.allRows;for(var e in d)if(d.hasOwnProperty(e)){var f=this.allRows[e];f.isAssigned()&&
!f.isMasterRecordType()&&c++}return c};this.clearRows=function(a){if(a)this.masterRow.assign(!1);else for(var b in this.allRows)this.allRows.hasOwnProperty(b)&&(a=this.allRows[b],a.isMasterRecordType()||a.assign(!1))};this.getDefault=function(a){for(var b in this.allRows)if(this.allRows.hasOwnProperty(b)){var c=this.allRows[b];if((void 0===a||c.rowId!=a.rowId)&&c.isDefault())return c}};this.maybeSetDefault=function(){if(1==this.countAssigned(!1)+(this.masterRow.isAssigned()?1:0)&&void 0===this.getDefault())for(var a in this.allRows)if(this.allRows.hasOwnProperty(a)){var b=
this.allRows[a];if(b.isAssigned()){b.markDefault(!0);break}}};this.registerSubEntityDefaultList=function(a,b){var c=document.getElementById(a);this.lists||(this.lists={},this.options={});this.options[b]||(this.options[b]={});this.lists[b]=c;for(var d=0;d<c.options.length;d++){var e=c.options[d];this.options[b][e.value]=e}this.noneEntry||(this.noneEntry={value:c[0].value,text:c[0].text});c.remove(0);this.ensureListUpdated(b)};this.ensureAllListsUpdated=function(){for(var a in this.scopedRows)this.scopedRows.hasOwnProperty(a)&&
this.ensureListUpdated(a)};this.ensureListUpdated=function(a){if(this.lists){var b=this.lists[a],c=b[b.selectedIndex].value,d=0,e=[],f;for(f in this.scopedRows[a])if(this.scopedRows[a].hasOwnProperty(f)){var g=this.allRows[f];g.isAssigned()&&(e[d++]={value:g.recordTypeId,text:this.htmlDecode(g.displayName)})}for(a=0;a<b.length;a++)b.remove(a);for(a=d=0;a<e.length;a++)b.options[a]=new Option(e[a].text,e[a].value),e[a].value==c&&(d=a);0===e.length&&(b.options[0]=new Option(this.noneEntry.text,this.noneEntry.value));
b.selectedIndex=d}};this.htmlDecode=function(a){return!a?a:Ext.util.Format.htmlDecode(a).replace(/&#39;/g,"'")}};
var PermissionConsole={resetLoginHours:function(b){Ext.each(b,function(a){"string"==typeof a?document.getElementById(a).selectedIndex=0:a.selectedIndex=0})},resetAllLoginHours:function(){this.resetLoginHours(Ext.select(".pc_loginHours_Select").elements)}};
var PermissionConsoleSave={disableSave:function(){var b=LC.getLabel("Buttons","saving"),c=Ext.select(".pc_buttonOnSave").elements;Ext.each(c,function(a){a.value=b;a.disabled=!0;a.className="btnDisabled"})}};
var ProfileDependentCheckboxes={dependents:{},antecedents:{},map:{},registerAllDependents:function(b){for(var a in b)b.hasOwnProperty(a)&&(this.dependents[a]=this.registerArray(this.dependents[a],b[a]))},registerAllAntecedents:function(b){for(var a in b)b.hasOwnProperty(a)&&(this.antecedents[a]=this.registerArray(this.antecedents[a],b[a]))},registerArray:function(b,a){if(void 0===b)return a;for(var c=0;c<a.length;c++)-1==b.indexOf(a[c])&&b.push(a[c]);return b},registerCheckbox:function(b,a,c){var d=
this.map[b];void 0===d&&(d={},this.map[b]=d);this.map[b][a]=c},handleClick:function(b,a,c){Perf.mark("profileDependentClickStarts");var d=ProfileDependentCheckboxes;d._ensureState(a,b.checked?d.dependents[c]:d.antecedents[c],b.checked);Perf.endMark("profileDependentClickStarts")},_ensureState:function(b,a,c){if(a)for(var d=0;d<a.length;d++){var e=document.getElementById(ProfileDependentCheckboxes.map[b][a[d]]);e&&(e.checked=c)}}};
var ProfileFind=function(d){var b=this,g=d+":findContainer",f=d+":keepTyping",h=d+":suggestions",k=d+":noResults",l=d+":searchingStatus",e=d+":input",m=d+":findItems:0:category";this.highlightItem=function(a){a=Ext.get(a);if(!a)return!1;(a=a.parent("tr"))&&a.addClass("pc_findSelectedTarget");return!1};this.submitFind=function(){var a=b.getSelectedFindItem();if(!a)return!1;a=a.child(".findItemUrl");if(!a)return!1;b.navigateToUrl(b.getElemText(a));return!1};this.getElemText=function(a){return a.dom.innerText||
a.dom.textContent};this.navigateToUrl=function(a){if(!a)return!1;b.clearFindInputAndFocus();Ext.get(e).blur();-1!=window.location.href.search("isdtp\x3dp1")&&(a=-1!=a.search("#")?a.replace("#","\x26isdtp\x3dp1#"):a+"\x26isdtp\x3dp1");window.location=a;Ext.each(Ext.select(".pc_findSelectedTarget"),function(a){a.removeClass("pc_findSelectedTarget")});Ext.each(document.getElementsByName(a.replace(/.*#/,"")),function(a){b.highlightItem(a)});return!1};this.downKeyPressed=function(a){var c=(a=b.getSelectedFindItem())?
a.next():b.getFindFirstItem();if(!c||!b.isFindSelectable(c)&&(c=c.next(),!c))return!1;b.isFindSelectable(c)&&(a&&a.removeClass("findSelectedItem"),c.addClass("findSelectedItem"));return!1};this.upKeyPressed=function(a){a=b.getSelectedFindItem();if(!a)return!1;var c=a.prev();if(!c||!b.isFindSelectable(c)&&(c=c.prev(),!c))return!1;b.isFindSelectable(c)&&(a.removeClass("findSelectedItem"),c.addClass("findSelectedItem"));return!1};this.getSelectedFindItem=function(){return Ext.select(".findSelectedItem",
"findItems").first()};this.isFindSelectable=function(a){return a&&!a.hasClass("findMoreItem")};this.isInputChanged=function(a){b.currentText||(b.currentText="");a=Ext.get(e).getValue();var c=a!=b.currentText;b.currentText=a;return c};this.handleFindKey=function(a){a=getEvent(a);if(a.keyCode==KEY_ARROW_U)return b.upKeyPressed(a);if(a.keyCode==KEY_ARROW_D)return b.downKeyPressed(a);if(a.keyCode==KEY_ENTER)return b.submitFind();if(a.keyCode==KEY_ESC)b.hideFindContainer();else if(a.keyCode==KEY_BACKSPACE)b.hideFindContainer();
else if(b.isInputChanged()){b.hideFindContainer();var c=ltrim(b.currentText).length;if(0===c)return!1;3>c?Ext.get(f).show():(Perf.mark("findStarts"),performFind(),Perf.endMark("findStarts"));b.showFindContainer();return a.keyCode!=KEY_ENTER}return!0};this.handleKeyPress=function(a){return getEvent(a).keyCode!=KEY_ENTER};this.getFindFirstItem=function(){return Ext.get(m)};this.mouseSelectFindItem=function(a){var c=b.getSelectedFindItem();c&&c.removeClass("findSelectedItem");Ext.get(a).addClass("findSelectedItem")};
this.updateFindDropDown=function(){b.hideFindContainer();Ext.get(l).hide();var a=Ext.get(e).getValue().length;if(0===a)return!1;3>a?Ext.get(f).show():b.getFindFirstItem()?Ext.get(h).show():Ext.get(k).show();b.showFindContainer();return!1};this.showFindContainer=function(){Ext.get(g).show();return!1};this.hideFindContainer=function(){Ext.get(g).hide();Ext.get(f).hide();Ext.get(h).hide();Ext.get(k).hide();return!1};this.clearFindInputAndFocus=function(){b.hideFindContainer();var a=Ext.get(e);a.dom.value=
"";a.focus();return!1};this.onInputFocus=function(a){var c=LC.getLabel("ProfileConsole","FindSettings");a.value==c&&(a.value="");b.hideFindContainer();ProfileBreadcrumbs.hideAll()}};
function ProfileOverviewProperties(a,b,c){this.id=a;this.isMovable=this.isModal=!0;this.width=400;this.title=c;this.maintitle=b;this.setupDefaultButtons();this.addEvents()}ProfileOverviewProperties.prototype=new OverlayDialog;
ProfileOverviewProperties.prototype.createContent=function(){var a=document.getElementById(this.id+"_content"),b=[];b.push(a.innerHTML);a.parentNode.removeChild(a);this.overrideButton(0,LC.getLabel("Buttons","save"),"ProfileOverviewProperties.doSave()");this.overrideButton(1,LC.getLabel("Buttons","cancel"),"true");this.createButtons(b);document.getElementById(this.getContentId()).innerHTML=b.join("")};
ProfileOverviewProperties.prototype.copyFromHiddenValues=function(){for(var a=0;a<PropertiesOverlayFields.hidden.length;a++)Ext.get(PropertiesOverlayFields.shown[a]).dom.value=Ext.get(PropertiesOverlayFields.hidden[a]).dom.value};ProfileOverviewProperties.prototype.copyToHiddenValues=function(){for(var a=0;a<PropertiesOverlayFields.hidden.length;a++)Ext.get(PropertiesOverlayFields.hidden[a]).dom.value=Ext.get(PropertiesOverlayFields.shown[a]).dom.value};
ProfileOverviewProperties.doSave=function(){commitProperties();return!1};var properties;ProfileOverviewProperties.prototype.afterCommit=function(){document.getElementById(PropertiesOverlayFields.messagesId)||(document.title=this.maintitle+": "+Ext.get(PropertiesOverlayFields.name).dom.value+document.title.substring(document.title.lastIndexOf(" ~ ")),properties.copyToHiddenValues(),properties.hide())};
ProfileOverviewProperties.showDialog=function(a,b,c){properties||(properties=new ProfileOverviewProperties(a,b,c),properties.register(),properties.dialog||properties.createDialog());properties.copyFromHiddenValues();document.getElementById(PropertiesOverlayFields.messagesId)&&Ext.get(PropertiesOverlayFields.messagesId).setDisplayed(!1);properties.show()};
var ProfileStatus={numTimesShown:0,show:function(c){var b=Ext.get(ProfileStatus.pc_status),a=(getWindowWidth()-b.getWidth())/2,d=(Sfdc.Window.getWindowHeight()-b.getHeight())/2;b.setLeftTop(a,d);a=Ext.get(ProfileStatus.pc_statusMessage);a.dom.innerText?a.dom.innerText=c:a.dom.textContent=c;Ext.get(ProfileStatus.pc_statusMask).show();b.show();this.numTimesShown++},hide:function(){Ext.get(ProfileStatus.pc_status).hide();Ext.get(ProfileStatus.pc_statusMask).hide()}};

//# sourceMappingURL=/javascript/1481361112000/sfdc/source/ProfileConsole.js.map
