/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
function UserPage(){}UserPage.setAlias=function(a,d,b){a=document.getElementById(a);d=document.getElementById(d);b=document.getElementById(b);0===a.value.length&&(a.value=d.value.substring(0,1).toLowerCase()+b.value.substring(0,4).toLowerCase())};UserPage.setCommNickname=function(a,d){var b=document.getElementById(a),c=document.getElementById(d);if(0===b.value.length){var e=c.value;0<c.value.indexOf("@")&&(e=c.value.substring(0,c.value.indexOf("@")));b.value=e.substring(0,40)}};
UserPage.setUsername=function(a,d){var b=document.getElementById(a),c=document.getElementById(d);0===c.value.length&&(c.value=b.value,c.onchange())};
function UserEdit(a,d,c,e,f,g){function h(){b.allCheckboxes={};for(var a in b.controlMap)if(b.controlMap.hasOwnProperty(a))for(var c=0;c<b.controlMap[a].length;c++){var d=b.controlMap[a][c];document.getElementById(d)&&(b.allCheckboxes[d]=!0)}}function k(){b.allLookups={};for(var a in b.lookupMap)if(b.lookupMap.hasOwnProperty(a))for(var c=0;c<b.lookupMap[a].length;c++){var d=b.lookupMap[a][c];document.getElementById(d)&&(b.allLookups[d]=!0)}}var b=this;b.picklist=document.getElementById(a);b.controlMap=
d;b.lookupMap=c;b.defaultMap=e;b.disabledMap=f;b.autoToggleChatterAnswersBitIfQualified=g;b.picklist&&b.controlMap&&(b.allCheckboxes=null,b.allLookups=null,this.handleSelectChange=function(a){a=b.picklist.options[b.picklist.selectedIndex];a.value&&0<a.value.length?b.setChecksTo(a.value):b.resetChecks(a.value)},h(),k(),addEvent(b.picklist,"change",this.handleSelectChange,!1),b.handleSelectChange(null))}
UserEdit.prototype.resetChecks=function(a){for(var d in this.allCheckboxes)this.allCheckboxes.hasOwnProperty(d)&&!this.disabledMap.hasOwnProperty(d)&&(document.getElementById(d).disabled=!1);for(var c=0;c<this.defaultMap[a].length;c++)this.defaultMap.hasOwnProperty(a)&&this.defaultMap[a].hasOwnProperty([c])&&(document.getElementById(this.defaultMap[a][c]).name===ChatterService.IS_CHATTER_ANSWER_USER_PERM?this.autoToggleChatterAnswersBitIfQualified?document.getElementById(this.defaultMap[a][c]).checked=
!0:this.autoToggleChatterAnswersBitIfQualified=!0:document.getElementById(this.defaultMap[a][c]).checked=!0);for(d in this.allLookups)this.allLookups.hasOwnProperty(d)&&(document.getElementById(d).disabled=!1,document.getElementById(d+LookupInputElement.pLOOKUP_WIDGET).style.display="inline")};
UserEdit.prototype.setChecksTo=function(a){this.resetChecks(a);if(a in this.controlMap||a in this.lookupMap){for(var d=this.controlMap[a],c=0;c<d.length;c++){var e=document.getElementById(d[c]);if(e){var f=picklist.picklists[d[c]];f&&(e.innerHTML="",f.addOption(e,f.picklistNAMarker,f.nonelabel,0));e.disabled=!0;e.checked&&(e.checked=!1);"selectedIndex"in e&&(e.selectedIndex=0)}}d=this.lookupMap[a];for(c=0;c<d.length;c++){if(a=document.getElementById(d[c]))a.disabled=!0,a.value="";if(a=document.getElementById(d[c]+
LookupInputElement.pLOOKUP_WIDGET))a.style.display="none"}}};

//# sourceMappingURL=/javascript/1410512610000/sfdc/source/User.js.map
