/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Ext.ns("Sfdc","Sfdc.category");Sfdc.category.MAXTIPS=5;Sfdc.category.DefaultDevName="Category";Sfdc.category.TreeLoader=function(a){config={preloadChildren:!0,loadScope:a};Sfdc.category.TreeLoader.superclass.constructor.call(this,config)};
Ext.extend(Sfdc.category.TreeLoader,Ext.tree.TreeLoader,{load:function(a,b){Sfdc.category.TreeLoader.superclass.load.call(this,a,b);a.getOwnerTree().onLoad.call(this.loadScope,a);if(a.isExpanded())for(var c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];this.load(d);0===d.childNodes.length&&(d.expand(),d.collapse())}}});
Sfdc.category.TreeEventModel=Ext.extend(Ext.tree.TreeEventModel,{onNodeOut:function(a,b){this.lastNodeOver=null;Sfdc.category.TreeEventModel.superclass.onNodeOut.call(this,a,b)},onNodeOver:function(a,b){if(this.lastNodeOver)this.lastNodeOver.ui.onOut(a);this.lastNodeOver=b;Sfdc.category.TreeEventModel.superclass.onNodeOver.call(this,a,b)}});
Sfdc.category.CategoryTreeDropZone=function(a){config={completeDrop:function(a){var c=a.dropNode,d=a.target;message={itemId:c.id,type:"Move",point:a.point,target:d.id};this.tree.handler.perform(message);c.ui.focus();d.ui.endDrop()},onNodeOver:function(a,c,d,e){a=Sfdc.category.CategoryTreeDropZone.superclass.onNodeOver.call(this,a,c,d,e);a!=this.dropNotAllowed&&(a="x-dd-drop-ok");return a},isValidDropPoint:function(a,c,d,e,f){var g=a.node,h=f.node;return"append"==c&&g.getDepth()+h.getOwnerTree().getNodeHeight(h)>=
VFmain.MAX_NODE_DEPTH||g.getDepth()-1+h.getOwnerTree().getNodeHeight(h)>=VFmain.MAX_NODE_DEPTH?!1:Sfdc.category.CategoryTreeDropZone.superclass.isValidDropPoint.call(this,a,c,d,e,f)}};Sfdc.category.CategoryTreeDropZone.superclass.constructor.call(this,a,config)};Ext.extend(Sfdc.category.CategoryTreeDropZone,Ext.tree.TreeDropZone);
Sfdc.category.MyFill=function(a){Sfdc.category.MyFill.superclass.constructor.call(this);this.render=function(b){b.style.width=a;Ext.Toolbar.Fill.superclass.render.call(this,b)}};Ext.extend(Sfdc.category.MyFill,Ext.Toolbar.Spacer);Sfdc.category.ActionLink=function(a,b,c){Sfdc.category.ActionLink.superclass.constructor.call(this,{autoEl:{tag:"a",href:"#",cls:"actionLink",html:a},listeners:{render:function(a){a.getEl().on("click",b,c)}}})};Ext.extend(Sfdc.category.ActionLink,Ext.BoxComponent);
Sfdc.category.HelpText=function(){Sfdc.category.HelpText.superclass.constructor.call(this,{autoEl:{tag:"div",id:"helptext",cls:"helptext",hidden:!0,html:""}})};Ext.extend(Sfdc.category.HelpText,Ext.BoxComponent);
Sfdc.category.AddField=function(a){var b=new Ext.Template("\x3ctbody\x3e","\x3ctr class\x3d'fieldLabels'\x3e\x3ctd\x3e"+LC.getLabel("DataCategoryUI","category_label")+"\x3c/td\x3e\x3ctd\x3e"+LC.getLabel("DataCategoryUI","category_dev_name")+"\x3c/td\x3e\x3c/tr\x3e","\x3ctr\x3e\x3ctd class\x3d'labelInput'\x3e\x3c/td\x3e\x3ctd class\x3d'apiNameInput'\x3e\x3c/td\x3e\x3ctd class\x3d'editButtons'\x3e\x3c/td\x3e\x3c/tr\x3e","\x3ctr\x3e\x3ctd width\x3d'160' class\x3d'labelError'\x3e\x3c/td\x3e\x3ctd width\x3d'160' class\x3d'apiNameError'\x3e\x3c/td\x3e\x3c/tr\x3e",
"\x3c/tbody\x3e");Sfdc.category.AddField.superclass.constructor.call(this,{autoEl:{tag:"table",cls:"categoryEdit",html:b.apply({})},isEditMode:!1,id:"newCategoryFieldWrap",hidden:!0,addButton:new Sfdc.category.ActionLink(LC.getLabel("DataCategoryUI","add"),function(){this.addField.isEditMode?this.completeEdit():this.completeAdd()},a),closeButton:new Sfdc.category.ActionLink(LC.getLabel("DataCategoryUI","cancel"),function(){this.addField.isEditMode?this.cancelEdit():this.cancelAdd()},a),label:new Ext.form.TextField({id:"newCategoryField",
hideLabel:!0,cls:"required",width:140,listeners:{focus:function(){this.focus(!1,350)}}}),apiName:new Ext.form.TextField({id:"newCategoryApiName",hideLabel:!0,cls:"required",width:140}),listeners:{render:function(a){a.addButton.render(a.getEl().child(".editButtons"));a.closeButton.render(a.getEl().child(".editButtons"));a.label.render(a.getEl().child(".labelInput"));a.apiName.render(a.getEl().child(".apiNameInput"));Ext.getDom(a.label.id).setAttribute("maxlength",VFmain.MAX_CATEGORY_LABEL_LENGTH);
Ext.getDom(a.apiName.id).setAttribute("maxlength",VFmain.MAX_CATEGORY_APINAME_LENGTH);a.getEl().child(".apiNameInput").setVisibilityMode(Ext.Element.DISPLAY);a.getEl().child(".fieldLabels").setVisibilityMode(Ext.Element.DISPLAY)},show:function(a){a.label.focus(!1,350)},hide:function(a){a.owningTree.helpText.hide();a.getEl().parent().removeClass(["x-tree-node-edit","x-tree-node-edit-hover"]);a.reset();a.getEl().child(".labelError").update("");a.getEl().child(".apiNameError").update("")}}});this.owningTree=
a;this.label.on("blur",function(a){a=a.getValue();!Ext.isEmpty(a)&&(Ext.isEmpty(this.apiName.getValue())&&this.getEl().child(".apiNameInput").isVisible())&&this.apiName.setValue(this.owningTree.makeDevName(a))},this)};
Ext.extend(Sfdc.category.AddField,Ext.BoxComponent,{labelError:function(a){this.getEl().child(".labelError").update(a);this.label.focus()},apiNameError:function(a){var b=this.getEl().child(".apiNameError");this.getEl().child(".apiNameInput").show();this.getEl().child(".fieldLabels").show();b.update(a);this.apiName.focus()},openForAdd:function(a){a.addClass(["adding","adding-hover"]);a.appendChild(this.getEl());this.getEl().child(".apiNameInput").hide();this.getEl().child(".fieldLabels").hide();this.addButton.getEl().update(LC.getLabel("DataCategoryUI",
"add"));this.isEditMode=!1;this.show()},openForEdit:function(a){a.addClass(["x-tree-node-edit","x-tree-node-edit-hover"]);a.appendChild(this.getEl());this.getEl().child(".apiNameInput").show();this.getEl().child(".fieldLabels").show();this.addButton.getEl().update(LC.getLabel("DataCategoryUI","update"));this.isEditMode=!0;this.show()},reset:function(){this.label.reset();this.apiName.reset();this.owningTree.getEl().appendChild(this.getEl())}});
Sfdc.category.Tree=function(a){!a.readonly&&!a.isSoftDeleted&&Ext.applyIf(a,{keys:[{key:Ext.EventObject.ENTER,handler:this.handleEnter,scope:this},{key:Ext.EventObject.TAB,handler:function(a,c){c.stopEvent();c.shiftKey?this.handleShiftTab():this.handleTab()},scope:this},{key:Ext.EventObject.ESC,handler:function(){this.cancelForms()},scope:this},{key:Ext.EventObject.DELETE,handler:function(a,c){var d=Ext.fly(c.getTarget()).dom.id;d!=this.addField.label.id&&d!=this.addField.apiName.id&&(d=this.getSelectionModel().getSelectedNode(),
d.parentNode&&!1!==d.attributes.deletable&&this.removeChild(d))},scope:this},{key:Ext.EventObject.SPACE,handler:function(a,c){var d=Ext.fly(c.getTarget()).dom.id;d!=this.addField.label.id&&d!=this.addField.apiName.id&&(c.preventDefault(),d=this.getSelectionModel().getSelectedNode(),this.startEdit(d,Ext.fly(d.ui.getAnchor()).up("div.x-tree-node-el"),!1),this.fireEvent("click",d),this.addField.label.focus())},scope:this},{key:Ext.EventObject.UP,handler:function(a,c){c.stopEvent();this.getSelectionModel().selectPrevious()},
scope:this},{key:Ext.EventObject.DOWN,handler:function(a,c){c.stopEvent();this.getSelectionModel().selectNext()},scope:this},{key:Ext.EventObject.RIGHT,handler:function(a,c){c.preventDefault();var d=this.getSelectionModel().selNode||this.lastSelNode;d.hasChildNodes()&&!d.isExpanded()&&d.expand()},scope:this},{key:Ext.EventObject.LEFT,handler:function(a,c){c.preventDefault();var d=this.getSelectionModel().selNode||this.lastSelNode;d.hasChildNodes()&&d.isExpanded()&&d.collapse()},scope:this}]});Ext.applyIf(a,
{cls:"categoryTree",autoScroll:!0,newCount:Sfdc.category.MAXTIPS,editNode:null,name:"",nameMap:{},deleteMap:{},deletedNodesApiName:[],nextDefault:0,listeners:{enddrag:function(a,c,d){Ext.fly(c.ui.getAnchor()).up("li.x-tree-node").removeClass("x-tree-node-dragging");Ext.fly(c.ui.getAnchor()).up("div.x-tree-node-el").fadeIn({duration:0.75})},startdrag:function(a,c,d){Ext.fly(c.ui.getAnchor()).up("li.x-tree-node").addClass("x-tree-node-dragging");a.cancelForms();Ext.fly(c.ui.getAnchor()).up("div.x-tree-node-el").fadeOut({duration:0.75})},
render:function(a){a.dropZone=new Sfdc.category.CategoryTreeDropZone(a)},beforeexpandnode:function(a){a.ui.beforeLoad()},expandnode:function(a){a.ui.afterLoad()}}});Sfdc.category.Tree.superclass.constructor.call(this,a);this.on("nodechange",function(a){Ext.fly(a.ui.getAnchor()).up("div.x-tree-node-el").highlight()});this.tipTemplate=new Ext.Template("\x3ctable\x3e","\x3ctbody\x3e","\x3ctr\x3e\x3cth scope\x3dcol\x3e"+LC.getLabel("DataCategoryUI","category_label")+'\x3c/th\x3e\x3ctd\x3e\x3cdiv style\x3d"width:15em;word-wrap:break-word;"\x3e{label}\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e',
"\x3ctr\x3e\x3cth scope\x3dcol\x3e"+LC.getLabel("DataCategoryUI","category_dev_name")+'\x3c/th\x3e\x3ctd\x3e\x3cdiv style\x3d"width:15em;word-wrap:break-word;"\x3e{apiName}\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e',"\x3c/tbody\x3e","\x3c/table\x3e");this.tipTemplate=this.tipTemplate.compile()};
Ext.extend(Sfdc.category.Tree,Ext.tree.TreePanel,{onRender:function(a,b){Sfdc.category.Tree.superclass.onRender.call(this,a,b);this.addField=new Sfdc.category.AddField(this);this.helpText=new Sfdc.category.HelpText;this.helpText.render(this.body);this.helpText.hide();var c=new Ext.Template('\x3ctable cellspacing\x3d"0" cellpadding\x3d"0" border\x3d"0" class\x3d"messageTable" style\x3d"margin: 0px; padding: 0px;"\x3e',"\x3ctbody\x3e",'\x3ctr valign\x3d"top"\x3e\x3ctd\x3e\x3cimg alt\x3d"ERROR" src\x3d"/s.gif" class\x3d"msgIcon" title\x3d"ERROR"/\x3e\x3c/td\x3e',
'\x3ctd class\x3d"messageCell"\x3e\x3cdiv class\x3d"messageText"\x3e'+LC.getLabel("DataCategoryUI","deleted_group_info")+"\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e","\x3c/tbody\x3e\x3c/table\x3e");this.getEl().child(".x-panel-body").insertFirst({tag:"div",cls:"message infoM3",style:"display:none",html:c.apply({})});this.deleteInfo=this.getEl().child(".message");this.deleteInfo.setVisibilityMode(Ext.Element.DISPLAY);!this.readonly&&!this.isSoftDeleted&&this.addField.render(this.getEl())},initComponent:function(){this.eventModel=
new Sfdc.category.TreeEventModel(this);Sfdc.category.Tree.superclass.initComponent.call(this);this.addEvents("nodechange");this.addEvents("startEdit");this.addEvents("startAdd");this.addEvents("sort");this.addEvents("delete");this.getSelectionModel().onKeyDown=this.getSelectionModel().onKeyDown.createInterceptor(function(a){return!1})},loadNames:function(a){this.nameMap=a;this.nodeCount=0;for(var b in this.nameMap)this.nameMap.hasOwnProperty(b)&&(this.incrementDefault(b),this.nodeCount++)},handleEnter:function(a,
b){b.stopEvent();var c=this.editNode,d=this.getSelectionModel().getSelectedNode();d||(nodeEl=Ext.fly(b.getTarget()).up("div.x-tree-node-el"))&&(d=this.getNodeById(nodeEl.getAttributeNS("ext","tree-node-id")));if(d==c)this.addField.isEditMode?this.completeEdit():this.completeAdd();else{if(this.nodeCount>=VFmain.MAX_CATEGORIES_PER_GROUP)return;if(d&&d.isExpanded()){if(d.getDepth()+1>=VFmain.MAX_NODE_DEPTH)return;this.addChild(d,d.firstChild)}else d&&(d.parentNode?this.addChild(d.parentNode,d.nextSibling):
this.addChild(d,d.firstChild))}return!1},handleTab:function(){var a=this.getSelectionModel().getSelectedNode();if(a)var b=a.previousSibling;if(b&&a!=this.editNode){if(!(b.getDepth()+this.getNodeHeight(a)>=VFmain.MAX_NODE_DEPTH)){b.expand();var c={itemId:a.id,type:"Move"};b.hasChildNodes()?(c.point="below",c.target=b.lastChild.id):c.target=b.id;this.handler.perform(c);this.fireEvent("click",a)}}else b&&!this.addField.getEl().child(".apiNameInput").isVisible()&&!(b.getDepth()+this.getNodeHeight(a)>=
VFmain.MAX_NODE_DEPTH)&&(b.expand(),b.insertBefore(a,null),this.fireEvent("click",a),this.addField.label.focus())},handleShiftTab:function(){var a=this.getSelectionModel().getSelectedNode();if(a)var b=a.parentNode;if(b)var c=a.parentNode.parentNode;c&&a!=this.editNode?(this.handler.perform({itemId:a.id,type:"Move",point:"below",target:b.id}),this.fireEvent("click",a)):c&&!this.addField.getEl().child(".apiNameInput").isVisible()&&(c.insertBefore(a,b.nextSibling),this.fireEvent("click",a),this.addField.label.focus())},
getJsonChildrenForSort:function(a){for(var b=[],c=0;c<a.childNodes.length;c++)b.push({id:a.childNodes[c].id,text:Sfdc.category.FormatText.htmlDecode(a.childNodes[c].text)});return b},toJsonObject:function(a){var b={text:a.text,apiName:a.attributes.apiName,categoryId:a.attributes.categoryId,children:[]};if(a.hasChildNodes())for(var c=0;c<a.childNodes.length;c++)b.children.push(this.toJsonObject(a.childNodes[c]));return b},toJsonObjectForSave:function(a){var b={text:Sfdc.category.FormatText.htmlDecode(a.text),
apiName:a.attributes.apiName,categoryId:a.attributes.categoryId,children:[]};if(a.hasChildNodes())for(var c=0;c<a.childNodes.length;c++)b.children.push(this.toJsonObjectForSave(a.childNodes[c]));return b},toJsonObjectForDelete:function(a,b){var c={text:a.text,origNodeId:a.id,children:[]};if(a.hasChildNodes())for(var d=0;d<a.childNodes.length;d++)a.childNodes[d]!==b&&c.children.push(this.toJsonObjectForDelete(a.childNodes[d],b));return c},parseDeleteMapForSave:function(a){for(var b in a)if(a.hasOwnProperty(b)){var c=
a[b];Ext.isEmpty(c)?a[b]="":a[b]=this.getNodeById(c).attributes.apiName}return a},isNew:function(a){return Ext.isEmpty(a.attributes.categoryId)},getNodeHeight:function(a){var b=1;if(!this.isNew(a)&&!a.isLoaded())b=a.attributes.height;else for(var b=1,c=0;c<a.childNodes.length;c++)b=Math.max(b,this.getNodeHeight(a.childNodes[c])+1);return b},getHeight:function(a){this.getNodeHeight(this.getRootNode())},cancelForms:function(){this.addField.isVisible()&&(this.addField.isEditMode?this.cancelEdit():this.cancelAdd())},
removeNode:function(a){for(;a.firstChild;)this.removeNode(a.firstChild);var b=a.parentNode;b&&b.removeChild(a)},startEdit:function(a,b,c){this.fireEvent("startEdit");this.editNode&&(this.addField.isEditMode?this.cancelEdit():this.cancelAdd());this.editNode=a;this.addField.openForEdit(b);this.addField.label.setValue(Sfdc.category.FormatText.htmlDecode(a.text));this.addField.apiName.setValue(a.attributes.apiName)},cancelEdit:function(){var a=this.editNode;this.editNode=null;this.addField.hide();this.fireEvent("click",
a)},completeEdit:function(){var a=this.editNode,b=this.addField.label.getValue().trim(),c=this.addField.apiName.getValue(),d=Sfdc.category.FormatText.htmlEncode(this.addField.label.getValue());if(a.text!=d||a.attributes.apiName!=c){b=this.isValidLabel(b);if(c!=a.attributes.apiName)var e=this.isValidAPIName(c);if(b&&e){this.addField.labelError(b);this.addField.apiNameError(e);return}if(b){this.addField.labelError(b);return}if(e){this.addField.apiNameError(e);return}message={itemId:a.id,type:"Edit",
data:{text:d,apiName:c}};this.handler.perform(message)}this.editNode=null;this.addField.hide();this.fireEvent("click",a)},action_doEdit:function(a,b){if(b)c=this.getNodeById(a.itemId),c.setText(a.old.text),c.attributes.apiName=a.old.apiName,this.updateTip(c),delete this.nameMap[a.data.apiName.toLowerCase()],this.nameMap[c.attributes.apiName.toLowerCase]=!0;else{var c=this.getNodeById(a.itemId);a.old={text:c.text,apiName:c.attributes.apiName};c.setText(a.data.text);c.attributes.apiName=a.data.apiName;
this.updateTip(c);delete this.nameMap[a.old.apiName.toLowerCase()];this.nameMap[c.attributes.apiName.toLowerCase()]=!0}this.incrementDefault(c.attributes.apiName);this.fireEvent("nodechange",c)},updateTip:function(a){new Ext.ToolTip({baseCls:"x-box",cls:"categoryGroupsInfoTip",html:this.tipTemplate.apply({label:a.text,apiName:a.attributes.apiName}),target:Ext.get(a.ui.getAnchor()).down("span")})},removeChild:function(a){this.fireEvent("delete");this.cancelForms();var b=a.getPath("text").substr(2),
c;c=a.hasChildNodes()?LC.getLabel("DataCategoryUI","delete_warning_children",a.text):LC.getLabel("DataCategoryUI","delete_warning_nochildren",a.text);b="\x3cp\x3e"+b+"\x3c/p\x3e\x3cp\x3e"+c+"\x3c/p\x3e";Ext.Msg.show({title:LC.getLabel("DataCategoryUI","delete_category_title",a.text),msg:b,buttons:Ext.MessageBox.OKCANCEL,scope:a,width:600,fn:function(a){"ok"==a&&(!Ext.isEmpty(this.attributes.categoryId)&&this.getOwnerTree().hasBeenActivated?this.getOwnerTree().removeOptions(this):(message={itemId:this.id,
type:"Remove"},this.getOwnerTree().handler.perform(message)))}})},removeOptions:function(a){var b="\x3cp\x3e"+a.getPath("text").substr(2)+"\x3c/p\x3e\x3cp\x3e"+LC.getLabel("DataCategoryUI","reassign_prompt",a.text)+"\x3c/p\x3e\x3cdiv class\x3d'deleteConfirm' id\x3d'deleteConfirm'/\x3e";Ext.Msg.show({title:LC.getLabel("DataCategoryUI","reassign"),msg:b,fn:function(a){"ok"==a&&(a=null,"PARENT"==this.getOwnerTree().deleteTarget?a=this.parentNode.id:"PICKER"==this.getOwnerTree().deleteTarget&&(a=null===
this.getOwnerTree().deletePicker.getSelectionModel().getSelectedNode()||void 0===this.getOwnerTree().deletePicker.getSelectionModel().getSelectedNode()?null:this.getOwnerTree().deletePicker.getSelectionModel().getSelectedNode().attributes.origNodeId),message={itemId:this.id,targetId:a,recategorize:!0,type:"Remove"},this.getOwnerTree().handler.perform(message));this.getOwnerTree().deletePicker=null},width:600,scope:a,buttons:Ext.MessageBox.OKCANCEL});b=a.parentNode;b=b.parentNode?b.parentNode.text+
" \x26gt; \x3cstrong\x3e"+b.text+"\x3c/strong\x3e":"\x3cstrong\x3e"+b.text+"\x3c/strong\x3e";this.deleteTarget="PARENT";new Ext.form.FieldSet({autoHeight:!0,style:{border:"none"},renderTo:"deleteConfirm",id:"deleteOptions",cls:"deleteOptions",defaultType:"radio",items:[{fieldLabel:"",labelSeparator:"",height:20,checked:!0,name:"delopt",boxLabel:LC.getLabel("DataCategoryUI","delete_option1",b),scope:this,handler:function(a,b){b&&(this.deleteTarget="PARENT")}},{fieldLabel:"",name:"delopt",labelSeparator:"",
height:20,boxLabel:LC.getLabel("DataCategoryUI","delete_option2"),scope:a,handler:function(a,b){var e=this.getOwnerTree();if(b)if(e.deleteTarget="PICKER",e.deletePicker)e.deletePicker.show();else{e.deletePicker=new Sfdc.category.Tree({readonly:!0,loader:e.loader,onLoad:Ext.emptyFn,height:200,width:400});var f=e.toJsonObjectForDelete(e.getRootNode(),this);e.deletePicker.setRootNode(new Ext.tree.AsyncTreeNode({text:f.text,origNodeId:f.origNodeId,children:f.children}));e.deletePicker.render(a.getEl().up("div.x-form-item"))}else e.deletePicker.hide(),
Ext.getCmp(a.getEl().up("div.x-window").dom.id).syncSize()}},{fieldLabel:"",name:"delopt",labelSeparator:"",boxLabel:LC.getLabel("DataCategoryUI","delete_option3"),scope:this,autoHeight:Ext.isIE?!1:!0,handler:function(a,b){b&&(this.deleteTarget=null)}}]})},deleteRecursive:function(a){delete this.nameMap[a.attributes.apiName.toLowerCase()];this.nodeCount--;for(var b=0;b<a.childNodes.length;b++)this.deleteRecursive(a.childNodes[b])},undeleteRecursive:function(a){this.nameMap[a.attributes.apiName.toLowerCase()]=
!0;this.nodeCount++;for(var b=0;b<a.childNodes.length;b++)this.undeleteRecursive(a.childNodes[b])},deleteAndRecategorizeRecursive:function(a,b){Ext.isEmpty(a.attributes.categoryId)||(this.deleteMap[a.attributes.categoryId]=b);delete this.nameMap[a.attributes.apiName.toLowerCase()];this.nodeCount--;this.deletedNodesApiName.push(a.attributes.apiName.toLowerCase());for(var c=0;c<a.childNodes.length;c++)this.deleteAndRecategorizeRecursive(a.childNodes[c],b)},undeleteAndRecategorizeRecursive:function(a){delete this.deleteMap[a.attributes.categoryId];
this.nameMap[a.attributes.apiName.toLowerCase()]=!0;this.nodeCount++;this.deletedNodesApiName.pop();for(var b=0;b<a.childNodes.length;b++)this.undeleteAndRecategorizeRecursive(a.childNodes[b])},makeDeleteTarget:function(a){a.deleteTargetCount++;this.setDeletable(a,!1)},setDeletable:function(a,b){null!==a.parentNode&&(a.attributes.deletable=b,this.setDeletable(a.parentNode,b))},isDeletable:function(a){if(0<a.deleteTargetCount)return!1;for(var b=0;b<a.childNodes.length;b++)if(!1===a.childNodes[b].deletable)return!1;
return!0},action_doRemove:function(a,b){var c;if(b){var d=new Ext.tree.AsyncTreeNode({text:a.data.text,id:a.itemId,apiName:a.data.apiName,categoryId:a.data.categoryId,children:a.data.children});c=this.getNodeById(a.parentId);var e=a.beforeId?c.findChild("id",a.beforeId):null;c.parentNode&&c.ensureVisible();c.expand();c.insertBefore(d,e);this.loader.load(d);0===d.childNodes.length&&(d.expand(),d.collapse());Ext.fly(d.getUI().getAnchor()).up("div.x-tree-node-el").fadeIn({duration:0.75});a.recategorize?
(a.targetId&&(c=this.getNodeById(a.targetId),c.deleteTargetCount--,this.isDeletable(c)&&this.setDeletable(c,!0)),this.undeleteAndRecategorizeRecursive(d)):this.undeleteRecursive(d)}else d=this.getNodeById(a.itemId),d.ensureVisible(),a.parentId=d.parentNode.id,a.beforeId=d.nextSibling?d.nextSibling.id:null,a.data=this.toJsonObject(d),e=d.parentNode,Ext.fly(d.getUI().getAnchor()).up("div.x-tree-node-el").ghost("t",{duration:0.75,callback:function(){this.remove()},scope:d}),a.recategorize?(a.targetId&&
(c=this.getNodeById(a.targetId),this.makeDeleteTarget(c)),this.deleteAndRecategorizeRecursive(d,a.targetId)):this.deleteRecursive(d),this.fireEvent("click",e)},onLoad:function(a){if(!a.isProcessed){a.isProcessed=!0;var b=Ext.get(a.getUI().getAnchor()).up("div.x-tree-node-el");this.tipTemplate.apply({label:a.text,apiName:a.attributes.apiName});new Ext.ToolTip({baseCls:"x-box",cls:"categoryGroupsInfoTip",html:this.tipTemplate.apply({label:a.text,apiName:a.attributes.apiName}),target:Ext.get(a.ui.getAnchor()).down("span")});
if(!a.getOwnerTree().readonly&&!a.getOwnerTree().isSoftDeleted){a.deleteTargetCount=0;a.attributes.deletable=!0;var c=null,c=null===a.parentNode?new Ext.menu.Menu({id:"actionMenu"+a.attributes.categoryId,items:[{text:LC.getLabel("DataCategoryUI","add_child"),id:"addchild"+a.attributes.categoryId,handler:function(){a.getOwnerTree().addChild(a,a.firstChild)}},{text:LC.getLabel("DataCategoryUI","edit"),id:"edit"+a.attributes.categoryId,handler:function(){a.getOwnerTree().startEdit(a,b,!0)}},new Ext.menu.Separator,
{text:LC.getLabel("DataCategoryUI","order"),id:"order"+a.attributes.categoryId,handler:function(){a.getOwnerTree().sortHandler(a)}}]}):new Ext.menu.Menu({id:"actionMenu"+a.attributes.categoryId,items:[{text:LC.getLabel("DataCategoryUI","add_sibling"),id:"addsibling"+a.attributes.categoryId,handler:function(){a.collapse();a.getOwnerTree().addChild(a.parentNode,a.nextSibling)}},{text:LC.getLabel("DataCategoryUI","add_child"),id:"addchild"+a.attributes.categoryId,handler:function(){a.getOwnerTree().addChild(a,
a.firstChild)}},{text:LC.getLabel("DataCategoryUI","edit"),id:"edit"+a.attributes.categoryId,handler:function(){a.getOwnerTree().startEdit(a,b,!0)}},new Ext.menu.Separator,{text:LC.getLabel("DataCategoryUI","order"),id:"order"+a.attributes.categoryId,handler:function(){a.getOwnerTree().sortHandler(a)}},new Ext.menu.Separator,{text:LC.getLabel("DataCategoryUI","delete"),id:"delete"+a.attributes.categoryId,handler:function(){a.getOwnerTree().removeChild(a)}}]}),c=new Ext.Button({menu:c,text:LC.getLabel("DataCategoryUI",
"actions"),renderTo:b.id,cls:"widget"});c.on("menushow",function(c,b){0===this.childNodes.length&&b.items.get("order"+a.attributes.categoryId).disable();this.parentNode?(this.getOwnerTree().nodeCount>=VFmain.MAX_CATEGORIES_PER_GROUP?(b.items.get("addchild"+a.attributes.categoryId).disable(),b.items.get("addsibling"+a.attributes.categoryId).disable(),Ext.QuickTips.register({cls:"infoTip",target:b.items.get("addchild"+a.attributes.categoryId).disable().getEl(),text:LC.getLabel("DataCategoryUI","categoryLimit")}),
Ext.QuickTips.register({cls:"infoTip",target:b.items.get("addsibling"+a.attributes.categoryId).disable().getEl(),text:LC.getLabel("DataCategoryUI","categoryLimit")})):a.getDepth()+1>=VFmain.MAX_NODE_DEPTH&&(b.items.get("addchild"+a.attributes.categoryId).disable(),Ext.QuickTips.register({cls:"infoTip",target:b.items.get("addchild"+a.attributes.categoryId).disable().getEl(),text:LC.getLabel("DataCategoryUI","depthLimit",VFmain.MAX_NODE_DEPTH)})),!1===this.attributes.deletable&&(b.items.get("delete"+
a.attributes.categoryId).disable(),Ext.QuickTips.register({cls:"infoTip",target:b.items.get("delete"+a.attributes.categoryId).getEl(),text:LC.getLabel("DataCategoryUI","canNotDelete",this.text)}))):this.getOwnerTree().nodeCount>=VFmain.MAX_CATEGORIES_PER_GROUP&&(b.items.get("addchild"+a.attributes.categoryId).disable(),Ext.QuickTips.register({cls:"infoTip",target:b.items.get("addchild"+a.attributes.categoryId).disable().getEl(),text:LC.getLabel("DataCategoryUI","categoryLimit")}))},a);c.on("menuhide",
function(c,b){b.items.get("order"+a.attributes.categoryId).enable();this.parentNode&&(b.items.get("addsibling"+a.attributes.categoryId).enable(),b.items.get("addchild"+a.attributes.categoryId).enable(),b.items.get("delete"+a.attributes.categoryId).enable(),Ext.QuickTips.unregister(b.items.get("delete"+a.attributes.categoryId).getEl()),Ext.QuickTips.unregister(b.items.get("delete"+a.attributes.categoryId).getEl()),Ext.QuickTips.unregister(b.items.get("delete"+a.attributes.categoryId).getEl()))},a);
a.mutton=c;a.on("beforeclick",function(a,b){if("[object HTMLTableCellElement]"!=b.getTarget()&&a.isSelected())return a.unselect(),!1});a.getUI().onDblClick=function(a){a=this.node;a!=a.getOwnerTree().editNode&&a.getOwnerTree().startEdit(a,Ext.fly(this.getAnchor()).up("div.x-tree-node-el"))}}}},sortHandler:function(a){this.fireEvent("sort");this.cancelForms();this.sortNodeId=a.id;sortChildren(Ext.encode(this.getJsonChildrenForSort(a)))},setOrder:function(a,b){for(var c=b.length,d=null,e=a.findChild("id",
b[0]),f=null,g=[],h=0;h<c;h++)f=a.findChild("id",b[h+1]),e.previousSibling=d,e.nextSibling=f,0===h&&a.setFirstChild(e),h==c-1&&a.setLastChild(e),e.render(!0),g.push(e),d=e,e=f;a.childNodes=g},action_doSort:function(a,b){var c;b?(c=this.getNodeById(a.itemId),this.setOrder(c,a.oldOrder)):(c=this.getNodeById(a.itemId),this.setOrder(c,a.newOrder))},isValidLabel:function(a){if(a.length>VFmain.MAX_CATEGORY_LABEL_LENGTH)return LC.getLabel("Edit","CannotExceedXCharacters",VFmain.MAX_CATEGORY_LABEL_LENGTH);
if(Ext.isEmpty(a.trim()))return LC.getLabel("Edit","Required")},isValidAPIName:function(a){if(Ext.isEmpty(a))return LC.getLabel("Global_Entity","missingDevName",LC.getLabel("DataCategoryUI","category_dev_name"));if(this.makeDevName(a)!=a)return LC.getLabel("Global_Entity","InvalidDeveloperNameOnEntity",LC.getLabel("DataCategoryUI","category_dev_name"));if(a.toLowerCase()in this.nameMap&&(null===this.editNode||void 0===this.editNode)||a.toLowerCase()in this.nameMap&&null!==this.editNode&&void 0!==
this.editNode&&a.toLowerCase()!=this.editNode.attributes.apiName.toLowerCase())return LC.getLabel("Global_Entity","duplicateDevName",LC.getLabel("DataCategoryUI","category_dev_name"));if(this.isApiNameInDeletedNodes(a))return LC.getLabel("DataCategoryUI","duplicateDeletedCategoryDevName")},isApiNameInDeletedNodes:function(a){for(var b=0;b<this.deletedNodesApiName.length;b++)if(this.deletedNodesApiName[b]==a.toLowerCase())return!0;return!1},makeDevName:function(a){var b={},c={};c.value=a;b.value="";
DeveloperNameInputElement.setName(c,b,Sfdc.category.DefaultDevName+this.nextDefault);return b.value},incrementDefault:function(a){0===a.indexOf(Sfdc.category.DefaultDevName)&&(a=parseInt(a.substring(Sfdc.category.DefaultDevName.length),10),"NaN"!=a&&(this.nextDefault=Math.max(this.nextDefault,a+1)))},addChild:function(a,b){this.fireEvent("startAdd");this.editNode&&(b==this.editNode&&(b=b.nextSibling),this.addField.isEditMode?this.cancelEdit():this.cancelAdd());var c=new Ext.tree.TreeNode({text:"",
apiName:"",children:[]});this.editNode=c;a.expand();a.unselect();a.insertBefore(c,b);c.select();c=Ext.fly(c.getUI().getAnchor()).up(".x-tree-node-el");this.addField.openForAdd(c);this.newCount<Sfdc.category.MAXTIPS&&c.createChild({tag:"div",cls:"categoryTips",html:Sfdc.category.tips[this.newCount]});this.newCount++},cancelAdd:function(){var a=this.editNode;this.editNode=null;Ext.fly(a.getUI().getAnchor()).up(".x-tree-node-el");this.addField.hide();sel=a.previousSibling;if(!sel||!a.parentNode.isExpanded())sel=
a.parentNode;a.remove();this.fireEvent("click",sel);Ext.fly(sel.ui.getAnchor()).focus()},completeAdd:function(){var a=this.addField.label.getValue(),b=this.addField.apiName.getValue();if(Ext.isEmpty(a)&&Ext.isEmpty(b))this.cancelAdd();else{var c=this.editNode;Ext.fly(c.getUI().getAnchor()).up(".x-tree-node-el");var d=c.parentNode,e=c.nextSibling;Ext.isEmpty(b)&&(b=this.makeDevName(a),this.addField.apiName.setValue(b));var f=this.isValidLabel(a),g=this.isValidAPIName(b);f&&g?(this.addField.labelError(f),
this.addField.apiNameError(g)):f?this.addField.labelError(f):g?this.addField.apiNameError(g):(message={itemId:c.id,data:{text:Sfdc.category.FormatText.htmlEncode(a.trim()),apiName:b},type:"Add",parentId:d.id,beforeId:e?e.id:null},this.addField.hide(),c.remove(),this.editNode=null,this.handler.perform(message),this.nodeCount<VFmain.MAX_CATEGORIES_PER_GROUP&&this.addChild(d,e))}},action_doAdd:function(a,b){if(b){var c=this.getNodeById(a.itemId);c.ensureVisible();Ext.fly(c.getUI().getAnchor()).up("div.x-tree-node-el").ghost("t",
{duration:0.75,callback:function(){this.remove()},scope:c});delete this.nameMap[a.data.apiName.toLowerCase()];this.nodeCount--}else{var c=new Ext.tree.TreeNode({text:a.data.text,id:a.itemId,apiName:a.data.apiName,categoryId:"",children:[]}),d=this.getNodeById(a.parentId),e=a.beforeId?d.findChild("id",a.beforeId):null;d.parentNode&&d.ensureVisible();d.expand();d.insertBefore(c,e);Ext.fly(c.getUI().getAnchor()).up("div.x-tree-node-el").fadeIn({duration:0.75});this.onLoad(c);this.nameMap[a.data.apiName.toLowerCase()]=
!0;this.incrementDefault(a.data.apiName);this.nodeCount++}},action_doMove:function(a,b){var c,d;if(b)c=this.getNodeById(a.itemId),d=this.getNodeById(a.old.parent),c.attributes.deletable||(this.isDeletable(c.parentNode)&&this.setDeletable(c.parentNode,!0),this.setDeletable(d,!1)),d.parentNode&&d.ensureVisible(),d.expand(),Ext.fly(c.getUI().getAnchor()).up("div.x-tree-node-el"),d.insertBefore(c,a.old.target?this.getNodeById(a.old.target):null);else{c=this.getNodeById(a.itemId);var e=this.getNodeById(a.target);
d=c.parentNode;a.old={parent:d.id,target:c.nextSibling?c.nextSibling.id:null};e.parentNode&&e.ensureVisible();d.expand();"above"==a.point?e.parentNode.insertBefore(c,e):"below"==a.point?e.parentNode.insertBefore(c,e.nextSibling):(e.expand(),e.appendChild(c));c.attributes.deletable||(this.setDeletable(c.parentNode,!1),this.isDeletable(d)&&this.setDeletable(d,!0))}}});

//# sourceMappingURL=/javascript/1429868265000/sfdc/source/DataCategoryTree.js.map
