/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Sfdc.category.Grid=function(c){var b=new Ext.Button({text:LC.getLabel("Buttons","create_new",""),id:"createCatGroup",disabled:c.readonly,handler:function(a,b){Ext.getCmp("saveCategory").disabled?(Ext.fly(VFmain.createForm).addClass("createFormBorder"),this.newCategoryGroup()):Ext.Msg.show({title:LC.getLabel("DataCategoryUI","unsaved_changes_title"),msg:LC.getLabel("DataCategoryUI","unsaved_changes_message",VFmain.tree.name),scope:this,width:600,fn:function(a){"yes"==a?Ext.getCmp("saveCategory").fireEvent("click"):
"no"==a&&(Ext.fly(VFmain.createForm).addClass("createFormBorder"),this.newCategoryGroup())},buttons:{yes:LC.getLabel("DataCategoryUI","save_changes"),no:LC.getLabel("DataCategoryUI","discard_changes"),cancel:LC.getLabel("Buttons","cancel")}})},scope:this});Ext.getCmp("createCatGroup").on("render",function(a){this.maxCatGroupTip=new Ext.ToolTip({cls:"infotip",html:LC.getLabel("DataCategoryUI","DataCategoryGroupLimit",VFmain.MAX_CATEGORY_GROUPS),target:Ext.getCmp("createCatGroup").getEl(),disabled:!0})},
this);Ext.applyIf(this,{singleSelect:!0,columns:[{header:"CategoryLabel",sortable:!1,dataIndex:"label"},{header:"state",hidden:!0,sortable:!0,dataIndex:"state"}],listeners:{render:function(a){a.getView().el.select(".x-grid3-header").setStyle("display","none")}},tbar:[b],isNewGroup:!1});Sfdc.category.Grid.superclass.constructor.call(this,c);if(!c.readonly)this.on("rowdblclick",function(a,b,c){a.store.getAt(b).data.state!=VFmain.DELETED_STATE&&(c=Ext.fly(a.view.getRow(b)).child("td.x-grid3-col").up(".x-grid3-row"),
a.edit(a.store.getAt(b),c))});this.tipTemplate=new Ext.Template("\x3ctable\x3e","\x3ctbody\x3e",'\x3ctr\x3e\x3cth scope\x3d"col"\x3e'+LC.getLabel("DataCategoryUI","group_label")+'\x3c/th\x3e\x3ctd\x3e\x3cdiv style\x3d"width:15em;word-wrap:break-word;"\x3e{label}\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e','\x3ctr\x3e\x3cth scope\x3d"col"\x3e'+LC.getLabel("DataCategoryUI","group_dev_name")+'\x3c/th\x3e\x3ctd\x3e\x3cdiv style\x3d"width:15em;word-wrap:break-word;"\x3e{apiName}\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e',
"\x3ctr\x3e\x3cth\x3e"+LC.getLabel("Global","description")+'\x3c/th\x3e\x3ctd\x3e\x3cdiv style\x3d"width:15em;word-wrap:break-word;"\x3e{description}\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e','\x3ctr\x3e\x3cth valign\x3d"top"\x3e'+LC.getLabel("DataCategoryUI","place_used")+'\x3c/th\x3e\x3ctd\x3e\x3cdiv style\x3d"width:15em;word-wrap:break-word;"\x3e{placeUsed}\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e',"\x3ctr\x3e\x3cth\x3e"+LC.getLabel("Global_Entity","created_by")+'\x3c/th\x3e\x3ctd\x3e\x3ca href\x3d"/{createdById}"\x3e{createdBy}\x3c/a\x3e, {createdByDate} \x3c/td\x3e\x3c/tr\x3e',
"\x3ctr\x3e\x3cth\x3e"+LC.getLabel("Global_Entity","last_modified_by")+'\x3c/th\x3e\x3ctd\x3e\x3ca href\x3d"/{lastModifiedById}"\x3e{lastModifiedBy}\x3c/a\x3e, {lastModifiedByDate}\x3c/td\x3e\x3c/tr\x3e',"\x3c/tbody\x3e","\x3c/table\x3e")};
Sfdc.category.Grid.categoryGroupRecord=Ext.data.Record.create([{name:"state"},{name:"label"},{name:"apiName"},{name:"description"},{name:"placeUsed"},{name:"id"},{name:"hasBeenActivated"},{name:"lastModifiedById"},{name:"lastModifiedBy"},{name:"lastModifiedByDate"},{name:"createdById"},{name:"createdBy"},{name:"createdByDate"},{name:"isEditable"}]);
Ext.extend(Sfdc.category.Grid,Ext.grid.GridPanel,{edit:function(c,b){Ext.getCmp("createCatGroup").disable();b.addClass("x-grid3-row-edit");VFmain.performCommand("cancel");VFmain.tree.cancelForms();Ext.fly(VFmain.createForm).removeClass("createFormBorder");Ext.fly(VFmain.editForm).setVisible(!0);b.appendChild(VFmain.editForm);VFmain.setVals(c.data);Ext.fly(inputsById.categoryGroupLabel).focus()},newCategoryGroup:function(){Ext.getCmp("createCatGroup").disable();var c=this.getSelectionModel();c.deselectRow(this.store.indexOf(c.getSelected()));
VFmain.tree.getRootNode().ui.hide();VFmain.performCommand("cancel");this.getTopToolbar().getEl().insertSibling(VFmain.editForm,"after");Ext.fly(VFmain.editForm).setVisible(!0);Ext.fly(inputsById.categoryGroupLabel).focus()},createToolTips:function(c){if(this.store.getAt(c).data.id!=VFmain.grid.store.DUMMY_NODE_ID){var b=Ext.get(this.getView().getRow(c)).child("td.x-grid3-col"),a=this.store.getAt(c);c=this.tipTemplate.apply(a.data);VFmain.isDoingSysAdmin&&(c=c+"\x3cbr\x3e"+a.data.id);new Ext.ToolTip({baseCls:"x-box",
cls:"categoryGroupsInfoTip",html:c,target:b.child(".x-grid3-cell-inner")});if(!this.readonly){c=b.createChild({tag:"div",cls:"erase"});var f=b.createChild({tag:"div",cls:"remove"}),g=b.createChild({tag:"div",cls:"toggleState"});b.createChild({tag:"div",cls:"edit"}).addClassOnOver("edit-hover");g.addClassOnOver("toggleState-hover");f.addClassOnOver("remove-hover");c.addClassOnOver("erase-hover");var e=b.up(".x-grid3-row");new Ext.ToolTip({cls:"infoTip",html:LC.getLabel("DataCategoryUI","edit_group"),
target:b.child(".edit")});new Ext.ToolTip({cls:"infoTip",html:LC.getLabel("DataCategoryUI","erase_group"),target:b.child(".erase")});a.data.state==VFmain.ACTIVE_STATE?(new Ext.ToolTip({cls:"infoTip",html:LC.getLabel("DataCategoryUI","delete_group"),target:b.child(".remove")}),new Ext.ToolTip({cls:"infoTip",html:LC.getLabel("DataCategoryUI","deactivate"),target:b.child(".toggleState")})):a.data.state==VFmain.INACTIVE_STATE?(new Ext.ToolTip({cls:"infoTip",html:LC.getLabel("DataCategoryUI","delete_group"),
target:b.child(".remove")}),this.store.numActiveCategory>=VFmain.MAX_ACTIVE_CATEGORY_GROUPS?(b.child("div.toggleState").addClass("toggleStateDisable"),new Ext.ToolTip({cls:"infoTip",html:LC.getLabel("DataCategoryUI","ActiveDataCategoryGroupLimit"),target:b.child(".toggleState")})):new Ext.ToolTip({cls:"infoTip",html:LC.getLabel("DataCategoryUI","activate"),target:b.child(".toggleState")})):new Ext.ToolTip({cls:"infoTip",html:LC.getLabel("DataCategoryUI","undelete"),target:b.child(".remove")});var d=
function(a){return{title:LC.getLabel("DataCategoryUI","unsaved_changes_title"),msg:LC.getLabel("DataCategoryUI","unsaved_changes_message",VFmain.tree.name),fn:function(b){"yes"==b?Ext.getCmp("saveCategory").fireEvent("click"):"no"==b&&a()},buttons:{yes:LC.getLabel("DataCategoryUI","save_changes"),no:LC.getLabel("DataCategoryUI","discard_changes"),cancel:LC.getLabel("Buttons","cancel")}}};b.child(".erase").on("click",function(b){Ext.Msg.show({title:LC.getLabel("DataCategoryUI","delete_group_title",
a.data.label),msg:"\x3cp\x3e"+LC.getLabel("DataCategoryUI","hard_delete_group_warning",a.data.label)+"\x3c/p\x3e\x3cp\x3e"+LC.getLabel("DataCategoryUI","delete_group_confirm")+"\x3c/p\x3e\x3cdiv class\x3d'deleteConfirm' id \x3d 'deleteConfirm'/\x3e",fn:function(b){Ext.Msg.getDialog().buttons[0].enable();"ok"==b&&Ext.getCmp("deleteCheck").getValue()&&hardDelete(a.data.id)},buttons:Ext.MessageBox.OKCANCEL,width:600});new Ext.form.Checkbox({id:"deleteCheck",boxLabel:LC.getLabel("DataCategoryUI","delete_group_check"),
renderTo:"deleteConfirm",listeners:{check:function(a,b){b?Ext.Msg.getDialog().buttons[0].enable():Ext.Msg.getDialog().buttons[0].disable()}}});Ext.Msg.getDialog().buttons[0].disable()});b.child(".edit").on("click",function(b){Ext.getCmp("saveCategory").disabled?this.edit(a,e):Ext.Msg.show(new d(function(){VFmain.tree.cancelForms();loadCategoryGroup(a.data.id);VFmain.grid.edit(a,e)}))},this);b.child(".toggleState").on("click",function(b){Ext.getCmp("saveCategory").disabled?a.data.state==VFmain.ACTIVE_STATE?
(setActivation(a.data.id,!1),this.store.numActiveCategory-=1):a.data.state==VFmain.INACTIVE_STATE&&(setActivation(a.data.id,!0),this.store.numActiveCategory<VFmain.MAX_ACTIVE_CATEGORY_GROUPS&&(this.store.numActiveCategory+=1)):Ext.Msg.show(new d(function(){VFmain.tree.cancelForms();a.data.state==VFmain.ACTIVE_STATE?(discardChanges(a.data.id,!1),VFmain.grid.store.numActiveCategory-=1):a.data.state==VFmain.INACTIVE_STATE&&(discardChanges(a.data.id,!0),VFmain.grid.store.numActiveCategory<VFmain.MAX_ACTIVE_CATEGORY_GROUPS&&
(VFmain.grid.store.numActiveCategory+=1))}))},this);b.child(".remove").on("click",function(b){Ext.getCmp("saveCategory").disabled?a.data.state!=VFmain.DELETED_STATE?(Ext.Msg.show({title:LC.getLabel("DataCategoryUI","delete_group_title",a.data.label),msg:"\x3cp\x3e"+LC.getLabel("DataCategoryUI","delete_group_warning",a.data.label)+"\x3c/p\x3e\x3cp\x3e"+LC.getLabel("DataCategoryUI","delete_group_confirm")+"\x3c/p\x3e\x3cdiv class\x3d'deleteConfirm' id \x3d 'deleteConfirm'/\x3e",fn:function(b){Ext.Msg.getDialog().buttons[0].enable();
"ok"==b&&Ext.getCmp("deleteCheck").getValue()&&(VFmain.tree.getRootNode().ui.hide(),VFmain.loadingScreen.show(),toggleDelete(a.data.id),a.data.state==VFmain.ACTIVE_STATE&&(this.store.numActiveCategory-=1))},buttons:Ext.MessageBox.OKCANCEL,width:600,scope:this}),new Ext.form.Checkbox({id:"deleteCheck",boxLabel:LC.getLabel("DataCategoryUI","delete_group_check"),renderTo:"deleteConfirm",listeners:{check:function(a,b){b?Ext.Msg.getDialog().buttons[0].enable():Ext.Msg.getDialog().buttons[0].disable()}}}),
Ext.Msg.getDialog().buttons[0].disable()):(VFmain.loadingScreen.show(),toggleDelete(a.data.id)):Ext.Msg.show(new d(function(){VFmain.tree.cancelForms();loadCategoryGroup(a.data.id);a.data.state!=VFmain.DELETED_STATE?(Ext.Msg.show({title:LC.getLabel("DataCategoryUI","delete_group_title",a.data.label),msg:"\x3cp\x3e"+LC.getLabel("DataCategoryUI","delete_group_warning",a.data.label)+"\x3c/p\x3e\x3cp\x3e"+LC.getLabel("DataCategoryUI","delete_group_confirm")+"\x3c/p\x3e\x3cdiv class\x3d'deleteConfirm' id \x3d 'deleteConfirm'/\x3e",
fn:function(b){Ext.Msg.getDialog().buttons[0].enable();"ok"==b&&Ext.getCmp("deleteCheck").getValue()&&(VFmain.tree.getRootNode().ui.hide(),VFmain.loadingScreen.show(),toggleDelete(a.data.id),a.data.state==VFmain.ACTIVE_STATE&&(VFmain.grid.store.numActiveCategory-=1))},buttons:Ext.MessageBox.OKCANCEL,width:600,scope:this}),new Ext.form.Checkbox({id:"deleteCheck",boxLabel:LC.getLabel("DataCategoryUI","delete_group_check"),renderTo:"deleteConfirm",listeners:{check:function(a,b){b?Ext.Msg.getDialog().buttons[0].enable():
Ext.Msg.getDialog().buttons[0].disable()}}}),Ext.Msg.getDialog().buttons[0].disable()):(VFmain.loadingScreen.show(),toggleDelete(a.data.id))}))},this)}}}});
Sfdc.category.TutorialSplashWindow=function(){Sfdc.category.TutorialSplashWindow.superclass.constructor.call(this,{title:LC.getLabel("DataCategoryUI","video_splash_title"),id:"tutorialSplashWindow",width:470,height:380,modal:!0,constrain:!0,cls:"tutorialWindow",buttons:[new Ext.Button({text:LC.getLabel("LayoutDNDSplash","closeBtn"),handler:function(){Ext.getCmp("tutorialSplashWindow").close()}})],buttonAlign:"center",listeners:{close:function(){Ext.getDom("closeAndNeverShow").checked&&UserContext.userPreferences.setBoolean("HideDataCategorySplash",
!0)}}})};
Ext.extend(Sfdc.category.TutorialSplashWindow,Ext.Window,{getTpl:function(){return new Ext.Template("\x3cp\x3e",LC.getLabel("DataCategoryUI","video_splash_topText"),"\x3c/p\x3e",'\x3cdiv class\x3d"play"\x3e\x3ca href\x3d"#" id\x3d"tutorial_playLink"\x3e\x3cimg class\x3d"playVideoBtn" src\x3d"/s.gif"\x3e',"\x3cbr/\x3e",'\x3cspan class\x3d"playBtnLabel"\x3e',LC.getLabel("DataCategoryUI","playVideo"),"\x3c/span\x3e","\x3c/a\x3e\x3c/div\x3e","\x3cbr/\x3e",'\x3cul class\x3d"bottomTextInfo"\x3e\x3cli\x3e',LC.getLabel("DataCategoryUI",
"video_splash_bottomText"),"\x3c/li\x3e\x3c/ul\x3e","\x3cp\x3e",'\x3cimg class\x3d"videoThumb" src\x3d"/img/ple/video_thumb.png"\x3e\x3c/p\x3e','\x3cbr/\x3e\x3cp class\x3d" closeCheckbox"\x3e','\x3cinput type\x3d"checkbox" id\x3d"closeAndNeverShow"\x3e',LC.getLabel("LayoutDNDSplash","closeAndNeverShow"),"\x3c/p\x3e")},onRender:function(){Sfdc.category.TutorialSplashWindow.superclass.onRender.apply(this,arguments);this.getTpl().overwrite(this.body,{});this.body.child("img.playVideoBtn").addClassOnOver("hover");
Ext.fly("tutorial_playLink").on("click",function(){Ext.getDom("closeAndNeverShow").checked&&UserContext.userPreferences.setBoolean("HideDataCategorySplash",!0);this.showVideo()},this)},showVideo:function(){VFmain.showTutorial();this.close()}});Sfdc.category.TutorialWindow=function(){Sfdc.category.TutorialWindow.superclass.constructor.call(this,{title:LC.getLabel("LayoutDNDSplash","videoTitle"),width:835,height:625,modal:!0,constrainHeader:!0})};
Ext.extend(Sfdc.category.TutorialWindow,Ext.Window,{onRender:function(){Sfdc.category.TutorialWindow.superclass.onRender.apply(this,arguments);this.body.update("\x3ciframe src\x3d'"+VFmain.tutorialUrl+"' height\x3d'600' width\x3d'800' scrolling\x3d'no' frameborder\x3d'0' marginheight\x3d'0' marginwidth\x3d'0'/\x3e")}});Sfdc.category.sandBoxPageWarningTemplate=new Ext.Template('\x3cdiv\x3e\x3cdiv class\x3d"message warningM3"\x3e\x3ctable cellspacing\x3d"0" cellpadding\x3d"0" border\x3d"0" style\x3d"margin: 0px; padding: 0px;" class\x3d"messageTable"\x3e\x3ctbody\x3e\x3ctr valign\x3d"top"\x3e\x3ctd\x3e\x3cimg title\x3d"WARNING" class\x3d"msgIcon" src\x3d"/s.gif" alt\x3d"WARNING"/\x3e\x3c/td\x3e\x3ctd class\x3d"messageCell"\x3e\x3cdiv class\x3d"messageText" \x3e\x3cspan\x3e\x3ch4\x3eWarning:\x3c/h4\x3e\x3c/span\x3e{msg}\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e\t\x3c/div');
Sfdc.category.FormatText={htmlEncode:function(e){return!e?e:Ext.util.Format.htmlEncode(e).replace(/'/g,"\x26#39;")},htmlDecode:function(e){return!e?e:Ext.util.Format.htmlDecode(e).replace(/&#39;/g,"'")}};
Ext.onReady(function(){Sfdc.Perf.endMark("start onReady");Ext.QuickTips.init(!1);VFmain.categoryGroupStore=new Ext.data.GroupingStore({reader:new Ext.data.JsonReader({},"state label apiName placeUsed description id hasBeenActivated lastModifiedById lastModifiedBy lastModifiedByDate createdById createdBy createdByDate isEditable".split(" ")),sortInfo:{field:"state",direction:"ASC"},groupField:"state",id:"categoryGroupStore",numActiveCategory:"",DUMMY_NODE_ID:-1,listeners:{load:function(a,b,c){Sfdc.Perf.mark("loadGroups");
b=new Sfdc.category.Grid.categoryGroupRecord({apiName:"Inactive_Empty_Node",description:"Inactive node place holder",state:VFmain.INACTIVE_STATE,isEditable:!0,id:this.DUMMY_NODE_ID});c=new Sfdc.category.Grid.categoryGroupRecord({apiName:"Active_Empty_Node",description:"Active node place holder",state:VFmain.ACTIVE_STATE,isEditable:!0,id:this.DUMMY_NODE_ID});this.addSorted(c);this.addSorted(b);this.getActiveCategoryCount();if(0===a.getTotalCount()&&!VFmain.isReadOnly)Ext.getCmp("createCatGroup").disable(),
VFmain.grid.newCategoryGroup(),Ext.fly(commandButtonsById.cancel).setVisible(!1),VFmain.tree.helpText.getEl().update(LC.getLabel("DataCategoryUI","noGroupsHelpText"));else{a.getTotalCount()>=VFmain.MAX_CATEGORY_GROUPS&&(Ext.getCmp("createCatGroup").disable(),VFmain.grid.maxCatGroupTip.enable());for(b=0;b<a.getCount();b++)VFmain.grid.createToolTips(b);VFmain.tree.helpText.getEl().update(LC.getLabel("DataCategoryUI","pageLoadHelpText"))}VFmain.tree.helpText.show();Sfdc.Perf.endMark("loadGroups");VFmain.loadingScreen.hide();
!UserContext.userPreferences.getBoolean("HideDataCategorySplash")&&VFmain.tutorialUrl&&(new Sfdc.category.TutorialSplashWindow).show()}},getActiveCategoryCount:function(){var a=0;this.queryBy(function(b,c){b.data.state==VFmain.ACTIVE_STATE&&b.data.id!=VFmain.grid.store.DUMMY_NODE_ID&&(a+=1)});this.numActiveCategory=a}});VFmain.categoryStore=new Ext.data.Store({reader:new Ext.data.JsonReader({},["text","apiName","categoryId","children","height"]),remoteSort:!1,id:"categoryStore",listeners:{load:function(a,
b,c){Sfdc.Perf.mark("loadTree");VFmain.tree.handler.clear();VFmain.tree.deleteMap={};var d=VFmain.tree.getRootNode();VFmain.tree.getEl().child("li")&&VFmain.tree.getEl().child("li").remove();Sfdc.Perf.endMark("loadTree");d=new Ext.tree.AsyncTreeNode({allowDrag:!1,text:b[0].data.text,categoryId:b[0].data.categoryId,children:b[0].data.children,expanded:!0,apiName:b[0].data.apiName});VFmain.tree.setRootNode(d);d.render();Ext.getCmp("expandBtn").enable();Ext.getCmp("colapseBtn").enable();Sfdc.Perf.endMark("loadTree");
d.ui.hide=d.ui.hide.createSequence(function(){d.getOwnerTree().handler.clear();VFmain.tree.setTitle(LC.getLabel("DataCategoryUI","empty_categories_title"));VFmain.tree.name="";VFmain.tree.categoryGroupId="";VFmain.tree.helpText.hide();VFmain.tree.deleteInfo.hide();VFmain.longSavingScreen.hide();Ext.getCmp("expandBtn").disable();Ext.getCmp("colapseBtn").disable()});VFmain.tree.getRootNode().ui.show();VFmain.tree.getRootNode().select();VFmain.grid.isNewGroup&&(VFmain.tree.newCount=0,VFmain.tree.addChild(d),
VFmain.tree.helpText.getEl().update(LC.getLabel("DataCategoryUI","newGroupHelpText")),VFmain.tree.helpText.show(),VFmain.grid.isNewGroup=!1);VFmain.treeLoadingScreen.hide();Sfdc.Perf.endMark("loadTree")}}});Sfdc.category.tips=[LC.getLabel("DataCategoryUI","tip1"),LC.getLabel("DataCategoryUI","tip2"),LC.getLabel("DataCategoryUI","tip3"),LC.getLabel("DataCategoryUI","tip4"),LC.getLabel("DataCategoryUI","tip5")];Sfdc.Perf.mark("grid");VFmain.grid=new Sfdc.category.Grid({id:"grid",region:"west",width:240,
margins:"8 0 8 8",cls:"categoryGroupSection",store:VFmain.categoryGroupStore,view:new Ext.grid.GroupingView({scrollOffset:0,forceFit:!0,groupTextTpl:"{[VFmain.getStateLabel(values.gvalue)]}"}),readonly:VFmain.isReadOnly,title:LC.getLabel("DataCategoryUI","categorygroups_title")});VFmain.grid.view.toggleGroup=Ext.emptyFn;VFmain.grid.view.getRowClass=function(a){if(a.data.id==VFmain.grid.store.DUMMY_NODE_ID)return"emptyActiveInactiveRows";var b="x-grid3-row-"+a.data.state;a.data.isEditable||(b+=" x-grid3-row-saving");
return b};VFmain.grid.getSelectionModel().on("beforerowselect",function(a,b,c,d){if(d.data.id==VFmain.tree.categoryGroupId||d.data.id==VFmain.grid.store.DUMMY_NODE_ID)return!1;VFmain.tree.cancelForms();VFmain.performCommand("cancel");if(!Ext.getCmp("saveCategory").disabled)return Ext.Msg.show({title:LC.getLabel("DataCategoryUI","unsaved_changes_title"),msg:LC.getLabel("DataCategoryUI","unsaved_changes_message",VFmain.tree.name),minWidth:582,fn:function(a){"yes"==a?Ext.getCmp("saveCategory").fireEvent("click"):
"no"==a&&(VFmain.tree.handler.clear(),VFmain.grid.getSelectionModel().selectRow(b))},buttons:{yes:LC.getLabel("DataCategoryUI","save_changes"),no:LC.getLabel("DataCategoryUI","discard_changes"),cancel:LC.getLabel("Buttons","cancel")}}),!1},VFmain.grid);VFmain.grid.getSelectionModel().on("rowselect",function(a,b,c){VFmain.tree.helpText.hide();c.data.state==VFmain.DELETED_STATE?(a=VFmain.tree.deleteInfo.child(".messageText"),a.update(LC.getLabel("DataCategoryUI","deleted_group_info",c.data.lastModifiedByDate)),
a.first("a").on("click",function(){toggleDelete(this.getSelectionModel().getSelected().data.id)},VFmain.grid),a.last("a").on("click",function(){var a=this.getSelectionModel().getSelected();Ext.Msg.show({title:LC.getLabel("DataCategoryUI","delete_group_title",a.data.label),msg:"\x3cp\x3e"+LC.getLabel("DataCategoryUI","hard_delete_group_warning",a.data.label)+"\x3c/p\x3e\x3cp\x3e"+LC.getLabel("DataCategoryUI","delete_group_confirm")+"\x3c/p\x3e\x3cdiv class\x3d'deleteConfirm' id \x3d 'deleteConfirm'/\x3e",
fn:function(b){Ext.Msg.getDialog().buttons[0].enable();"ok"==b&&Ext.getCmp("deleteCheck").getValue()&&hardDelete(a.data.id)},buttons:Ext.MessageBox.OKCANCEL,width:600});new Ext.form.Checkbox({id:"deleteCheck",boxLabel:LC.getLabel("DataCategoryUI","delete_group_check"),renderTo:"deleteConfirm",listeners:{check:function(a,b){b?Ext.Msg.getDialog().buttons[0].enable():Ext.Msg.getDialog().buttons[0].disable()}}});Ext.Msg.getDialog().buttons[0].disable()},VFmain.grid),VFmain.tree.deleteInfo.show(),VFmain.tree.isSoftDeleted=
!0):(VFmain.tree.deleteInfo.hide(),VFmain.tree.isSoftDeleted=!1);c.data.isEditable?(VFmain.longSavingScreen.hide(),VFmain.treeLoadingScreen.show()):VFmain.longSavingScreen.show();VFmain.tree.setTitle(LC.getLabel("DataCategoryUI","categories_title",c.data.label));VFmain.tree.name=c.data.label;VFmain.tree.categoryGroupId=VFmain.grid.getSelectionModel().getSelected().data.id;VFmain.tree.hasBeenActivated=c.data.hasBeenActivated;loadCategoryGroup(c.data.id)},VFmain.grid);Sfdc.Perf.endMark("grid");Sfdc.Perf.mark("tree");
var e=new Ext.Button({text:LC.getLabel("Buttons","save"),id:"saveCategory",listeners:{click:function(){VFmain.tree.cancelForms();VFmain.jsonTree=Ext.encode(VFmain.tree.toJsonObjectForSave(VFmain.tree.getRootNode()));this.disable();simulateSave(VFmain.jsonTree)}},disabled:!0}),f=new Ext.Button({text:LC.getLabel("DataCategoryUI","Undo"),id:"undoBtn",iconCls:"undo-btn-icon",disabled:!0,handler:function(){VFmain.tree.cancelForms();VFmain.tree.handler.undoLast()},listeners:{disable:function(){Ext.getCmp("saveCategory").disable()},
enable:function(){Ext.getCmp("saveCategory").enable()}}}),g=new Ext.Button({text:LC.getLabel("DataCategoryUI","Redo"),id:"redoBtn",iconCls:"redo-btn-icon",disabled:!0,handler:function(){VFmain.tree.cancelForms();VFmain.tree.handler.redo()}}),e=new Ext.Toolbar({cls:"mainToolBar",items:[e,{xtype:"tbseparator"},f,g,{xtype:"tbseparator"},{id:"expandBtn",disabled:!0,text:LC.getLabel("DataCategoryUI","expand"),handler:function(){VFmain.tree.expandAll()}},{id:"colapseBtn",disabled:!0,text:LC.getLabel("DataCategoryUI",
"collapse"),handler:function(){VFmain.tree.collapseAll()}}]});VFmain.tree=new Sfdc.category.Tree({enableDD:!0,pathSeparator:" \x3e ",floating:!0,margins:"8 8 8 0",shadow:"frame",style:"z-index:500",region:"center",title:LC.getLabel("DataCategoryUI","empty_categories_title"),id:"tree",readonly:VFmain.isReadOnly,isSoftDeleted:!1,tbar:e,loader:new Sfdc.category.TreeLoader});VFmain.tree.setRootNode(new Ext.tree.TreeNode);VFmain.tree.loader.loadScope=VFmain.tree;VFmain.tree.getRootNode().ui.hide();VFmain.tree.on("startEdit",
function(){VFmain.performCommand("cancel")});VFmain.tree.on("startAdd",function(){VFmain.performCommand("cancel")});VFmain.tree.on("startdrag",function(){VFmain.performCommand("cancel")});VFmain.tree.on("delete",function(){VFmain.performCommand("cancel")});VFmain.tree.on("sort",function(){VFmain.performCommand("cancel")});VFmain.tree.getSelectionModel().on("selectionchange",function(a,b){b&&Ext.fly(b.ui.getAnchor()).focus()});e=new Sfdc.MessageHandler;VFmain.tree.handler=e;e.addObserver(VFmain.tree);
new Ext.KeyMap(document,{key:[Ext.EventObject.Z,Ext.EventObject.Y,Ext.EventObject.S],ctrl:!0,handler:function(a,b){VFmain.tree.editNode||(b.preventDefault(),a==Ext.EventObject.Z?VFmain.tree.handler.undoLast():a==Ext.EventObject.Y?VFmain.tree.handler.redo():a==Ext.EventObject.S&&Ext.getCmp("saveCategory").fireEvent("click"))},scope:this});Sfdc.Perf.endMark("tree");viewport=new Ext.Panel({layout:"border",cls:"includeDescPageWrap x-theme-aloha-esque",items:[{layout:"border",region:"center",cls:"main",
items:[VFmain.grid,VFmain.tree]}]});Ext.EventManager.onWindowResize(function(a,b){this.setWidth(a-Ext.get("bodyDiv_setup").child(".oLeft").getWidth()-35);Ext.isIE6&&(VFmain.grid.setWidth(240),VFmain.tree.setWidth(this.getInnerWidth()-240));this.setHeight(Math.max(435,VFmain.getWindowHeight()-Ext.get("bPageTitle").getBottom()-15))},viewport);Sfdc.Perf.mark("render");viewport.render("mainTarget");Sfdc.Perf.endMark("render");viewport.setHeight(Math.max(435,VFmain.getWindowHeight()-Ext.get("bPageTitle").getBottom()-
15));e=new Ext.Template('\x3cimg src\x3d"'+UserContext.getUrl("/img/dataCategories/spinner24.gif")+'"/\x3e'+LC.getLabel("Global","loading"));Sfdc.category.LoadingScreen=function(a,b,c){Sfdc.category.LoadingScreen.superclass.constructor.call(this,a,b,c)};Ext.extend(Sfdc.category.LoadingScreen,LoadingScreen,{addLoadingDescription:function(a,b){var c=document.createElement("div");b.appendChild(c);c.className="waitingHolder";var d=b.offsetHeight/5;100<d&&(d=100);c.style.top=d+"px";d=document.createElement("img");
c.appendChild(d);d.src=UserContext.getUrl("/img/loading.gif");d.className="waitingImage";d=document.createElement("span");c.appendChild(d);d.innerHTML=a;d.className="waitingDescription";return c}});VFmain.loadingScreen=new Sfdc.category.LoadingScreen(viewport.getEl().child(".x-panel-bwrap").dom,e.apply({}),"CategoryAdmin_LoadingScreen");VFmain.loadingScreen.show();VFmain.performCommand("loadGroups");-1<navigator.userAgent.toLowerCase().indexOf("msie 8")&&VFmain.tree.addClass("ext-ie8");VFmain.treeLoadingScreen=
new Sfdc.category.LoadingScreen(VFmain.tree.getEl().child(".x-panel-bwrap").dom,e.apply({}),"CategoryTree_LoadingScreen");e=new Ext.Template("{title}","\x3cul class\x3d'saveSteps'\x3e",'\x3cli\x3e\x3cimg src\x3d"'+UserContext.getUrl("/img/dataCategories/spinner.gif")+'"class\x3d"step-one"/\x3e'+LC.getLabel("DataCategoryUI","oneStepSaveText")+"\x3c/li\x3e","\x3c/ul\x3e","\x3cp class\x3d'saveWarning'\x3e{text}\x3c/p\x3e");f=new Ext.Template("{title}","\x3cul class\x3d'saveSteps'\x3e",'\x3cli\x3e\x3cimg src\x3d"'+
UserContext.getUrl("/img/dataCategories/spinner.gif")+'"class\x3d"step-one"/\x3e'+LC.getLabel("DataCategoryUI","step1")+"\x3c/li\x3e",'\x3cli\x3e\x3cimg src\x3d"'+UserContext.getUrl("/img/dataCategories/spinner.gif")+'"class\x3d"step-two"/\x3e'+LC.getLabel("DataCategoryUI","step2")+"\x3c/li\x3e","\x3c/ul\x3e","\x3cp class\x3d'saveWarning'\x3e{text}\x3c/p\x3e");VFmain.oneStepSavingScreen=new Sfdc.category.LoadingScreen(Ext.getBody().dom,e.apply({title:LC.getLabel("DataCategoryUI","saving"),text:LC.getLabel("DataCategoryUI",
"shortwarning")}),"categoryAdmin_ShortSavingScreen");VFmain.shortSavingScreen=new Sfdc.category.LoadingScreen(Ext.getBody().dom,f.apply({title:LC.getLabel("DataCategoryUI","saving1"),text:LC.getLabel("DataCategoryUI","longwarning")}),"categoryAdmin_ShortSavingScreen");VFmain.longSavingScreen=new Sfdc.category.LoadingScreen(VFmain.tree.getEl().child(".x-panel-bwrap").dom,f.apply({title:LC.getLabel("DataCategoryUI","saving2"),text:LC.getLabel("DataCategoryUI","longwarning")}),"categoryAdmin_LongSavingScreen");
new Ext.ToolTip({cls:"infotip",id:"saveDisableTip",html:LC.getLabel("DataCategoryUI","saveDisableTip"),target:Ext.get("thepage:newGroupForm:pb:pbs:saveGroup")});VFmain.sandBoxPopupTemplate=new Ext.Template(LC.getLabel("DataCategoryUI","long_save_prompt1"),"\x3ctable style\x3d'margin-left:1.3em;'\x3e","\x3ctr\x3e\x3ctd class\x3d'bullet'\x3e\x3c/td\x3e\x3ctd\x3e",LC.getLabel("DataCategoryUI","long_save_prompt2"),"\x3c/td\x3e\x3c/tr\x3e","\x3ctr\x3e\x3ctd class\x3d'bullet'\x3e\x3c/td\x3e\x3ctd\x3e",
LC.getLabel("DataCategoryUI","long_save_prompt3"),"\x3c/td\x3e\x3c/tr\x3e","\x3ctr\x3e\x3ctd class\x3d'bullet'\x3e\x3c/td\x3e\x3ctd\x3e",LC.getLabel("DataCategoryUI","long_save_prompt4"),"\x3c/td\x3e\x3c/tr\x3e","\x3c/table\x3e","\x3cbr/\x3e",LC.getLabel("DataCategoryUI","long_save_prompt5"),"{warning}","\x3cbr/\x3e",LC.getLabel("DataCategoryUI","long_save_prompt6"));Sfdc.Perf.endMark("end onReady")});

//# sourceMappingURL=/javascript/1429868265000/sfdc/source/DataCategory.js.map
