/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Sfdc.ns("SfdcApp.Dedupe.MatchResults");SfdcApp.Dedupe.MatchResults=function(){var a=this;Sfdc.onReady(function(){a.context=Sfdc.get(".DedupeMatchResult");a.bindEvents();a.bindDedupeOverrideFieldEvents()})};SfdcApp.Dedupe.MatchResults.actionOverrides=[];SfdcApp.Dedupe.MatchResults.actionOverrideFieldIds=[];
SfdcApp.Dedupe.MatchResults.prototype.bindEvents=function(){if(null!==Sfdc.get(".bottomNav",this.context))for(var a=Sfdc.select(".actionLink",this.context),b=0;b<a.length;b++)Sfdc.on(a[b],"click",this.toggleTableRows,this);a=Sfdc.select(".DedupeMatchResultCallout",this.context);Sfdc.Array.forEach(a,function(a){a=Sfdc.get(".zen-closeBtn",a);Sfdc.on(a,"click",this.disableMatchResultCallout,this)},this);SfdcApp.Dedupe.MatchResults.actionOverrides=Sfdc.select(".DedupeActionOverride");Sfdc.Array.forEach(SfdcApp.Dedupe.MatchResults.actionOverrides,
function(a){var b=Sfdc.Dom.getAttribute(a,"data-name");a=Sfdc.Dom.getAttribute(a,"data-value");SfdcApp.Dedupe.MatchResults.renameButtonLabel("[name\x3d"+b+"]",a)},this)};
SfdcApp.Dedupe.MatchResults.prototype.bindDedupeOverrideFieldEvents=function(){SfdcApp.Dedupe.MatchResults.actionOverrideFieldIds=[];var a=Sfdc.select(".dedupeOverrideFields");Sfdc.Array.forEach(a,function(a){a=Sfdc.Dom.getAttribute(a,"data-value");SfdcApp.Dedupe.MatchResults.actionOverrideFieldIds.push(a);SfdcApp.Dedupe.MatchResults.bindResetSaveAction(a)},this)};
SfdcApp.Dedupe.MatchResults.rebindDedupeOverrideFieldEvents=function(a){-1!==Sfdc.Array.indexOf(SfdcApp.Dedupe.MatchResults.actionOverrideFieldIds,a)&&SfdcApp.Dedupe.MatchResults.bindResetSaveAction(a)};SfdcApp.Dedupe.MatchResults.bindResetSaveAction=function(a){a=Sfdc.get(a);if(null!==a)Sfdc.on(a,"change",SfdcApp.Dedupe.MatchResults.resetSaveAction,this)};
SfdcApp.Dedupe.MatchResults.prototype.toggleTableRows=function(a){var b=Sfdc.Dom.getParent(Sfdc.Event.getEventTarget(a),".bottomNav"),c=Sfdc.select(".actionLink",b);for(a=0;a<c.length;a++)Sfdc.Dom.toggleClass(c[a],"hidden");b=this.getToggleTableRows(b);for(a=0;a<b.length;a++)Sfdc.Dom.toggleClass(b[a],"hidden")};SfdcApp.Dedupe.MatchResults.prototype.getToggleTableRows=function(a){a=Sfdc.Dom.getPrevious(a,".MatchResultList");return Sfdc.select(".toggleRow",a)};
SfdcApp.Dedupe.MatchResults.prototype.disableMatchResultCallout=function(a){a=Sfdc.Event.getEventTarget(a);a=Sfdc.Dom.getParent(a,".DedupeMatchResultCallout");Sfdc.Dom.hideByDisplay(a);UserContext.userPreferences.setBoolean("HideDedupeMatchResultCallout",!0)};
SfdcApp.Dedupe.MatchResults.resetSaveAction=function(){SfdcApp.Dedupe.MatchResults.revertDedupeOverride();0===SfdcApp.Dedupe.MatchResults.actionOverrides.length&&(SfdcApp.Dedupe.MatchResults.renameButtonLabel("[name\x3d"+EditPageConstants.pSAVE+"]",LC.getLabel("Buttons","save")),SfdcApp.Dedupe.MatchResults.renameButtonLabel("[name\x3d"+EditPageConstants.pSAVE_NEW+"]",LC.getLabel("Buttons","save_and_new")))};
SfdcApp.Dedupe.MatchResults.renameButtonLabel=function(a,b){var c=Sfdc.select(a);Sfdc.Array.forEach(c,function(a){a.value=b},this)};SfdcApp.Dedupe.MatchResults.processDedupeOverride=function(a){var b=Sfdc.get(".dedupe_override");null!==b&&(a[b.name]=b.value)};
SfdcApp.Dedupe.MatchResults.revertDedupeOverride=function(){var a=Sfdc.select(".dedupe_override");Sfdc.Array.forEach(a,function(a){Sfdc.Dom.removeChild(a)},this);Sfdc.Array.forEach(SfdcApp.Dedupe.MatchResults.actionOverrides,function(a){a=Sfdc.Dom.getAttribute(a,"data-name");SfdcApp.Dedupe.MatchResults.renameButtonLabel("[name\x3d"+a+"]",LC.getLabel("Buttons","save"))},this)};

//# sourceMappingURL=/javascript/1428053751000/sfdc/source/DedupeJS.js.map
