/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Sfdc.provide("SfdcApp.FilterEdit",{onScopeChange:function(){var h=UserContext.getUrl("/ui/list/FilterEditPage"),f=QueryString.createQueryString(window.location.href);FilterEdit.addFormVal(f,FilterEditConstants.pNAME);FilterEdit.addFormVal(f,FilterEditConstants.pDEV_NAME);FilterEdit.addFormVal(f,FilterEditConstants.pSCOPE);Sfdc.Url.navigateTo(h+f.toString())},addFormVal:function(h,f){var g=document.getElementById(f);g&&h.add(f,g.value)},setupLocationUiElements:function(){for(var h=function(){var a=
document.createElement("select"),b=LC.getLabel("Filter","mi"),c=LC.getLabel("Filter","km");a.innerHTML="\x3coption value\x3d'mi'\x3e"+b+"\x3c/option\x3e\x3coption value\x3d'km'\x3e"+c+"\x3c/option\x3e";return a},f=function(a){var b=document.createElement("div");b.id=FilterEditConstants.pVALUE+a+"-components";a=document.createElement("span");a.className="distance-input";var c=document.createElement("input");c.placeholder=LC.getLabel("Filter","Distance");c.setAttribute("type","text");a.appendChild(c);
a.appendChild(h());c=document.createElement("span");c.className="location-input";var d=document.createElement("input");d.setAttribute("type","text");d.setAttribute("size",10);d.placeholder=LC.getLabel("Filter","Latitude");var e=document.createElement("input");e.setAttribute("type","text");e.setAttribute("size",10);e.placeholder=LC.getLabel("Filter","Longitude");c.appendChild(d);c.appendChild(e);b.appendChild(a);b.appendChild(c);return b},g=function(a,b,c){var d=document.getElementById(FilterEditConstants.pVALUE+
c),e=f(c),h=d.style.display;d.parentNode.appendChild(e);var g="w"===a.value,k=function(c){"w"===a.value?(d.style.display="none",e.style.display="",g=!0):(d.style.display=h,g&&(d.value=""),e.style.display="none",g=!1)};c=function(a){Sfdc.on(a,"click",function(a){if(g){a=Sfdc.get(".distance-input input",e);var c=Sfdc.get(".distance-input select",e),b=Sfdc.select(".location-input input",e);d.value='"'+[b[0].value,b[1].value,a.value,c.value].join(":")+'"'}})};for(var l=Sfdc.select("input[name\x3dsave]"),
m=0;m<l.length;m++)c(l[m]);Sfdc.on(a,"change",k);Sfdc.on(b,"change",k);(function(){var c=d.value;if("w"===a.value){var c="",b=d.value.replace(/"/g,"").split(":"),f=Sfdc.get(".distance-input input",e),g=Sfdc.get(".distance-input select",e),h=Sfdc.select(".location-input input",e);b[0]&&(h[0].value=b[0]);b[1]&&(h[1].value=b[1]);b[2]&&(f.value=b[2]);b[3]&&(g.value=b[3])}k();d.value=c})()},q=function(a,b){return a.id.localeCompare(b.id)},k=function(a){return Sfdc.Array.toArray(a).sort(q)},n=k(Sfdc.select(".declarativeFilterTable select.operator")),
k=k(Sfdc.select(".declarativeFilterTable select.column")),l=0;l<n.length;l++){var p=n[l],r=k[l],s=p.id.substring(FilterEditConstants.pOPERATOR.length);g(p,r,s)}}});Sfdc.onReady(SfdcApp.FilterEdit.setupLocationUiElements);

//# sourceMappingURL=/javascript/1432114439000/sfdc/source/FilterEdit.js.map
