/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
function FieldAttributesUi(a,d,b){this.formulaFilter=new NewFormulaFilter(d,b,new FormulaFilterCriteriaEntityData(a));var c=this;this.handleIsOptionalClick=function(a){c.setErrorsDisabled("1"==getEventTarget(getEvent(a)).value);c.toggleResetDisabled("1"==getEventTarget(getEvent(a)).value)};this.setErrorsDisabled=function(a){var b=document.getElementById(CriteriaInputConstants.ERROR_MESSAGE);b&&(b.disabled=a,c.toggleResetDisabled(a))};this.toggleResetDisabled=function(a){var b=document.getElementById(CriteriaInputConstants.RESET_ERROR_MESSAGE_LINK),
c=document.getElementById(CriteriaInputConstants.RESET_ERROR_MESSAGE);b&&(b.style.display=a?"none":"");c&&(c.style.display=a?"":"none")};this.changeUsingDefaultFlag=function(a){document.getElementById(CriteriaInputConstants.IS_DEFAULT_MESSAGE).value=a?"1":"0"};this.handleResetMessageClick=function(a){if((a=document.getElementById(CriteriaInputConstants.ERROR_MESSAGE))&&!a.disabled)a.value=LC.getLabel("FilteredLookup","filter_not_matched"),c.changeUsingDefaultFlag(!0)};this.init()}
FieldAttributesUi.prototype.init=function(){for(var a=document.getElementsByName(CriteriaInputConstants.IS_OPTIONAL),d=0;d<a.length;d++)addEvent(a[d],"click",this.handleIsOptionalClick,!1),"1"==a[d].value&&a[d].checked?(this.setErrorsDisabled(!0),this.toggleResetDisabled(!0)):(this.setErrorsDisabled(!1),this.toggleResetDisabled(!1));(a=document.getElementById(CriteriaInputConstants.RESET_ERROR_MESSAGE_LINK))&&addEvent(a,"click",this.handleResetMessageClick);var b=this;this.formulaFilter.setIsPopulatedHook(function(a){b.setFiltersDisabled(!a)});
this.setFiltersDisabled(!this.formulaFilter.isPopulated());if(a=sfdcPage.getDialogById("InsertDepDialogId"))a.setManualTabControl(!0),a.controller.setFieldAttributesCallback(function(a,d){b.insertIntoCriteria(a,d)});if(a=document.getElementById(CriteriaInputConstants.ERROR_MESSAGE))addEvent(a,"keypress",function(){b.changeUsingDefaultFlag(!1)}),addEvent(a,"change",function(){b.changeUsingDefaultFlag(!1)});if(this.formulaFilter.isRowPopulated(this.formulaFilter.numFilters)&&(a=document.getElementById(CriteriaInputConstants.MAX_ROWS_ID)))a.style.display=
"";a=document.getElementById(CriteriaInputConstants.HAS_ERROR_OR_WARNING);FieldAttributesUi.setFilterSettingsDisplay(this.formulaFilter.isPopulated()||null!==a)};
FieldAttributesUi.prototype.insertIntoCriteria=function(a,d){for(var b=null,c=1;c<=this.formulaFilter.numFilters;c++)if(!this.formulaFilter.isRowPopulated(c)){b=c;break}null!==b&&(c=document.getElementById(CriteriaInputConstants.pCOL+b),c.comboObject.setValue(a),FieldAttributesUi.fireChangeAndBlurEvent(c),c=document.getElementById(CriteriaInputConstants.pOP+b),c.value="e",FieldAttributesUi.fireChangeAndBlurEvent(c),c=document.getElementById(CriteriaInputConstants.pIS_FLD+b),c.value="true",FieldAttributesUi.fireChangeAndBlurEvent(c),
b=document.getElementById(CriteriaInputConstants.pFLD+b),b.comboObject.setValue(d),FieldAttributesUi.fireChangeAndBlurEvent(b))};
FieldAttributesUi.prototype.setFiltersDisabled=function(a){document.getElementById(CriteriaInputConstants.IS_ACTIVE).disabled=a;for(var d=document.getElementsByName(CriteriaInputConstants.IS_OPTIONAL),b=0;b<d.length;b++)d[b].disabled=a,"1"==d[b].value&&d[b].checked?this.setErrorsDisabled(!0):"1"==d[b].value&&this.setErrorsDisabled(a);if(d=document.getElementById("msgBox"))d.style.display=a?"none":"";document.getElementById(CriteriaInputConstants.INFO_MESSAGE).disabled=a;document.getElementById(CriteriaInputConstants.LOOKUP_FILTER_SECTION_ID+
"2").className="pbSubsection"+(a?" showDisabled":"")};FieldAttributesUi.fireChangeAndBlurEvent=function(a){Sfdc.Event.fireEvent(a,"change");Sfdc.Event.fireEvent(a,"blur")};FieldAttributesUi.toggleFilterSettingsDisplay=function(){var a=document.getElementById(CriteriaInputConstants.LOOKUP_FILTER_SECTION_ID);FieldAttributesUi.setFilterSettingsDisplay("none"==getCurrentStyle(a,"display"))};
FieldAttributesUi.setFilterSettingsDisplay=function(a){var d=document.getElementById(CriteriaInputConstants.LOOKUP_FILTER_SECTION_ID),b=document.getElementById(CriteriaInputConstants.LOOKUP_FILTER_SECTION_ID+"2"),c=document.getElementById(CriteriaInputConstants.LOOKUP_FILTER_SECTION_ID+"_link"),e=document.getElementById(CriteriaInputConstants.LOOKUP_FILTER_SECTION_ID+"_twisty");a?(d.style.display="",b.style.display="",c.innerHTML=LC.getLabel("FieldAttributesUi","hideFilterSettings"),e.className="hideTriangle"):
(d.style.display="none",b.style.display="none",c.innerHTML=LC.getLabel("FieldAttributesUi","showFilterSettings"),e.className="showTriangle")};
function FormulaFieldTreeController(a,b,c,d,e,f,h,g){FieldTreeController.call(this,a,b,c,d,e,f,h,g);this.resetToValue=this.selectedNode=this.insertToElementName=null;this.dbNamePrefix=FormulaFieldTreeController.getRootName(this.tree);this.qs=new QueryString;this.filter=this.qs.get("filter")}FormulaFieldTreeController.getRootName=function(a){for(var b=0;b<a.rootList.length;b++)if("$"!=a.rootList[b].attributes[FieldTreeConstants.DB_NAME].charAt(0))return a.rootList[b].attributes[FieldTreeConstants.DB_NAME]};
FormulaFieldTreeController.prototype=new FieldTreeController;FormulaFieldTreeController.prototype.setInsertToElementName=function(a){this.insertToElementName=a;this.resetToValue=document.getElementById(a).value};
FormulaFieldTreeController.prototype.reset=function(){this.tree.ascend(0);this.selects=[document.getElementById(this.selectId+"0")];var a=this.resetToValue.split(".");if(1<a.length){"$"==a[1].charAt(0)&&(a=this.resetToValue.substring(this.resetToValue.indexOf(".")+1).split("."));for(var b=0;b<a.length;b++){var c=this.selects[b];if(0===c.options.length)break;var d=b==a.length-1,e=this.tree.getNodeFromListByAttr(this.tree.getCurrentList(),FieldTreeConstants.DB_NAME,a[b],d);if(null===e)break;for(var f=
0;f<c.options.length;f++)c.options[f].value==e.key&&(c.selectedIndex=f);this.moveSelectionTo(b,e.key);if(d)return}}a=this.selects[0];0<a.options.length&&(a.selectedIndex=0,this.moveSelectionTo(0,a.options[0].value))};FormulaFieldTreeController.prototype.getInsertDisplayHTML=function(a){return escapeHTML(a.getLabelNameToInsert())};
FormulaFieldTreeController.prototype.filterBuildSelectMap=function(a){for(var b=[],c=0<=this.insertToElementName.indexOf(CriteriaInputConstants.pCOL)?document.getElementById(this.insertToElementName.replace(CriteriaInputConstants.pCOL,CriteriaInputConstants.pFLD)).value:document.getElementById(this.insertToElementName.replace(CriteriaInputConstants.pFLD,CriteriaInputConstants.pCOL)).value,d=0;d<a.length;d++){var e=a[d].isLeaf?escapeHTML(a[d].labelName):escapeHTML(a[d].labelName)+" \x26gt;";if(""==
c||c==CriteriaInputConstants.INVALID_FIELD_VALUE||!a[d].isLeaf)b.push([e,a[d].key]);else for(var f=ColumnType[a[d].attributes[FieldTreeConstants.COLUMN_TYPE]].datatypeLetter,h=ColumnType[this.getNodeByDbName(c).attributes[FieldTreeConstants.COLUMN_TYPE]].comparableDatatypes,g=0;g<h.length;g++)if(h[g]==f){b.push([e,a[d].key]);break}}return b};
FormulaFieldTreeController.prototype.insertCode=function(a,b,c){a=document.getElementById(this.insertToElementName);b=b.getAttributeToInsert(FieldTreeConstants.DB_NAME,!0);"$"==b.charAt(0)&&(b=this.dbNamePrefix+"."+b);a.comboObject.setValue(b);this.reFocusToFieldPickerIcon();Sfdc.Event.fireEvent(a,"change");Sfdc.Event.fireEvent(a,"blur");this.afterInsertCallback&&this.afterInsertCallback()};
FormulaFieldTreeController.prototype.getNodeByDbName=function(a){a=a.split(".");for(var b=this.tree.rootList,c=0;c<a.length;c++){"$"==a[c].charAt(0)&&(b=this.tree.rootList);b=this.tree.getNodeFromListByAttr(b,FieldTreeConstants.DB_NAME,a[c],c==a.length-1);if(!b)return null;b.isLeaf||(b=b.children)}return b};FormulaFieldTreeController.prototype.reFocusToFieldPickerIcon=function(){this.insertToElementName&&document.getElementById(this.insertToElementName+"_fs").focus()};
function InsertDependencyController(b,a,c,d){FieldTreeController.call(this,b,a,"",c,!1,d,null,null);this.selectedNode=this.fieldAttributesCallback=null;this.idPrefix=CriteriaInputConstants.INSERT_DEP_ID_PREFIX}InsertDependencyController.prototype=new FieldTreeController;
InsertDependencyController.prototype.getInsertDisplayHTML=function(b){var a=[];a.push(escapeHTML(b.attributes[CriteriaInputConstants.pCOL+"_label"]));a.push("\x3cbr/\x3e");a.push('\x3cspan class\x3d"InsertDepAPIName"\x3e');a.push(LC.getLabel("Global","labelWithColonNSpace",LC.getLabel("NewFormulaEditor","ApiName")));a.push(escapeHTML(b.attributes[CriteriaInputConstants.pCOL+"_api"]));a.push("\x3c/span\x3e");a.push('\x3cspan class\x3d"insertDepEquals"\x3e');a.push(LC.getLabel("Filter","e"));a.push("\x3c/span\x3e");
a.push(escapeHTML(b.attributes[CriteriaInputConstants.pFLD+"_label"]));a.push("\x3cbr/\x3e");a.push('\x3cspan class\x3d"InsertDepAPIName"\x3e');a.push(LC.getLabel("Global","labelWithColonNSpace",LC.getLabel("NewFormulaEditor","ApiName")));a.push(escapeHTML(b.attributes[CriteriaInputConstants.pFLD+"_api"]));a.push("\x3c/span\x3e");return a.join("")};InsertDependencyController.prototype.getAttributesDisplayHTML=function(b){return null};
InsertDependencyController.prototype.setFieldAttributesCallback=function(b){this.fieldAttributesCallback=b};InsertDependencyController.prototype.insertCode=function(b,a,c){this.fieldAttributesCallback&&this.fieldAttributesCallback(a.attributes[CriteriaInputConstants.pCOL],a.attributes[CriteriaInputConstants.pFLD]);this.afterInsertCallback&&this.afterInsertCallback()};
function NewFormulaFilter(a,b,c){CriteriaInput.call(this,a,b,c,!1);this.numFilters=b;var e=this;this.showFieldPicker=function(a){document.getElementById(CriteriaInputConstants.pCOL+"1").disabled||(sfdcPage.getDialogById("FieldTreeDialogId").controller.setInsertToElementName(a),sfdcPage.getDialogById("FieldTreeDialogId").show())};this.handleClearFiltersClick=function(a){document.getElementById(CriteriaInputConstants.pCOL+"1").disabled||e.clearFilters()};this.handleClearFilterRowClick=function(a){document.getElementById(CriteriaInputConstants.pCOL+
"1").disabled||e.clearFilterRow(a)};this.showFieldOrValueEle=function(a){if(!document.getElementById(CriteriaInputConstants.pCOL+"1").disabled){var b="true"==document.getElementById(CriteriaInputConstants.pIS_FLD+a).value?!0:!1,c=document.getElementById(CriteriaInputConstants.pVAL+a);c.style.display=b?"none":"";c.nextSibling&&hasStyleClass(c.nextSibling,"errorMsg")&&(c.nextSibling.style.display=b?"none":"");document.getElementById(CriteriaInputConstants.pLOOKUP+a+"_div").style.display=b?"none":"";
document.getElementById(CriteriaInputConstants.pFLD+a+"_div").style.display=b?"":"none";document.getElementById(CriteriaInputConstants.pFLD+a+"_fs").style.display=b?"":"none"}};this.initTypeAhead();this.initEvents()}NewFormulaFilter.combos=[];NewFormulaFilter.makeComboBox=function(a,b,c,e,d){NewFormulaFilter.combos.push([a,b,c,d,e])};NewFormulaFilter.prototype=new CriteriaInput;
NewFormulaFilter.prototype.initTypeAhead=function(){for(var a=sfdcPage.getDialogById("FieldTreeDialogId").controller.tree,b=FormulaFieldTreeController.getRootName(a),c=function(a,e,d,h,g){var f=a.getAttributeToInsert(FieldTreeConstants.DB_NAME,!0),k=!1;"$"==f.charAt(0)&&(f=b+"."+f,0===e&&(h.push([CriteriaInputConstants.INVALID_PREFIX+f,a.getLabelNameToInsert(!1)+": ",d,""]),k=!0));if(void 0!==a.children&&0<a.children.length){k||h.push([CriteriaInputConstants.INVALID_PREFIX+f,a.getLabelNameToInsert(!0)+
": ",d,""]);for(f=0;f<a.children.length;f++)c(a.children[f],e+1,d,h,g)}else 1==e?h.push([f,a.getLabelNameToInsert(!0),d,ColumnType[a.attributes[FieldTreeConstants.COLUMN_TYPE]].datatypeLetter]):g.push([f,a.getLabelNameToInsert(!0),d,ColumnType[a.attributes[FieldTreeConstants.COLUMN_TYPE]].datatypeLetter])},e=[],d=0;d<a.rootList.length;d++){var g=[],h=[];c(a.rootList[d],0,this.getGroupLabel(a.rootList[d]),g,h);e=e.concat(g.concat(h))}a=new Ext.data.ArrayStore({fields:["value","label","group","datatype"],
idIndex:0,data:e});this.displayCombos(a)};NewFormulaFilter.prototype.getGroupLabel=function(a){a=a.getAttributeToInsert(FieldTreeConstants.DB_NAME,!0);if("$"!=a.charAt(0))return LC.getLabel("NewFormulaFilter","TargetEntity");switch(a){case "$Source":return LC.getLabel("NewFormulaFilter","SourceEntity");case "$User":case "$Profile":case "$UserRole":return LC.getLabel("NewFormulaFilter","GlobalContexts");default:return a}};
NewFormulaFilter.prototype.displayCombos=function(a){for(var b=LC.getLabel("FieldAttributesUi","emptyTypeahead"),c=LC.getLabel("OpportunitySplit","Error")+LC.getLabel("FieldAttributesUi","invalidLHS"),e=0;e<NewFormulaFilter.combos.length;e++){var d=Ext.getDom(NewFormulaFilter.combos[e][0]).value;d==CriteriaInputConstants.INVALID_FIELD_VALUE&&(d=NewFormulaFilter.combos[e][2]);d=new Sfdc.LimitedComboBox({fieldClass:"",focusClass:"",disabledClass:"FAdisabled",size:600,width:225,listWidth:225,store:a,
id:NewFormulaFilter.combos[e][0]+"_label",mode:"local",triggerAction:"query",valueField:"value",displayField:"label",emptyText:b,hideTrigger:!0,resizable:!0,value:d,shadow:!1,lazyInit:!0,validationEvent:"change",hiddenId:NewFormulaFilter.combos[e][0],tabIndex:NewFormulaFilter.combos[e][3],msgTarget:NewFormulaFilter.combos[e][0]+"_error",msgDisplay:"block",invalidClass:"",invalidText:c});Ext.getDom(NewFormulaFilter.combos[e][0]).comboObject=d;d.addListener("blur",NewFormulaFilter.onBlur);d.addListener("blur",
this.revealHiddenRow);d.addListener("select",NewFormulaFilter.onSelect);d.addListener("specialkey",NewFormulaFilter.onSpecialKey);d.render(NewFormulaFilter.combos[e][1]);0<NewFormulaFilter.combos[e][4].length&&d.markInvalid(NewFormulaFilter.combos[e][4])}a.displayField=d.displayField};NewFormulaFilter.onSpecialKey=function(a,b){b.getKey()==b.ENTER&&(NewFormulaFilter.onBlur(a),b.preventDefault())};
NewFormulaFilter.onBlur=function(a){if(0===a.getRawValue().length)a.setValueInternal(""),NewFormulaFilter.onSelect(a);else{var b=!1,c=a.findRecord(a.displayField,a.getRawValue());c&&0!==c.data[a.valueField].search(CriteriaInputConstants.INVALID_PREFIX)&&(a.setValueInternal(c.data[a.valueField]),a.clearInvalid(),b=!0);b||(a.markInvalid(),a.setValueInternal(CriteriaInputConstants.INVALID_FIELD_VALUE))}};NewFormulaFilter.onSelect=function(a){Sfdc.Event.fireEvent(a.hiddenField,"change")};
NewFormulaFilter.prototype.initEvents=function(){for(var a=this,b=function(b,c){return function(){a.showFieldPicker(b+c)}},c=function(b){return function(){a.showFieldOrValueEle(b)}},e=function(b){return function(){a.handleClearFilterRowClick(b)}},d=1;d<=this.numFilters;d++){this.addEventsToFieldElements(CriteriaInputConstants.pCOL,d,b);this.addEventsToFieldElements(CriteriaInputConstants.pFLD,d,b);addEvent(document.getElementById(CriteriaInputConstants.pIS_FLD+d),"change",c(d),!1);addEvent(document.getElementById(CriteriaInputConstants.pFLD+
d),"blur",this.revealHiddenRow,!1);var g=document.getElementById(CriteriaInputConstants.CLEAR_FILTERS_LINK+d);g&&addEvent(g,"click",e(d),!1)}(b=document.getElementById(CriteriaInputConstants.CLEAR_FILTERS_LINK))&&addEvent(b,"click",this.handleClearFiltersClick);this.setInsertDepButtonDisabled(this.isAllPopulated());sfdcPage.getDialogById("FieldTreeDialogId").setManualTabControl(!0)};
NewFormulaFilter.prototype.addEventsToFieldElements=function(a,b,c){var e=document.getElementById("labelFor"+a+b);addEvent(e,"blur",this.revealHiddenRow,!1);addEvent(document.getElementById(a+b+"_fs"),"click",c(a,b),!1)};NewFormulaFilter.prototype.clearFilters=function(){CriteriaInput.prototype.clearFilters.call(this);this.setInsertDepButtonDisabled(!1)};
NewFormulaFilter.prototype.clearFilterRow=function(a,b){document.getElementById(CriteriaInputConstants.pCOL+a).comboObject.reset();document.getElementById(CriteriaInputConstants.pFLD+a).comboObject.reset();document.getElementById(CriteriaInputConstants.pIS_FLD+a).selectedIndex=0;this.showFieldOrValueEle(a);delStyleClass(document.getElementById(CriteriaInputConstants.pVAL+a),"error");CriteriaInput.prototype.clearFilterRow.call(this,a);b||this.setInsertDepButtonDisabled(!1)};
NewFormulaFilter.prototype.setInsertDepButtonDisabled=function(a){var b=document.getElementById(CriteriaInputConstants.INSERT_DEP_BUTTON_ID);b&&(b.disabled=a,b.className=a?"btnDisabled":"btn",b.title=a?LC.getLabel("FieldAttributesUi","noEmptyRows",this.numFilters):LC.getLabel("FieldAttributesUi","insertDependency"))};
NewFormulaFilter.prototype.isRowPopulated=function(a){return CriteriaInput.prototype.isRowPopulated.call(this,a)||null!==document.getElementById(CriteriaInputConstants.pFLD+a)&&0<document.getElementById(CriteriaInputConstants.pFLD+a).value.length};NewFormulaFilter.prototype.hook_revealHiddenRow=function(){CriteriaInput.prototype.hook_revealHiddenRow.call(this);this.setInsertDepButtonDisabled(this.isAllPopulated())};Ext.ns("Sfdc");
Sfdc.LimitedDataView=function(a){this.size=a.size;Sfdc.LimitedDataView.superclass.constructor.call(this,a)};
Ext.extend(Sfdc.LimitedDataView,Ext.DataView,{refresh:function(){this.clearSelections(!1,!0);this.el.update("");var a=this.store.getRange(0,this.size-1);1>a.length?((!this.deferEmptyText||this.hasSkippedEmptyText)&&this.el.update(this.emptyText),this.hasSkippedEmptyText=!0,this.all.clear()):(this.tpl.overwrite(this.el,this.collectData(a,0)),this.all.fill(Ext.query(this.itemSelector,this.el.dom)),this.updateIndexes(0))},getSize:function(){return this.size}});
Sfdc.LimitedComboBox=function(a){this.filter=(new QueryString).get("filter");this.size=a.size;this.lastValue=a.value;this.tpl=new Ext.XTemplate('{[this.getRegex()]}\x3ctpl for\x3d"."\x3e','\x3ctpl if\x3d"values.group \x26\x26 (xindex \x3d\x3d 1 || parent[xindex - 2].group !\x3d values.group)"\x3e','\x3cdiv class\x3d"x-combo-list-group"\x3e{group}\x3c/div\x3e',"\x3c/tpl\x3e",'\x3cdiv class\x3d"x-combo-list-item" title\x3d"{[this.getTitle(values)]}"\x3e{[this.massage(values)]}\x3c/div\x3e\x3c/tpl\x3e',
{getTitle:function(a){return Ext.util.Format.htmlEncode(a[this.combobox.displayField])},massage:function(a){a=Ext.util.Format.htmlEncode(a[this.combobox.displayField]);this.regex&&(a=a.replace(this.regex,"\x3cb\x3e$1\x3c/b\x3e$2"));return a},getRegex:function(){if(void 0!==this.combobox.lastQuery&&!this.combobox.lastQuery.match(/^\s*$/)){var a=Ext.util.Format.htmlEncode(this.combobox.lastQuery.replace(/([\/.*+?|()[\]{}\\^$])/g,"\\$1"));this.regex=RegExp((a.charAt(0).match(/^\w/)?"\\b":"")+"("+a+")([^:]*:?\\s?$)",
"ig")}else this.regex=null;return""}});this.tpl.combobox=this;Sfdc.LimitedComboBox.superclass.constructor.call(this,a)};
Ext.extend(Sfdc.LimitedComboBox,Ext.form.ComboBox,{initList:function(){if(!this.list){this.list=new Ext.Layer({shadow:this.shadow,cls:["x-combo-list",this.listClass].join(" "),constrain:!1});var a=this.listWidth||Math.max(this.wrap.getWidth(),this.minListWidth);this.list.setWidth(a);this.list.swallowEvent("mousewheel");this.assetHeight=0;this.title&&(this.header=this.list.createChild({cls:"x-combo-list-hd",html:this.title}),this.assetHeight+=this.header.getHeight());this.innerList=this.list.createChild({cls:"x-combo-list-inner"});
this.innerList.on("mouseover",this.onViewOver,this);this.innerList.on("mousemove",this.onViewMove,this);this.innerList.setWidth(a-this.list.getFrameWidth("lr"));this.pageSize&&(this.footer=this.list.createChild({cls:"x-combo-list-ft"}),this.pageTb=new Ext.PagingToolbar({store:this.store,pageSize:this.pageSize,renderTo:this.footer}),this.assetHeight+=this.footer.getHeight());this.tpl||(this.tpl='\x3ctpl for\x3d"."\x3e\x3cdiv class\x3d"x-combo-list-item"\x3e{'+this.displayField+"}\x3c/div\x3e\x3c/tpl\x3e");
this.view=new Sfdc.LimitedDataView({size:this.size,applyTo:this.innerList,tpl:this.tpl,singleSelect:!0,selectedClass:this.selectedClass,itemSelector:this.itemSelector||".x-combo-list-item"});this.view.on("click",this.onViewClick,this);this.bindStore(this.store,!0);this.resizable&&(this.resizer=new Ext.Resizable(this.list,{pinned:!0,handles:"se"}),this.resizer.on("resize",function(a,c,e){this.maxHeight=e-this.handleHeight-this.list.getFrameWidth("tb")-this.assetHeight;this.listWidth=c;this.innerList.setWidth(c-
this.list.getFrameWidth("lr"));this.restrictHeight()},this),this[this.pageSize?"footer":"innerList"].setStyle("margin-bottom",this.handleHeight+"px"))}},getRegex:function(a){if("string"==typeof a){if(a.match(/^\s*$/))return/^[^:]*:?\s?$/;var b=a.replace(/([\/.*+?|()[\]{}\\^$])/g,"\\$1");return RegExp((a.charAt(0).match(/^\w/)?"\\b":"")+b+"[^:]*:?\\s?$","i")}return a},selectNext:function(){var a=Math.min(this.view.getSize(),this.store.getCount());0<a&&this.selectedIndex<a-1&&this.select(this.selectedIndex+
1)},onRender:function(a,b){Ext.form.ComboBox.superclass.onRender.call(this,a,b);this.hiddenName?(this.hiddenField=this.el.insertSibling({tag:"input",type:"hidden",name:this.hiddenName,id:this.hiddenId||this.hiddenName},"before",!0),this.el.dom.removeAttribute("name")):this.hiddenId&&(this.hiddenField=Ext.getDom(this.hiddenId));Ext.isGecko&&this.el.dom.setAttribute("autocomplete","off");if(this.lazyInit)this.on("focus",this.initList,this,{single:!0});else this.initList();this.editable||(this.editable=
!0,this.setEditable(!1));var c=this.el.dom.type;c&&("password"==c&&(c="text"),this.el.removeClass("x-form-"+c));this.el.on("mousedown",this.onMouseDown,this)},onDisable:function(){Ext.form.TriggerField.superclass.onDisable.call(this);this.wrap&&this.wrap.addClass(this.disabledClass)},onEnable:function(){Ext.form.TriggerField.superclass.onEnable.call(this);this.wrap&&this.wrap.removeClass(this.disabledClass)},validateValue:function(a){return Sfdc.LimitedComboBox.superclass.validateValue.call(this,
a)?this.value!=CriteriaInputConstants.INVALID_FIELD_VALUE:!1},reset:function(){Ext.form.ComboBox.superclass.setValue.call(this,"");this.setValueInternal("")},setValue:function(a){var b=a;if(this.valueField&&null!==a&&0<a.length){var c=this.findRecord(this.valueField,a);c?b=c.data[this.displayField]:a=CriteriaInputConstants.INVALID_FIELD_VALUE}this.lastSelectionText=b;Ext.form.ComboBox.superclass.setValue.call(this,b);this.setValueInternal(a)},setValueInternal:function(a){this.hiddenField&&(this.hiddenField.value=
a);this.lastValue=this.value=a},onViewClick:function(a){var b=this.view.getSelectedIndexes()[0],c=this.store.getAt(b);if(c)this.onSelect(c,b);!1!==a&&(this.el.focus(),0===this.getValue().search(CriteriaInputConstants.INVALID_PREFIX)&&this.initQuery())},findRecord:function(a,b){var c,e=this.store.snapshot||this.store.data;0<e.getCount()&&e.each(function(d){if(d.data[a]==b)return c=d,!1});return c},onMouseDown:function(){this.el.focus();this.initQuery()},onFocus:function(){this.hiddenId!==this.store.hiddenId&&
(this.store.hiddenId=this.hiddenId,this.store.partnerId=0<=this.hiddenId.indexOf(CriteriaInputConstants.pCOL)?document.getElementById(this.hiddenId.replace(CriteriaInputConstants.pCOL,CriteriaInputConstants.pFLD)).value:document.getElementById(this.hiddenId.replace(CriteriaInputConstants.pFLD,CriteriaInputConstants.pCOL)).value,this.store.partnerTypes=""!==this.store.partnerId&&this.store.partnerId!==CriteriaInputConstants.INVALID_FIELD_VALUE?ColumnType[sfdcPage.getDialogById("FieldTreeDialogId").controller.getNodeByDbName(this.store.partnerId).attributes.columnType].comparableDatatypes:
[]);Ext.form.ComboBox.superclass.onFocus.call(this)},filterAll:function(a,b){var c=this.regex,e=a.data.datatype;if(Ext.isEmpty(c,!1)||c.test(a.data[this.displayField])){if(""===this.partnerId||this.partnerId==CriteriaInputConstants.INVALID_FIELD_VALUE||""===e||0===this.partnerTypes.length)return!0;for(c=0;c<this.partnerTypes.length;c++)if(this.partnerTypes[c]==e)return!0}return!1},doQuery:function(a,b){if(void 0===a||null===a)a="";var c={query:a,forceAll:b,combo:this,cancel:!1};if(!1===this.fireEvent("beforequery",
c)||c.cancel)return!1;a=c.query;b=c.forceAll;if(!0===b||a.length>=this.minChars)this.lastQuery!==a?(this.lastQuery=a,"local"==this.mode?(this.selectedIndex=-1,this.store.regex=this.getRegex(a),this.store.filterBy(this.filterAll),this.onLoad()):(this.store.baseParams[this.queryParam]=a,this.store.load({params:this.getParams(a)}),this.expand())):(this.selectedIndex=-1,this.onLoad())}});

//# sourceMappingURL=/javascript/1428053751000/sfdc/source/FilteredLookups.js.map
