/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
function SearchClickTracking(){}var searchResultClick=new SearchClickTracking;
SearchClickTracking.prototype.mousedown=function(a,b){var c=getEvent(b);if(void 0!==c.button&&(0===c.button||1===c.button))if(c=a.getAttribute("href",2),-1===QueryString.getURI(c).indexOf(SearchClickLoggingUtil.SEARCH_CLICK_LOGGING_SERVLET_PATH)){a.getAttribute("data-seclkp");var f=a.getAttribute("data-seclki"),h=a.getAttribute("data-seclkr"),k=a.getAttribute("data-seclkh"),d=a.getAttribute("data-seclke");if("true"!==a.getAttribute("data-seclkd")){if(Sfdc.resolve("Sfdc.servicedeskview")){var e=Sfdc.resolve("Sfdc.support.servicedesk.FooterWidgetWindowHelper",
top),e=e?e.getMasterWindow():top.Sfdc.support.servicedesk.getMasterWindow();if(e=Sfdc.resolve("SfdcApp.Search.ConsoleSearchLogSwitcher",e)){var g=this.getClickedRecordId(f,d,c);g&&e.switchOnForObject(g)}}e=new QueryString;e=SearchClickLoggingUtil.addSearchResultClickLoggingParams(e,{recordId:f,queryGuid:this.clickResults.queryGuid,totalResultsForEntity:this.clickResults.counts[d],rank:h,bucketRank:this.clickResults.bucketRanks[d],idHash:k,resultList:this.clickResults.resultLists[d],numResultsForEntityBeforeDb:this.clickResults.numResultsForEntityBeforeDb[d],
pageNum:this.clickResults.pageNums[d],numResultsPerPage:this.clickResults.numResultsPerPage[d],filter:this.clickResults.filters[d],sort:this.clickResults.sorts[d],isTagging:this.clickResults.isTagging[d],entityName:d});Sfdc.resolve("Sfdc.servicedeskview")||top.isDesktopPage||!SearchClickLoggingUtil.isRedirectableUrl(c)?(this.ajaxStatus=null,Sfdc.Ajax.get(SearchClickLoggingUtil.getClickLoggingServletUrl(e,null),function(a,b){b&&(this.searchResultClick.ajaxStatus=b.status)})):a.href=SearchClickLoggingUtil.getClickLoggingServletUrl(e,
c)}}};SearchClickTracking.prototype.getClickedRecordId=function(a,b,c){if("KnowledgeArticleVersion"===b){var f;c&&(a=Sfdc.resolve("Sfdc.support.servicedesk",top),(c=a.extractSrcUpUrl(c))&&0!==c.indexOf("javascript")&&(f=a.getEntityIdFromUrl(c)));return f}return a};
SearchClickTracking.prototype.setRelatedListQueryData=function(a){this.clickResults||(this.clickResults={},this.clickResults.totalCount=0,this.clickResults.counts={},this.clickResults.bucketRanks={},this.clickResults.pageNums={},this.clickResults.numResultsPerPage={},this.clickResults.filters={},this.clickResults.sorts={},this.clickResults.numResultsForEntityBeforeDb={},this.clickResults.isTagging={},this.clickResults.resultLists={});this.clickResults.queryGuid=a.queryGuid;var b=this.clickResults.counts.name;
0<b&&(this.clickResults.totalCount-=b);this.clickResults.totalCount+=a.count;b=a.name;this.clickResults.counts[b]=a.count;this.clickResults.pageNums[b]=a.pageNum;this.clickResults.numResultsPerPage[b]=a.numResultsPerPage;this.clickResults.filters[b]=a.filter;this.clickResults.sorts[b]=a.sort;this.clickResults.numResultsForEntityBeforeDb[b]=a.numResultsForEntityBeforeDb;this.clickResults.isTagging[b]=a.isTagging;this.clickResults.resultLists[b]=a.resultList;if(!this.clickResults.bucketRanks[b]){a=
0;for(var c in this.clickResults.bucketRanks)if(this.clickResults.bucketRanks.hasOwnProperty(c)){var f=this.clickResults.bucketRanks[c];f>a&&(a=f)}this.clickResults.bucketRanks[b]=a+1}};

//# sourceMappingURL=/javascript/1432374000000/sfdc/source/SearchClickTracking.js.map
