//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermore.apps.meetings {
    
    
    public partial class meetinglist2 {
        
        /// <summary>
        /// StyleAdapter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.StyleAdapter StyleAdapter;
        
        /// <summary>
        /// SesstionTimeout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.SesstionTimeout SesstionTimeout1;
        
        /// <summary>
        /// TopRight1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebClient.UIControls.TopNav TopRight1;
        
        /// <summary>
        /// MainNav1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebClient.UIControls.MainNav MainNav1;
        
        /// <summary>
        /// EasyGridListInit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Youyou.HRCore.Web.UI.EasyGridListInit EasyGridListInit1;
    }
}
