//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.apps {
    
    
    public partial class addGroupto {
        
        /// <summary>
        /// StyleAdapter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.StyleAdapter StyleAdapter;
        
        /// <summary>
        /// SesstionTimeout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.SesstionTimeout SesstionTimeout1;
        
        /// <summary>
        /// TopRight1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebClient.UIControls.TopNav TopRight1;
        
        /// <summary>
        /// MainNav1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebClient.UIControls.MainNav MainNav1;
        
        /// <summary>
        /// LeftQuickMenu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.LeftQuickMenu LeftQuickMenu1;
        
        /// <summary>
        /// RegisterParamsHiddenFieldsControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.RegisterParamsHiddenFieldsControl RegisterParamsHiddenFieldsControl1;
        
        /// <summary>
        /// PageFooter1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OA.Web.UI.WebControls.PageFooter PageFooter1;
    }
}
